#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v3_hfpatch}"

# Aggressive primary-view texture injection:
# 1) keep each view as primary long enough to imprint detail,
# 2) keep neighbor/settle weak so they do not immediately average the detail away,
# 3) add a direct top-guidance patch delta loss on the strongest prior residual pixels.
export PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS:-10}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS:-1}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS:-1}"
export PRIOR_VIEW_CURRICULUM_SETTLE_ITERS="${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS:-120}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-4.5}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE:-0.18}"
export PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE="${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE:-0.04}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS:-8}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT:-1.55}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN:-1.55}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT:-1.05}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL:-7}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT:-0.25}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT:-2.50}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION:-0.14}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE:-0.10}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN:-1.25}"

export PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-4.5}"
export PRIOR_RESIDUAL_DELTA_CLIP="${PRIOR_RESIDUAL_DELTA_CLIP:-1.0}"

export PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-192}"
export PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-131072}"
export PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-0.32}"
export PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.16}"
export PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.10}"
export PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.050}"
export PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST:-3.2}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-6.0}"
export PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-2.8}"
export PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-6.0}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen_viewmajor_hfboot.sh"
