#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"
PYTHON_BIN="${PYTHON_BIN:-python}"
CONDA_ENV_NAME="${CONDA_ENV_NAME:-}"

RUN_BASE_MAINLINE_IF_MISSING="${RUN_BASE_MAINLINE_IF_MISSING:-1}"
RUN_DETECT="${RUN_DETECT:-1}"
RUN_BUILD_QUALITY_PRIORS="${RUN_BUILD_QUALITY_PRIORS:-1}"
RUN_CORRECTION="${RUN_CORRECTION:-1}"

BASE_RUN_NAME="${BASE_RUN_NAME:-mip_to_soflr_surface_v0}"
BASE_RUN_ROOT="${BASE_RUN_ROOT:-${SOF_ROOT}/output/mip_to_sof_surface_v0/${SCENE_NAME}/${BASE_RUN_NAME}}"
BASE_MODEL_PATH="${BASE_MODEL_PATH:-${BASE_RUN_ROOT}/pulled_mip_model}"
BASE_ITERATION="${BASE_ITERATION:-32000}"
BASELINE_ITERATION="${BASELINE_ITERATION:-30000}"

MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"
RAW_MIP_MODEL_PATH="${RAW_MIP_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}}"
RAW_MIP_INPUT_MODEL_PATH="${RAW_MIP_INPUT_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}_sof_native_input}"
SOF_SURFACE_MODEL="${SOF_SURFACE_MODEL:-${SCENE_ASSET_ROOT}/${SCENE_NAME}_sof_vanilla_images8_v1/soflr30k}"
SOF_SURFACE_ITERATION="${SOF_SURFACE_ITERATION:-${BASELINE_ITERATION}}"

LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR:-images_8}"
SURFACE_IMAGES_SUBDIR="${SURFACE_IMAGES_SUBDIR:-images_8}"
SR_IMAGES_SUBDIR="${SR_IMAGES_SUBDIR:-images_2}"
RENDER_IMAGES_SUBDIR="${RENDER_IMAGES_SUBDIR:-images_2}"
RENDER_SPLIT="${RENDER_SPLIT:-test}"
RAW_SR_PRIOR_DIR="${RAW_SR_PRIOR_DIR:-${SCENE_ROOT}/priors}"
SR_MASK_THRESHOLD="${SR_MASK_THRESHOLD:-0.12}"
SR_MASK_MODE="${SR_MASK_MODE:-soft}"
BASE_PREPARED_SR_PRIOR_ROOT="${BASE_PREPARED_SR_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/sof_surface_v0_${LR_REFERENCE_IMAGES_SUBDIR}_to_${SR_IMAGES_SUBDIR}_mask${SR_MASK_THRESHOLD}_${SR_MASK_MODE}}"
IE_SRGS_MASK_DIR="${IE_SRGS_MASK_DIR:-${BASE_PREPARED_SR_PRIOR_ROOT}/usable_masks}"
RAW_MIP_RENDER_ROOT="${RAW_MIP_RENDER_ROOT:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}_render_no_gt_${RENDER_IMAGES_SUBDIR}}"
PREPARE_RAW_MIP_REFERENCES_IF_MISSING="${PREPARE_RAW_MIP_REFERENCES_IF_MISSING:-1}"

BASE_RENDER_DIR="${BASE_RENDER_DIR:-${BASE_RUN_ROOT}/base_mip_renders_no_gt/${RENDER_SPLIT}/ours_${BASELINE_ITERATION}/renders}"

DETECT_RUN_NAME="${DETECT_RUN_NAME:-${BASE_RUN_NAME}_starburst_mipref_v0}"
DETECT_OUTPUT_DIR="${DETECT_OUTPUT_DIR:-${SOF_ROOT}/output/starburst_gaussian_scores_v0/${SCENE_NAME}/${DETECT_RUN_NAME}}"
DETECT_INTERACTION_IMAGES_SUBDIR="${DETECT_INTERACTION_IMAGES_SUBDIR:-${RENDER_IMAGES_SUBDIR}}"
DETECT_SPLIT="${DETECT_SPLIT:-test}"
DETECT_MAX_VIEWS="${DETECT_MAX_VIEWS:-16}"
DETECT_VIEW_INDICES="${DETECT_VIEW_INDICES:-}"
DETECT_SELECT_QUANTILE="${DETECT_SELECT_QUANTILE:-0.990}"
DETECT_MIN_STAR_SCORE="${DETECT_MIN_STAR_SCORE:-0.08}"
DETECT_MIN_UNSUPPORTED_SCORE="${DETECT_MIN_UNSUPPORTED_SCORE:-0.04}"
DETECT_MIN_STAR_VIEW_COUNT="${DETECT_MIN_STAR_VIEW_COUNT:-1}"
DETECT_GLOBAL_LONG_AXIS_QUANTILE="${DETECT_GLOBAL_LONG_AXIS_QUANTILE:-0.94}"
DETECT_GLOBAL_ANISOTROPY_QUANTILE="${DETECT_GLOBAL_ANISOTROPY_QUANTILE:-0.90}"
DETECT_GLOBAL_RADIUS_MAX_QUANTILE="${DETECT_GLOBAL_RADIUS_MAX_QUANTILE:-0.94}"
DETECT_GLOBAL_PREFILTER_MIN_HITS="${DETECT_GLOBAL_PREFILTER_MIN_HITS:-2}"
DETECT_GLOBAL_PREFILTER_MAX_FRACTION="${DETECT_GLOBAL_PREFILTER_MAX_FRACTION:-0.10}"
DETECT_GLOBAL_PREFILTER_MAX_COUNT="${DETECT_GLOBAL_PREFILTER_MAX_COUNT:-120000}"
DETECT_MAX_CANDIDATE_FRACTION="${DETECT_MAX_CANDIDATE_FRACTION:-0.015}"
DETECT_MAX_CANDIDATE_COUNT="${DETECT_MAX_CANDIDATE_COUNT:-30000}"
STARBURST_SCORE_PAYLOAD="${STARBURST_SCORE_PAYLOAD:-${DETECT_OUTPUT_DIR}/starburst_gaussian_scores_v0.pt}"
STARBURST_MASK_KEY="${STARBURST_MASK_KEY:-starburst_candidate}"
DETECT_REFERENCE_DIR="${DETECT_REFERENCE_DIR:-${MIP_REFERENCE_DIR:-${RAW_MIP_RENDER_ROOT}/${DETECT_SPLIT}/ours_${BASELINE_ITERATION}/renders}}"

CORRECTION_PROFILE="${CORRECTION_PROFILE:-safe_v0}"
QUALITY_FUSE_PROFILE="${QUALITY_FUSE_PROFILE:-safe_hf_v1}"
QUALITY_FUSE_NAME="${QUALITY_FUSE_NAME:-quality_fuse_v1_${BASE_RUN_NAME}_mip_overlay_${QUALITY_FUSE_PROFILE}}"
QUALITY_FUSE_ROOT="${QUALITY_FUSE_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/${QUALITY_FUSE_NAME}}"
QUALITY_FUSE_IMAGES_SUBDIR="${QUALITY_FUSE_IMAGES_SUBDIR:-${RENDER_IMAGES_SUBDIR}}"
QUALITY_FUSE_SPLIT="${QUALITY_FUSE_SPLIT:-train}"
QUALITY_FUSE_MAX_VIEWS="${QUALITY_FUSE_MAX_VIEWS:-0}"
QUALITY_FUSE_DEBUG_VIEWS="${QUALITY_FUSE_DEBUG_VIEWS:-4}"
QUALITY_FUSE_STABLE_DIR="${QUALITY_FUSE_STABLE_DIR:-${RAW_MIP_RENDER_ROOT}/${QUALITY_FUSE_SPLIT}/ours_${BASELINE_ITERATION}/renders}"
QUALITY_FUSE_REFERENCE_DIR="${QUALITY_FUSE_REFERENCE_DIR:-${QUALITY_FUSE_STABLE_DIR}}"
QUALITY_FUSE_SOURCE_MASK_DIR="${QUALITY_FUSE_SOURCE_MASK_DIR:-${IE_SRGS_MASK_DIR}}"

DEFAULT_CORRECTION_RUN_NAME="${BASE_RUN_NAME}_starcorr_v0"
if [[ "${CORRECTION_PROFILE}" != "safe_v0" ]]; then
  DEFAULT_CORRECTION_RUN_NAME="${BASE_RUN_NAME}_${CORRECTION_PROFILE}"
fi
CORRECTION_RUN_NAME="${CORRECTION_RUN_NAME:-${DEFAULT_CORRECTION_RUN_NAME}}"
CORRECTION_RUN_ROOT="${CORRECTION_RUN_ROOT:-${SOF_ROOT}/output/mip_to_sof_surface_v0/${SCENE_NAME}/${CORRECTION_RUN_NAME}}"
CORRECTION_OUTPUT_MODEL="${CORRECTION_OUTPUT_MODEL:-${CORRECTION_RUN_ROOT}/pulled_mip_model}"
CORRECTION_EXTRA_ITERS="${CORRECTION_EXTRA_ITERS:-1000}"
CORRECTION_GAUSSIAN_UPDATE_SCALE="${CORRECTION_GAUSSIAN_UPDATE_SCALE:-1.0}"
CORRECTION_GAUSSIAN_SCALE_AXIS_MODE="${CORRECTION_GAUSSIAN_SCALE_AXIS_MODE:-all}"
CORRECTION_GAUSSIAN_SCALE_MIN_MULTIPLIER="${CORRECTION_GAUSSIAN_SCALE_MIN_MULTIPLIER:-0.0}"
CORRECTION_GAUSSIAN_SCALE_MAX_MULTIPLIER="${CORRECTION_GAUSSIAN_SCALE_MAX_MULTIPLIER:-0.0}"
CORRECTION_XYZ_LR="${CORRECTION_XYZ_LR:-}"
CORRECTION_OPACITY_LR="${CORRECTION_OPACITY_LR:-}"
CORRECTION_SCALE_LR="${CORRECTION_SCALE_LR:-}"
CORRECTION_LAMBDA_RGB_PRESERVE="${CORRECTION_LAMBDA_RGB_PRESERVE:-}"
CORRECTION_LAMBDA_ANCHOR="${CORRECTION_LAMBDA_ANCHOR:-}"
CORRECTION_LAMBDA_SCALE_ANCHOR="${CORRECTION_LAMBDA_SCALE_ANCHOR:-}"
CORRECTION_MAX_DISPLACEMENT_RATIO="${CORRECTION_MAX_DISPLACEMENT_RATIO:-}"
CORRECTION_SR_PRIOR_L1_WEIGHT="${CORRECTION_SR_PRIOR_L1_WEIGHT:-}"
CORRECTION_SR_PRIOR_HF_WEIGHT="${CORRECTION_SR_PRIOR_HF_WEIGHT:-}"
CORRECTION_ENABLE_OPACITY_UPDATE="${CORRECTION_ENABLE_OPACITY_UPDATE:-}"
CORRECTION_ENABLE_SCALE_UPDATE="${CORRECTION_ENABLE_SCALE_UPDATE:-}"
CORRECTION_RUN_RENDER="${CORRECTION_RUN_RENDER:-1}"
CORRECTION_RUN_BASE_RENDER="${CORRECTION_RUN_BASE_RENDER:-1}"
CORRECTION_RUN_RENDER_COMPARE="${CORRECTION_RUN_RENDER_COMPARE:-1}"

case "${CORRECTION_PROFILE}" in
  safe_v0)
    ;;
  aggressive_v1)
    DETECT_SELECT_QUANTILE="${DETECT_SELECT_QUANTILE:-0.985}"
    DETECT_GLOBAL_PREFILTER_MAX_FRACTION="${DETECT_GLOBAL_PREFILTER_MAX_FRACTION:-0.15}"
    DETECT_MAX_CANDIDATE_FRACTION="${DETECT_MAX_CANDIDATE_FRACTION:-0.04}"
    DETECT_MAX_CANDIDATE_COUNT="${DETECT_MAX_CANDIDATE_COUNT:-80000}"
    CORRECTION_EXTRA_ITERS="${CORRECTION_EXTRA_ITERS:-4000}"
    CORRECTION_GAUSSIAN_UPDATE_SCALE="${CORRECTION_GAUSSIAN_UPDATE_SCALE:-4.0}"
    CORRECTION_XYZ_LR="${CORRECTION_XYZ_LR:-8e-5}"
    CORRECTION_OPACITY_LR="${CORRECTION_OPACITY_LR:-1e-3}"
    CORRECTION_SCALE_LR="${CORRECTION_SCALE_LR:-2e-4}"
    CORRECTION_LAMBDA_RGB_PRESERVE="${CORRECTION_LAMBDA_RGB_PRESERVE:-0.35}"
    CORRECTION_LAMBDA_ANCHOR="${CORRECTION_LAMBDA_ANCHOR:-10.0}"
    CORRECTION_MAX_DISPLACEMENT_RATIO="${CORRECTION_MAX_DISPLACEMENT_RATIO:-0.006}"
    CORRECTION_SR_PRIOR_L1_WEIGHT="${CORRECTION_SR_PRIOR_L1_WEIGHT:-0.08}"
    CORRECTION_SR_PRIOR_HF_WEIGHT="${CORRECTION_SR_PRIOR_HF_WEIGHT:-0.45}"
    CORRECTION_ENABLE_OPACITY_UPDATE="${CORRECTION_ENABLE_OPACITY_UPDATE:-1}"
    CORRECTION_ENABLE_SCALE_UPDATE="${CORRECTION_ENABLE_SCALE_UPDATE:-1}"
    ;;
  major_axis_probe_v0)
    CORRECTION_EXTRA_ITERS="${CORRECTION_EXTRA_ITERS:-800}"
    DETECT_SELECT_QUANTILE="${DETECT_SELECT_QUANTILE:-0.985}"
    DETECT_GLOBAL_PREFILTER_MAX_FRACTION="${DETECT_GLOBAL_PREFILTER_MAX_FRACTION:-0.15}"
    DETECT_MAX_CANDIDATE_FRACTION="${DETECT_MAX_CANDIDATE_FRACTION:-0.04}"
    DETECT_MAX_CANDIDATE_COUNT="${DETECT_MAX_CANDIDATE_COUNT:-80000}"
    CORRECTION_GAUSSIAN_UPDATE_SCALE="${CORRECTION_GAUSSIAN_UPDATE_SCALE:-1.5}"
    CORRECTION_GAUSSIAN_SCALE_AXIS_MODE="${CORRECTION_GAUSSIAN_SCALE_AXIS_MODE:-major_only}"
    CORRECTION_GAUSSIAN_SCALE_MIN_MULTIPLIER="${CORRECTION_GAUSSIAN_SCALE_MIN_MULTIPLIER:-0.4}"
    CORRECTION_GAUSSIAN_SCALE_MAX_MULTIPLIER="${CORRECTION_GAUSSIAN_SCALE_MAX_MULTIPLIER:-1.0}"
    CORRECTION_XYZ_LR="${CORRECTION_XYZ_LR:-0.0}"
    CORRECTION_OPACITY_LR="${CORRECTION_OPACITY_LR:-0.0}"
    CORRECTION_SCALE_LR="${CORRECTION_SCALE_LR:-2e-4}"
    CORRECTION_LAMBDA_RGB_PRESERVE="${CORRECTION_LAMBDA_RGB_PRESERVE:-1.0}"
    CORRECTION_LAMBDA_SCALE_ANCHOR="${CORRECTION_LAMBDA_SCALE_ANCHOR:-0.05}"
    CORRECTION_LAMBDA_ANCHOR="${CORRECTION_LAMBDA_ANCHOR:-50.0}"
    CORRECTION_MAX_DISPLACEMENT_RATIO="${CORRECTION_MAX_DISPLACEMENT_RATIO:-0.0}"
    CORRECTION_SR_PRIOR_L1_WEIGHT="${CORRECTION_SR_PRIOR_L1_WEIGHT:-0.02}"
    CORRECTION_SR_PRIOR_HF_WEIGHT="${CORRECTION_SR_PRIOR_HF_WEIGHT:-0.0}"
    CORRECTION_ENABLE_OPACITY_UPDATE="${CORRECTION_ENABLE_OPACITY_UPDATE:-0}"
    CORRECTION_ENABLE_SCALE_UPDATE="${CORRECTION_ENABLE_SCALE_UPDATE:-1}"
    ;;
  *)
    echo "[mipsof-starcorr-v0] unsupported CORRECTION_PROFILE=${CORRECTION_PROFILE}; use safe_v0, aggressive_v1, or major_axis_probe_v0" >&2
    exit 1
    ;;
esac

if [[ -z "${CORRECTION_FINAL_ITERATION:-}" ]]; then
  CORRECTION_FINAL_ITERATION="$((BASE_ITERATION + CORRECTION_EXTRA_ITERS))"
else
  CORRECTION_FINAL_ITERATION="${CORRECTION_FINAL_ITERATION}"
fi

validate_quality_fused_priors() {
  (
    cd "${SOF_ROOT}/.."
    "${PYTHON_BIN}" "${SOF_ROOT}/../mip-splatting/hybrid_sdfgs/tools/validate_prepared_sr_priors.py" \
      --output_root "${QUALITY_FUSE_ROOT}" \
      --prior_subdir "fused_priors" \
      --mask_subdir "usable_masks"
  )
}

ensure_raw_mip_references() {
  local need_render=0
  if [[ "${RUN_DETECT}" == "1" && ! -d "${DETECT_REFERENCE_DIR}" ]]; then
    need_render=1
  fi
  if [[ "${RUN_BUILD_QUALITY_PRIORS}" == "1" ]]; then
    if [[ ! -d "${QUALITY_FUSE_STABLE_DIR}" || ! -d "${QUALITY_FUSE_REFERENCE_DIR}" ]]; then
      need_render=1
    fi
  fi
  if [[ "${need_render}" != "1" ]]; then
    return
  fi
  if [[ "${PREPARE_RAW_MIP_REFERENCES_IF_MISSING}" != "1" ]]; then
    return
  fi
  if [[ ! -e "${RAW_MIP_MODEL_PATH}/point_cloud/iteration_${BASELINE_ITERATION}/point_cloud.ply" ]]; then
    echo "[mipsof-starcorr-v0] raw mip model missing for reference rendering: ${RAW_MIP_MODEL_PATH}/point_cloud/iteration_${BASELINE_ITERATION}/point_cloud.ply" >&2
    exit 1
  fi
  echo
  echo "[0/4] render raw mip references (train+test) for detect and quality fuse"
  "${PYTHON_BIN}" -u "${SOF_ROOT}/scripts/render_model_no_gt.py" \
    --scene_root "${SCENE_ROOT}" \
    --model_path "${RAW_MIP_MODEL_PATH}" \
    --output_dir "${RAW_MIP_RENDER_ROOT}" \
    --images_subdir "${RENDER_IMAGES_SUBDIR}" \
    --iteration "${BASELINE_ITERATION}" \
    --split both
}

echo "[mipsof-starcorr-v0] scene            : ${SCENE_ROOT}"
echo "[mipsof-starcorr-v0] base latest run  : ${BASE_MODEL_PATH} iter=${BASE_ITERATION}"
echo "[mipsof-starcorr-v0] detect reference : ${DETECT_REFERENCE_DIR}"
echo "[mipsof-starcorr-v0] quality stable   : ${QUALITY_FUSE_STABLE_DIR}"
echo "[mipsof-starcorr-v0] quality ref      : ${QUALITY_FUSE_REFERENCE_DIR}"
echo "[mipsof-starcorr-v0] starburst score  : ${STARBURST_SCORE_PAYLOAD}"
echo "[mipsof-starcorr-v0] quality priors   : ${QUALITY_FUSE_ROOT}"
echo "[mipsof-starcorr-v0] correction tune  : profile=${CORRECTION_PROFILE} extra_iters=${CORRECTION_EXTRA_ITERS} update_scale=${CORRECTION_GAUSSIAN_UPDATE_SCALE} axis=${CORRECTION_GAUSSIAN_SCALE_AXIS_MODE} range=[${CORRECTION_GAUSSIAN_SCALE_MIN_MULTIPLIER},${CORRECTION_GAUSSIAN_SCALE_MAX_MULTIPLIER}] xyz_lr=${CORRECTION_XYZ_LR:-<default>} anchor=${CORRECTION_LAMBDA_ANCHOR:-<default>} max_disp=${CORRECTION_MAX_DISPLACEMENT_RATIO:-<default>}"
echo "[mipsof-starcorr-v0] correction model : ${CORRECTION_OUTPUT_MODEL} iter=${CORRECTION_FINAL_ITERATION}"

for path in "${SCENE_ROOT}" "${RAW_SR_PRIOR_DIR}" "${SOF_SURFACE_MODEL}"; do
  if [[ ! -e "${path}" ]]; then
    echo "[mipsof-starcorr-v0] required path not found: ${path}" >&2
    exit 1
  fi
done

if [[ ! -d "${SCENE_ROOT}/${RENDER_IMAGES_SUBDIR}" ]]; then
  echo "[mipsof-starcorr-v0] render image dir missing: ${SCENE_ROOT}/${RENDER_IMAGES_SUBDIR}" >&2
  exit 1
fi

if [[ ! -e "${BASE_MODEL_PATH}/point_cloud/iteration_${BASE_ITERATION}/point_cloud.ply" ]]; then
  if [[ "${RUN_BASE_MAINLINE_IF_MISSING}" != "1" ]]; then
    echo "[mipsof-starcorr-v0] base mainline model missing: ${BASE_MODEL_PATH}/point_cloud/iteration_${BASE_ITERATION}/point_cloud.ply" >&2
    echo "[mipsof-starcorr-v0] rerun with RUN_BASE_MAINLINE_IF_MISSING=1 or pass BASE_MODEL_PATH." >&2
    exit 1
  fi
  echo
  echo "[1/4] build latest mip->SOF base run"
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
  MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP}" \
  MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
  MIP_MODEL_PATH="${RAW_MIP_MODEL_PATH}" \
  MIP_INPUT_MODEL_PATH="${RAW_MIP_INPUT_MODEL_PATH}" \
  SOF_SURFACE_MODEL="${SOF_SURFACE_MODEL}" \
  SOF_SURFACE_ITERATION="${SOF_SURFACE_ITERATION}" \
  RUN_NAME="${BASE_RUN_NAME}" \
  RUN_ROOT="${BASE_RUN_ROOT}" \
  OUTPUT_MODEL="${BASE_MODEL_PATH}" \
  BASELINE_ITERATION="${BASELINE_ITERATION}" \
  FINAL_ITERATION="${BASE_ITERATION}" \
  MIP_ITERATION="${BASELINE_ITERATION}" \
  OUTPUT_ITERATION="${BASE_ITERATION}" \
  SURFACE_IMAGES_SUBDIR="${SURFACE_IMAGES_SUBDIR}" \
  RENDER_IMAGES_SUBDIR="${RENDER_IMAGES_SUBDIR}" \
  RENDER_SPLIT="${RENDER_SPLIT}" \
  SR_IMAGES_SUBDIR="${SR_IMAGES_SUBDIR}" \
  SR_PRIOR_DIR="${RAW_SR_PRIOR_DIR}" \
  PREPARED_SR_PRIOR_ROOT="${BASE_PREPARED_SR_PRIOR_ROOT}" \
  SR_MASK_THRESHOLD="${SR_MASK_THRESHOLD}" \
  SR_MASK_MODE="${SR_MASK_MODE}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SCRIPT_DIR}/run_mip_to_sof_surface_v0_kitchen.sh"
fi

ensure_raw_mip_references

if [[ ! -e "${BASE_MODEL_PATH}/point_cloud/iteration_${BASE_ITERATION}/point_cloud.ply" ]]; then
  echo "[mipsof-starcorr-v0] base mainline model still missing after stage 1: ${BASE_MODEL_PATH}/point_cloud/iteration_${BASE_ITERATION}/point_cloud.ply" >&2
  exit 1
fi

if [[ ! -d "${IE_SRGS_MASK_DIR}" ]]; then
  echo "[mipsof-starcorr-v0] IE-SRGS mask dir missing: ${IE_SRGS_MASK_DIR}" >&2
  exit 1
fi

if [[ "${RUN_DETECT}" == "1" && ! -d "${DETECT_REFERENCE_DIR}" ]]; then
  echo "[mipsof-starcorr-v0] detect reference dir missing: ${DETECT_REFERENCE_DIR}" >&2
  echo "[mipsof-starcorr-v0] rerender raw mip references or pass DETECT_REFERENCE_DIR." >&2
  exit 1
fi

if [[ "${RUN_BUILD_QUALITY_PRIORS}" == "1" && ! -d "${QUALITY_FUSE_STABLE_DIR}" ]]; then
  echo "[mipsof-starcorr-v0] quality stable dir missing: ${QUALITY_FUSE_STABLE_DIR}" >&2
  echo "[mipsof-starcorr-v0] rerender raw mip references or pass QUALITY_FUSE_STABLE_DIR." >&2
  exit 1
fi

if [[ "${RUN_BUILD_QUALITY_PRIORS}" == "1" && ! -d "${QUALITY_FUSE_REFERENCE_DIR}" ]]; then
  echo "[mipsof-starcorr-v0] quality reference dir missing: ${QUALITY_FUSE_REFERENCE_DIR}" >&2
  echo "[mipsof-starcorr-v0] rerender raw mip references or pass QUALITY_FUSE_REFERENCE_DIR." >&2
  exit 1
fi

if [[ "${RUN_DETECT}" == "1" ]]; then
  echo
  echo "[2/4] detect starburst gaussians from mip-vs-SOF image residual"
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  MODEL_PATH="${BASE_MODEL_PATH}" \
  ITERATION="${BASE_ITERATION}" \
  RUN_NAME="${DETECT_RUN_NAME}" \
  OUTPUT_DIR="${DETECT_OUTPUT_DIR}" \
  INTERACTION_IMAGES_SUBDIR="${DETECT_INTERACTION_IMAGES_SUBDIR}" \
  REFERENCE_SOURCE="custom" \
  REFERENCE_IMAGE_DIR="${DETECT_REFERENCE_DIR}" \
  SPLIT="${DETECT_SPLIT}" \
  MAX_VIEWS="${DETECT_MAX_VIEWS}" \
  VIEW_INDICES="${DETECT_VIEW_INDICES}" \
  SELECT_QUANTILE="${DETECT_SELECT_QUANTILE}" \
  MIN_STAR_SCORE="${DETECT_MIN_STAR_SCORE}" \
  MIN_UNSUPPORTED_SCORE="${DETECT_MIN_UNSUPPORTED_SCORE}" \
  MIN_STAR_VIEW_COUNT="${DETECT_MIN_STAR_VIEW_COUNT}" \
  GLOBAL_LONG_AXIS_QUANTILE="${DETECT_GLOBAL_LONG_AXIS_QUANTILE}" \
  GLOBAL_ANISOTROPY_QUANTILE="${DETECT_GLOBAL_ANISOTROPY_QUANTILE}" \
  GLOBAL_RADIUS_MAX_QUANTILE="${DETECT_GLOBAL_RADIUS_MAX_QUANTILE}" \
  GLOBAL_PREFILTER_MIN_HITS="${DETECT_GLOBAL_PREFILTER_MIN_HITS}" \
  GLOBAL_PREFILTER_MAX_FRACTION="${DETECT_GLOBAL_PREFILTER_MAX_FRACTION}" \
  GLOBAL_PREFILTER_MAX_COUNT="${DETECT_GLOBAL_PREFILTER_MAX_COUNT}" \
  MAX_CANDIDATE_FRACTION="${DETECT_MAX_CANDIDATE_FRACTION}" \
  MAX_CANDIDATE_COUNT="${DETECT_MAX_CANDIDATE_COUNT}" \
  EXPORT_CANDIDATE_MODEL=0 \
  RENDER_CANDIDATE_AFTER=0 \
  CONDA_ENV_NAME="${CONDA_ENV_NAME}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SCRIPT_DIR}/run_detect_starburst_gaussian_artifacts_v0_kitchen.sh"
fi

if [[ ! -f "${STARBURST_SCORE_PAYLOAD}" ]]; then
  echo "[mipsof-starcorr-v0] starburst payload missing: ${STARBURST_SCORE_PAYLOAD}" >&2
  exit 1
fi

if [[ "${RUN_BUILD_QUALITY_PRIORS}" == "1" ]]; then
  echo
  echo "[3/4] build mip-stable + SOF-detail fused SR priors"
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
  DETAIL_MODEL_PATH="${BASE_MODEL_PATH}" \
  DETAIL_ITERATION="${BASE_ITERATION}" \
  STABLE_PRIOR_DIR="${QUALITY_FUSE_STABLE_DIR}" \
  REFERENCE_DIR="${QUALITY_FUSE_REFERENCE_DIR}" \
  SOURCE_MASK_DIR="${QUALITY_FUSE_SOURCE_MASK_DIR}" \
  QUALITY_FUSE_PROFILE="${QUALITY_FUSE_PROFILE}" \
  QUALITY_FUSE_NAME="${QUALITY_FUSE_NAME}" \
  OUTPUT_ROOT="${QUALITY_FUSE_ROOT}" \
  IMAGES_SUBDIR="${QUALITY_FUSE_IMAGES_SUBDIR}" \
  SPLIT="${QUALITY_FUSE_SPLIT}" \
  MAX_VIEWS="${QUALITY_FUSE_MAX_VIEWS}" \
  DEBUG_VIEWS="${QUALITY_FUSE_DEBUG_VIEWS}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SCRIPT_DIR}/run_build_quality_fused_sr_priors_v0_kitchen.sh"
fi

if [[ ! -f "${QUALITY_FUSE_ROOT}/manifest.json" || ! -d "${QUALITY_FUSE_ROOT}/fused_priors" || ! -d "${QUALITY_FUSE_ROOT}/usable_masks" ]]; then
  echo "[mipsof-starcorr-v0] quality-fused prior root incomplete: ${QUALITY_FUSE_ROOT}" >&2
  exit 1
fi

validate_quality_fused_priors

if [[ "${RUN_CORRECTION}" == "1" ]]; then
  echo
  echo "[4/4] masked starburst correction on latest mip->SOF mainline"
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
  MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP}" \
  MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
  PREPARE_INPUT_IF_MISSING=0 \
  MIP_MODEL_PATH="${BASE_MODEL_PATH}" \
  MIP_INPUT_MODEL_PATH="${BASE_MODEL_PATH}" \
  SOF_SURFACE_MODEL="${SOF_SURFACE_MODEL}" \
  SOF_SURFACE_ITERATION="${SOF_SURFACE_ITERATION}" \
  RUN_NAME="${CORRECTION_RUN_NAME}" \
  RUN_ROOT="${CORRECTION_RUN_ROOT}" \
  OUTPUT_MODEL="${CORRECTION_OUTPUT_MODEL}" \
  BASELINE_ITERATION="${BASE_ITERATION}" \
  FINAL_ITERATION="${CORRECTION_FINAL_ITERATION}" \
  MIP_ITERATION="${BASE_ITERATION}" \
  OUTPUT_ITERATION="${CORRECTION_FINAL_ITERATION}" \
  SURFACE_IMAGES_SUBDIR="${SURFACE_IMAGES_SUBDIR}" \
  RENDER_IMAGES_SUBDIR="${RENDER_IMAGES_SUBDIR}" \
  RENDER_SPLIT="${RENDER_SPLIT}" \
  SR_IMAGES_SUBDIR="${SR_IMAGES_SUBDIR}" \
  SR_PRIOR_DIR="${RAW_SR_PRIOR_DIR}" \
  PREPARED_SR_PRIOR_ROOT="${QUALITY_FUSE_ROOT}" \
  SR_PRIOR_SUBDIR="fused_priors" \
  SR_PRIOR_MASK_SUBDIR="usable_masks" \
  SR_ANCHOR_SUBDIR="aligned_references" \
  SR_MASK_THRESHOLD="${SR_MASK_THRESHOLD}" \
  SR_MASK_MODE="${SR_MASK_MODE}" \
  XYZ_LR="${CORRECTION_XYZ_LR}" \
  OPACITY_LR="${CORRECTION_OPACITY_LR}" \
  SCALE_LR="${CORRECTION_SCALE_LR}" \
  LAMBDA_RGB_PRESERVE="${CORRECTION_LAMBDA_RGB_PRESERVE}" \
  LAMBDA_SCALE_ANCHOR="${CORRECTION_LAMBDA_SCALE_ANCHOR}" \
  LAMBDA_ANCHOR="${CORRECTION_LAMBDA_ANCHOR}" \
  MAX_DISPLACEMENT_RATIO="${CORRECTION_MAX_DISPLACEMENT_RATIO}" \
  SR_PRIOR_L1_WEIGHT="${CORRECTION_SR_PRIOR_L1_WEIGHT}" \
  SR_PRIOR_HF_WEIGHT="${CORRECTION_SR_PRIOR_HF_WEIGHT}" \
  ENABLE_OPACITY_UPDATE="${CORRECTION_ENABLE_OPACITY_UPDATE}" \
  ENABLE_SCALE_UPDATE="${CORRECTION_ENABLE_SCALE_UPDATE}" \
  OPTIMIZE_GAUSSIAN_MASK_PAYLOAD="${STARBURST_SCORE_PAYLOAD}" \
  OPTIMIZE_GAUSSIAN_MASK_KEY="${STARBURST_MASK_KEY}" \
  GAUSSIAN_UPDATE_SCALE="${CORRECTION_GAUSSIAN_UPDATE_SCALE}" \
  GAUSSIAN_SCALE_AXIS_MODE="${CORRECTION_GAUSSIAN_SCALE_AXIS_MODE}" \
  GAUSSIAN_SCALE_MIN_MULTIPLIER="${CORRECTION_GAUSSIAN_SCALE_MIN_MULTIPLIER}" \
  GAUSSIAN_SCALE_MAX_MULTIPLIER="${CORRECTION_GAUSSIAN_SCALE_MAX_MULTIPLIER}" \
  RUN_BASE_RENDER="${CORRECTION_RUN_BASE_RENDER}" \
  RUN_RENDER="${CORRECTION_RUN_RENDER}" \
  RUN_RENDER_COMPARE="${CORRECTION_RUN_RENDER_COMPARE}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SCRIPT_DIR}/run_mip_to_sof_surface_v0_kitchen.sh"
fi

echo
echo "[done] base latest run  : ${BASE_MODEL_PATH}"
echo "[done] detect reference : ${DETECT_REFERENCE_DIR}"
echo "[done] quality stable   : ${QUALITY_FUSE_STABLE_DIR}"
echo "[done] quality ref      : ${QUALITY_FUSE_REFERENCE_DIR}"
echo "[done] starburst score  : ${STARBURST_SCORE_PAYLOAD}"
echo "[done] quality priors   : ${QUALITY_FUSE_ROOT}"
if [[ "${RUN_CORRECTION}" == "1" ]]; then
  echo "[done] corrected model  : ${CORRECTION_OUTPUT_MODEL}"
fi
