#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"

SCENE_NAME="${SCENE_NAME:-kitchen}" \
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
OUTPUT_NAME="${OUTPUT_NAME:-${MIP_EXPERIMENT_NAME}_sof_native_input_init_energy_curve_refit_v0}" \
INIT_REPAIR_MODE="${INIT_REPAIR_MODE:-energy_split_replace}" \
CONDA_ENV_NAME="${CONDA_ENV_NAME:-srtest}" \
INIT_REPAIR_MAX_FRACTION="${INIT_REPAIR_MAX_FRACTION:-0.05}" \
INIT_REPAIR_MAX_COUNT="${INIT_REPAIR_MAX_COUNT:-90000}" \
INIT_REPAIR_MIN_OPACITY="${INIT_REPAIR_MIN_OPACITY:-0.035}" \
INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO="${INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO:-0.0022}" \
INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO="${INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO:-0.0010}" \
INIT_REPAIR_MIN_FILTER_SCALE_RATIO="${INIT_REPAIR_MIN_FILTER_SCALE_RATIO:-0.45}" \
INIT_REPAIR_MIN_FULL_ANISOTROPY="${INIT_REPAIR_MIN_FULL_ANISOTROPY:-5.0}" \
INIT_REPAIR_SPLIT_COUNT="${INIT_REPAIR_SPLIT_COUNT:-6}" \
INIT_REPAIR_CHILD_LAYOUT="${INIT_REPAIR_CHILD_LAYOUT:-major_axis}" \
INIT_REPAIR_CHILD_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_SCALE_MULTIPLIER:-0.80}" \
INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER:-0.32}" \
INIT_REPAIR_CHILD_OPACITY_SCALE="${INIT_REPAIR_CHILD_OPACITY_SCALE:-1.0}" \
INIT_REPAIR_ENERGY_CONSERVE_MODE="${INIT_REPAIR_ENERGY_CONSERVE_MODE:-area}" \
INIT_REPAIR_FILTER_SCALE="${INIT_REPAIR_FILTER_SCALE:-0.35}" \
INIT_REPAIR_FILTER_CAP_RATIO="${INIT_REPAIR_FILTER_CAP_RATIO:-0.0010}" \
INIT_REPAIR_OFFSET_SCALE="${INIT_REPAIR_OFFSET_SCALE:-0.85}" \
bash "${SCRIPT_DIR}/run_prepare_hrgs_mip_input_scene.sh"
