#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

BASE_RUN_NAME="${BASE_RUN_NAME:-k27_base}"
BASE_MODEL_NAME="${BASE_MODEL_NAME:-recovered_mip_model_lr_miphr_v1}"
BASE_ITERATION="${BASE_ITERATION:-31600}"
BASE_MODEL_PATH="${BASE_MODEL_PATH:-${SOF_ROOT}/output/recover_cleaned_mip_lr_v0/${SCENE_NAME}/${BASE_RUN_NAME}/${BASE_MODEL_NAME}}"

QUALITY_PRIOR_NAME="${QUALITY_PRIOR_NAME:-quality_fuse_v1_${BASE_RUN_NAME}_mip30ksr_safe_hf_v1}"
QUALITY_PRIOR_ROOT="${QUALITY_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/${QUALITY_PRIOR_NAME}}"

MIP_GROUP_NAME="${MIP_GROUP_NAME:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_PARENT_NAME="${MIP_PARENT_NAME:-mip30k_sof_native_input_init_repair_v0}"
MIP_PARENT_MODEL_PATH="${MIP_PARENT_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_GROUP_NAME}/${MIP_PARENT_NAME}}"
MIP_PARENT_ITERATION="${MIP_PARENT_ITERATION:-30000}"

RUN_NAME="${RUN_NAME:-${BASE_RUN_NAME}_hf_error_correct_rest_v0}"
ITERATIONS="${ITERATIONS:-700}"
OUTPUT_ITERATION="${OUTPUT_ITERATION:-$((BASE_ITERATION + ITERATIONS))}"

echo "[hf-error-correct-rest-v0] base model  : ${BASE_MODEL_PATH} iter=${BASE_ITERATION}"
echo "[hf-error-correct-rest-v0] prior root  : ${QUALITY_PRIOR_ROOT}"
echo "[hf-error-correct-rest-v0] mip parent  : ${MIP_PARENT_MODEL_PATH} iter=${MIP_PARENT_ITERATION}"
echo "[hf-error-correct-rest-v0] output run  : ${RUN_NAME} iter=${OUTPUT_ITERATION}"
echo "[hf-error-correct-rest-v0] mode        : freeze xyz/opacity/scale, lightly update DC/rest-SH from image-domain HF losses"

START_MODEL_PATH="${BASE_MODEL_PATH}" \
START_ITERATION="${BASE_ITERATION}" \
ANCHOR_MODEL_PATH="${MIP_PARENT_MODEL_PATH}" \
ANCHOR_ITERATION="${MIP_PARENT_ITERATION}" \
MIP_CLOSURE_MODEL_PATH="${MIP_PARENT_MODEL_PATH}" \
MIP_CLOSURE_ITERATION="${MIP_PARENT_ITERATION}" \
RUN_NAME="${RUN_NAME}" \
REFINE_PROFILE="mip_hr_anchor_v0" \
ITERATIONS="${ITERATIONS}" \
OUTPUT_ITERATION="${OUTPUT_ITERATION}" \
IMAGES_SUBDIR="${IMAGES_SUBDIR:-images_8}" \
MAX_VIEWS="${MAX_VIEWS:-20}" \
USE_SR_PRIOR="1" \
SR_PRIOR_ROOT="${QUALITY_PRIOR_ROOT}" \
SR_PRIOR_SUBDIR="${SR_PRIOR_SUBDIR:-fused_priors}" \
SR_PRIOR_MASK_SUBDIR="${SR_PRIOR_MASK_SUBDIR:-usable_masks}" \
SR_ANCHOR_SUBDIR="${SR_ANCHOR_SUBDIR:-aligned_references}" \
SR_IMAGES_SUBDIR="${SR_IMAGES_SUBDIR:-images_2}" \
SR_MAX_VIEWS="${SR_MAX_VIEWS:-20}" \
SR_RESIDUAL_ANCHOR="${SR_RESIDUAL_ANCHOR:-mip_hr}" \
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT:-0.018}" \
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT:-0.11}" \
SR_PRIOR_START_SCALE="${SR_PRIOR_START_SCALE:-0.35}" \
SR_PRIOR_END_SCALE="${SR_PRIOR_END_SCALE:-0.60}" \
SR_PRIOR_UPDATE_SCALE="${SR_PRIOR_UPDATE_SCALE:-0.45}" \
SR_PRIOR_WARMUP_START_ITER="${SR_PRIOR_WARMUP_START_ITER:-1}" \
SR_PRIOR_WARMUP_END_ITER="${SR_PRIOR_WARMUP_END_ITER:-450}" \
SR_PRIOR_DELTA_CLIP="${SR_PRIOR_DELTA_CLIP:-0.055}" \
SR_PRIOR_CONSISTENCY_THRESHOLD="${SR_PRIOR_CONSISTENCY_THRESHOLD:-0.085}" \
SR_PRIOR_MIN_VALID_RATIO="${SR_PRIOR_MIN_VALID_RATIO:-0.45}" \
SR_PRIOR_MIN_PIXELS="${SR_PRIOR_MIN_PIXELS:-96}" \
LAMBDA_PREMUL_HF_EXCESS="${LAMBDA_PREMUL_HF_EXCESS:-0.16}" \
PREMUL_HF_EXCESS_KERNEL="${PREMUL_HF_EXCESS_KERNEL:-9}" \
PREMUL_HF_EXCESS_RATIO="${PREMUL_HF_EXCESS_RATIO:-1.00}" \
PREMUL_HF_EXCESS_MARGIN="${PREMUL_HF_EXCESS_MARGIN:-0.0045}" \
LAMBDA_MIP_HR_LOWFREQ="${LAMBDA_MIP_HR_LOWFREQ:-0.18}" \
MIP_HR_LOWFREQ_KERNEL="${MIP_HR_LOWFREQ_KERNEL:-25}" \
MIP_HR_LOWFREQ_CONSISTENCY_THRESHOLD="${MIP_HR_LOWFREQ_CONSISTENCY_THRESHOLD:-0.18}" \
MIP_CLOSURE_IMAGES_SUBDIR="${MIP_CLOSURE_IMAGES_SUBDIR:-images_2}" \
MIP_CLOSURE_MAX_VIEWS="${MIP_CLOSURE_MAX_VIEWS:-20}" \
LAMBDA_MIP_CLOSURE_ALPHA="${LAMBDA_MIP_CLOSURE_ALPHA:-0.06}" \
LAMBDA_MIP_CLOSURE_PREMUL="${LAMBDA_MIP_CLOSURE_PREMUL:-0.18}" \
LAMBDA_MIP_CLOSURE_DEPTH="${LAMBDA_MIP_CLOSURE_DEPTH:-0.01}" \
LAMBDA_MIP_CLOSURE_ALPHA_OVER="${LAMBDA_MIP_CLOSURE_ALPHA_OVER:-0.05}" \
LAMBDA_MIP_CLOSURE_PREMUL_OVER="${LAMBDA_MIP_CLOSURE_PREMUL_OVER:-0.28}" \
LAMBDA_LR_RGB="${LAMBDA_LR_RGB:-1.0}" \
LAMBDA_XYZ_ANCHOR="${LAMBDA_XYZ_ANCHOR:-200.0}" \
XYZ_LR="${XYZ_LR:-0.0}" \
ENABLE_OPACITY_UPDATE="0" \
ENABLE_SCALE_UPDATE="0" \
ENABLE_DC_UPDATE="${ENABLE_DC_UPDATE:-1}" \
ENABLE_REST_UPDATE="${ENABLE_REST_UPDATE:-1}" \
DC_LR="${DC_LR:-2e-5}" \
REST_LR="${REST_LR:-2e-4}" \
LAMBDA_DC_ANCHOR="${LAMBDA_DC_ANCHOR:-0.18}" \
LAMBDA_REST_ANCHOR="${LAMBDA_REST_ANCHOR:-0.045}" \
LAMBDA_RISK_REST="${LAMBDA_RISK_REST:-0.018}" \
LAMBDA_SR_RISK_REST="${LAMBDA_SR_RISK_REST:-0.045}" \
SR_RISK_BOOST="${SR_RISK_BOOST:-1.8}" \
RECOMPUTE_FILTER3D_BEFORE_TRAIN="${RECOMPUTE_FILTER3D_BEFORE_TRAIN:-1}" \
RECOMPUTE_FILTER3D="${RECOMPUTE_FILTER3D:-1}" \
RUN_RENDER="${RUN_RENDER:-1}" \
RENDER_IMAGES_SUBDIR="${RENDER_IMAGES_SUBDIR:-images_2}" \
RENDER_SPLIT="${RENDER_SPLIT:-test}" \
bash "${SOF_ROOT}/scripts/run_recover_cleaned_mip_lr_v0_kitchen.sh"
