#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"

SCENE_NAME="${SCENE_NAME:-kitchen}" \
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
OUTPUT_NAME="${OUTPUT_NAME:-${MIP_EXPERIMENT_NAME}_sof_native_input_init_early4ksoft_v1}" \
SCALE_CLAMP_MODE="${SCALE_CLAMP_MODE:-max_only}" \
INIT_REPAIR_MODE="${INIT_REPAIR_MODE:-energy_split_replace_soften_bright}" \
CONDA_ENV_NAME="${CONDA_ENV_NAME:-srtest}" \
INIT_REPAIR_MAX_FRACTION="${INIT_REPAIR_MAX_FRACTION:-0.05}" \
INIT_REPAIR_MAX_COUNT="${INIT_REPAIR_MAX_COUNT:-90000}" \
INIT_REPAIR_MIN_OPACITY="${INIT_REPAIR_MIN_OPACITY:-0.035}" \
INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO="${INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO:-0.0022}" \
INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO="${INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO:-0.0010}" \
INIT_REPAIR_MIN_FILTER_SCALE_RATIO="${INIT_REPAIR_MIN_FILTER_SCALE_RATIO:-0.45}" \
INIT_REPAIR_MIN_FULL_ANISOTROPY="${INIT_REPAIR_MIN_FULL_ANISOTROPY:-5.0}" \
INIT_REPAIR_SPLIT_COUNT="${INIT_REPAIR_SPLIT_COUNT:-6}" \
INIT_REPAIR_CHILD_LAYOUT="${INIT_REPAIR_CHILD_LAYOUT:-major_axis}" \
INIT_REPAIR_CHILD_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_SCALE_MULTIPLIER:-0.80}" \
INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER:-0.32}" \
INIT_REPAIR_CHILD_OPACITY_SCALE="${INIT_REPAIR_CHILD_OPACITY_SCALE:-1.0}" \
INIT_REPAIR_ENERGY_CONSERVE_MODE="${INIT_REPAIR_ENERGY_CONSERVE_MODE:-area}" \
INIT_REPAIR_FILTER_SCALE="${INIT_REPAIR_FILTER_SCALE:-0.35}" \
INIT_REPAIR_FILTER_CAP_RATIO="${INIT_REPAIR_FILTER_CAP_RATIO:-0.0010}" \
INIT_REPAIR_OFFSET_SCALE="${INIT_REPAIR_OFFSET_SCALE:-0.85}" \
INIT_REPAIR_BRIGHT_MAX_FRACTION="${INIT_REPAIR_BRIGHT_MAX_FRACTION:-0.015}" \
INIT_REPAIR_BRIGHT_MAX_COUNT="${INIT_REPAIR_BRIGHT_MAX_COUNT:-25000}" \
INIT_REPAIR_BRIGHT_TARGET="${INIT_REPAIR_BRIGHT_TARGET:-children_only}" \
INIT_REPAIR_BRIGHT_MIN_OPACITY="${INIT_REPAIR_BRIGHT_MIN_OPACITY:-0.020}" \
INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO="${INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO:-0.0022}" \
INIT_REPAIR_BRIGHT_LUMA_QUANTILE="${INIT_REPAIR_BRIGHT_LUMA_QUANTILE:-0.985}" \
INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO="${INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO:-1.15}" \
INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA="${INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA:-0.045}" \
INIT_REPAIR_BRIGHT_NEIGHBOR_K="${INIT_REPAIR_BRIGHT_NEIGHBOR_K:-12}" \
INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER="${INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER:-1.20}" \
INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER="${INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER:-1.15}" \
INIT_REPAIR_BRIGHT_OPACITY_SCALE="${INIT_REPAIR_BRIGHT_OPACITY_SCALE:-0.55}" \
INIT_REPAIR_BRIGHT_DC_SCALE="${INIT_REPAIR_BRIGHT_DC_SCALE:-0.78}" \
INIT_REPAIR_BRIGHT_REST_SCALE="${INIT_REPAIR_BRIGHT_REST_SCALE:-0.10}" \
INIT_REPAIR_BRIGHT_FILTER_SCALE="${INIT_REPAIR_BRIGHT_FILTER_SCALE:-1.20}" \
INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO="${INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO:-0.0010}" \
bash "${SCRIPT_DIR}/run_prepare_hrgs_mip_input_scene.sh"
