#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"
ANCHOR_MODEL_PATH="${ANCHOR_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}_sof_native_input_init_repair_v0}"
ANCHOR_ITERATION="${ANCHOR_ITERATION:-30000}"
BASE_RUN_NAME="${BASE_RUN_NAME:-k27_base}"
BASE_MODEL_NAME="${BASE_MODEL_NAME:-recovered_mip_model_lr_miphr_v1}"
BASE_MODEL_PATH="${BASE_MODEL_PATH:-${SOF_ROOT}/output/recover_cleaned_mip_lr_v0/${SCENE_NAME}/${BASE_RUN_NAME}/${BASE_MODEL_NAME}}"
BASE_ITERATION="${BASE_ITERATION:-31600}"

QUARANTINE_PROFILE="${QUARANTINE_PROFILE:-gentle_safe_hf_v1}"
QUARANTINE_RUN_NAME="${QUARANTINE_RUN_NAME:-${BASE_RUN_NAME}_starq_${QUARANTINE_PROFILE}}"
QUARANTINE_MODEL_PATH="${QUARANTINE_MODEL_PATH:-${SOF_ROOT}/output/star_quarantine_v0/${SCENE_NAME}/${QUARANTINE_RUN_NAME}}"
RELEASE_RUN_NAME="${RELEASE_RUN_NAME:-${BASE_RUN_NAME}_starq_release_${QUARANTINE_PROFILE}}"

RUN_BASELINE_RECOVERY="${RUN_BASELINE_RECOVERY:-0}"
RUN_DETECT="${RUN_DETECT:-1}"
RUN_QUARANTINE_RENDER="${RUN_QUARANTINE_RENDER:-0}"
RUN_RELEASE_RECOVERY="${RUN_RELEASE_RECOVERY:-1}"
RUN_RELEASE_RENDER="${RUN_RELEASE_RENDER:-1}"

VIEW_INDICES="${VIEW_INDICES:-}"
MAX_VIEWS="${MAX_VIEWS:-8}"
DETECT_RUN_NAME="${DETECT_RUN_NAME:-${BASE_RUN_NAME}_starburst_release_v0}"
DETECT_RENDER_CANDIDATE_AFTER="${DETECT_RENDER_CANDIDATE_AFTER:-0}"
QUARANTINE_CANDIDATE_MODE="${QUARANTINE_CANDIDATE_MODE:-threshold}"
USE_PAYLOAD_CANDIDATE_MASK="${USE_PAYLOAD_CANDIDATE_MASK:-0}"
MIN_QUARANTINE_STARBURST_SCORE="${MIN_QUARANTINE_STARBURST_SCORE:-0.12}"
MIN_QUARANTINE_UNSUPPORTED_SCORE="${MIN_QUARANTINE_UNSUPPORTED_SCORE:-0.04}"
MIN_QUARANTINE_GEOMETRY_RISK="${MIN_QUARANTINE_GEOMETRY_RISK:-0.0}"
MAX_QUARANTINE_FRACTION="${MAX_QUARANTINE_FRACTION:-0.006}"
STAR_REST_SCALE="${STAR_REST_SCALE:-0.22}"
STAR_TAU_SCALE="${STAR_TAU_SCALE:-0.72}"

ITERATIONS="${ITERATIONS:-700}"
OUTPUT_ITERATION="${OUTPUT_ITERATION:-$((BASE_ITERATION + ITERATIONS))}"
STAR_RELEASE_START_ITER="${STAR_RELEASE_START_ITER:-0}"
STAR_RELEASE_END_ITER="${STAR_RELEASE_END_ITER:-${ITERATIONS}}"
STAR_RELEASE_REST_START_SCALE="${STAR_RELEASE_REST_START_SCALE:-${STAR_REST_SCALE}}"
STAR_RELEASE_REST_END_SCALE="${STAR_RELEASE_REST_END_SCALE:-0.55}"
STAR_RELEASE_TAU_START_SCALE="${STAR_RELEASE_TAU_START_SCALE:-${STAR_TAU_SCALE}}"
STAR_RELEASE_TAU_END_SCALE="${STAR_RELEASE_TAU_END_SCALE:-0.92}"
STAR_RELEASE_OPACITY="${STAR_RELEASE_OPACITY:-1}"
STAR_RELEASE_MODE="${STAR_RELEASE_MODE:-smoothstep}"

QUALITY_FUSE_PROFILE="${QUALITY_FUSE_PROFILE:-safe_hf_v1}"
QUALITY_FUSE_NAME="${QUALITY_FUSE_NAME:-quality_fuse_v1_${BASE_RUN_NAME}_mip30ksr_${QUALITY_FUSE_PROFILE}}"
QUALITY_FUSE_PRIOR_ROOT="${QUALITY_FUSE_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/${QUALITY_FUSE_NAME}}"
RELEASE_USE_SR_PRIOR="${RELEASE_USE_SR_PRIOR:-1}"
RELEASE_SR_PRIOR_ROOT="${RELEASE_SR_PRIOR_ROOT:-${QUALITY_FUSE_PRIOR_ROOT}}"
RELEASE_SR_PRIOR_L1_WEIGHT="${RELEASE_SR_PRIOR_L1_WEIGHT:-0.025}"
RELEASE_SR_PRIOR_HF_WEIGHT="${RELEASE_SR_PRIOR_HF_WEIGHT:-0.10}"
RELEASE_SR_PRIOR_UPDATE_SCALE="${RELEASE_SR_PRIOR_UPDATE_SCALE:-0.30}"
RELEASE_SR_PRIOR_START_SCALE="${RELEASE_SR_PRIOR_START_SCALE:-0.35}"
RELEASE_SR_PRIOR_END_SCALE="${RELEASE_SR_PRIOR_END_SCALE:-0.55}"
RELEASE_SR_PRIOR_WARMUP_END_ITER="${RELEASE_SR_PRIOR_WARMUP_END_ITER:-450}"
RELEASE_SR_PRIOR_CONSISTENCY_THRESHOLD="${RELEASE_SR_PRIOR_CONSISTENCY_THRESHOLD:-0.10}"
RELEASE_SR_PRIOR_DELTA_CLIP="${RELEASE_SR_PRIOR_DELTA_CLIP:-0.06}"
RELEASE_LAMBDA_PREMUL_HF_EXCESS="${RELEASE_LAMBDA_PREMUL_HF_EXCESS:-0.10}"
RELEASE_PREMUL_HF_EXCESS_RATIO="${RELEASE_PREMUL_HF_EXCESS_RATIO:-1.02}"
RELEASE_PREMUL_HF_EXCESS_MARGIN="${RELEASE_PREMUL_HF_EXCESS_MARGIN:-0.005}"
RELEASE_USE_MIP_CLOSURE="${RELEASE_USE_MIP_CLOSURE:-1}"
RELEASE_LAMBDA_MIP_HR_LOWFREQ="${RELEASE_LAMBDA_MIP_HR_LOWFREQ:-0.30}"
RELEASE_LAMBDA_MIP_CLOSURE_ALPHA="${RELEASE_LAMBDA_MIP_CLOSURE_ALPHA:-0.12}"
RELEASE_LAMBDA_MIP_CLOSURE_PREMUL="${RELEASE_LAMBDA_MIP_CLOSURE_PREMUL:-0.35}"
RELEASE_LAMBDA_MIP_CLOSURE_DEPTH="${RELEASE_LAMBDA_MIP_CLOSURE_DEPTH:-0.02}"
RELEASE_LAMBDA_MIP_CLOSURE_ALPHA_OVER="${RELEASE_LAMBDA_MIP_CLOSURE_ALPHA_OVER:-0.08}"
RELEASE_LAMBDA_MIP_CLOSURE_PREMUL_OVER="${RELEASE_LAMBDA_MIP_CLOSURE_PREMUL_OVER:-0.45}"
if [[ "${RELEASE_USE_MIP_CLOSURE}" != "1" ]]; then
  RELEASE_LAMBDA_MIP_HR_LOWFREQ="0"
  RELEASE_LAMBDA_MIP_CLOSURE_ALPHA="0"
  RELEASE_LAMBDA_MIP_CLOSURE_PREMUL="0"
  RELEASE_LAMBDA_MIP_CLOSURE_DEPTH="0"
  RELEASE_LAMBDA_MIP_CLOSURE_ALPHA_OVER="0"
  RELEASE_LAMBDA_MIP_CLOSURE_PREMUL_OVER="0"
fi

echo "[star-release-v0] base model        : ${BASE_MODEL_PATH} iter=${BASE_ITERATION}"
echo "[star-release-v0] quarantine model  : ${QUARANTINE_MODEL_PATH}"
echo "[star-release-v0] release run       : ${RELEASE_RUN_NAME} iter=${ITERATIONS} out=${OUTPUT_ITERATION}"
echo "[star-release-v0] candidate mode    : ${QUARANTINE_CANDIDATE_MODE} max_frac=${MAX_QUARANTINE_FRACTION}"
echo "[star-release-v0] start gates       : rest=${STAR_REST_SCALE} tau=${STAR_TAU_SCALE}"
echo "[star-release-v0] release gates     : rest=${STAR_RELEASE_REST_START_SCALE}->${STAR_RELEASE_REST_END_SCALE} tau=${STAR_RELEASE_TAU_START_SCALE}->${STAR_RELEASE_TAU_END_SCALE}"
echo "[star-release-v0] quality prior     : use=${RELEASE_USE_SR_PRIOR} root=${RELEASE_SR_PRIOR_ROOT}"
echo "[star-release-v0] closure weights   : low=${RELEASE_LAMBDA_MIP_HR_LOWFREQ} closure=${RELEASE_LAMBDA_MIP_CLOSURE_ALPHA}/${RELEASE_LAMBDA_MIP_CLOSURE_PREMUL}/${RELEASE_LAMBDA_MIP_CLOSURE_DEPTH} over=${RELEASE_LAMBDA_MIP_CLOSURE_ALPHA_OVER}/${RELEASE_LAMBDA_MIP_CLOSURE_PREMUL_OVER}"

if [[ ! -e "${BASE_MODEL_PATH}/point_cloud/iteration_${BASE_ITERATION}/point_cloud.ply" && "${RUN_BASELINE_RECOVERY}" != "1" ]]; then
  echo "[star-release-v0] missing base model: ${BASE_MODEL_PATH}/point_cloud/iteration_${BASE_ITERATION}/point_cloud.ply" >&2
  echo "[star-release-v0] rerun with RUN_BASELINE_RECOVERY=1 to rebuild ${BASE_RUN_NAME}" >&2
  exit 1
fi

RECOVER_RUN_NAME="${BASE_RUN_NAME}" \
MODEL_PATH="${BASE_MODEL_PATH}" \
ITERATION="${BASE_ITERATION}" \
RUN_BASELINE_RECOVERY="${RUN_BASELINE_RECOVERY}" \
RUN_DETECT="${RUN_DETECT}" \
DETECT_RUN_NAME="${DETECT_RUN_NAME}" \
RUN_RENDER="${RUN_QUARANTINE_RENDER}" \
VIEW_INDICES="${VIEW_INDICES}" \
MAX_VIEWS="${MAX_VIEWS}" \
DETECT_RENDER_CANDIDATE_AFTER="${DETECT_RENDER_CANDIDATE_AFTER}" \
OUTPUT_RUN_NAME="${QUARANTINE_RUN_NAME}" \
OUTPUT_MODEL_PATH="${QUARANTINE_MODEL_PATH}" \
QUARANTINE_CANDIDATE_MODE="${QUARANTINE_CANDIDATE_MODE}" \
USE_PAYLOAD_CANDIDATE_MASK="${USE_PAYLOAD_CANDIDATE_MASK}" \
MIN_QUARANTINE_STARBURST_SCORE="${MIN_QUARANTINE_STARBURST_SCORE}" \
MIN_QUARANTINE_UNSUPPORTED_SCORE="${MIN_QUARANTINE_UNSUPPORTED_SCORE}" \
MIN_QUARANTINE_GEOMETRY_RISK="${MIN_QUARANTINE_GEOMETRY_RISK}" \
MAX_QUARANTINE_FRACTION="${MAX_QUARANTINE_FRACTION}" \
STAR_REST_SCALE="${STAR_REST_SCALE}" \
STAR_TAU_SCALE="${STAR_TAU_SCALE}" \
bash "${SCRIPT_DIR}/run_apply_star_quarantine_v0_kitchen.sh"

if [[ "${RUN_RELEASE_RECOVERY}" != "1" ]]; then
  echo "[done] quarantine model: ${QUARANTINE_MODEL_PATH}"
  exit 0
fi

START_MODEL_PATH="${QUARANTINE_MODEL_PATH}" \
START_ITERATION="${BASE_ITERATION}" \
ANCHOR_MODEL_PATH="${ANCHOR_MODEL_PATH}" \
ANCHOR_ITERATION="${ANCHOR_ITERATION}" \
RUN_NAME="${RELEASE_RUN_NAME}" \
USE_SR_PRIOR="${RELEASE_USE_SR_PRIOR}" \
SR_PRIOR_ROOT="${RELEASE_SR_PRIOR_ROOT}" \
SR_PRIOR_SUBDIR="fused_priors" \
SR_ANCHOR_SUBDIR="aligned_references" \
SR_PRIOR_MASK_SUBDIR="usable_masks" \
SR_PRIOR_CONSISTENCY_THRESHOLD="${RELEASE_SR_PRIOR_CONSISTENCY_THRESHOLD}" \
SR_PRIOR_L1_WEIGHT="${RELEASE_SR_PRIOR_L1_WEIGHT}" \
SR_PRIOR_HF_WEIGHT="${RELEASE_SR_PRIOR_HF_WEIGHT}" \
SR_PRIOR_UPDATE_SCALE="${RELEASE_SR_PRIOR_UPDATE_SCALE}" \
SR_PRIOR_START_SCALE="${RELEASE_SR_PRIOR_START_SCALE}" \
SR_PRIOR_END_SCALE="${RELEASE_SR_PRIOR_END_SCALE}" \
SR_PRIOR_WARMUP_START_ITER=0 \
SR_PRIOR_WARMUP_END_ITER="${RELEASE_SR_PRIOR_WARMUP_END_ITER}" \
SR_PRIOR_SCHEDULE_MODE=smoothstep \
SR_PRIOR_DELTA_CLIP="${RELEASE_SR_PRIOR_DELTA_CLIP}" \
ITERATIONS="${ITERATIONS}" \
OUTPUT_ITERATION="${OUTPUT_ITERATION}" \
RUN_RENDER="${RUN_RELEASE_RENDER}" \
RENDER_IMAGES_SUBDIR="${RENDER_IMAGES_SUBDIR:-images_2}" \
RENDER_SPLIT="${RENDER_SPLIT:-test}" \
RENDER_DIR="${RENDER_DIR:-${SOF_ROOT}/output/recover_cleaned_mip_lr_v0/${SCENE_NAME}/${RELEASE_RUN_NAME}/recovered_mip_renders_no_gt_hr_v0}" \
MAX_VIEWS="${RECOVERY_MAX_VIEWS:-16}" \
LAMBDA_MIP_HR_LOWFREQ="${RELEASE_LAMBDA_MIP_HR_LOWFREQ}" \
LAMBDA_MIP_CLOSURE_ALPHA="${RELEASE_LAMBDA_MIP_CLOSURE_ALPHA}" \
LAMBDA_MIP_CLOSURE_PREMUL="${RELEASE_LAMBDA_MIP_CLOSURE_PREMUL}" \
LAMBDA_MIP_CLOSURE_DEPTH="${RELEASE_LAMBDA_MIP_CLOSURE_DEPTH}" \
LAMBDA_MIP_CLOSURE_ALPHA_OVER="${RELEASE_LAMBDA_MIP_CLOSURE_ALPHA_OVER}" \
LAMBDA_MIP_CLOSURE_PREMUL_OVER="${RELEASE_LAMBDA_MIP_CLOSURE_PREMUL_OVER}" \
LAMBDA_PREMUL_HF_EXCESS="${RELEASE_LAMBDA_PREMUL_HF_EXCESS}" \
PREMUL_HF_EXCESS_RATIO="${RELEASE_PREMUL_HF_EXCESS_RATIO}" \
PREMUL_HF_EXCESS_MARGIN="${RELEASE_PREMUL_HF_EXCESS_MARGIN}" \
STAR_QUARANTINE_PAYLOAD_PATH="${QUARANTINE_MODEL_PATH}/star_quarantine_payload.pt" \
STAR_RELEASE_START_ITER="${STAR_RELEASE_START_ITER}" \
STAR_RELEASE_END_ITER="${STAR_RELEASE_END_ITER}" \
STAR_RELEASE_MODE="${STAR_RELEASE_MODE}" \
STAR_RELEASE_REST_START_SCALE="${STAR_RELEASE_REST_START_SCALE}" \
STAR_RELEASE_REST_END_SCALE="${STAR_RELEASE_REST_END_SCALE}" \
STAR_RELEASE_TAU_START_SCALE="${STAR_RELEASE_TAU_START_SCALE}" \
STAR_RELEASE_TAU_END_SCALE="${STAR_RELEASE_TAU_END_SCALE}" \
STAR_RELEASE_OPACITY="${STAR_RELEASE_OPACITY}" \
bash "${SCRIPT_DIR}/run_recover_cleaned_mip_lr_v0_kitchen.sh"

echo "[done] release model : ${SOF_ROOT}/output/recover_cleaned_mip_lr_v0/${SCENE_NAME}/${RELEASE_RUN_NAME}/recovered_mip_model_lr_miphr_v1"
echo "[done] release render: ${SOF_ROOT}/output/recover_cleaned_mip_lr_v0/${SCENE_NAME}/${RELEASE_RUN_NAME}/recovered_mip_renders_no_gt_hr_v0"
