#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-${WORK_ROOT}/${SCENE_NAME}}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

SR_PRIOR_NAME="${SR_PRIOR_NAME:-qwen_steps1_seed42_rcgm_aligned_images2_train244_v0}"
EVIDENCE_NAME="${EVIDENCE_NAME:-${SR_PRIOR_NAME}_sr_hf_evidence_v0}"
EVIDENCE_ROOT="${EVIDENCE_ROOT:-${SCENE_ASSET_ROOT}/sr_hf_evidence/${EVIDENCE_NAME}}"
TARGET_SUBDIR="${TARGET_SUBDIR:-geometry_carrier_rgb}"
MASK_SUBDIR="${MASK_SUBDIR:-geometry_weight}"

TARGET_DIR="${TARGET_DIR:-${EVIDENCE_ROOT}/${TARGET_SUBDIR}}"
MASK_DIR="${MASK_DIR:-${EVIDENCE_ROOT}/${MASK_SUBDIR}}"
ANCHOR_DIR="${ANCHOR_DIR:-${SCENE_ASSET_ROOT}/kitchen_mip_vanilla_images8_v1/mip30k_rerun_check_directsrc_r1_v0/train/ours_30000/test_preds_1}"

OUTPUT_NAME="${OUTPUT_NAME:-${EVIDENCE_NAME}_${TARGET_SUBDIR}_2dgs_v0}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${SOF_ROOT}/output/2dgs_sr_hf_evidence_carrier/${OUTPUT_NAME}}"

FIT_TARGET_MODE="${FIT_TARGET_MODE:-evidence_rgb}"
RGB_LOSS_WEIGHT_MODE="${RGB_LOSS_WEIGHT_MODE:-trust}"
OUTPUT_PROFILE="${OUTPUT_PROFILE:-carrier_only}"
MODEL_BACKGROUND="${MODEL_BACKGROUND:-0.0}"
BACKGROUND_WEIGHT="${BACKGROUND_WEIGHT:-0.001}"
NEUTRAL_OUTSIDE_MASK="${NEUTRAL_OUTSIDE_MASK:-0}"
SEGMENT_INIT="${SEGMENT_INIT:-1}"
LIGHT_VIS="${LIGHT_VIS:-0}"
MATCH_POLICY="${MATCH_POLICY:-order_if_needed}"
LIMIT="${LIMIT:-1}"
DEBUG_LIMIT="${DEBUG_LIMIT:-8}"
OVERWRITE="${OVERWRITE:-0}"
NUM_GAUSSIANS="${NUM_GAUSSIANS:-32768}"
GAUSSIANIMAGE_MODEL="${GAUSSIANIMAGE_MODEL:-cholesky}"
GAUSSIANIMAGE_OPTIMIZER="${GAUSSIANIMAGE_OPTIMIZER:-adam}"
ITERATIONS="${ITERATIONS:-700}"
LR="${LR:-0.001}"
LOSS="${LOSS:-l1_l2}"
LAMBDA_L1="${LAMBDA_L1:-0.5}"
LAMBDA_L2="${LAMBDA_L2:-0.5}"
HIGHPASS_KERNEL="${HIGHPASS_KERNEL:-9}"
DETAIL_ALPHA="${DETAIL_ALPHA:-0.8}"
RESIDUAL_CLIP="${RESIDUAL_CLIP:-0.08}"
CONFIDENCE_POWER="${CONFIDENCE_POWER:-1.5}"
MASK_POWER="${MASK_POWER:-1.0}"
INIT_RANDOM="${INIT_RANDOM:-0}"
INIT_MIN_SCORE="${INIT_MIN_SCORE:-0.035}"
INIT_NMS_RADIUS_PX="${INIT_NMS_RADIUS_PX:-2}"
INIT_MAX_CANDIDATES="${INIT_MAX_CANDIDATES:-0}"
INIT_WEIGHT_POWER="${INIT_WEIGHT_POWER:-0.5}"
INIT_ORIENTATION_RADIUS_PX="${INIT_ORIENTATION_RADIUS_PX:-5}"
INIT_SIGMA_LONG_PX="${INIT_SIGMA_LONG_PX:-5.0}"
INIT_SIGMA_SHORT_PX="${INIT_SIGMA_SHORT_PX:-0.8}"
INIT_COHERENCE_LONG_BOOST="${INIT_COHERENCE_LONG_BOOST:-0.75}"
SEGMENT_SAMPLES_PER_SEED="${SEGMENT_SAMPLES_PER_SEED:-7}"
SEGMENT_STEP_PX="${SEGMENT_STEP_PX:-2.0}"
SEGMENT_SEED_NMS_RADIUS_PX="${SEGMENT_SEED_NMS_RADIUS_PX:-8}"
SEGMENT_TRACE_SEARCH_RADIUS_PX="${SEGMENT_TRACE_SEARCH_RADIUS_PX:-2}"
SEGMENT_TURN_MIN_COS="${SEGMENT_TURN_MIN_COS:-0.45}"
SEGMENT_MIN_SCORE="${SEGMENT_MIN_SCORE:--1.0}"
SEGMENT_ANCHOR_WEIGHT="${SEGMENT_ANCHOR_WEIGHT:-0.015}"
SEGMENT_PAIR_WEIGHT="${SEGMENT_PAIR_WEIGHT:-0.030}"
SEGMENT_SHAPE_WEIGHT="${SEGMENT_SHAPE_WEIGHT:-0.001}"
SEGMENT_COLOR_SMOOTH_WEIGHT="${SEGMENT_COLOR_SMOOTH_WEIGHT:-0.002}"
LIGHT_VIS_STRENGTH="${LIGHT_VIS_STRENGTH:-0.75}"
SAVE_PT="${SAVE_PT:-0}"

for required in "${EVIDENCE_ROOT}" "${TARGET_DIR}" "${MASK_DIR}" "${ANCHOR_DIR}"; do
  if [[ ! -d "${required}" ]]; then
    echo "[2dgs-sr-hf-evidence-v0] required path not found: ${required}" >&2
    exit 1
  fi
done

echo "[2dgs-sr-hf-evidence-v0] evidence : ${EVIDENCE_ROOT}"
echo "[2dgs-sr-hf-evidence-v0] target   : ${TARGET_DIR}"
echo "[2dgs-sr-hf-evidence-v0] mask     : ${MASK_DIR}"
echo "[2dgs-sr-hf-evidence-v0] output   : ${OUTPUT_ROOT}"

export TARGET_DIR MASK_DIR ANCHOR_DIR OUTPUT_ROOT
export FIT_TARGET_MODE RGB_LOSS_WEIGHT_MODE OUTPUT_PROFILE MODEL_BACKGROUND BACKGROUND_WEIGHT
export NEUTRAL_OUTSIDE_MASK SEGMENT_INIT LIGHT_VIS MATCH_POLICY LIMIT DEBUG_LIMIT OVERWRITE
export NUM_GAUSSIANS GAUSSIANIMAGE_MODEL GAUSSIANIMAGE_OPTIMIZER ITERATIONS LR LOSS LAMBDA_L1 LAMBDA_L2
export HIGHPASS_KERNEL DETAIL_ALPHA RESIDUAL_CLIP CONFIDENCE_POWER MASK_POWER
export INIT_RANDOM INIT_MIN_SCORE INIT_NMS_RADIUS_PX INIT_MAX_CANDIDATES INIT_WEIGHT_POWER
export INIT_ORIENTATION_RADIUS_PX INIT_SIGMA_LONG_PX INIT_SIGMA_SHORT_PX INIT_COHERENCE_LONG_BOOST
export SEGMENT_SAMPLES_PER_SEED SEGMENT_STEP_PX SEGMENT_SEED_NMS_RADIUS_PX
export SEGMENT_TRACE_SEARCH_RADIUS_PX SEGMENT_TURN_MIN_COS SEGMENT_MIN_SCORE
export SEGMENT_ANCHOR_WEIGHT SEGMENT_PAIR_WEIGHT SEGMENT_SHAPE_WEIGHT SEGMENT_COLOR_SMOOTH_WEIGHT
export LIGHT_VIS_STRENGTH SAVE_PT
bash "${SOF_ROOT}/scripts/run_build_2dgs_hf_residual_cache_v0_kitchen.sh"

echo "[2dgs-sr-hf-evidence-v0] main inspect:"
echo "  ${OUTPUT_ROOT}/evidence_target"
echo "  ${OUTPUT_ROOT}/evidence_render"
echo "  ${OUTPUT_ROOT}/evidence_alpha"
echo "  ${OUTPUT_ROOT}/evidence_primitives"
echo "  ${OUTPUT_ROOT}/primitives"
