#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

BASE_TAG="${BASE_TAG:-k22}" \
POST_REFIT_NAME="${POST_REFIT_NAME:-childsoft}" \
POST_REFIT_MODE="${POST_REFIT_MODE:-energy_split_replace_soften_bright}" \
LR_RECOVER_PROFILE="${LR_RECOVER_PROFILE:-prior_recovery_v1}" \
LR_RECOVER_RUN_NAME="${LR_RECOVER_RUN_NAME:-${BASE_TAG}_${POST_REFIT_NAME}}" \
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT:-0.08}" \
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT:-0.42}" \
LAMBDA_SR_RISK_OPACITY="${LAMBDA_SR_RISK_OPACITY:-0.040}" \
LAMBDA_SR_RISK_SCALE="${LAMBDA_SR_RISK_SCALE:-0.008}" \
SR_RISK_BOOST="${SR_RISK_BOOST:-1.80}" \
ITERATIONS="${ITERATIONS:-1800}" \
MAX_DISPLACEMENT_RATIO="${MAX_DISPLACEMENT_RATIO:-0.0016}" \
POST_REFIT_MAX_FRACTION="${POST_REFIT_MAX_FRACTION:-0.14}" \
POST_REFIT_MAX_COUNT="${POST_REFIT_MAX_COUNT:-220000}" \
POST_REFIT_MIN_OPACITY="${POST_REFIT_MIN_OPACITY:-0.018}" \
POST_REFIT_MIN_EFFECTIVE_SCALE_RATIO="${POST_REFIT_MIN_EFFECTIVE_SCALE_RATIO:-0.0015}" \
POST_REFIT_MIN_VOLUME_RADIUS_RATIO="${POST_REFIT_MIN_VOLUME_RADIUS_RATIO:-0.00065}" \
POST_REFIT_MIN_FILTER_SCALE_RATIO="${POST_REFIT_MIN_FILTER_SCALE_RATIO:-0.25}" \
POST_REFIT_MIN_FULL_ANISOTROPY="${POST_REFIT_MIN_FULL_ANISOTROPY:-1.9}" \
POST_REFIT_BRIGHT_MAX_FRACTION="${POST_REFIT_BRIGHT_MAX_FRACTION:-0.08}" \
POST_REFIT_BRIGHT_MAX_COUNT="${POST_REFIT_BRIGHT_MAX_COUNT:-100000}" \
POST_REFIT_BRIGHT_TARGET="${POST_REFIT_BRIGHT_TARGET:-children_only}" \
POST_REFIT_BRIGHT_MIN_OPACITY="${POST_REFIT_BRIGHT_MIN_OPACITY:-0.010}" \
POST_REFIT_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO="${POST_REFIT_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO:-0.0022}" \
POST_REFIT_BRIGHT_LUMA_QUANTILE="${POST_REFIT_BRIGHT_LUMA_QUANTILE:-0.970}" \
POST_REFIT_BRIGHT_MIN_LOCAL_LUMA_RATIO="${POST_REFIT_BRIGHT_MIN_LOCAL_LUMA_RATIO:-1.10}" \
POST_REFIT_BRIGHT_MIN_COLOR_DELTA="${POST_REFIT_BRIGHT_MIN_COLOR_DELTA:-0.035}" \
POST_REFIT_BRIGHT_NEIGHBOR_K="${POST_REFIT_BRIGHT_NEIGHBOR_K:-12}" \
POST_REFIT_BRIGHT_EXPAND_SCALE_MULTIPLIER="${POST_REFIT_BRIGHT_EXPAND_SCALE_MULTIPLIER:-1.30}" \
POST_REFIT_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER="${POST_REFIT_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER:-1.35}" \
POST_REFIT_BRIGHT_OPACITY_SCALE="${POST_REFIT_BRIGHT_OPACITY_SCALE:-0.48}" \
POST_REFIT_BRIGHT_DC_SCALE="${POST_REFIT_BRIGHT_DC_SCALE:-0.72}" \
POST_REFIT_BRIGHT_REST_SCALE="${POST_REFIT_BRIGHT_REST_SCALE:-0.0}" \
POST_REFIT_BRIGHT_FILTER_SCALE="${POST_REFIT_BRIGHT_FILTER_SCALE:-1.80}" \
POST_REFIT_BRIGHT_FILTER_CAP_RATIO="${POST_REFIT_BRIGHT_FILTER_CAP_RATIO:-0.0012}" \
bash "${SCRIPT_DIR}/run_image22_cleanup_then_post_curve_refit_v1_kitchen.sh"
