#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v4_hfband}"

# Keep the strong view-major injection from hfpatch, but remove raw low-frequency
# write authority from the primary patch loss. The patch term now matches only
# band/highpass residuals on top-guidance pixels, while a low-frequency guard
# discourages broad color/brightness drift.
export PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT:-0.0}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT:-1.35}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT:-3.20}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION:-0.16}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE:-0.12}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN:-1.35}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL:-5}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT:-0.85}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL:-17}"

export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-5.0}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE:-0.16}"
export PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE="${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE:-0.035}"
export PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-5.0}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-7.0}"
export PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-3.0}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen_viewmajor_hfpatch.sh"
