#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v2_hfboot}"

# Stronger primary-view bootstrap supervision: keep the view-major sweep, but add
# an explicit high-frequency energy underfill penalty during the first primary steps.
export PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS:-6}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS:-2}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-3.0}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE:-0.35}"
export PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE="${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE:-0.10}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS:-3}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT:-1.25}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN:-1.25}"

export PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-128}"
export PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-131072}"
export PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-0.42}"
export PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.15}"
export PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.14}"
export PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.055}"
export PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST:-2.5}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-4.0}"
export PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-4.5}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen_viewmajor.sh"
