#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v6_hfsmall_clamp}"

# v6 keeps v5's pixel-scale births, strengthens the prior high-frequency push a
# bit, and clamps PRIOR_INJECTED scales after optimization so high-frequency
# residuals cannot be explained by broad or needle-like artifact carriers.
export PRIOR_HF_SEED_SCALE_CLAMP_ENABLE="${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE:-1}"
export PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS:-0.020}"
export PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS:-0.0}"
export PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY:-10.0}"
export PRIOR_HF_SEED_DIAG_LARGE_SCALE="${PRIOR_HF_SEED_DIAG_LARGE_SCALE:-0.020}"

export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-5.8}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT:-1.65}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT:-3.85}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION:-0.20}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN:-1.45}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT:-1.05}"
export PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-5.8}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-8.0}"
export PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-3.2}"

export PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.22}"
export PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-320}"
export PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-229376}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen_viewmajor_hfsmall.sh"
