#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"

SCENE_NAME="${SCENE_NAME}" \
SCENE_ROOT="${SCENE_ROOT}" \
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP}" \
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
MIP_MODEL_PATH="${MIP_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}_sof_native_input_init_repair_softbright_aggressive_v0}" \
RUN_NAME="${RUN_NAME:-view_aligned_volume_delete_v1_initrepair_softbright_aggressive_v0}" \
LR_RECOVER_RUN_NAME="${LR_RECOVER_RUN_NAME:-view_aligned_volume_delete_v1_initrepair_softbright_aggressive_v0_mip_hr_anchor_v0_miphr_v1}" \
RECOMPUTE_FILTER3D="${RECOMPUTE_FILTER3D:-0}" \
RUN_RENDER="${RUN_RENDER:-1}" \
RUN_LR_RECOVER="${RUN_LR_RECOVER:-1}" \
DELETE_QUANTILE="${DELETE_QUANTILE:-0.940}" \
MAX_PRUNE_FRACTION="${MAX_PRUNE_FRACTION:-0.080}" \
MAX_PRUNE_COUNT="${MAX_PRUNE_COUNT:-0}" \
MIN_EFFECTIVE_SCALE_RATIO="${MIN_EFFECTIVE_SCALE_RATIO:-0.0020}" \
MIN_VOLUME_RADIUS_RATIO="${MIN_VOLUME_RADIUS_RATIO:-0.0010}" \
MIN_FILTER_SCALE_RATIO="${MIN_FILTER_SCALE_RATIO:-0.45}" \
MIN_FILTER_INFLATION="${MIN_FILTER_INFLATION:-1.10}" \
MIN_RADIUS_PX="${MIN_RADIUS_PX:-14}" \
MIN_SIDE_RADIUS_PX="${MIN_SIDE_RADIUS_PX:-18}" \
MIN_AXIS_ANISOTROPY="${MIN_AXIS_ANISOTROPY:-1.35}" \
MIN_RAY_THICKNESS_RATIO="${MIN_RAY_THICKNESS_RATIO:-1.45}" \
MIN_SIDE_EXPLOSION="${MIN_SIDE_EXPLOSION:-1.45}" \
MIN_STRESS_IMPACT="${MIN_STRESS_IMPACT:-0.020}" \
MIN_STRESS_RADIUS_PX="${MIN_STRESS_RADIUS_PX:-16}" \
bash "${SCRIPT_DIR}/run_cleanup_mip_view_aligned_volume_artifacts_v0_kitchen.sh"
