#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-${WORK_ROOT}/${SCENE_NAME}}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR:-images_8}"
TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR:-images_8}"
TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR:-images_2}"

MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k_rerun_v0}"
BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}}"
BASELINE_ITERATION="${BASELINE_ITERATION:-30000}"
START_CHECKPOINT="${START_CHECKPOINT:-${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth}"

PREPARED_SR_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/sof_surface_v0_${LR_REFERENCE_IMAGES_SUBDIR}_to_${TARGET_IMAGES_SUBDIR}_mask0.12_soft}"
PRIOR_EDGE_SUBDIR="${PRIOR_EDGE_SUBDIR:-fused_priors}"
PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR:-usable_masks}"
PRIOR_DIR="${PRIOR_DIR:-${SCENE_ROOT}/priors}"
FORCE_PREPARE_PRIORS="${FORCE_PREPARE_PRIORS:-0}"

SURFACE_STATE_PROFILE="${SURFACE_STATE_PROFILE:-conservative_v0}"
STATE_RUN_NAME_DEFAULT="mip30k_rerun_gs2mesh_surface_state_v0"
if [[ "${SURFACE_STATE_PROFILE}" != "conservative_v0" ]]; then
  STATE_RUN_NAME_DEFAULT="${STATE_RUN_NAME_DEFAULT}_${SURFACE_STATE_PROFILE}"
fi
STATE_RUN_NAME="${STATE_RUN_NAME:-${STATE_RUN_NAME_DEFAULT}}"
STATE_DIR="${STATE_DIR:-${SOF_ROOT}/output/gaussian_surface_state_v0/${SCENE_NAME}/${STATE_RUN_NAME}}"
SURFACE_STATE_PAYLOAD="${SURFACE_STATE_PAYLOAD:-${STATE_DIR}/gaussian_surface_state_v0.pt}"
SURFACE_MASK_KEY="${SURFACE_MASK_KEY:-surface_candidate}"

ROUTE_SIGNAL_MODE="${ROUTE_SIGNAL_MODE:-anchor_residual}"
if [[ -z "${ROUTE_ANCHOR_MODE+x}" ]]; then
  if [[ "${ROUTE_SIGNAL_MODE}" == "anchor_residual" ]]; then
    ROUTE_ANCHOR_MODE="surface"
  else
    ROUTE_ANCHOR_MODE="full"
  fi
fi

CONSENSUS_TAG_DEFAULT="${MIP_EXPERIMENT_NAME}_${SURFACE_MASK_KEY}_route_consensus_v0"
if [[ "${ROUTE_SIGNAL_MODE}" != "direct_sr_highfreq" ]]; then
  CONSENSUS_TAG_DEFAULT="${CONSENSUS_TAG_DEFAULT}_${ROUTE_SIGNAL_MODE}"
fi
CONSENSUS_TAG="${CONSENSUS_TAG:-${CONSENSUS_TAG_DEFAULT}}"
SURFACE_ROUTE_CONSENSUS_ROOT="${SURFACE_ROUTE_CONSENSUS_ROOT:-${SOF_ROOT}/output/surface_route_consensus_v0/${SCENE_NAME}/${CONSENSUS_TAG}}"
FORCE_BUILD_CONSENSUS="${FORCE_BUILD_CONSENSUS:-0}"

LAMBDA_SURFACE_ROUTE_CONSENSUS="${LAMBDA_SURFACE_ROUTE_CONSENSUS:-0.15}"
SURFACE_ROUTE_CONSENSUS_FROM_ITER="${SURFACE_ROUTE_CONSENSUS_FROM_ITER:-0}"
SURFACE_ROUTE_CONSENSUS_MIN_PIXELS="${SURFACE_ROUTE_CONSENSUS_MIN_PIXELS:-64}"
SURFACE_ROUTE_VIEW_SAMPLE_PROB="${SURFACE_ROUTE_VIEW_SAMPLE_PROB:-0.60}"
PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-0.35}"

ROUTE_MAX_VIEWS="${ROUTE_MAX_VIEWS:-0}"
ROUTE_TOP_K="${ROUTE_TOP_K:-2}"
ROUTE_CELL_GRID="${ROUTE_CELL_GRID:-4}"
ROUTE_TILE_SIZE="${ROUTE_TILE_SIZE:-32}"
ROUTE_MAX_CANDIDATE_PIXELS="${ROUTE_MAX_CANDIDATE_PIXELS:-6000}"
ROUTE_LOCAL_CONSENSUS_VIEWS="${ROUTE_LOCAL_CONSENSUS_VIEWS:-3}"
ROUTE_RADIUS_SCALE="${ROUTE_RADIUS_SCALE:-2.5}"
ROUTE_MIN_RADIUS_PX="${ROUTE_MIN_RADIUS_PX:-1.5}"
ROUTE_MIN_PRIOR_MASK="${ROUTE_MIN_PRIOR_MASK:-0.05}"
ROUTE_MIN_QUALITY="${ROUTE_MIN_QUALITY:-0.08}"
ROUTE_MIN_RESIDUAL_ENERGY="${ROUTE_MIN_RESIDUAL_ENERGY:-0.01}"
ROUTE_MIN_VIEWS="${ROUTE_MIN_VIEWS:-2}"
ROUTE_VAR_TAU="${ROUTE_VAR_TAU:-0.01}"
ROUTE_PRIOR_DELTA_CLIP="${ROUTE_PRIOR_DELTA_CLIP:-0.20}"
ROUTE_LOWFREQ_GATE_KERNEL="${ROUTE_LOWFREQ_GATE_KERNEL:-9}"
ROUTE_LOWFREQ_GATE_TAU="${ROUTE_LOWFREQ_GATE_TAU:-0.08}"
ROUTE_SPARSE_PAYLOAD="${ROUTE_SPARSE_PAYLOAD:-1}"
ROUTE_SAVE_DEBUG_PNG="${ROUTE_SAVE_DEBUG_PNG:-1}"
SURFACE_ROUTE_SURFACE_ONLY="${SURFACE_ROUTE_SURFACE_ONLY:-1}"
SURFACE_NORMAL_LOCK="${SURFACE_NORMAL_LOCK:-0}"
SURFACE_NORMAL_LOCK_PAYLOAD="${SURFACE_NORMAL_LOCK_PAYLOAD:-}"
SURFACE_NORMAL_LOCK_NORMAL_KEY="${SURFACE_NORMAL_LOCK_NORMAL_KEY:-anchor_normal}"
SURFACE_NORMAL_LOCK_ANCHOR_KEY="${SURFACE_NORMAL_LOCK_ANCHOR_KEY:-anchor_xyz}"
SURFACE_FILTER_3D="${SURFACE_FILTER_3D:-0}"
SURFACE_FILTER_3D_PAYLOAD="${SURFACE_FILTER_3D_PAYLOAD:-${SURFACE_STATE_PAYLOAD}}"
SURFACE_FILTER_3D_KEY="${SURFACE_FILTER_3D_KEY:-${SURFACE_MASK_KEY}}"
SURFACE_FILTER_3D_SCALE="${SURFACE_FILTER_3D_SCALE:-1.4142135623730951}"
SURFACE_FILTER_3D_MIN="${SURFACE_FILTER_3D_MIN:-0.0}"
DENSIFY_FROM_ITER="${DENSIFY_FROM_ITER:-500}"
DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER:-15000}"
DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL:-100}"
DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.0002}"
OPACITY_RESET_INTERVAL="${OPACITY_RESET_INTERVAL:-3000}"
TRAIN_RESOLUTION="${TRAIN_RESOLUTION:-1}"
RENDER_RESOLUTION="${RENDER_RESOLUTION:-1}"

ITERATIONS="${ITERATIONS:-32000}"
RUN_NAME_DEFAULT="${MIP_EXPERIMENT_NAME}_surface_route_consensus_v0_${SURFACE_MASK_KEY}"
if [[ "${ROUTE_SIGNAL_MODE}" != "direct_sr_highfreq" ]]; then
  RUN_NAME_DEFAULT="${RUN_NAME_DEFAULT}_${ROUTE_SIGNAL_MODE}"
fi
RUN_NAME_DEFAULT="${RUN_NAME_DEFAULT}_r${TRAIN_RESOLUTION}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-${RUN_NAME_DEFAULT}}"
RUN_ROOT="${RUN_ROOT:-${SOF_ROOT}/output/mipsplatting_surface_route_consensus_v0/${SCENE_NAME}}"
PRIOR_MODEL_DIR="${PRIOR_MODEL_DIR:-${RUN_ROOT}/${EXPERIMENT_NAME}}"

RUN_RENDER_AFTER="${RUN_RENDER_AFTER:-1}"
RUN_METRICS_AFTER="${RUN_METRICS_AFTER:-1}"
PYTHON_BIN="${PYTHON_BIN:-python}"

if [[ ! -f "${START_CHECKPOINT}" ]]; then
  echo "[mip-surface-route-v0] missing baseline checkpoint: ${START_CHECKPOINT}" >&2
  exit 1
fi
if [[ ! -f "${SURFACE_STATE_PAYLOAD}" ]]; then
  echo "[mip-surface-route-v0] missing surface-state payload: ${SURFACE_STATE_PAYLOAD}" >&2
  exit 1
fi
if [[ ! -d "${PREPARED_SR_PRIOR_ROOT}" ]]; then
  echo "[mip-surface-route-v0] missing prepared prior root: ${PREPARED_SR_PRIOR_ROOT}" >&2
  exit 1
fi

if [[ "${FORCE_BUILD_CONSENSUS}" == "1" || ! -f "${SURFACE_ROUTE_CONSENSUS_ROOT}/manifest.json" ]]; then
  (
    cd "${SOF_ROOT}"
    SCENE_NAME="${SCENE_NAME}" \
    SCENE_ROOT="${SCENE_ROOT}" \
    SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
    TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR}" \
    MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP}" \
    MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
    BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR}" \
    BASELINE_ITERATION="${BASELINE_ITERATION}" \
    SURFACE_STATE_PROFILE="${SURFACE_STATE_PROFILE}" \
    STATE_RUN_NAME="${STATE_RUN_NAME}" \
    SURFACE_STATE_PAYLOAD="${SURFACE_STATE_PAYLOAD}" \
    SURFACE_MASK_KEY="${SURFACE_MASK_KEY}" \
    PREPARED_SR_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT}" \
    PRIOR_EDGE_SUBDIR="${PRIOR_EDGE_SUBDIR}" \
    PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR}" \
    CONSENSUS_TAG="${CONSENSUS_TAG}" \
    OUTPUT_ROOT="${SURFACE_ROUTE_CONSENSUS_ROOT}" \
    MAX_VIEWS="${ROUTE_MAX_VIEWS}" \
    TOP_K="${ROUTE_TOP_K}" \
    CELL_GRID="${ROUTE_CELL_GRID}" \
    TILE_SIZE="${ROUTE_TILE_SIZE}" \
    MAX_CANDIDATE_PIXELS="${ROUTE_MAX_CANDIDATE_PIXELS}" \
    LOCAL_CONSENSUS_VIEWS="${ROUTE_LOCAL_CONSENSUS_VIEWS}" \
    ROUTE_RADIUS_SCALE="${ROUTE_RADIUS_SCALE}" \
    ROUTE_MIN_RADIUS_PX="${ROUTE_MIN_RADIUS_PX}" \
    MIN_PRIOR_MASK="${ROUTE_MIN_PRIOR_MASK}" \
    MIN_ROUTE_QUALITY="${ROUTE_MIN_QUALITY}" \
    MIN_RESIDUAL_ENERGY="${ROUTE_MIN_RESIDUAL_ENERGY}" \
    ROUTE_MIN_VIEWS="${ROUTE_MIN_VIEWS}" \
    ROUTE_VAR_TAU="${ROUTE_VAR_TAU}" \
    PRIOR_DELTA_CLIP="${ROUTE_PRIOR_DELTA_CLIP}" \
    SIGNAL_MODE="${ROUTE_SIGNAL_MODE}" \
    ANCHOR_MODE="${ROUTE_ANCHOR_MODE}" \
    LOWFREQ_GATE_KERNEL="${ROUTE_LOWFREQ_GATE_KERNEL}" \
    LOWFREQ_GATE_TAU="${ROUTE_LOWFREQ_GATE_TAU}" \
    SPARSE_PAYLOAD="${ROUTE_SPARSE_PAYLOAD}" \
    SAVE_DEBUG_PNG="${ROUTE_SAVE_DEBUG_PNG}" \
    PYTHON_BIN="${PYTHON_BIN}" \
    bash "${SCRIPT_DIR}/run_build_surface_route_consensus_v0_kitchen.sh"
  )
fi

echo "[mip-surface-route-v0] scene                 : ${SCENE_ROOT}"
echo "[mip-surface-route-v0] baseline model        : ${BASELINE_MODEL_DIR} iter=${BASELINE_ITERATION}"
echo "[mip-surface-route-v0] route consensus root  : ${SURFACE_ROUTE_CONSENSUS_ROOT}"
echo "[mip-surface-route-v0] surface payload       : ${SURFACE_STATE_PAYLOAD}"
echo "[mip-surface-route-v0] surface mask key      : ${SURFACE_MASK_KEY}"
echo "[mip-surface-route-v0] route lambda          : ${LAMBDA_SURFACE_ROUTE_CONSENSUS}"
echo "[mip-surface-route-v0] route view sample prob: ${SURFACE_ROUTE_VIEW_SAMPLE_PROB}"
echo "[mip-surface-route-v0] route signal mode     : ${ROUTE_SIGNAL_MODE}"
echo "[mip-surface-route-v0] route lowfreq anchor  : ${ROUTE_ANCHOR_MODE}"
echo "[mip-surface-route-v0] route lowfreq gate    : kernel=${ROUTE_LOWFREQ_GATE_KERNEL} tau=${ROUTE_LOWFREQ_GATE_TAU}"
echo "[mip-surface-route-v0] route surface-only    : ${SURFACE_ROUTE_SURFACE_ONLY}"
echo "[mip-surface-route-v0] surface normal lock  : ${SURFACE_NORMAL_LOCK}"
echo "[mip-surface-route-v0] surface 3D filter   : ${SURFACE_FILTER_3D} payload=${SURFACE_FILTER_3D_PAYLOAD:-<infer>} key=${SURFACE_FILTER_3D_KEY} mode=global_plus_surface_extra scale=${SURFACE_FILTER_3D_SCALE} min=${SURFACE_FILTER_3D_MIN}"
echo "[mip-surface-route-v0] densify              : from=${DENSIFY_FROM_ITER} until=${DENSIFY_UNTIL_ITER}"
echo "[mip-surface-route-v0] train/render res      : ${TRAIN_RESOLUTION}/${RENDER_RESOLUTION}"
echo "[mip-surface-route-v0] output model          : ${PRIOR_MODEL_DIR}"

(
  cd "${SOF_ROOT}"
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
  LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR}" \
  TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR}" \
  TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR}" \
  BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR}" \
  BASELINE_ITERATION="${BASELINE_ITERATION}" \
  START_CHECKPOINT="${START_CHECKPOINT}" \
  PREPARED_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT}" \
  PRIOR_DIR="${PRIOR_DIR}" \
  FORCE_PREPARE_PRIORS="${FORCE_PREPARE_PRIORS}" \
  PREPARED_PRIOR_EXPECTED_REFERENCE_DIR="${SCENE_ROOT}/${TARGET_IMAGES_SUBDIR}" \
  PRIOR_SUBDIR="${PRIOR_EDGE_SUBDIR}" \
  PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR}" \
  PRIOR_L1_WEIGHT=0.0 \
  PRIOR_HF_WEIGHT=0.0 \
  LAMBDA_PRIOR_LOCAL=0.0 \
  LAMBDA_PRIOR_EDGE=0.0 \
  PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE}" \
  SURFACE_ROUTE_CONSENSUS_ROOT="${SURFACE_ROUTE_CONSENSUS_ROOT}" \
  LAMBDA_SURFACE_ROUTE_CONSENSUS="${LAMBDA_SURFACE_ROUTE_CONSENSUS}" \
  SURFACE_ROUTE_CONSENSUS_FROM_ITER="${SURFACE_ROUTE_CONSENSUS_FROM_ITER}" \
  SURFACE_ROUTE_CONSENSUS_MIN_PIXELS="${SURFACE_ROUTE_CONSENSUS_MIN_PIXELS}" \
  SURFACE_ROUTE_VIEW_SAMPLE_PROB="${SURFACE_ROUTE_VIEW_SAMPLE_PROB}" \
  SURFACE_ROUTE_SURFACE_ONLY="${SURFACE_ROUTE_SURFACE_ONLY}" \
  SURFACE_NORMAL_LOCK="${SURFACE_NORMAL_LOCK}" \
  SURFACE_NORMAL_LOCK_PAYLOAD="${SURFACE_NORMAL_LOCK_PAYLOAD}" \
  SURFACE_NORMAL_LOCK_NORMAL_KEY="${SURFACE_NORMAL_LOCK_NORMAL_KEY}" \
  SURFACE_NORMAL_LOCK_ANCHOR_KEY="${SURFACE_NORMAL_LOCK_ANCHOR_KEY}" \
  SURFACE_FILTER_3D="${SURFACE_FILTER_3D}" \
  SURFACE_FILTER_3D_PAYLOAD="${SURFACE_FILTER_3D_PAYLOAD}" \
  SURFACE_FILTER_3D_KEY="${SURFACE_FILTER_3D_KEY}" \
  SURFACE_FILTER_3D_SCALE="${SURFACE_FILTER_3D_SCALE}" \
  SURFACE_FILTER_3D_MIN="${SURFACE_FILTER_3D_MIN}" \
  DENSIFY_FROM_ITER="${DENSIFY_FROM_ITER}" \
  DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER}" \
  DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL}" \
  DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD}" \
  OPACITY_RESET_INTERVAL="${OPACITY_RESET_INTERVAL}" \
  PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD="${SURFACE_STATE_PAYLOAD}" \
  PRIOR_LOSS_GAUSSIAN_MASK_KEY="${SURFACE_MASK_KEY}" \
  PRIOR_ONLY_EDGE_FINETUNE=0 \
  RUN_BASELINE_IF_MISSING=0 \
  ITERATIONS="${ITERATIONS}" \
  TRAIN_RESOLUTION="${TRAIN_RESOLUTION}" \
  RENDER_RESOLUTION="${RENDER_RESOLUTION}" \
  EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
  PRIOR_MODEL_DIR="${PRIOR_MODEL_DIR}" \
  RUN_RENDER_AFTER="${RUN_RENDER_AFTER}" \
  RUN_METRICS_AFTER="${RUN_METRICS_AFTER}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SCRIPT_DIR}/run_mipsplatting_stablesr_prior_scene.sh"
)
