#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

PHASE_MODE="${PHASE_MODE:-alternating}"
TOTAL_STEPS="${TOTAL_STEPS:-5000}"
APPEARANCE_STEPS="${APPEARANCE_STEPS:-250}"
GEOMETRY_STEPS="${GEOMETRY_STEPS:-250}"
SAVE_EVERY_CYCLES="${SAVE_EVERY_CYCLES:-0}"
SAVE_INITIAL_SURFACE_MAP="${SAVE_INITIAL_SURFACE_MAP:-0}"
SAVE_CYCLE_SURFACE_MAPS="${SAVE_CYCLE_SURFACE_MAPS:-0}"
SAVE_CYCLE_SURFACE_TARGETS="${SAVE_CYCLE_SURFACE_TARGETS:-0}"
SAVE_CYCLE_MEMORY="${SAVE_CYCLE_MEMORY:-0}"
SAVE_FINAL_SURFACE_MAP="${SAVE_FINAL_SURFACE_MAP:-0}"
SAVE_FINAL_MEMORY="${SAVE_FINAL_MEMORY:-1}"
MAX_VIEWS="${MAX_VIEWS:-0}"

# Conservative color/geometry movement for a safety run.
APPEARANCE_LR="${APPEARANCE_LR:-1e-4}"
GEOMETRY_LR="${GEOMETRY_LR:-1e-4}"
LAMBDA_DC_ANCHOR="${LAMBDA_DC_ANCHOR:-0.20}"
LAMBDA_BASE_GUARD="${LAMBDA_BASE_GUARD:-0.30}"
LAMBDA_UV="${LAMBDA_UV:-0.20}"
LAMBDA_DELTA="${LAMBDA_DELTA:-0.20}"
TRUSTED_TANGENT_SCALE="${TRUSTED_TANGENT_SCALE:-1.0}"
LOOSE_TANGENT_SCALE="${LOOSE_TANGENT_SCALE:-0.5}"
TRUSTED_NORMAL_SCALE="${TRUSTED_NORMAL_SCALE:-0.5}"
LOOSE_NORMAL_SCALE="${LOOSE_NORMAL_SCALE:-0.25}"
GEOMETRY_PRIOR_MASK_THRESHOLD="${GEOMETRY_PRIOR_MASK_THRESHOLD:-0.10}"
MIN_SAMPLE_WEIGHT="${MIN_SAMPLE_WEIGHT:-0.08}"
MIN_SUPPORT_VIEWS="${MIN_SUPPORT_VIEWS:-2}"
AGGREGATION_MODE="${AGGREGATION_MODE:-trimmed_mean}"
ROBUST_TRIM_SIGMA="${ROBUST_TRIM_SIGMA:-0.10}"
ROBUST_TRIM_DISAGREEMENT_SCALE="${ROBUST_TRIM_DISAGREEMENT_SCALE:-2.0}"
BASE_SUPPORT_MODE="${BASE_SUPPORT_MODE:-floor}"
BASE_SUPPORT_FLOOR="${BASE_SUPPORT_FLOOR:-0.25}"
AGGREGATION_RESIDUAL_SAMPLE_CLIP="${AGGREGATION_RESIDUAL_SAMPLE_CLIP:-0.12}"
AGGREGATION_RESIDUAL_BAND="${AGGREGATION_RESIDUAL_BAND:-raw}"
AGGREGATION_RESIDUAL_LOWPASS_KERNEL="${AGGREGATION_RESIDUAL_LOWPASS_KERNEL:-5}"
AGGREGATION_RESIDUAL_MIN_L1="${AGGREGATION_RESIDUAL_MIN_L1:-0.0}"
AGGREGATION_RESIDUAL_MAX_L1="${AGGREGATION_RESIDUAL_MAX_L1:-0.0}"
APPEARANCE_TARGET_MODE="${APPEARANCE_TARGET_MODE:-residual_clipped}"
APPEARANCE_RESIDUAL_CLIP="${APPEARANCE_RESIDUAL_CLIP:-0.05}"
APPEARANCE_RESIDUAL_SCALE="${APPEARANCE_RESIDUAL_SCALE:-1.0}"
ENABLE_SURFACE_MEMORY="${ENABLE_SURFACE_MEMORY:-1}"
MEMORY_BETA="${MEMORY_BETA:-0.15}"
MEMORY_MIN_CONFIDENCE="${MEMORY_MIN_CONFIDENCE:-0.05}"
MEMORY_MAX_DISAGREEMENT="${MEMORY_MAX_DISAGREEMENT:-0.14}"
MEMORY_STABLE_UPDATES="${MEMORY_STABLE_UPDATES:-2}"
MEMORY_STABLE_MIN_CONFIDENCE="${MEMORY_STABLE_MIN_CONFIDENCE:-0.08}"
MEMORY_STABLE_MAX_DISAGREEMENT="${MEMORY_STABLE_MAX_DISAGREEMENT:-0.12}"
MEMORY_ELIGIBILITY="${MEMORY_ELIGIBILITY:-trust_surface}"
MEMORY_LOOSE_MIN_VISIBLE_VIEWS="${MEMORY_LOOSE_MIN_VISIBLE_VIEWS:-2}"
MEMORY_LOOSE_MIN_TOUCH_VIEWS="${MEMORY_LOOSE_MIN_TOUCH_VIEWS:-1}"
MEMORY_LOOSE_MIN_TOUCH_RATIO="${MEMORY_LOOSE_MIN_TOUCH_RATIO:-0.0}"

# Keep this safety run focused on movement strength, not pruning side effects.
PRUNE_AFTER_CYCLE="${PRUNE_AFTER_CYCLE:-0}"

RUN_TAG="${RUN_TAG:-mainline5k_safe_v1}"
RUN_NAME="${RUN_NAME:-${START_RUN_NAME:-debug_stage_00b3_after_scale_canonicalize_geometry_only_v0}_bounded_${PHASE_MODE}_${RUN_TAG}}"

export PHASE_MODE
export TOTAL_STEPS
export APPEARANCE_STEPS
export GEOMETRY_STEPS
export SAVE_EVERY_CYCLES
export SAVE_INITIAL_SURFACE_MAP
export SAVE_CYCLE_SURFACE_MAPS
export SAVE_CYCLE_SURFACE_TARGETS
export SAVE_CYCLE_MEMORY
export SAVE_FINAL_SURFACE_MAP
export SAVE_FINAL_MEMORY
export MAX_VIEWS
export APPEARANCE_LR
export GEOMETRY_LR
export LAMBDA_DC_ANCHOR
export LAMBDA_BASE_GUARD
export LAMBDA_UV
export LAMBDA_DELTA
export TRUSTED_TANGENT_SCALE
export LOOSE_TANGENT_SCALE
export TRUSTED_NORMAL_SCALE
export LOOSE_NORMAL_SCALE
export GEOMETRY_PRIOR_MASK_THRESHOLD
export MIN_SAMPLE_WEIGHT
export MIN_SUPPORT_VIEWS
export AGGREGATION_MODE
export ROBUST_TRIM_SIGMA
export ROBUST_TRIM_DISAGREEMENT_SCALE
export BASE_SUPPORT_MODE
export BASE_SUPPORT_FLOOR
export AGGREGATION_RESIDUAL_SAMPLE_CLIP
export AGGREGATION_RESIDUAL_BAND
export AGGREGATION_RESIDUAL_LOWPASS_KERNEL
export AGGREGATION_RESIDUAL_MIN_L1
export AGGREGATION_RESIDUAL_MAX_L1
export APPEARANCE_TARGET_MODE
export APPEARANCE_RESIDUAL_CLIP
export APPEARANCE_RESIDUAL_SCALE
export ENABLE_SURFACE_MEMORY
export MEMORY_BETA
export MEMORY_MIN_CONFIDENCE
export MEMORY_MAX_DISAGREEMENT
export MEMORY_STABLE_UPDATES
export MEMORY_STABLE_MIN_CONFIDENCE
export MEMORY_STABLE_MAX_DISAGREEMENT
export MEMORY_ELIGIBILITY
export MEMORY_LOOSE_MIN_VISIBLE_VIEWS
export MEMORY_LOOSE_MIN_TOUCH_VIEWS
export MEMORY_LOOSE_MIN_TOUCH_RATIO
export PRUNE_AFTER_CYCLE
export RUN_NAME

bash "${SOF_ROOT}/scripts/run_bounded_surface_alternating_v0_kitchen.sh"
