#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-${WORK_ROOT}/${SCENE_NAME}}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR:-images_8}"
TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR:-${LR_REFERENCE_IMAGES_SUBDIR}}"
TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR:-images_2}"
PRIOR_SUPERVISION_IMAGES_SUBDIR="${PRIOR_SUPERVISION_IMAGES_SUBDIR:-${TARGET_IMAGES_SUBDIR}}"

MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k_rerun_check_directsrc_r1_v0}"
BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}}"
BASELINE_ITERATION="${BASELINE_ITERATION:-30000}"

RAW_PRIOR_DIR="${RAW_PRIOR_DIR:-${WORK_ROOT}/test_preds_1_vosr_same/qwen_steps1_seed42_rcgm}"
PREPARED_SR_PRIOR_NAME="${PREPARED_SR_PRIOR_NAME:-qwen_steps1_seed42_rcgm_aligned_images2_train244_v0}"
PREPARED_SR_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/${PREPARED_SR_PRIOR_NAME}}"
PRIOR_EDGE_SUBDIR="${PRIOR_EDGE_SUBDIR:-fused_priors}"
PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR:-usable_masks}"
PRIOR_ANCHOR_DIR="${PRIOR_ANCHOR_DIR:-${PREPARED_SR_PRIOR_ROOT}/aligned_references}"
RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_prioronly_nomask_v0}"
RUN_ROOT="${RUN_ROOT:-${SOF_ROOT}/output/mipsplatting_hf_seed_prior_v0/${SCENE_NAME}}"
PRIOR_MODEL_DIR="${PRIOR_MODEL_DIR:-${RUN_ROOT}/${RUN_TAG}}"

FINAL_ITER="${FINAL_ITER:-32000}"
FORCE_RERUN="${FORCE_RERUN:-0}"
PYTHON_BIN="${PYTHON_BIN:-python}"
TRAIN_RESOLUTION="${TRAIN_RESOLUTION:-1}"
RENDER_RESOLUTION="${RENDER_RESOLUTION:-1}"

LAMBDA_PRIOR_EDGE="${LAMBDA_PRIOR_EDGE:-0.12}"
PRIOR_EDGE_DETAIL_ALPHA="${PRIOR_EDGE_DETAIL_ALPHA:-0.35}"
PRIOR_EDGE_DETAIL_ALPHA_FINAL="${PRIOR_EDGE_DETAIL_ALPHA_FINAL:-0.70}"
PRIOR_EDGE_DETAIL_WARMUP_ITERS="${PRIOR_EDGE_DETAIL_WARMUP_ITERS:-$(( FINAL_ITER - BASELINE_ITERATION ))}"
PRIOR_EDGE_DETAIL_BLUR_KERNEL="${PRIOR_EDGE_DETAIL_BLUR_KERNEL:-9}"
PRIOR_EDGE_DETAIL_MIN_GAIN="${PRIOR_EDGE_DETAIL_MIN_GAIN:-0.004}"
PRIOR_EDGE_CONFIDENCE_POWER="${PRIOR_EDGE_CONFIDENCE_POWER:-1.5}"
PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-0.35}"
PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-0.10}"
PRIOR_RESIDUAL_DELTA_CLIP="${PRIOR_RESIDUAL_DELTA_CLIP:-0.15}"
PRIOR_SOFT_MASK_POWER="${PRIOR_SOFT_MASK_POWER:-1.0}"
PRIOR_HARD_MASK_THRESHOLD="${PRIOR_HARD_MASK_THRESHOLD:-0.5}"
PRIOR_MASKED_MIN_PIXELS="${PRIOR_MASKED_MIN_PIXELS:-64}"
PRIOR_RESIDUAL_USE_MASKS="${PRIOR_RESIDUAL_USE_MASKS:-0}"
PRIOR_VIEW_SAMPLE_PROB="${PRIOR_VIEW_SAMPLE_PROB:-0.0}"
PRIOR_RESIDUAL_MASKED_UPDATE="${PRIOR_RESIDUAL_MASKED_UPDATE:-0}"
PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL:-0}"
PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE:-1.0}"

PRIOR_HF_SEED_ENABLE="${PRIOR_HF_SEED_ENABLE:-1}"
PRIOR_HF_SEED_FROM_ITER="${PRIOR_HF_SEED_FROM_ITER:-30100}"
PRIOR_HF_SEED_UNTIL_ITER="${PRIOR_HF_SEED_UNTIL_ITER:-30600}"
PRIOR_HF_SEED_INTERVAL="${PRIOR_HF_SEED_INTERVAL:-100}"
PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-512}"
PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-4096}"
PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-0.30}"
PRIOR_HF_SEED_SCALE_MODE="${PRIOR_HF_SEED_SCALE_MODE:-legacy_max}"
PRIOR_HF_SEED_MIN_PIXEL_RADIUS="${PRIOR_HF_SEED_MIN_PIXEL_RADIUS:-0.0}"
PRIOR_HF_SEED_MAX_PIXEL_RADIUS="${PRIOR_HF_SEED_MAX_PIXEL_RADIUS:-0.0}"
PRIOR_HF_SEED_MAX_PROVIDER_RATIO="${PRIOR_HF_SEED_MAX_PROVIDER_RATIO:-0.0}"
PRIOR_HF_SEED_SHAPE_MODE="${PRIOR_HF_SEED_SHAPE_MODE:-isotropic}"
PRIOR_HF_SEED_SHAPE_LONG_RATIO="${PRIOR_HF_SEED_SHAPE_LONG_RATIO:-1.0}"
PRIOR_HF_SEED_SHAPE_SHORT_RATIO="${PRIOR_HF_SEED_SHAPE_SHORT_RATIO:-1.0}"
PRIOR_HF_SEED_SHAPE_NORMAL_RATIO="${PRIOR_HF_SEED_SHAPE_NORMAL_RATIO:-1.0}"
PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER="${PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER:-1.0}"
PRIOR_HF_SEED_DIAG_LARGE_SCALE="${PRIOR_HF_SEED_DIAG_LARGE_SCALE:-0.0}"
PRIOR_HF_SEED_SCALE_CLAMP_ENABLE="${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE:-0}"
PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS:-0.0}"
PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS:-0.0}"
PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY:-0.0}"
PRIOR_BUBBLE_CLEANUP_ENABLE="${PRIOR_BUBBLE_CLEANUP_ENABLE:-0}"
PRIOR_BUBBLE_CLEANUP_FROM_ITER="${PRIOR_BUBBLE_CLEANUP_FROM_ITER:-0}"
PRIOR_BUBBLE_CLEANUP_UNTIL_ITER="${PRIOR_BUBBLE_CLEANUP_UNTIL_ITER:-0}"
PRIOR_BUBBLE_CLEANUP_INTERVAL="${PRIOR_BUBBLE_CLEANUP_INTERVAL:-1}"
PRIOR_BUBBLE_CLEANUP_OPACITY_MIN="${PRIOR_BUBBLE_CLEANUP_OPACITY_MIN:-0.10}"
PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN:-0.0}"
PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX:-0.0}"
PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX="${PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX:-2.5}"
PRIOR_BUBBLE_CLEANUP_MIN_GENERATION="${PRIOR_BUBBLE_CLEANUP_MIN_GENERATION:-0}"
LAMBDA_PRIOR_BUBBLE_HF="${LAMBDA_PRIOR_BUBBLE_HF:-0.0}"
LAMBDA_PRIOR_BUBBLE_RGB_ENERGY="${LAMBDA_PRIOR_BUBBLE_RGB_ENERGY:-0.0}"
LAMBDA_PRIOR_BUBBLE_ALPHA_HF="${LAMBDA_PRIOR_BUBBLE_ALPHA_HF:-0.0}"
LAMBDA_PRIOR_BUBBLE_ALPHA_MASS="${LAMBDA_PRIOR_BUBBLE_ALPHA_MASS:-0.0}"
PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY="${PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY:-1.0}"
PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.015}"
PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.10}"
PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN="${PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN:-1.0}"
PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.0}"
PRIOR_HF_SEED_FIRST_CYCLE_ONLY="${PRIOR_HF_SEED_FIRST_CYCLE_ONLY:-0}"
PRIOR_HF_SEED_ORIGINAL_ONLY="${PRIOR_HF_SEED_ORIGINAL_ONLY:-1}"
PRIOR_HF_SEED_PRUNE_PROTECT_ITERS="${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS:-0}"
PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST:-0.0}"
PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT="${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT:-0.0}"
PRIOR_HF_SEED_RECENT_IMPRINT_GAIN="${PRIOR_HF_SEED_RECENT_IMPRINT_GAIN:-1.0}"
PRIOR_HF_SEED_RECENT_IMPRINT_ITERS="${PRIOR_HF_SEED_RECENT_IMPRINT_ITERS:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_ENABLE="${PRIOR_HF_LOWFREQ_CLEANUP_ENABLE:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL="${PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL:-20}"
PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS="${PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS:-240}"
PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN:-0.06}"
PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY:-1.0}"
PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW="${PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT:-0}"
PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-0.0}"
PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-1.0}"
PRIOR_GUIDANCE_DECAY_FROM_ITER="${PRIOR_GUIDANCE_DECAY_FROM_ITER:-0}"
PRIOR_GUIDANCE_DECAY_UNTIL_ITER="${PRIOR_GUIDANCE_DECAY_UNTIL_ITER:-0}"
PRIOR_GUIDANCE_FINAL_SCALE="${PRIOR_GUIDANCE_FINAL_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_ENABLE="${PRIOR_VIEW_CURRICULUM_ENABLE:-0}"
PRIOR_VIEW_CURRICULUM_START_ITER="${PRIOR_VIEW_CURRICULUM_START_ITER:-0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS:-2}"
PRIOR_VIEW_CURRICULUM_MAX_VIEWS="${PRIOR_VIEW_CURRICULUM_MAX_VIEWS:-0}"
PRIOR_VIEW_CURRICULUM_SETTLE_ITERS="${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY="${PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY:-1}"
PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE="${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN:-1.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL:-7}"
PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION:-0.15}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE:-0.08}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN:-1.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL:-0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL:-15}"
OPTIMIZE_SOURCE_TAG="${OPTIMIZE_SOURCE_TAG:-prior}"
PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD="${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD:-}"
PRIOR_LOSS_GAUSSIAN_MASK_KEY="${PRIOR_LOSS_GAUSSIAN_MASK_KEY:-selected_mask}"
PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS="${PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS:-0}"
SURFACE_NORMAL_LOCK="${SURFACE_NORMAL_LOCK:-0}"
SURFACE_NORMAL_LOCK_PAYLOAD="${SURFACE_NORMAL_LOCK_PAYLOAD:-}"
SURFACE_NORMAL_LOCK_NORMAL_KEY="${SURFACE_NORMAL_LOCK_NORMAL_KEY:-anchor_normal}"
SURFACE_NORMAL_LOCK_ANCHOR_KEY="${SURFACE_NORMAL_LOCK_ANCHOR_KEY:-anchor_xyz}"
SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS="${SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS:-0}"
LAYER_FREQUENCY_MASK_PAYLOAD="${LAYER_FREQUENCY_MASK_PAYLOAD:-}"
LAYER_FREQUENCY_NON_SURFACE_KEY="${LAYER_FREQUENCY_NON_SURFACE_KEY:-non_surface_active}"
LAYER_FREQUENCY_SURFACE_KEY="${LAYER_FREQUENCY_SURFACE_KEY:-surface_carrier}"
LAYER_FREQUENCY_DYNAMIC_ROOTS="${LAYER_FREQUENCY_DYNAMIC_ROOTS:-0}"
LAYER_FREQUENCY_SURFACE_TARGET="${LAYER_FREQUENCY_SURFACE_TARGET:-gt}"
LAMBDA_NON_SURFACE_HF="${LAMBDA_NON_SURFACE_HF:-0.0}"
LAMBDA_NON_SURFACE_RGB_ENERGY="${LAMBDA_NON_SURFACE_RGB_ENERGY:-0.0}"
LAMBDA_NON_SURFACE_ALPHA_HF="${LAMBDA_NON_SURFACE_ALPHA_HF:-0.0}"
LAMBDA_NON_SURFACE_ALPHA_MASS="${LAMBDA_NON_SURFACE_ALPHA_MASS:-0.0}"
LAMBDA_SURFACE_HF_CLOSURE="${LAMBDA_SURFACE_HF_CLOSURE:-0.0}"
SURFACE_HF_UPDATE_SCALE="${SURFACE_HF_UPDATE_SCALE:-1.0}"
LAYER_FREQUENCY_FROM_ITER="${LAYER_FREQUENCY_FROM_ITER:-0}"
LAYER_FREQUENCY_UNTIL_ITER="${LAYER_FREQUENCY_UNTIL_ITER:-0}"
LAYER_FREQUENCY_LOG_INTERVAL="${LAYER_FREQUENCY_LOG_INTERVAL:-100}"

DENSIFY_FROM_ITER="${DENSIFY_FROM_ITER:-30000}"
DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER:-32000}"
DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL:-100}"
DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.00015}"
OPACITY_RESET_INTERVAL="${OPACITY_RESET_INTERVAL:-1000000}"

if [[ "${PRIOR_RESIDUAL_USE_MASKS}" == "1" ]]; then
  RESIDUAL_SOFT_MASK_DIR="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_MASK_SUBDIR}"
  RESIDUAL_HARD_MASK_DIR="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_MASK_SUBDIR}"
  RESIDUAL_MASK_LOG="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_MASK_SUBDIR}"
else
  RESIDUAL_SOFT_MASK_DIR=""
  RESIDUAL_HARD_MASK_DIR=""
  RESIDUAL_MASK_LOG="disabled"
fi

if [[ ! -f "${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth" ]]; then
  echo "[hf-seed-prior-v0] missing baseline checkpoint: ${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth" >&2
  exit 1
fi

if [[ "${FORCE_RERUN}" != "1" && -f "${PRIOR_MODEL_DIR}/chkpnt${FINAL_ITER}.pth" ]]; then
  echo "[hf-seed-prior-v0] checkpoint exists, skipping training: ${PRIOR_MODEL_DIR}/chkpnt${FINAL_ITER}.pth"
  exit 0
fi

echo "[hf-seed-prior-v0] scene              : ${SCENE_ROOT}"
echo "[hf-seed-prior-v0] baseline          : ${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth"
echo "[hf-seed-prior-v0] train images      : ${TRAIN_IMAGES_SUBDIR}"
echo "[hf-seed-prior-v0] prior camera      : ${PRIOR_SUPERVISION_IMAGES_SUBDIR}"
echo "[hf-seed-prior-v0] prior residual    : prior=${PREPARED_SR_PRIOR_ROOT}/${PRIOR_EDGE_SUBDIR} anchor=${PRIOR_ANCHOR_DIR} mask=${RESIDUAL_MASK_LOG}"
if [[ "${PRIOR_HF_SEED_ENABLE}" == "1" ]]; then
  echo "[hf-seed-prior-v0] seed schedule     : ${PRIOR_HF_SEED_FROM_ITER}->${PRIOR_HF_SEED_UNTIL_ITER} every ${PRIOR_HF_SEED_INTERVAL}, total=${PRIOR_HF_SEED_MAX_TOTAL}"
else
  echo "[hf-seed-prior-v0] seed schedule     : disabled"
fi
if [[ "${PRIOR_VIEW_CURRICULUM_ENABLE}" == "1" ]]; then
  echo "[hf-seed-prior-v0] view curriculum   : start=${PRIOR_VIEW_CURRICULUM_START_ITER} primary=${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS} neighbor=${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS} radius=${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS} max_views=${PRIOR_VIEW_CURRICULUM_MAX_VIEWS} settle=${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS} primary_hfe=${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT}x${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN} band=${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT}@${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL} residual=${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT} patch=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT}@top${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION}/min${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE} gain=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN} hp=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL} lf_guard=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT}@${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL} boot=${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS}"
fi
echo "[hf-seed-prior-v0] output            : ${PRIOR_MODEL_DIR}"

(
  cd "${SOF_ROOT}"
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
  LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR}" \
  TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR}" \
  TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR}" \
  BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR}" \
  BASELINE_ITERATION="${BASELINE_ITERATION}" \
  START_CHECKPOINT="${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth" \
  PREPARED_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT}" \
  PRIOR_DIR="${RAW_PRIOR_DIR}" \
  PRIOR_SUBDIR="${PRIOR_EDGE_SUBDIR}" \
  PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR}" \
  FORCE_PREPARE_PRIORS=0 \
  ALLOW_PREPARED_PRIOR_REBUILD="${ALLOW_PREPARED_PRIOR_REBUILD:-0}" \
  PREPARED_PRIOR_EXPECTED_REFERENCE_DIR="${SCENE_ROOT}/${PRIOR_SUPERVISION_IMAGES_SUBDIR}" \
  PRIOR_LOSS_MODE=masked_residual_hf_v1 \
  PRIOR_ANCHOR_DIR="${PRIOR_ANCHOR_DIR}" \
  PRIOR_SOFT_MASK_DIR="${RESIDUAL_SOFT_MASK_DIR}" \
  PRIOR_HARD_MASK_DIR="${RESIDUAL_HARD_MASK_DIR}" \
  PRIOR_RESIDUAL_USE_MASKS="${PRIOR_RESIDUAL_USE_MASKS}" \
  PRIOR_SOFT_MASK_POWER="${PRIOR_SOFT_MASK_POWER}" \
  PRIOR_HARD_MASK_THRESHOLD="${PRIOR_HARD_MASK_THRESHOLD}" \
  PRIOR_MASKED_MIN_PIXELS="${PRIOR_MASKED_MIN_PIXELS}" \
  PRIOR_VIEW_SAMPLE_PROB="${PRIOR_VIEW_SAMPLE_PROB}" \
  PRIOR_RESIDUAL_MASKED_UPDATE="${PRIOR_RESIDUAL_MASKED_UPDATE}" \
  PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL}" \
  PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE}" \
  PRIOR_DELTA_CLIP="${PRIOR_RESIDUAL_DELTA_CLIP}" \
  PRIOR_L1_WEIGHT=0.0 \
  PRIOR_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT}" \
  PRIOR_SUPERVISION_IMAGES_SUBDIR="${PRIOR_SUPERVISION_IMAGES_SUBDIR}" \
  PRIOR_EDGE_DIR="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_EDGE_SUBDIR}" \
  PRIOR_EDGE_MASK_DIR="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_MASK_SUBDIR}" \
  LAMBDA_PRIOR_EDGE=0.0 \
  PRIOR_EDGE_LOSS_MODE=detail_v1 \
  PRIOR_EDGE_FROM_ITER="${BASELINE_ITERATION}" \
  PRIOR_EDGE_DETAIL_ALPHA="${PRIOR_EDGE_DETAIL_ALPHA}" \
  PRIOR_EDGE_DETAIL_ALPHA_FINAL="${PRIOR_EDGE_DETAIL_ALPHA_FINAL}" \
  PRIOR_EDGE_DETAIL_WARMUP_ITERS="${PRIOR_EDGE_DETAIL_WARMUP_ITERS}" \
  PRIOR_EDGE_DETAIL_BLUR_KERNEL="${PRIOR_EDGE_DETAIL_BLUR_KERNEL}" \
  PRIOR_EDGE_DETAIL_WEIGHT=1.0 \
  PRIOR_EDGE_LOWFREQ_WEIGHT=0.0 \
  PRIOR_EDGE_GRAD_WEIGHT=0.0 \
  PRIOR_EDGE_LOWFREQ_THRESHOLD=0.08 \
  PRIOR_EDGE_LOWFREQ_ANCHOR=render \
  PRIOR_EDGE_DETAIL_MIN_GAIN="${PRIOR_EDGE_DETAIL_MIN_GAIN}" \
  PRIOR_EDGE_CONFIDENCE_POWER="${PRIOR_EDGE_CONFIDENCE_POWER}" \
  PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE}" \
  PRIOR_HF_SEED_ENABLE="${PRIOR_HF_SEED_ENABLE}" \
  PRIOR_HF_SEED_FROM_ITER="${PRIOR_HF_SEED_FROM_ITER}" \
  PRIOR_HF_SEED_UNTIL_ITER="${PRIOR_HF_SEED_UNTIL_ITER}" \
  PRIOR_HF_SEED_INTERVAL="${PRIOR_HF_SEED_INTERVAL}" \
  PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER}" \
  PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL}" \
  PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER}" \
  PRIOR_HF_SEED_SCALE_MODE="${PRIOR_HF_SEED_SCALE_MODE}" \
  PRIOR_HF_SEED_MIN_PIXEL_RADIUS="${PRIOR_HF_SEED_MIN_PIXEL_RADIUS}" \
  PRIOR_HF_SEED_MAX_PIXEL_RADIUS="${PRIOR_HF_SEED_MAX_PIXEL_RADIUS}" \
  PRIOR_HF_SEED_MAX_PROVIDER_RATIO="${PRIOR_HF_SEED_MAX_PROVIDER_RATIO}" \
  PRIOR_HF_SEED_SHAPE_MODE="${PRIOR_HF_SEED_SHAPE_MODE}" \
  PRIOR_HF_SEED_SHAPE_LONG_RATIO="${PRIOR_HF_SEED_SHAPE_LONG_RATIO}" \
  PRIOR_HF_SEED_SHAPE_SHORT_RATIO="${PRIOR_HF_SEED_SHAPE_SHORT_RATIO}" \
  PRIOR_HF_SEED_SHAPE_NORMAL_RATIO="${PRIOR_HF_SEED_SHAPE_NORMAL_RATIO}" \
  PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER="${PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER}" \
  PRIOR_HF_SEED_DIAG_LARGE_SCALE="${PRIOR_HF_SEED_DIAG_LARGE_SCALE}" \
  PRIOR_HF_SEED_SCALE_CLAMP_ENABLE="${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE}" \
  PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS}" \
  PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS}" \
  PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY}" \
  PRIOR_BUBBLE_CLEANUP_ENABLE="${PRIOR_BUBBLE_CLEANUP_ENABLE}" \
  PRIOR_BUBBLE_CLEANUP_FROM_ITER="${PRIOR_BUBBLE_CLEANUP_FROM_ITER}" \
  PRIOR_BUBBLE_CLEANUP_UNTIL_ITER="${PRIOR_BUBBLE_CLEANUP_UNTIL_ITER}" \
  PRIOR_BUBBLE_CLEANUP_INTERVAL="${PRIOR_BUBBLE_CLEANUP_INTERVAL}" \
  PRIOR_BUBBLE_CLEANUP_OPACITY_MIN="${PRIOR_BUBBLE_CLEANUP_OPACITY_MIN}" \
  PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN}" \
  PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX}" \
  PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX="${PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX}" \
  PRIOR_BUBBLE_CLEANUP_MIN_GENERATION="${PRIOR_BUBBLE_CLEANUP_MIN_GENERATION}" \
  LAMBDA_PRIOR_BUBBLE_HF="${LAMBDA_PRIOR_BUBBLE_HF}" \
  LAMBDA_PRIOR_BUBBLE_RGB_ENERGY="${LAMBDA_PRIOR_BUBBLE_RGB_ENERGY}" \
  LAMBDA_PRIOR_BUBBLE_ALPHA_HF="${LAMBDA_PRIOR_BUBBLE_ALPHA_HF}" \
  LAMBDA_PRIOR_BUBBLE_ALPHA_MASS="${LAMBDA_PRIOR_BUBBLE_ALPHA_MASS}" \
  PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY="${PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY}" \
  PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY}" \
  PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE}" \
  PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN="${PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN}" \
  PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD}" \
  PRIOR_HF_SEED_FIRST_CYCLE_ONLY="${PRIOR_HF_SEED_FIRST_CYCLE_ONLY}" \
  PRIOR_HF_SEED_ORIGINAL_ONLY="${PRIOR_HF_SEED_ORIGINAL_ONLY}" \
  PRIOR_HF_SEED_PRUNE_PROTECT_ITERS="${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS}" \
  PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST}" \
  PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT="${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT}" \
  PRIOR_HF_SEED_RECENT_IMPRINT_GAIN="${PRIOR_HF_SEED_RECENT_IMPRINT_GAIN}" \
  PRIOR_HF_SEED_RECENT_IMPRINT_ITERS="${PRIOR_HF_SEED_RECENT_IMPRINT_ITERS}" \
  PRIOR_HF_LOWFREQ_CLEANUP_ENABLE="${PRIOR_HF_LOWFREQ_CLEANUP_ENABLE}" \
  PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER}" \
  PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER}" \
  PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL="${PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL}" \
  PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS="${PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS}" \
  PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN}" \
  PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN}" \
  PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX}" \
  PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX}" \
  PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY}" \
  PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW="${PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW}" \
  PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION}" \
  PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT}" \
  PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST}" \
  PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER}" \
  PRIOR_GUIDANCE_DECAY_FROM_ITER="${PRIOR_GUIDANCE_DECAY_FROM_ITER}" \
  PRIOR_GUIDANCE_DECAY_UNTIL_ITER="${PRIOR_GUIDANCE_DECAY_UNTIL_ITER}" \
  PRIOR_GUIDANCE_FINAL_SCALE="${PRIOR_GUIDANCE_FINAL_SCALE}" \
  PRIOR_VIEW_CURRICULUM_ENABLE="${PRIOR_VIEW_CURRICULUM_ENABLE}" \
  PRIOR_VIEW_CURRICULUM_START_ITER="${PRIOR_VIEW_CURRICULUM_START_ITER}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS}" \
  PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS}" \
  PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS}" \
  PRIOR_VIEW_CURRICULUM_MAX_VIEWS="${PRIOR_VIEW_CURRICULUM_MAX_VIEWS}" \
  PRIOR_VIEW_CURRICULUM_SETTLE_ITERS="${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS}" \
  PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY="${PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE}" \
  PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE}" \
  PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE="${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT}" \
  PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL}" \
  OPTIMIZE_SOURCE_TAG="${OPTIMIZE_SOURCE_TAG}" \
  PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD="${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD}" \
  PRIOR_LOSS_GAUSSIAN_MASK_KEY="${PRIOR_LOSS_GAUSSIAN_MASK_KEY}" \
  PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS="${PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS}" \
  SURFACE_NORMAL_LOCK="${SURFACE_NORMAL_LOCK}" \
  SURFACE_NORMAL_LOCK_PAYLOAD="${SURFACE_NORMAL_LOCK_PAYLOAD}" \
  SURFACE_NORMAL_LOCK_NORMAL_KEY="${SURFACE_NORMAL_LOCK_NORMAL_KEY}" \
  SURFACE_NORMAL_LOCK_ANCHOR_KEY="${SURFACE_NORMAL_LOCK_ANCHOR_KEY}" \
  SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS="${SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS}" \
  LAYER_FREQUENCY_MASK_PAYLOAD="${LAYER_FREQUENCY_MASK_PAYLOAD}" \
  LAYER_FREQUENCY_NON_SURFACE_KEY="${LAYER_FREQUENCY_NON_SURFACE_KEY}" \
  LAYER_FREQUENCY_SURFACE_KEY="${LAYER_FREQUENCY_SURFACE_KEY}" \
  LAYER_FREQUENCY_DYNAMIC_ROOTS="${LAYER_FREQUENCY_DYNAMIC_ROOTS}" \
  LAYER_FREQUENCY_SURFACE_TARGET="${LAYER_FREQUENCY_SURFACE_TARGET}" \
  LAMBDA_NON_SURFACE_HF="${LAMBDA_NON_SURFACE_HF}" \
  LAMBDA_NON_SURFACE_RGB_ENERGY="${LAMBDA_NON_SURFACE_RGB_ENERGY}" \
  LAMBDA_NON_SURFACE_ALPHA_HF="${LAMBDA_NON_SURFACE_ALPHA_HF}" \
  LAMBDA_NON_SURFACE_ALPHA_MASS="${LAMBDA_NON_SURFACE_ALPHA_MASS}" \
  LAMBDA_SURFACE_HF_CLOSURE="${LAMBDA_SURFACE_HF_CLOSURE}" \
  SURFACE_HF_UPDATE_SCALE="${SURFACE_HF_UPDATE_SCALE}" \
  LAYER_FREQUENCY_FROM_ITER="${LAYER_FREQUENCY_FROM_ITER}" \
  LAYER_FREQUENCY_UNTIL_ITER="${LAYER_FREQUENCY_UNTIL_ITER}" \
  LAYER_FREQUENCY_LOG_INTERVAL="${LAYER_FREQUENCY_LOG_INTERVAL}" \
  PRIOR_ONLY_EDGE_FINETUNE=0 \
  DENSIFY_FROM_ITER="${DENSIFY_FROM_ITER}" \
  DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER}" \
  DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL}" \
  DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD}" \
  OPACITY_RESET_INTERVAL="${OPACITY_RESET_INTERVAL}" \
  RUN_BASELINE_IF_MISSING=0 \
  ITERATIONS="${FINAL_ITER}" \
  TRAIN_RESOLUTION="${TRAIN_RESOLUTION}" \
  RENDER_RESOLUTION="${RENDER_RESOLUTION}" \
  RUN_ROOT="${RUN_ROOT}" \
  EXPERIMENT_NAME="${RUN_TAG}" \
  PRIOR_MODEL_DIR="${PRIOR_MODEL_DIR}" \
  RUN_RENDER_AFTER="${RUN_RENDER_AFTER:-1}" \
  RUN_METRICS_AFTER="${RUN_METRICS_AFTER:-1}" \
  SAVE_CHECKPOINT_AFTER="${SAVE_CHECKPOINT_AFTER:-1}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SCRIPT_DIR}/run_mipsplatting_stablesr_prior_scene.sh"
)

echo
echo "[done] model      : ${PRIOR_MODEL_DIR}"
if [[ "${SAVE_CHECKPOINT_AFTER:-1}" == "1" ]]; then
  echo "[done] checkpoint : ${PRIOR_MODEL_DIR}/chkpnt${FINAL_ITER}.pth"
else
  echo "[done] checkpoint : skipped (SAVE_CHECKPOINT_AFTER=0)"
fi
echo "[done] metrics    : ${PRIOR_MODEL_DIR}/results_psnr_ssim.json"
