#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_prioronly_nomask_visibility_v2}"

# Diagnostic preset: keep optimization on the injected/prior branch, but make that
# branch physically hard to ignore in the renderer.
export PRIOR_RESIDUAL_USE_MASKS="${PRIOR_RESIDUAL_USE_MASKS:-0}"
export OPTIMIZE_SOURCE_TAG="${OPTIMIZE_SOURCE_TAG:-prior}"
export PRIOR_HF_SEED_ORIGINAL_ONLY="${PRIOR_HF_SEED_ORIGINAL_ONLY:-0}"

export PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-5.0}"
export PRIOR_RESIDUAL_DELTA_CLIP="${PRIOR_RESIDUAL_DELTA_CLIP:-0.80}"
export PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-5.0}"

export PRIOR_HF_SEED_FROM_ITER="${PRIOR_HF_SEED_FROM_ITER:-30001}"
export PRIOR_HF_SEED_UNTIL_ITER="${PRIOR_HF_SEED_UNTIL_ITER:-0}"
export PRIOR_HF_SEED_INTERVAL="${PRIOR_HF_SEED_INTERVAL:-1}"
export PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-1536}"
export PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-49152}"
export PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-1.00}"
export PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.30}"
export PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.30}"
export PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.04}"
export PRIOR_HF_SEED_FIRST_CYCLE_ONLY="${PRIOR_HF_SEED_FIRST_CYCLE_ONLY:-1}"
export PRIOR_HF_SEED_PRUNE_PROTECT_ITERS="${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS:-700}"
export PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST:-2.5}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-3.5}"
export PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-2.0}"

export DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER:-30900}"
export DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL:-40}"
export DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.000025}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen.sh"
