#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-${WORK_ROOT}/${SCENE_NAME}}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"

PREPARE_DEBUG_MODEL_PATH="${PREPARE_DEBUG_MODEL_PATH:-${SCENE_ASSET_ROOT}/${SCENE_NAME}_mip_vanilla_images8_v1/mip30k_sof_native_input_init_early4ksoft_v1_debug}"
PREPARE_DEBUG_ITERATION="${PREPARE_DEBUG_ITERATION:-34000}"
STAGE_NAME="${STAGE_NAME:-debug_stage_00b3_after_scale_canonicalize}"
BASE_MODEL_PATH="${BASE_MODEL_PATH:-${PREPARE_DEBUG_MODEL_PATH}/debug_prepare_stages/${STAGE_NAME}}"
BASE_ITERATION="${BASE_ITERATION:-${PREPARE_DEBUG_ITERATION}}"

MASK_REPARAM_RUN_NAME="${MASK_REPARAM_RUN_NAME:-${STAGE_NAME}_geometry_then_highlight_v1}"
SETTLE_RUN_NAME="${SETTLE_RUN_NAME:-${MASK_REPARAM_RUN_NAME}_settle_v1_manual}"
SETTLE_MODEL_PATH="${SETTLE_MODEL_PATH:-${SOF_ROOT}/output/mask_reparam_settle_v0/${SCENE_NAME}/${SETTLE_RUN_NAME}/settled_model}"
SETTLE_ITERATION="${SETTLE_ITERATION:--1}"

DEFAULT_MIP_STABLE_MODEL="${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}_sof_native_input_init_repair_v0"
DEFAULT_MIP_STABLE_ITERATION="30000"
if [[ -z "${MIP_STABLE_MODEL_PATH+x}" ]]; then
  if [[ -d "${DEFAULT_MIP_STABLE_MODEL}" ]]; then
    MIP_STABLE_MODEL_PATH="${DEFAULT_MIP_STABLE_MODEL}"
    MIP_STABLE_ITERATION_DEFAULT="${DEFAULT_MIP_STABLE_ITERATION}"
  else
    MIP_STABLE_MODEL_PATH="${BASE_MODEL_PATH}"
    MIP_STABLE_ITERATION_DEFAULT="${BASE_ITERATION}"
  fi
fi
MIP_STABLE_ITERATION="${MIP_STABLE_ITERATION:-${MIP_STABLE_ITERATION_DEFAULT:-${BASE_ITERATION}}}"

RELEASE_PROFILE="${RELEASE_PROFILE:-release_v0}"
case "${RELEASE_PROFILE}" in
  release_v0)
    DEFAULT_ITERATIONS="1000"
    DEFAULT_MAX_VIEWS="24"
    DEFAULT_XYZ_LR="3e-6"
    DEFAULT_OPACITY_LR="6e-4"
    DEFAULT_SCALE_LR="1.5e-4"
    DEFAULT_DC_LR="1.0e-4"
    DEFAULT_REST_LR="3e-5"
    DEFAULT_LAMBDA_XYZ_ANCHOR="30.0"
    DEFAULT_LAMBDA_OPACITY_ANCHOR="0.03"
    DEFAULT_LAMBDA_SCALE_ANCHOR="0.12"
    DEFAULT_LAMBDA_REST_ANCHOR="0.02"
    DEFAULT_LAMBDA_RISK_OPACITY="0.020"
    DEFAULT_LAMBDA_RISK_SCALE="0.002"
    DEFAULT_LAMBDA_RISK_REST="0.010"
    DEFAULT_LAMBDA_SR_RISK_REST="0.012"
    DEFAULT_SR_RISK_BOOST="1.20"
    DEFAULT_SR_PRIOR_L1_WEIGHT="0.015"
    DEFAULT_SR_PRIOR_HF_WEIGHT="0.050"
    DEFAULT_LAMBDA_PREMUL_HF_EXCESS="0.040"
    DEFAULT_SR_PRIOR_WARMUP_END_ITER="300"
    DEFAULT_SR_PRIOR_START_SCALE="0.15"
    DEFAULT_SR_PRIOR_END_SCALE="1.0"
    DEFAULT_SR_PRIOR_UPDATE_SCALE="0.60"
    DEFAULT_LAMBDA_MIP_HR_LOWFREQ="0.45"
    DEFAULT_MIP_HR_LOWFREQ_KERNEL="31"
    DEFAULT_MIP_HR_LOWFREQ_CONSISTENCY_THRESHOLD="0.28"
    DEFAULT_LAMBDA_MIP_CLOSURE_ALPHA="0.16"
    DEFAULT_LAMBDA_MIP_CLOSURE_PREMUL="0.65"
    DEFAULT_LAMBDA_MIP_CLOSURE_DEPTH="0.02"
    DEFAULT_LAMBDA_MIP_CLOSURE_ALPHA_OVER="0.16"
    DEFAULT_LAMBDA_MIP_CLOSURE_PREMUL_OVER="0.80"
    DEFAULT_MAX_DISPLACEMENT_RATIO="0.0015"
    ;;
  *)
    echo "[mask-reparam-detail-release-v0] unknown RELEASE_PROFILE=${RELEASE_PROFILE}" >&2
    exit 1
    ;;
esac

ITERATIONS="${ITERATIONS:-${DEFAULT_ITERATIONS}}"
MAX_VIEWS="${MAX_VIEWS:-${DEFAULT_MAX_VIEWS}}"
SR_MAX_VIEWS="${SR_MAX_VIEWS:-${MAX_VIEWS}}"
MIP_CLOSURE_MAX_VIEWS="${MIP_CLOSURE_MAX_VIEWS:-${SR_MAX_VIEWS}}"
XYZ_LR="${XYZ_LR:-${DEFAULT_XYZ_LR}}"
OPACITY_LR="${OPACITY_LR:-${DEFAULT_OPACITY_LR}}"
SCALE_LR="${SCALE_LR:-${DEFAULT_SCALE_LR}}"
DC_LR="${DC_LR:-${DEFAULT_DC_LR}}"
REST_LR="${REST_LR:-${DEFAULT_REST_LR}}"

OUTPUT_RUN_NAME="${OUTPUT_RUN_NAME:-${SETTLE_RUN_NAME}_${RELEASE_PROFILE}}"
RUN_NAME="${RUN_NAME:-${OUTPUT_RUN_NAME}}"
RUN_ROOT="${RUN_ROOT:-${SOF_ROOT}/output/mask_reparam_detail_release_v0/${SCENE_NAME}/${OUTPUT_RUN_NAME}}"
OUTPUT_MODEL="${OUTPUT_MODEL:-${RUN_ROOT}/released_model}"
RENDER_DIR="${RENDER_DIR:-${RUN_ROOT}/preview_renders_no_gt_v0}"
OUTPUT_ITERATION="${OUTPUT_ITERATION:--1}"

START_MODEL_PATH="${START_MODEL_PATH:-${SETTLE_MODEL_PATH}}"
START_ITERATION="${START_ITERATION:-${SETTLE_ITERATION}}"
ANCHOR_MODEL_PATH="${ANCHOR_MODEL_PATH:-${MIP_STABLE_MODEL_PATH}}"
ANCHOR_ITERATION="${ANCHOR_ITERATION:-${MIP_STABLE_ITERATION}}"
MIP_CLOSURE_MODEL_PATH="${MIP_CLOSURE_MODEL_PATH:-${MIP_STABLE_MODEL_PATH}}"
MIP_CLOSURE_ITERATION="${MIP_CLOSURE_ITERATION:-${MIP_STABLE_ITERATION}}"

IMAGES_SUBDIR="${IMAGES_SUBDIR:-images_8}"
SR_IMAGES_SUBDIR="${SR_IMAGES_SUBDIR:-images_2}"
MIP_CLOSURE_IMAGES_SUBDIR="${MIP_CLOSURE_IMAGES_SUBDIR:-${SR_IMAGES_SUBDIR}}"
RENDER_IMAGES_SUBDIR="${RENDER_IMAGES_SUBDIR:-images_2}"
RENDER_SPLIT="${RENDER_SPLIT:-test}"

REFINE_PROFILE="${REFINE_PROFILE:-conservative_v0}"
USE_SR_PRIOR="${USE_SR_PRIOR:-1}"
ENABLE_OPACITY_UPDATE="${ENABLE_OPACITY_UPDATE:-1}"
ENABLE_SCALE_UPDATE="${ENABLE_SCALE_UPDATE:-1}"
ENABLE_DC_UPDATE="${ENABLE_DC_UPDATE:-1}"
ENABLE_REST_UPDATE="${ENABLE_REST_UPDATE:-1}"
LAMBDA_LR_RGB="${LAMBDA_LR_RGB:-1.0}"
LAMBDA_ANCHOR_RGB="${LAMBDA_ANCHOR_RGB:-0.0}"
LAMBDA_XYZ_ANCHOR="${LAMBDA_XYZ_ANCHOR:-${DEFAULT_LAMBDA_XYZ_ANCHOR}}"
LAMBDA_OPACITY_ANCHOR="${LAMBDA_OPACITY_ANCHOR:-${DEFAULT_LAMBDA_OPACITY_ANCHOR}}"
LAMBDA_SCALE_ANCHOR="${LAMBDA_SCALE_ANCHOR:-${DEFAULT_LAMBDA_SCALE_ANCHOR}}"
LAMBDA_DC_ANCHOR="${LAMBDA_DC_ANCHOR:-0.0}"
LAMBDA_REST_ANCHOR="${LAMBDA_REST_ANCHOR:-${DEFAULT_LAMBDA_REST_ANCHOR}}"
LAMBDA_RISK_OPACITY="${LAMBDA_RISK_OPACITY:-${DEFAULT_LAMBDA_RISK_OPACITY}}"
LAMBDA_RISK_SCALE="${LAMBDA_RISK_SCALE:-${DEFAULT_LAMBDA_RISK_SCALE}}"
LAMBDA_RISK_REST="${LAMBDA_RISK_REST:-${DEFAULT_LAMBDA_RISK_REST}}"
LAMBDA_SR_RISK_OPACITY="${LAMBDA_SR_RISK_OPACITY:-0.0}"
LAMBDA_SR_RISK_SCALE="${LAMBDA_SR_RISK_SCALE:-0.0}"
LAMBDA_SR_RISK_REST="${LAMBDA_SR_RISK_REST:-${DEFAULT_LAMBDA_SR_RISK_REST}}"
SR_RISK_BOOST="${SR_RISK_BOOST:-${DEFAULT_SR_RISK_BOOST}}"
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT:-${DEFAULT_SR_PRIOR_L1_WEIGHT}}"
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT:-${DEFAULT_SR_PRIOR_HF_WEIGHT}}"
LAMBDA_PREMUL_HF_EXCESS="${LAMBDA_PREMUL_HF_EXCESS:-${DEFAULT_LAMBDA_PREMUL_HF_EXCESS}}"
DISABLE_SR_PRIOR_HF_RESIDUAL="${DISABLE_SR_PRIOR_HF_RESIDUAL:-0}"
SR_PRIOR_WARMUP_START_ITER="${SR_PRIOR_WARMUP_START_ITER:-0}"
SR_PRIOR_WARMUP_END_ITER="${SR_PRIOR_WARMUP_END_ITER:-${DEFAULT_SR_PRIOR_WARMUP_END_ITER}}"
SR_PRIOR_START_SCALE="${SR_PRIOR_START_SCALE:-${DEFAULT_SR_PRIOR_START_SCALE}}"
SR_PRIOR_END_SCALE="${SR_PRIOR_END_SCALE:-${DEFAULT_SR_PRIOR_END_SCALE}}"
SR_PRIOR_UPDATE_SCALE="${SR_PRIOR_UPDATE_SCALE:-${DEFAULT_SR_PRIOR_UPDATE_SCALE}}"
SR_PRIOR_SCHEDULE_MODE="${SR_PRIOR_SCHEDULE_MODE:-smoothstep}"
SR_RESIDUAL_ANCHOR="${SR_RESIDUAL_ANCHOR:-mip_hr}"
LAMBDA_MIP_HR_LOWFREQ="${LAMBDA_MIP_HR_LOWFREQ:-${DEFAULT_LAMBDA_MIP_HR_LOWFREQ}}"
MIP_HR_LOWFREQ_KERNEL="${MIP_HR_LOWFREQ_KERNEL:-${DEFAULT_MIP_HR_LOWFREQ_KERNEL}}"
MIP_HR_LOWFREQ_CONSISTENCY_THRESHOLD="${MIP_HR_LOWFREQ_CONSISTENCY_THRESHOLD:-${DEFAULT_MIP_HR_LOWFREQ_CONSISTENCY_THRESHOLD}}"
MIP_HR_LOWFREQ_MASK_FLOOR="${MIP_HR_LOWFREQ_MASK_FLOOR:-0.0}"
LAMBDA_MIP_CLOSURE_ALPHA="${LAMBDA_MIP_CLOSURE_ALPHA:-${DEFAULT_LAMBDA_MIP_CLOSURE_ALPHA}}"
LAMBDA_MIP_CLOSURE_PREMUL="${LAMBDA_MIP_CLOSURE_PREMUL:-${DEFAULT_LAMBDA_MIP_CLOSURE_PREMUL}}"
LAMBDA_MIP_CLOSURE_DEPTH="${LAMBDA_MIP_CLOSURE_DEPTH:-${DEFAULT_LAMBDA_MIP_CLOSURE_DEPTH}}"
LAMBDA_MIP_CLOSURE_ALPHA_OVER="${LAMBDA_MIP_CLOSURE_ALPHA_OVER:-${DEFAULT_LAMBDA_MIP_CLOSURE_ALPHA_OVER}}"
LAMBDA_MIP_CLOSURE_PREMUL_OVER="${LAMBDA_MIP_CLOSURE_PREMUL_OVER:-${DEFAULT_LAMBDA_MIP_CLOSURE_PREMUL_OVER}}"
MIP_CLOSURE_KERNEL="${MIP_CLOSURE_KERNEL:-25}"
MIP_CLOSURE_ALPHA_THRESHOLD="${MIP_CLOSURE_ALPHA_THRESHOLD:-0.05}"
MIP_CLOSURE_REFERENCE_LOWPASS="${MIP_CLOSURE_REFERENCE_LOWPASS:-1}"
MIP_CLOSURE_MIN_PIXELS="${MIP_CLOSURE_MIN_PIXELS:-256}"
MIP_CLOSURE_DEPTH_RELATIVE_MIN="${MIP_CLOSURE_DEPTH_RELATIVE_MIN:-0.5}"
RISK_RADIUS_THRESHOLD="${RISK_RADIUS_THRESHOLD:-48}"
RISK_LR_RESIDUAL_THRESHOLD="${RISK_LR_RESIDUAL_THRESHOLD:-0.10}"
RISK_ANISOTROPY_THRESHOLD="${RISK_ANISOTROPY_THRESHOLD:-20}"
RISK_MIN_SUPPORT_VIEWS="${RISK_MIN_SUPPORT_VIEWS:-4}"
MAX_DISPLACEMENT_RATIO="${MAX_DISPLACEMENT_RATIO:-${DEFAULT_MAX_DISPLACEMENT_RATIO}}"
RECOMPUTE_FILTER3D_BEFORE_TRAIN="${RECOMPUTE_FILTER3D_BEFORE_TRAIN:-1}"
RECOMPUTE_FILTER3D="${RECOMPUTE_FILTER3D:-1}"
SAVE_EVERY="${SAVE_EVERY:-200}"
RUN_RENDER="${RUN_RENDER:-1}"
RENDER_PREVIEW="${RENDER_PREVIEW:-1}"
RENDER_PREVIEW_MAX_IMAGES="${RENDER_PREVIEW_MAX_IMAGES:-16}"
RENDER_PREVIEW_COLUMNS="${RENDER_PREVIEW_COLUMNS:-4}"
RENDER_PREVIEW_THUMB_WIDTH="${RENDER_PREVIEW_THUMB_WIDTH:-360}"

echo "[mask-reparam-detail-release-v0] scene          : ${SCENE_ROOT}"
echo "[mask-reparam-detail-release-v0] settle model   : ${START_MODEL_PATH} iter=${START_ITERATION}"
echo "[mask-reparam-detail-release-v0] anchor model   : ${ANCHOR_MODEL_PATH} iter=${ANCHOR_ITERATION}"
echo "[mask-reparam-detail-release-v0] mip closure    : ${MIP_CLOSURE_MODEL_PATH} iter=${MIP_CLOSURE_ITERATION}"
echo "[mask-reparam-detail-release-v0] output model   : ${OUTPUT_MODEL}"
echo "[mask-reparam-detail-release-v0] release profile: ${RELEASE_PROFILE}"
echo "[mask-reparam-detail-release-v0] train          : iter=${ITERATIONS} xyz_lr=${XYZ_LR} op_lr=${OPACITY_LR} scale_lr=${SCALE_LR} dc_lr=${DC_LR} rest_lr=${REST_LR}"
echo "[mask-reparam-detail-release-v0] priors         : sr=${SR_PRIOR_L1_WEIGHT}/${SR_PRIOR_HF_WEIGHT} hf_excess=${LAMBDA_PREMUL_HF_EXCESS} mip_hr_lowfreq=${LAMBDA_MIP_HR_LOWFREQ}"
echo "[mask-reparam-detail-release-v0] closure        : ${LAMBDA_MIP_CLOSURE_ALPHA}/${LAMBDA_MIP_CLOSURE_PREMUL}/${LAMBDA_MIP_CLOSURE_DEPTH} over=${LAMBDA_MIP_CLOSURE_ALPHA_OVER}/${LAMBDA_MIP_CLOSURE_PREMUL_OVER}"

export SCENE_NAME SCENE_ROOT SCENE_ASSET_ROOT
export MIP_EXPERIMENT_GROUP MIP_EXPERIMENT_NAME
export START_MODEL_PATH START_ITERATION
export ANCHOR_MODEL_PATH ANCHOR_ITERATION
export MIP_CLOSURE_MODEL_PATH MIP_CLOSURE_ITERATION
export REFINE_PROFILE
export RUN_NAME RUN_ROOT OUTPUT_MODEL OUTPUT_ITERATION
export IMAGES_SUBDIR MAX_VIEWS ITERATIONS
export XYZ_LR OPACITY_LR SCALE_LR DC_LR REST_LR
export LAMBDA_LR_RGB LAMBDA_ANCHOR_RGB
export LAMBDA_XYZ_ANCHOR LAMBDA_OPACITY_ANCHOR LAMBDA_SCALE_ANCHOR
export LAMBDA_DC_ANCHOR LAMBDA_REST_ANCHOR
export LAMBDA_RISK_OPACITY LAMBDA_RISK_SCALE LAMBDA_RISK_REST
export LAMBDA_SR_RISK_OPACITY LAMBDA_SR_RISK_SCALE LAMBDA_SR_RISK_REST
export SR_RISK_BOOST
export USE_SR_PRIOR
export SR_IMAGES_SUBDIR SR_MAX_VIEWS
export SR_PRIOR_L1_WEIGHT SR_PRIOR_HF_WEIGHT
export SR_PRIOR_WARMUP_START_ITER SR_PRIOR_WARMUP_END_ITER
export SR_PRIOR_START_SCALE SR_PRIOR_END_SCALE SR_PRIOR_UPDATE_SCALE SR_PRIOR_SCHEDULE_MODE
export LAMBDA_PREMUL_HF_EXCESS DISABLE_SR_PRIOR_HF_RESIDUAL
export SR_RESIDUAL_ANCHOR
export LAMBDA_MIP_HR_LOWFREQ MIP_HR_LOWFREQ_KERNEL
export MIP_HR_LOWFREQ_CONSISTENCY_THRESHOLD MIP_HR_LOWFREQ_MASK_FLOOR
export MIP_CLOSURE_IMAGES_SUBDIR MIP_CLOSURE_MAX_VIEWS
export LAMBDA_MIP_CLOSURE_ALPHA LAMBDA_MIP_CLOSURE_PREMUL LAMBDA_MIP_CLOSURE_DEPTH
export LAMBDA_MIP_CLOSURE_ALPHA_OVER LAMBDA_MIP_CLOSURE_PREMUL_OVER
export MIP_CLOSURE_KERNEL MIP_CLOSURE_ALPHA_THRESHOLD MIP_CLOSURE_REFERENCE_LOWPASS
export MIP_CLOSURE_MIN_PIXELS MIP_CLOSURE_DEPTH_RELATIVE_MIN
export RISK_RADIUS_THRESHOLD RISK_LR_RESIDUAL_THRESHOLD
export RISK_ANISOTROPY_THRESHOLD RISK_MIN_SUPPORT_VIEWS
export MAX_DISPLACEMENT_RATIO
export ENABLE_OPACITY_UPDATE ENABLE_SCALE_UPDATE ENABLE_DC_UPDATE ENABLE_REST_UPDATE
export RECOMPUTE_FILTER3D_BEFORE_TRAIN RECOMPUTE_FILTER3D SAVE_EVERY
export RUN_RENDER RENDER_DIR RENDER_IMAGES_SUBDIR RENDER_SPLIT
export RENDER_PREVIEW RENDER_PREVIEW_MAX_IMAGES RENDER_PREVIEW_COLUMNS RENDER_PREVIEW_THUMB_WIDTH

bash "${SCRIPT_DIR}/run_recover_cleaned_mip_lr_v0_kitchen.sh"
