#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"
PREPARE_DEBUG_MODEL_PATH="${PREPARE_DEBUG_MODEL_PATH:-${SCENE_ASSET_ROOT}/${SCENE_NAME}_mip_vanilla_images8_v1/mip30k_sof_native_input_init_early4ksoft_v1_debug}"
PREPARE_DEBUG_ITERATION="${PREPARE_DEBUG_ITERATION:-34000}"
STAGE_NAME="${STAGE_NAME:-debug_stage_00b3_after_scale_canonicalize}"
BASE_MODEL_PATH="${BASE_MODEL_PATH:-${PREPARE_DEBUG_MODEL_PATH}/debug_prepare_stages/${STAGE_NAME}}"
BASE_ITERATION="${BASE_ITERATION:-${PREPARE_DEBUG_ITERATION}}"

DETAIL_RUN_NAME="${DETAIL_RUN_NAME:-k27_base}"
DETAIL_MODEL_PATH="${DETAIL_MODEL_PATH:-${SOF_ROOT}/output/recover_cleaned_mip_lr_v0/${SCENE_NAME}/${DETAIL_RUN_NAME}/recovered_mip_model_lr_miphr_v1}"
DETAIL_ITERATION="${DETAIL_ITERATION:-31600}"

DEFAULT_MIP_STABLE_MODEL="${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}_sof_native_input_init_repair_v0"
DEFAULT_MIP_STABLE_ITERATION="30000"
if [[ -z "${MIP_STABLE_MODEL_PATH+x}" ]]; then
  if [[ -d "${DEFAULT_MIP_STABLE_MODEL}" ]]; then
    MIP_STABLE_MODEL_PATH="${DEFAULT_MIP_STABLE_MODEL}"
    MIP_STABLE_ITERATION_DEFAULT="${DEFAULT_MIP_STABLE_ITERATION}"
  else
    MIP_STABLE_MODEL_PATH="${BASE_MODEL_PATH}"
    MIP_STABLE_ITERATION_DEFAULT="${BASE_ITERATION}"
  fi
fi
MIP_STABLE_ITERATION="${MIP_STABLE_ITERATION:-${MIP_STABLE_ITERATION_DEFAULT:-${BASE_ITERATION}}}"

STABLE_PRIOR_ROOT="${STABLE_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/sof_surface_v0_images_8_to_images_2_mask0.12_soft}"
STABLE_PRIOR_DIR="${STABLE_PRIOR_DIR:-${STABLE_PRIOR_ROOT}/fused_priors}"
REFERENCE_DIR="${REFERENCE_DIR:-${STABLE_PRIOR_ROOT}/aligned_references}"
SOURCE_MASK_DIR="${SOURCE_MASK_DIR:-${STABLE_PRIOR_ROOT}/usable_masks}"

QUALITY_FUSE_PROFILE="${QUALITY_FUSE_PROFILE:-safe_hf_v1}"
QUALITY_FUSE_NAME="${QUALITY_FUSE_NAME:-quality_fuse_v1_${DETAIL_RUN_NAME}_mip30ksr_${QUALITY_FUSE_PROFILE}}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/${QUALITY_FUSE_NAME}}"
REPARAM_MASK_ROOT="${REPARAM_MASK_ROOT:-${DETAIL_MODEL_PATH}/masks}"
REPARAM_OUTPUT_SOURCE_IDX_PATH="${REPARAM_OUTPUT_SOURCE_IDX_PATH:-${REPARAM_MASK_ROOT}/output_source_idx.pt}"
REPARAM_PARENT_MASK_PATH="${REPARAM_PARENT_MASK_PATH:-${REPARAM_MASK_ROOT}/geometry_selected_output_mask.pt}"
REPARAM_CHILD_MASK_PATH="${REPARAM_CHILD_MASK_PATH:-${REPARAM_MASK_ROOT}/geometry_child_output_mask.pt}"
GEOMETRY_PARENT_MASK_PATH="${GEOMETRY_PARENT_MASK_PATH:-${REPARAM_MASK_ROOT}/geometry_selected_output_mask.pt}"

IMAGES_SUBDIR="${IMAGES_SUBDIR:-images_2}"
SPLIT="${SPLIT:-train}"
MAX_VIEWS="${MAX_VIEWS:-0}"
DEBUG_VIEWS="${DEBUG_VIEWS:-4}"
PROGRESS_EVERY="${PROGRESS_EVERY:-1}"

case "${QUALITY_FUSE_PROFILE}" in
  safe_hf_v1)
    DEFAULT_LOWPASS_RADIUS="6.0"
    DEFAULT_MASK_RADIUS="3.5"
    DEFAULT_DETAIL_TEMPERATURE="0.0045"
    DEFAULT_STAR_RATIO="1.08"
    DEFAULT_STAR_MARGIN="0.006"
    DEFAULT_STAR_THRESHOLD="0.0025"
    DEFAULT_STAR_TEMPERATURE="0.0025"
    DEFAULT_LOW_REPLACE_STRENGTH="0.60"
    DEFAULT_STAR_SUPPRESS_STRENGTH="1.00"
    DEFAULT_SOURCE_MASK_RISK_STRENGTH="0.85"
    DEFAULT_DETAIL_CONF_POWER="1.75"
    DEFAULT_CONFIDENCE_STAR_POWER="1.60"
    DEFAULT_DETAIL_FLOOR="0.00"
    DEFAULT_HF_CLIP_RATIO="1.08"
    DEFAULT_HF_CLIP_MARGIN="0.008"
    DEFAULT_PRIOR_MASK_FLOOR="0.00"
    ;;
  legacy_v0)
    DEFAULT_LOWPASS_RADIUS="6.0"
    DEFAULT_MASK_RADIUS="3.0"
    DEFAULT_DETAIL_TEMPERATURE="0.006"
    DEFAULT_STAR_RATIO="1.25"
    DEFAULT_STAR_MARGIN="0.012"
    DEFAULT_STAR_THRESHOLD="0.004"
    DEFAULT_STAR_TEMPERATURE="0.0035"
    DEFAULT_LOW_REPLACE_STRENGTH="0.45"
    DEFAULT_STAR_SUPPRESS_STRENGTH="0.65"
    DEFAULT_SOURCE_MASK_RISK_STRENGTH="0.0"
    DEFAULT_DETAIL_CONF_POWER="1.0"
    DEFAULT_CONFIDENCE_STAR_POWER="1.0"
    DEFAULT_DETAIL_FLOOR="0.30"
    DEFAULT_HF_CLIP_RATIO="1.35"
    DEFAULT_HF_CLIP_MARGIN="0.020"
    DEFAULT_PRIOR_MASK_FLOOR="0.35"
    ;;
  *)
    echo "[quality-fuse-v0] unknown QUALITY_FUSE_PROFILE=${QUALITY_FUSE_PROFILE}" >&2
    exit 1
    ;;
esac

LOWPASS_RADIUS="${LOWPASS_RADIUS:-${DEFAULT_LOWPASS_RADIUS}}"
MASK_RADIUS="${MASK_RADIUS:-${DEFAULT_MASK_RADIUS}}"
DETAIL_TEMPERATURE="${DETAIL_TEMPERATURE:-${DEFAULT_DETAIL_TEMPERATURE}}"
STAR_RATIO="${STAR_RATIO:-${DEFAULT_STAR_RATIO}}"
STAR_MARGIN="${STAR_MARGIN:-${DEFAULT_STAR_MARGIN}}"
STAR_THRESHOLD="${STAR_THRESHOLD:-${DEFAULT_STAR_THRESHOLD}}"
STAR_TEMPERATURE="${STAR_TEMPERATURE:-${DEFAULT_STAR_TEMPERATURE}}"
LOW_REPLACE_STRENGTH="${LOW_REPLACE_STRENGTH:-${DEFAULT_LOW_REPLACE_STRENGTH}}"
STAR_SUPPRESS_STRENGTH="${STAR_SUPPRESS_STRENGTH:-${DEFAULT_STAR_SUPPRESS_STRENGTH}}"
SOURCE_MASK_RISK_STRENGTH="${SOURCE_MASK_RISK_STRENGTH:-${DEFAULT_SOURCE_MASK_RISK_STRENGTH}}"
DETAIL_CONF_POWER="${DETAIL_CONF_POWER:-${DEFAULT_DETAIL_CONF_POWER}}"
CONFIDENCE_STAR_POWER="${CONFIDENCE_STAR_POWER:-${DEFAULT_CONFIDENCE_STAR_POWER}}"
DETAIL_FLOOR="${DETAIL_FLOOR:-${DEFAULT_DETAIL_FLOOR}}"
HF_CLIP_RATIO="${HF_CLIP_RATIO:-${DEFAULT_HF_CLIP_RATIO}}"
HF_CLIP_MARGIN="${HF_CLIP_MARGIN:-${DEFAULT_HF_CLIP_MARGIN}}"
PRIOR_MASK_FLOOR="${PRIOR_MASK_FLOOR:-${DEFAULT_PRIOR_MASK_FLOOR}}"

PYTHON_BIN="${PYTHON_BIN:-python}"

PLY_PATH="${DETAIL_MODEL_PATH}/point_cloud/iteration_${DETAIL_ITERATION}/point_cloud.ply"
if [[ ! -f "${PLY_PATH}" ]]; then
  echo "[quality-fuse-v0] missing detail model: ${PLY_PATH}" >&2
  echo "[quality-fuse-v0] expected DETAIL_RUN_NAME=${DETAIL_RUN_NAME}" >&2
  exit 1
fi
if [[ ! -d "${STABLE_PRIOR_DIR}" ]]; then
  echo "[quality-fuse-v0] missing stable prior dir: ${STABLE_PRIOR_DIR}" >&2
  exit 1
fi

REFERENCE_ARGS=()
if [[ -n "${REFERENCE_DIR}" && -d "${REFERENCE_DIR}" ]]; then
  REFERENCE_ARGS=(--reference_dir "${REFERENCE_DIR}")
elif [[ -n "${REFERENCE_DIR}" ]]; then
  echo "[quality-fuse-v0] warning: reference dir missing, using stable prior as reference: ${REFERENCE_DIR}" >&2
fi
SOURCE_MASK_ARGS=()
if [[ -n "${SOURCE_MASK_DIR}" && -d "${SOURCE_MASK_DIR}" ]]; then
  SOURCE_MASK_ARGS=(--source_mask_dir "${SOURCE_MASK_DIR}")
elif [[ -n "${SOURCE_MASK_DIR}" ]]; then
  echo "[quality-fuse-v0] warning: source mask dir missing, writing full-confidence fallback masks: ${SOURCE_MASK_DIR}" >&2
fi

echo "[quality-fuse-v0] scene root    : ${SCENE_ROOT}"
echo "[quality-fuse-v0] detail model  : ${DETAIL_MODEL_PATH} iter=${DETAIL_ITERATION}"
echo "[quality-fuse-v0] stable prior  : ${STABLE_PRIOR_DIR}"
echo "[quality-fuse-v0] reference     : ${REFERENCE_DIR:-<stable-prior>}"
echo "[quality-fuse-v0] source mask   : ${SOURCE_MASK_DIR:-<none>}"
echo "[quality-fuse-v0] output root   : ${OUTPUT_ROOT}"
echo "[quality-fuse-v0] views         : split=${SPLIT} max=${MAX_VIEWS}"
echo "[quality-fuse-v0] profile       : ${QUALITY_FUSE_PROFILE} detail_floor=${DETAIL_FLOOR} star=${STAR_RATIO}/${STAR_MARGIN}/${STAR_THRESHOLD} clip=${HF_CLIP_RATIO}/${HF_CLIP_MARGIN}"

"${PYTHON_BIN}" "${SOF_ROOT}/scripts/build_quality_fused_sr_priors_v0.py" \
  --scene_root "${SCENE_ROOT}" \
  --detail_model_path "${DETAIL_MODEL_PATH}" \
  --detail_iteration "${DETAIL_ITERATION}" \
  --stable_prior_dir "${STABLE_PRIOR_DIR}" \
  "${REFERENCE_ARGS[@]}" \
  "${SOURCE_MASK_ARGS[@]}" \
  --output_root "${OUTPUT_ROOT}" \
  --images_subdir "${IMAGES_SUBDIR}" \
  --split "${SPLIT}" \
  --max_views "${MAX_VIEWS}" \
  --debug_views "${DEBUG_VIEWS}" \
  --progress_every "${PROGRESS_EVERY}" \
  --lowpass_radius "${LOWPASS_RADIUS}" \
  --mask_radius "${MASK_RADIUS}" \
  --detail_temperature "${DETAIL_TEMPERATURE}" \
  --star_ratio "${STAR_RATIO}" \
  --star_margin "${STAR_MARGIN}" \
  --star_threshold "${STAR_THRESHOLD}" \
  --star_temperature "${STAR_TEMPERATURE}" \
  --low_replace_strength "${LOW_REPLACE_STRENGTH}" \
  --star_suppress_strength "${STAR_SUPPRESS_STRENGTH}" \
  --source_mask_risk_strength "${SOURCE_MASK_RISK_STRENGTH}" \
  --detail_conf_power "${DETAIL_CONF_POWER}" \
  --confidence_star_power "${CONFIDENCE_STAR_POWER}" \
  --detail_floor "${DETAIL_FLOOR}" \
  --hf_clip_ratio "${HF_CLIP_RATIO}" \
  --hf_clip_margin "${HF_CLIP_MARGIN}" \
  --prior_mask_floor "${PRIOR_MASK_FLOOR}"

if [[ "${RUN_RECOVERY:-0}" == "1" ]]; then
  echo "[quality-fuse-v0] running recovery with fused prior root: ${OUTPUT_ROOT}"
  START_MODEL_PATH="${DETAIL_MODEL_PATH}" \
  START_ITERATION="${DETAIL_ITERATION}" \
  ANCHOR_MODEL_PATH="${ANCHOR_MODEL_PATH:-${MIP_STABLE_MODEL_PATH}}" \
  ANCHOR_ITERATION="${ANCHOR_ITERATION:-${MIP_STABLE_ITERATION}}" \
  MIP_CLOSURE_MODEL_PATH="${MIP_CLOSURE_MODEL_PATH:-${MIP_STABLE_MODEL_PATH}}" \
  MIP_CLOSURE_ITERATION="${MIP_CLOSURE_ITERATION:-${MIP_STABLE_ITERATION}}" \
  RUN_NAME="${RECOVERY_RUN_NAME:-${DETAIL_RUN_NAME}_quality_fuse_${QUALITY_FUSE_PROFILE}}" \
  REFINE_PROFILE="${REFINE_PROFILE:-mip_hr_anchor_v0}" \
  SR_PRIOR_ROOT="${OUTPUT_ROOT}" \
  SR_PRIOR_SUBDIR="fused_priors" \
  SR_ANCHOR_SUBDIR="aligned_references" \
  SR_PRIOR_MASK_SUBDIR="usable_masks" \
  SR_PRIOR_MASK_FLOOR="${RECOVERY_SR_PRIOR_MASK_FLOOR:-0.0}" \
  SR_PRIOR_CONSISTENCY_THRESHOLD="${RECOVERY_SR_PRIOR_CONSISTENCY_THRESHOLD:-0.10}" \
  SR_PRIOR_L1_WEIGHT="${RECOVERY_SR_PRIOR_L1_WEIGHT:-0.035}" \
  SR_PRIOR_HF_WEIGHT="${RECOVERY_SR_PRIOR_HF_WEIGHT:-0.16}" \
  SR_PRIOR_WARMUP_START_ITER="${RECOVERY_SR_PRIOR_WARMUP_START_ITER:-0}" \
  SR_PRIOR_WARMUP_END_ITER="${RECOVERY_SR_PRIOR_WARMUP_END_ITER:-450}" \
  SR_PRIOR_START_SCALE="${RECOVERY_SR_PRIOR_START_SCALE:-0.40}" \
  SR_PRIOR_END_SCALE="${RECOVERY_SR_PRIOR_END_SCALE:-0.60}" \
  SR_PRIOR_UPDATE_SCALE="${RECOVERY_SR_PRIOR_UPDATE_SCALE:-0.35}" \
  SR_PRIOR_SCHEDULE_MODE="${RECOVERY_SR_PRIOR_SCHEDULE_MODE:-smoothstep}" \
  SR_PRIOR_DELTA_CLIP="${RECOVERY_SR_PRIOR_DELTA_CLIP:-0.08}" \
  LAMBDA_PREMUL_HF_EXCESS="${RECOVERY_LAMBDA_PREMUL_HF_EXCESS:-0.08}" \
  PREMUL_HF_EXCESS_KERNEL="${RECOVERY_PREMUL_HF_EXCESS_KERNEL:-9}" \
  PREMUL_HF_EXCESS_RATIO="${RECOVERY_PREMUL_HF_EXCESS_RATIO:-1.05}" \
  PREMUL_HF_EXCESS_MARGIN="${RECOVERY_PREMUL_HF_EXCESS_MARGIN:-0.006}" \
  LAMBDA_MIP_HR_LOWFREQ="${RECOVERY_LAMBDA_MIP_HR_LOWFREQ:-0.35}" \
  LAMBDA_MIP_CLOSURE_ALPHA="${RECOVERY_LAMBDA_MIP_CLOSURE_ALPHA:-0.16}" \
  LAMBDA_MIP_CLOSURE_PREMUL="${RECOVERY_LAMBDA_MIP_CLOSURE_PREMUL:-0.45}" \
  LAMBDA_MIP_CLOSURE_ALPHA_OVER="${RECOVERY_LAMBDA_MIP_CLOSURE_ALPHA_OVER:-0.12}" \
  LAMBDA_MIP_CLOSURE_PREMUL_OVER="${RECOVERY_LAMBDA_MIP_CLOSURE_PREMUL_OVER:-0.75}" \
  REPARAM_OUTPUT_SOURCE_IDX_PATH="${RECOVERY_REPARAM_OUTPUT_SOURCE_IDX_PATH:-${REPARAM_OUTPUT_SOURCE_IDX_PATH}}" \
  REPARAM_PARENT_MASK_PATH="${RECOVERY_REPARAM_PARENT_MASK_PATH:-${REPARAM_PARENT_MASK_PATH}}" \
  REPARAM_CHILD_MASK_PATH="${RECOVERY_REPARAM_CHILD_MASK_PATH:-${REPARAM_CHILD_MASK_PATH}}" \
  GEOMETRY_PARENT_MASK_PATH="${RECOVERY_GEOMETRY_PARENT_MASK_PATH:-${GEOMETRY_PARENT_MASK_PATH}}" \
  LAMBDA_REPARAM_MASS_CAP="${RECOVERY_LAMBDA_REPARAM_MASS_CAP:-0.04}" \
  REPARAM_MASS_CAP_EPS="${RECOVERY_REPARAM_MASS_CAP_EPS:-0.10}" \
  LAMBDA_REPARAM_CHILD_TAU_CAP="${RECOVERY_LAMBDA_REPARAM_CHILD_TAU_CAP:-0.03}" \
  REPARAM_CHILD_TAU_CAP_SCALE="${RECOVERY_REPARAM_CHILD_TAU_CAP_SCALE:-1.60}" \
  REPARAM_CHILD_TAU_CAP_ABS="${RECOVERY_REPARAM_CHILD_TAU_CAP_ABS:-0.02}" \
  LAMBDA_GEOMETRY_PARENT_TAU_BRAKE="${RECOVERY_LAMBDA_GEOMETRY_PARENT_TAU_BRAKE:-0.01}" \
  GEOMETRY_PARENT_TAU_SCALE="${RECOVERY_GEOMETRY_PARENT_TAU_SCALE:-0.90}" \
  REPARAM_PRUNE_ITERS="${RECOVERY_REPARAM_PRUNE_ITERS:-1000,2500,4000}" \
  REPARAM_PRUNE_CHILD_DEAD_TAU="${RECOVERY_REPARAM_PRUNE_CHILD_DEAD_TAU:-0.002}" \
  REPARAM_PRUNE_CHILD_SPIKE_TAU_SCALE="${RECOVERY_REPARAM_PRUNE_CHILD_SPIKE_TAU_SCALE:-1.35}" \
  REPARAM_PRUNE_CHILD_SPIKE_TAU_ABS="${RECOVERY_REPARAM_PRUNE_CHILD_SPIKE_TAU_ABS:-0.02}" \
  REPARAM_PRUNE_CHILD_SPIKE_ANISOTROPY="${RECOVERY_REPARAM_PRUNE_CHILD_SPIKE_ANISOTROPY:-14.0}" \
  REPARAM_PRUNE_CHILD_SPIKE_RISK_MIN="${RECOVERY_REPARAM_PRUNE_CHILD_SPIKE_RISK_MIN:-0.20}" \
  ITERATIONS="${RECOVERY_ITERATIONS:-5000}" \
  MAX_VIEWS="${RECOVERY_MAX_VIEWS:-0}" \
  SR_MAX_VIEWS="${RECOVERY_SR_MAX_VIEWS:-0}" \
  MIP_CLOSURE_MAX_VIEWS="${RECOVERY_MIP_CLOSURE_MAX_VIEWS:-0}" \
  SAVE_EVERY="${RECOVERY_SAVE_EVERY:-2500}" \
  RENDER_CHECKPOINTS="${RECOVERY_RENDER_CHECKPOINTS:-1}" \
  RENDER_CHECKPOINT_MAX_VIEWS="${RECOVERY_RENDER_CHECKPOINT_MAX_VIEWS:-0}" \
  RUN_RENDER="${RUN_RENDER:-1}" \
  bash "${SOF_ROOT}/scripts/run_recover_cleaned_mip_lr_v0_kitchen.sh"
fi
