#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v8_hfsmall_dense}"

# v8 focuses on denser, smaller HF carriers and mild position refinement:
# more seed births, smaller screen-space footprint, stricter carrier clamp, and
# a capped direct xyz nudge from the prior residual loss for PRIOR_INJECTED only.
export SAVE_CHECKPOINT_AFTER="${SAVE_CHECKPOINT_AFTER:-0}"

export PRIOR_HF_SEED_SCALE_MODE="${PRIOR_HF_SEED_SCALE_MODE:-pixel}"
export PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-0.50}"
export PRIOR_HF_SEED_MIN_PIXEL_RADIUS="${PRIOR_HF_SEED_MIN_PIXEL_RADIUS:-0.18}"
export PRIOR_HF_SEED_MAX_PIXEL_RADIUS="${PRIOR_HF_SEED_MAX_PIXEL_RADIUS:-0.62}"
export PRIOR_HF_SEED_MAX_PROVIDER_RATIO="${PRIOR_HF_SEED_MAX_PROVIDER_RATIO:-0.10}"
export PRIOR_HF_SEED_SCALE_CLAMP_ENABLE="${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE:-1}"
export PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS:-0.016}"
export PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY:-7.0}"
export PRIOR_HF_SEED_DIAG_LARGE_SCALE="${PRIOR_HF_SEED_DIAG_LARGE_SCALE:-0.016}"

export PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.30}"
export PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-768}"
export PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-393216}"
export PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.045}"
export PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.020}"
export PRIOR_HF_SEED_PRUNE_PROTECT_ITERS="${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS:-1200}"

export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-6.9}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT:-2.10}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT:-4.90}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION:-0.30}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN:-1.60}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT:-1.35}"
export PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-6.9}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-10.0}"
export PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-3.6}"

export PRIOR_DIRECT_XYZ_NUDGE_LR="${PRIOR_DIRECT_XYZ_NUDGE_LR:-0.00002}"
export PRIOR_DIRECT_XYZ_NUDGE_MAX_STEP="${PRIOR_DIRECT_XYZ_NUDGE_MAX_STEP:-0.00070}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen_viewmajor_hfsmall_boost.sh"
