#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v10_hfsmall_bubbleclean}"

# v10 keeps v9's stronger residual-color carry, but ports the NoSR
# non-surface cleanup idea to dynamic PRIOR_INJECTED bubble candidates:
# round, opaque small blobs get a black-background HF/alpha penalty plus
# a soft post-step opacity quarantine.
export PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN="${PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN:-3.0}"

export PRIOR_BUBBLE_CLEANUP_ENABLE="${PRIOR_BUBBLE_CLEANUP_ENABLE:-1}"
export PRIOR_BUBBLE_CLEANUP_FROM_ITER="${PRIOR_BUBBLE_CLEANUP_FROM_ITER:-30200}"
export PRIOR_BUBBLE_CLEANUP_UNTIL_ITER="${PRIOR_BUBBLE_CLEANUP_UNTIL_ITER:-32000}"
export PRIOR_BUBBLE_CLEANUP_INTERVAL="${PRIOR_BUBBLE_CLEANUP_INTERVAL:-4}"
export PRIOR_BUBBLE_CLEANUP_OPACITY_MIN="${PRIOR_BUBBLE_CLEANUP_OPACITY_MIN:-0.14}"
export PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN:-0.0025}"
export PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX:-0.0165}"
export PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX="${PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX:-2.35}"
export PRIOR_BUBBLE_CLEANUP_MIN_GENERATION="${PRIOR_BUBBLE_CLEANUP_MIN_GENERATION:-0}"

export LAMBDA_PRIOR_BUBBLE_HF="${LAMBDA_PRIOR_BUBBLE_HF:-1.2}"
export LAMBDA_PRIOR_BUBBLE_RGB_ENERGY="${LAMBDA_PRIOR_BUBBLE_RGB_ENERGY:-0.15}"
export LAMBDA_PRIOR_BUBBLE_ALPHA_HF="${LAMBDA_PRIOR_BUBBLE_ALPHA_HF:-0.70}"
export LAMBDA_PRIOR_BUBBLE_ALPHA_MASS="${LAMBDA_PRIOR_BUBBLE_ALPHA_MASS:-0.08}"
export PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY="${PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY:-0.82}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen_viewmajor_hfsmall_carry.sh"
