#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v0}"

# View-major curriculum: each prior view gets a short primary injection episode,
# then nearby views refine the injected carriers before the sweep moves on.
export PRIOR_VIEW_CURRICULUM_ENABLE="${PRIOR_VIEW_CURRICULUM_ENABLE:-1}"
export PRIOR_VIEW_CURRICULUM_START_ITER="${PRIOR_VIEW_CURRICULUM_START_ITER:-30001}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS:-4}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS:-3}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS:-2}"
export PRIOR_VIEW_CURRICULUM_MAX_VIEWS="${PRIOR_VIEW_CURRICULUM_MAX_VIEWS:-0}"
export PRIOR_VIEW_CURRICULUM_SETTLE_ITERS="${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS:-250}"
export PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY="${PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY:-1}"
export PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-2.0}"
export PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE:-0.9}"
export PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE="${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE:-0.35}"

export PRIOR_RESIDUAL_USE_MASKS="${PRIOR_RESIDUAL_USE_MASKS:-0}"
export OPTIMIZE_SOURCE_TAG="${OPTIMIZE_SOURCE_TAG:-prior}"
export PRIOR_HF_SEED_ORIGINAL_ONLY="${PRIOR_HF_SEED_ORIGINAL_ONLY:-0}"
export PRIOR_HF_SEED_FIRST_CYCLE_ONLY="${PRIOR_HF_SEED_FIRST_CYCLE_ONLY:-0}"

export PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-3.0}"
export PRIOR_RESIDUAL_DELTA_CLIP="${PRIOR_RESIDUAL_DELTA_CLIP:-0.80}"
export PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-4.0}"

export PRIOR_HF_SEED_FROM_ITER="${PRIOR_HF_SEED_FROM_ITER:-30001}"
export PRIOR_HF_SEED_UNTIL_ITER="${PRIOR_HF_SEED_UNTIL_ITER:-0}"
export PRIOR_HF_SEED_INTERVAL="${PRIOR_HF_SEED_INTERVAL:-1}"
export PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-128}"
export PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-131072}"
export PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-0.75}"
export PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.22}"
export PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.22}"
export PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.045}"
export PRIOR_HF_SEED_PRUNE_PROTECT_ITERS="${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS:-900}"
export PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST:-2.0}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-3.0}"
export PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-2.0}"

export DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER:-31850}"
export DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL:-50}"
export DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.000025}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen.sh"
