#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-${WORK_ROOT}/${SCENE_NAME}}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR:-images_8}"
TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR:-images_8}"
TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR:-images_2}"

MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k_rerun_v0}"
BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}}"
BASELINE_ITERATION="${BASELINE_ITERATION:-30000}"
START_CHECKPOINT="${START_CHECKPOINT:-${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth}"

PREPARED_SR_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/sof_surface_v0_${LR_REFERENCE_IMAGES_SUBDIR}_to_${TARGET_IMAGES_SUBDIR}_mask0.12_soft}"
PRIOR_EDGE_SUBDIR="${PRIOR_EDGE_SUBDIR:-fused_priors}"
PRIOR_LOCAL_SUBDIR="${PRIOR_LOCAL_SUBDIR:-aligned_references}"
PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR:-usable_masks}"
PRIOR_DIR="${PRIOR_DIR:-${SCENE_ROOT}/priors}"
FORCE_PREPARE_PRIORS="${FORCE_PREPARE_PRIORS:-0}"

SURFACE_STATE_PROFILE="${SURFACE_STATE_PROFILE:-conservative_v0}"
STATE_RUN_NAME_DEFAULT="mip30k_rerun_gs2mesh_surface_state_v0"
if [[ "${SURFACE_STATE_PROFILE}" != "conservative_v0" ]]; then
  STATE_RUN_NAME_DEFAULT="${STATE_RUN_NAME_DEFAULT}_${SURFACE_STATE_PROFILE}"
fi
STATE_RUN_NAME="${STATE_RUN_NAME:-${STATE_RUN_NAME_DEFAULT}}"
STATE_DIR="${STATE_DIR:-${SOF_ROOT}/output/gaussian_surface_state_v0/${SCENE_NAME}/${STATE_RUN_NAME}}"
SURFACE_STATE_PAYLOAD="${SURFACE_STATE_PAYLOAD:-${STATE_DIR}/gaussian_surface_state_v0.pt}"
SURFACE_MASK_KEY="${SURFACE_MASK_KEY:-surface_candidate}"

LAMBDA_PRIOR_LOCAL="${LAMBDA_PRIOR_LOCAL:-0.03}"
LAMBDA_PRIOR_EDGE="${LAMBDA_PRIOR_EDGE:-0.20}"
PRIOR_EDGE_LOSS_MODE="${PRIOR_EDGE_LOSS_MODE:-detail_v1}"
PRIOR_EDGE_DETAIL_ALPHA="${PRIOR_EDGE_DETAIL_ALPHA:-0.60}"
PRIOR_EDGE_DETAIL_ALPHA_FINAL="${PRIOR_EDGE_DETAIL_ALPHA_FINAL:--1.0}"
PRIOR_EDGE_DETAIL_WARMUP_ITERS="${PRIOR_EDGE_DETAIL_WARMUP_ITERS:-0}"
PRIOR_EDGE_DETAIL_WEIGHT="${PRIOR_EDGE_DETAIL_WEIGHT:-1.0}"
PRIOR_EDGE_LOWFREQ_WEIGHT="${PRIOR_EDGE_LOWFREQ_WEIGHT:-0.03}"
PRIOR_EDGE_GRAD_WEIGHT="${PRIOR_EDGE_GRAD_WEIGHT:-0.0}"
PRIOR_EDGE_LOWFREQ_THRESHOLD="${PRIOR_EDGE_LOWFREQ_THRESHOLD:-0.08}"
PRIOR_EDGE_LOWFREQ_ANCHOR="${PRIOR_EDGE_LOWFREQ_ANCHOR:-render}"
PRIOR_EDGE_DETAIL_MIN_GAIN="${PRIOR_EDGE_DETAIL_MIN_GAIN:-0.0}"
PRIOR_EDGE_CONFIDENCE_POWER="${PRIOR_EDGE_CONFIDENCE_POWER:-1.0}"
PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-0.35}"
PRIOR_EDGE_MIN_PIXELS="${PRIOR_EDGE_MIN_PIXELS:-64}"
TRAIN_RESOLUTION="${TRAIN_RESOLUTION:-1}"
RENDER_RESOLUTION="${RENDER_RESOLUTION:-1}"

ITERATIONS="${ITERATIONS:-32000}"
RUN_NAME_DEFAULT="${MIP_EXPERIMENT_NAME}_surface_prior_simple_v0_${SURFACE_MASK_KEY}_r${TRAIN_RESOLUTION}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-${RUN_NAME_DEFAULT}}"
RUN_ROOT="${RUN_ROOT:-${SOF_ROOT}/output/${SCENE_NAME}_mipsplatting_surface_prior_simple_v0}"
PRIOR_MODEL_DIR="${PRIOR_MODEL_DIR:-${RUN_ROOT}/${EXPERIMENT_NAME}}"

RUN_RENDER_AFTER="${RUN_RENDER_AFTER:-1}"
RUN_METRICS_AFTER="${RUN_METRICS_AFTER:-1}"
PYTHON_BIN="${PYTHON_BIN:-python}"

PRIOR_EDGE_DIR="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_EDGE_SUBDIR}"
PRIOR_LOCAL_DIR="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_LOCAL_SUBDIR}"
PRIOR_MASK_DIR="${PREPARED_SR_PRIOR_ROOT}/${PRIOR_MASK_SUBDIR}"

if [[ ! -f "${START_CHECKPOINT}" ]]; then
  echo "[mip-surface-prior-simple-v0] missing baseline checkpoint: ${START_CHECKPOINT}" >&2
  exit 1
fi
if [[ ! -f "${SURFACE_STATE_PAYLOAD}" ]]; then
  echo "[mip-surface-prior-simple-v0] missing surface-state payload: ${SURFACE_STATE_PAYLOAD}" >&2
  exit 1
fi
if [[ ! -d "${PREPARED_SR_PRIOR_ROOT}" ]]; then
  echo "[mip-surface-prior-simple-v0] missing prepared prior root: ${PREPARED_SR_PRIOR_ROOT}" >&2
  exit 1
fi
for path in "${PRIOR_EDGE_DIR}" "${PRIOR_LOCAL_DIR}" "${PRIOR_MASK_DIR}"; do
  if [[ ! -d "${path}" ]]; then
    echo "[mip-surface-prior-simple-v0] required prepared-prior subdir missing: ${path}" >&2
    exit 1
  fi
done

echo "[mip-surface-prior-simple-v0] scene              : ${SCENE_ROOT}"
echo "[mip-surface-prior-simple-v0] baseline model     : ${BASELINE_MODEL_DIR} iter=${BASELINE_ITERATION}"
echo "[mip-surface-prior-simple-v0] prepared prior     : ${PREPARED_SR_PRIOR_ROOT}"
echo "[mip-surface-prior-simple-v0] surface payload    : ${SURFACE_STATE_PAYLOAD}"
echo "[mip-surface-prior-simple-v0] surface mask key   : ${SURFACE_MASK_KEY}"
echo "[mip-surface-prior-simple-v0] local/edge lambda  : ${LAMBDA_PRIOR_LOCAL}/${LAMBDA_PRIOR_EDGE}"
echo "[mip-surface-prior-simple-v0] train/render res   : ${TRAIN_RESOLUTION}/${RENDER_RESOLUTION}"
echo "[mip-surface-prior-simple-v0] output model       : ${PRIOR_MODEL_DIR}"

(
  cd "${SOF_ROOT}"
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
  LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR}" \
  TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR}" \
  TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR}" \
  BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR}" \
  BASELINE_ITERATION="${BASELINE_ITERATION}" \
  START_CHECKPOINT="${START_CHECKPOINT}" \
  PREPARED_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT}" \
  PRIOR_DIR="${PRIOR_DIR}" \
  FORCE_PREPARE_PRIORS="${FORCE_PREPARE_PRIORS}" \
  PREPARED_PRIOR_EXPECTED_REFERENCE_DIR="${SCENE_ROOT}/${TARGET_IMAGES_SUBDIR}" \
  PRIOR_SUBDIR="${PRIOR_EDGE_SUBDIR}" \
  PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR}" \
  PRIOR_LOCAL_DIR="${PRIOR_LOCAL_DIR}" \
  PRIOR_LOCAL_MASK_DIR="${PRIOR_MASK_DIR}" \
  LAMBDA_PRIOR_LOCAL="${LAMBDA_PRIOR_LOCAL}" \
  PRIOR_EDGE_DIR="${PRIOR_EDGE_DIR}" \
  PRIOR_EDGE_MASK_DIR="${PRIOR_MASK_DIR}" \
  LAMBDA_PRIOR_EDGE="${LAMBDA_PRIOR_EDGE}" \
  PRIOR_EDGE_LOSS_MODE="${PRIOR_EDGE_LOSS_MODE}" \
  PRIOR_EDGE_MIN_PIXELS="${PRIOR_EDGE_MIN_PIXELS}" \
  PRIOR_EDGE_DETAIL_ALPHA="${PRIOR_EDGE_DETAIL_ALPHA}" \
  PRIOR_EDGE_DETAIL_ALPHA_FINAL="${PRIOR_EDGE_DETAIL_ALPHA_FINAL}" \
  PRIOR_EDGE_DETAIL_WARMUP_ITERS="${PRIOR_EDGE_DETAIL_WARMUP_ITERS}" \
  PRIOR_EDGE_DETAIL_WEIGHT="${PRIOR_EDGE_DETAIL_WEIGHT}" \
  PRIOR_EDGE_LOWFREQ_WEIGHT="${PRIOR_EDGE_LOWFREQ_WEIGHT}" \
  PRIOR_EDGE_GRAD_WEIGHT="${PRIOR_EDGE_GRAD_WEIGHT}" \
  PRIOR_EDGE_LOWFREQ_THRESHOLD="${PRIOR_EDGE_LOWFREQ_THRESHOLD}" \
  PRIOR_EDGE_LOWFREQ_ANCHOR="${PRIOR_EDGE_LOWFREQ_ANCHOR}" \
  PRIOR_EDGE_DETAIL_MIN_GAIN="${PRIOR_EDGE_DETAIL_MIN_GAIN}" \
  PRIOR_EDGE_CONFIDENCE_POWER="${PRIOR_EDGE_CONFIDENCE_POWER}" \
  PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE}" \
  PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD="${SURFACE_STATE_PAYLOAD}" \
  PRIOR_LOSS_GAUSSIAN_MASK_KEY="${SURFACE_MASK_KEY}" \
  PRIOR_ONLY_EDGE_FINETUNE=0 \
  RUN_BASELINE_IF_MISSING=0 \
  ITERATIONS="${ITERATIONS}" \
  TRAIN_RESOLUTION="${TRAIN_RESOLUTION}" \
  RENDER_RESOLUTION="${RENDER_RESOLUTION}" \
  EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
  PRIOR_MODEL_DIR="${PRIOR_MODEL_DIR}" \
  RUN_RENDER_AFTER="${RUN_RENDER_AFTER}" \
  RUN_METRICS_AFTER="${RUN_METRICS_AFTER}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SCRIPT_DIR}/run_mipsplatting_stablesr_prior_scene.sh"
)
