#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"

SCENE_NAME="${SCENE_NAME}" \
SCENE_ROOT="${SCENE_ROOT}" \
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP}" \
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
MIP_MODEL_PATH="${MIP_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}}" \
MIP_TO_SOF_PROFILE="${MIP_TO_SOF_PROFILE:-early4ksoft_v1}" \
PREPARE_INPUT_PROFILE="${PREPARE_INPUT_PROFILE:-early4ksoft_v1}" \
RUN_NAME="${RUN_NAME:-detail34k_early4ksoft_depthprior_full_v0}" \
FINAL_ITERATION="${FINAL_ITERATION:-34000}" \
OUTPUT_ITERATION="${OUTPUT_ITERATION:-34000}" \
MAX_VIEWS="${MAX_VIEWS:-0}" \
SR_MAX_VIEWS="${SR_MAX_VIEWS:-0}" \
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT:-0.0}" \
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT:-0.0}" \
MIP_OBS_CLOSURE_MAX_VIEWS="${MIP_OBS_CLOSURE_MAX_VIEWS:-0}" \
FILTER_MAX_VIEWS="${FILTER_MAX_VIEWS:-0}" \
DEPTH_PRIOR_ROOT="${DEPTH_PRIOR_ROOT:-${SCENE_ROOT}/depthpriors}" \
DEPTH_PRIOR_SUBDIRS="${DEPTH_PRIOR_SUBDIRS:-depth,}" \
DEPTH_PRIOR_CONFIDENCE_SUBDIRS="${DEPTH_PRIOR_CONFIDENCE_SUBDIRS:-}" \
DEPTH_PRIOR_CONFIDENCE_MIN="${DEPTH_PRIOR_CONFIDENCE_MIN:-0.0}" \
DEPTH_PRIOR_AGREEMENT_THRESHOLD="${DEPTH_PRIOR_AGREEMENT_THRESHOLD:-0.0}" \
DEPTH_PRIOR_AGREEMENT_FLOOR="${DEPTH_PRIOR_AGREEMENT_FLOOR:-0.0}" \
DEPTH_PRIOR_ALIGN_MODE="${DEPTH_PRIOR_ALIGN_MODE:-affine_robust}" \
DEPTH_PRIOR_WEIGHT_GAIN="${DEPTH_PRIOR_WEIGHT_GAIN:-1.0}" \
DEPTH_PRIOR_WEIGHT_POWER="${DEPTH_PRIOR_WEIGHT_POWER:-1.0}" \
DEPTH_PRIOR_WEIGHT_MIN="${DEPTH_PRIOR_WEIGHT_MIN:-0.0}" \
LAMBDA_DEPTH_PRIOR="${LAMBDA_DEPTH_PRIOR:-0.05}" \
LAMBDA_DEPTH_PRIOR_NORMAL="${LAMBDA_DEPTH_PRIOR_NORMAL:-0.0}" \
LAMBDA_DEPTH_PRIOR_SELF_NORMAL="${LAMBDA_DEPTH_PRIOR_SELF_NORMAL:-0.05}" \
DEPTH_PRIOR_WARMUP_START_ITER="${DEPTH_PRIOR_WARMUP_START_ITER:-0}" \
DEPTH_PRIOR_WARMUP_END_ITER="${DEPTH_PRIOR_WARMUP_END_ITER:-1200}" \
DEPTH_PRIOR_START_SCALE="${DEPTH_PRIOR_START_SCALE:-1.0}" \
DEPTH_PRIOR_END_SCALE="${DEPTH_PRIOR_END_SCALE:-1.6}" \
DEPTH_PRIOR_UPDATE_SCALE="${DEPTH_PRIOR_UPDATE_SCALE:-1.0}" \
bash "${SCRIPT_DIR}/run_mip_to_sof_surface_v0_kitchen.sh"
