#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-${WORK_ROOT}/${SCENE_NAME}}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

INPUT_EXPERIMENT_NAME="${INPUT_EXPERIMENT_NAME:-mip30k_rerun_check_directsrc_r1_v0}"
INPUT_ITERATION="${INPUT_ITERATION:-30000}"
CLEANUP_ITERS="${CLEANUP_ITERS:-2000}"
FINAL_ITER="${FINAL_ITER:-$(( INPUT_ITERATION + CLEANUP_ITERS ))}"

CAVE_REASSIGN_NAME="${CAVE_REASSIGN_NAME:-render_x1_restormer_cave_hf_reassignment_dense_v0_smoke}"
CAVE_REASSIGN_PAYLOAD="${CAVE_REASSIGN_PAYLOAD:-${SCENE_ASSET_ROOT}/cave_hf_reassignment/${CAVE_REASSIGN_NAME}/cave_hf_reassignment_v0.pt}"

RESTORMER_PRIOR_ROOT="${RESTORMER_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/render_x1_restormer_aligned_images_2_scratch_v0}"
RESTORMER_PRIOR_SUBDIR="${RESTORMER_PRIOR_SUBDIR:-fused_priors}"
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
INPUT_MODEL_DIR="${INPUT_MODEL_DIR:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${INPUT_EXPERIMENT_NAME}}"

if [[ ! -f "${CAVE_REASSIGN_PAYLOAD}" ]]; then
  echo "[cave-hf-transfer-v0] CAVE reassignment payload not found: ${CAVE_REASSIGN_PAYLOAD}" >&2
  echo "[cave-hf-transfer-v0] build it first with scripts/run_build_cave_hf_reassignment_payload_v0_kitchen.sh" >&2
  exit 1
fi

export WORK_ROOT
export SCENE_NAME
export INPUT_EXPERIMENT_NAME
export INPUT_ITERATION
export CLEANUP_ITERS
export MIP_EXPERIMENT_GROUP
export INPUT_MODEL_DIR

export RUN_TAG="${RUN_TAG:-${INPUT_EXPERIMENT_NAME}_cave_hf_transfer_to${FINAL_ITER}_v0}"
export FORCE_RERUN="${FORCE_RERUN:-1}"
export SAVE_CHECKPOINT_AFTER="${SAVE_CHECKPOINT_AFTER:-0}"

export EXTERNAL_PRIOR_ROOT="${EXTERNAL_PRIOR_ROOT:-${RESTORMER_PRIOR_ROOT}}"
export EXTERNAL_PRIOR_SUBDIR="${EXTERNAL_PRIOR_SUBDIR:-${RESTORMER_PRIOR_SUBDIR}}"
export PRIOR_LOSS_MODE="${PRIOR_LOSS_MODE:-ie_srgs_fusion_v0}"
export PRIOR_IE_SRGS_THRESHOLD="${PRIOR_IE_SRGS_THRESHOLD:-0.9}"
export PRIOR_L1_WEIGHT="${PRIOR_L1_WEIGHT:-0.05}"
export PRIOR_HF_WEIGHT="${PRIOR_HF_WEIGHT:-0.10}"
export PRIOR_ANCHOR_DIR="${PRIOR_ANCHOR_DIR:-${INPUT_MODEL_DIR}/train/ours_30000/test_preds_1}"

export LAYER_FREQUENCY_MASK_PAYLOAD="${LAYER_FREQUENCY_MASK_PAYLOAD:-${CAVE_REASSIGN_PAYLOAD}}"
export LAYER_FREQUENCY_NON_SURFACE_KEY="${LAYER_FREQUENCY_NON_SURFACE_KEY:-lf_safe}"
export LAYER_FREQUENCY_SURFACE_KEY="${LAYER_FREQUENCY_SURFACE_KEY:-hf_owned}"
export LAYER_FREQUENCY_TRANSFER_SCORE_KEY="${LAYER_FREQUENCY_TRANSFER_SCORE_KEY:-hf_score}"
export LAYER_FREQUENCY_TRANSFER_CANDIDATE_KEY="${LAYER_FREQUENCY_TRANSFER_CANDIDATE_KEY:-hf_candidate}"
export LAYER_FREQUENCY_TRANSFER_START_RATIO="${LAYER_FREQUENCY_TRANSFER_START_RATIO:-0.12}"
export LAYER_FREQUENCY_TRANSFER_FINAL_RATIO="${LAYER_FREQUENCY_TRANSFER_FINAL_RATIO:-0.55}"
export LAYER_FREQUENCY_TRANSFER_MIN_SCORE="${LAYER_FREQUENCY_TRANSFER_MIN_SCORE:-0.03}"
export LAYER_FREQUENCY_TRANSFER_CURVE="${LAYER_FREQUENCY_TRANSFER_CURVE:-smoothstep}"
export LAYER_FREQUENCY_TRANSFER_COMPLEMENT_TO_NON_SURFACE="${LAYER_FREQUENCY_TRANSFER_COMPLEMENT_TO_NON_SURFACE:-1}"
export LAYER_FREQUENCY_SURFACE_SUBSET_HF="${LAYER_FREQUENCY_SURFACE_SUBSET_HF:-1}"
export LAYER_FREQUENCY_SURFACE_TARGET="${LAYER_FREQUENCY_SURFACE_TARGET:-prior}"

export LAMBDA_NON_SURFACE_HF="${LAMBDA_NON_SURFACE_HF:-0.020}"
export LAMBDA_SURFACE_HF_CLOSURE="${LAMBDA_SURFACE_HF_CLOSURE:-0.010}"
export LAMBDA_SURFACE_LOWFREQ_ENERGY="${LAMBDA_SURFACE_LOWFREQ_ENERGY:-0.002}"
export LAMBDA_LAYER_HANDOFF_LOW_BALANCE="${LAMBDA_LAYER_HANDOFF_LOW_BALANCE:-0.006}"
export LAMBDA_LAYER_HANDOFF_TOTAL_HF="${LAMBDA_LAYER_HANDOFF_TOTAL_HF:-0.000}"
export LAYER_FREQUENCY_HANDOFF_LOWFREQ_KERNEL="${LAYER_FREQUENCY_HANDOFF_LOWFREQ_KERNEL:-15}"
export SURFACE_HF_UPDATE_SCALE="${SURFACE_HF_UPDATE_SCALE:-0.75}"

echo "[cave-hf-transfer-v0] payload : ${CAVE_REASSIGN_PAYLOAD}"
echo "[cave-hf-transfer-v0] prior   : ${EXTERNAL_PRIOR_ROOT}/${EXTERNAL_PRIOR_SUBDIR}"
echo "[cave-hf-transfer-v0] run tag : ${RUN_TAG}"
echo "[cave-hf-transfer-v0] handoff : low=${LAMBDA_LAYER_HANDOFF_LOW_BALANCE} total_hf=${LAMBDA_LAYER_HANDOFF_TOTAL_HF} surf_lf=${LAMBDA_SURFACE_LOWFREQ_ENERGY}"

bash "${SCRIPT_DIR}/run_mipsplatting_nosr_layerfreq_cleanup_v0_kitchen.sh"
