#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
DEFAULT_MIPSPLATTING_ROOT="$(cd -- "${SOF_ROOT}/.." && pwd)/mip-splatting"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"

MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"
MIP_TO_SOF_PROFILE="${MIP_TO_SOF_PROFILE:-default_v0}"
PREPARE_INPUT_PROFILE="${PREPARE_INPUT_PROFILE:-${MIP_TO_SOF_PROFILE}}"

case "${PREPARE_INPUT_PROFILE}" in
  default_v0)
    DEFAULT_MIP_INPUT_MODEL_NAME="${MIP_EXPERIMENT_NAME}_sof_native_input"
    DEFAULT_SCALE_CLAMP_MODE="both"
    DEFAULT_INIT_REPAIR_MODE="none"
    DEFAULT_INIT_REPAIR_MAX_FRACTION="0.04"
    DEFAULT_INIT_REPAIR_MAX_COUNT="50000"
    DEFAULT_INIT_REPAIR_MIN_OPACITY="0.04"
    DEFAULT_INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO="0.003"
    DEFAULT_INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO="0.0015"
    DEFAULT_INIT_REPAIR_MIN_FILTER_SCALE_RATIO="0.75"
    DEFAULT_INIT_REPAIR_MIN_FULL_ANISOTROPY="0.0"
    DEFAULT_INIT_REPAIR_SPLIT_COUNT="4"
    DEFAULT_INIT_REPAIR_CHILD_LAYOUT="grid"
    DEFAULT_INIT_REPAIR_CHILD_SCALE_MULTIPLIER="0.55"
    DEFAULT_INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER="-1.0"
    DEFAULT_INIT_REPAIR_CHILD_OPACITY_SCALE="0.75"
    DEFAULT_INIT_REPAIR_ENERGY_CONSERVE_MODE="none"
    DEFAULT_INIT_REPAIR_FILTER_SCALE="0.25"
    DEFAULT_INIT_REPAIR_FILTER_CAP_RATIO="0.0015"
    DEFAULT_INIT_REPAIR_OFFSET_SCALE="0.45"
    DEFAULT_INIT_REPAIR_BRIGHT_MAX_FRACTION="0.01"
    DEFAULT_INIT_REPAIR_BRIGHT_MAX_COUNT="15000"
    DEFAULT_INIT_REPAIR_BRIGHT_TARGET="non_children"
    DEFAULT_INIT_REPAIR_BRIGHT_MIN_OPACITY="0.06"
    DEFAULT_INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO="0.0025"
    DEFAULT_INIT_REPAIR_BRIGHT_LUMA_QUANTILE="0.995"
    DEFAULT_INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO="1.8"
    DEFAULT_INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA="0.18"
    DEFAULT_INIT_REPAIR_BRIGHT_NEIGHBOR_K="8"
    DEFAULT_INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER="1.35"
    DEFAULT_INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER="1.0"
    DEFAULT_INIT_REPAIR_BRIGHT_OPACITY_SCALE="0.6"
    DEFAULT_INIT_REPAIR_BRIGHT_DC_SCALE="0.82"
    DEFAULT_INIT_REPAIR_BRIGHT_REST_SCALE="0.4"
    DEFAULT_INIT_REPAIR_BRIGHT_FILTER_SCALE="0.5"
    DEFAULT_INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO="0.001"
    ;;
  early4ksoft_v1)
    DEFAULT_MIP_INPUT_MODEL_NAME="${MIP_EXPERIMENT_NAME}_sof_native_input_init_early4ksoft_v1"
    DEFAULT_SCALE_CLAMP_MODE="max_only"
    DEFAULT_INIT_REPAIR_MODE="energy_split_replace_soften_bright"
    DEFAULT_INIT_REPAIR_MAX_FRACTION="0.05"
    DEFAULT_INIT_REPAIR_MAX_COUNT="90000"
    DEFAULT_INIT_REPAIR_MIN_OPACITY="0.035"
    DEFAULT_INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO="0.0022"
    DEFAULT_INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO="0.0010"
    DEFAULT_INIT_REPAIR_MIN_FILTER_SCALE_RATIO="0.45"
    DEFAULT_INIT_REPAIR_MIN_FULL_ANISOTROPY="5.0"
    DEFAULT_INIT_REPAIR_SPLIT_COUNT="6"
    DEFAULT_INIT_REPAIR_CHILD_LAYOUT="major_axis"
    DEFAULT_INIT_REPAIR_CHILD_SCALE_MULTIPLIER="0.80"
    DEFAULT_INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER="0.32"
    DEFAULT_INIT_REPAIR_CHILD_OPACITY_SCALE="1.0"
    DEFAULT_INIT_REPAIR_ENERGY_CONSERVE_MODE="area"
    DEFAULT_INIT_REPAIR_FILTER_SCALE="0.35"
    DEFAULT_INIT_REPAIR_FILTER_CAP_RATIO="0.0010"
    DEFAULT_INIT_REPAIR_OFFSET_SCALE="0.85"
    DEFAULT_INIT_REPAIR_BRIGHT_MAX_FRACTION="0.015"
    DEFAULT_INIT_REPAIR_BRIGHT_MAX_COUNT="25000"
    DEFAULT_INIT_REPAIR_BRIGHT_TARGET="children_only"
    DEFAULT_INIT_REPAIR_BRIGHT_MIN_OPACITY="0.020"
    DEFAULT_INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO="0.0022"
    DEFAULT_INIT_REPAIR_BRIGHT_LUMA_QUANTILE="0.985"
    DEFAULT_INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO="1.15"
    DEFAULT_INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA="0.045"
    DEFAULT_INIT_REPAIR_BRIGHT_NEIGHBOR_K="12"
    DEFAULT_INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER="1.20"
    DEFAULT_INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER="1.15"
    DEFAULT_INIT_REPAIR_BRIGHT_OPACITY_SCALE="0.55"
    DEFAULT_INIT_REPAIR_BRIGHT_DC_SCALE="0.78"
    DEFAULT_INIT_REPAIR_BRIGHT_REST_SCALE="0.10"
    DEFAULT_INIT_REPAIR_BRIGHT_FILTER_SCALE="1.20"
    DEFAULT_INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO="0.0010"
    ;;
  *)
    echo "[mip-to-sof-surface-v0] unsupported PREPARE_INPUT_PROFILE=${PREPARE_INPUT_PROFILE}; use default_v0 or early4ksoft_v1" >&2
    exit 1
    ;;
esac

case "${MIP_TO_SOF_PROFILE}" in
  default_v0)
    DEFAULT_RUN_NAME="mip_to_soflr_surface_v0"
    DEFAULT_FINAL_ITERATION="32000"
    DEFAULT_XYZ_LR="2e-5"
    DEFAULT_OPACITY_LR="5e-4"
    DEFAULT_SCALE_LR="1e-4"
    DEFAULT_LAMBDA_RGB_PRESERVE="1.0"
    DEFAULT_LAMBDA_DEPTH="0.25"
    DEFAULT_LAMBDA_NORMAL="0.03"
    DEFAULT_LAMBDA_ALPHA="0.05"
    DEFAULT_LAMBDA_MIP_CLOSURE_ALPHA="0.10"
    DEFAULT_LAMBDA_MIP_CLOSURE_PREMUL="0.15"
    DEFAULT_LAMBDA_MIP_CLOSURE_DEPTH="0.05"
    DEFAULT_LAMBDA_MIP_OBS_CLOSURE_ALPHA="0.0"
    DEFAULT_LAMBDA_MIP_OBS_CLOSURE_PREMUL="0.0"
    DEFAULT_LAMBDA_MIP_OBS_CLOSURE_DEPTH="0.0"
    DEFAULT_LAMBDA_OPACITY_ANCHOR="0.04"
    DEFAULT_LAMBDA_SCALE_ANCHOR="0.14"
    DEFAULT_LAMBDA_ANCHOR="50.0"
    DEFAULT_MAX_DISPLACEMENT_RATIO="0.002"
    DEFAULT_SR_PRIOR_L1_WEIGHT="0.05"
    DEFAULT_SR_PRIOR_HF_WEIGHT="0.30"
    DEFAULT_SR_PRIOR_WARMUP_START_ITER="0"
    DEFAULT_SR_PRIOR_WARMUP_END_ITER="0"
    DEFAULT_SR_PRIOR_START_SCALE="1.0"
    DEFAULT_SR_PRIOR_END_SCALE="1.0"
    DEFAULT_SR_PRIOR_UPDATE_SCALE="1.0"
    DEFAULT_SR_PRIOR_CONSISTENCY_THRESHOLD="0.12"
    DEFAULT_SR_PRIOR_MIN_VALID_RATIO="0.50"
    DEFAULT_SR_PRIOR_DELTA_CLIP="0.15"
    DEFAULT_DEPTH_PRIOR_SURFACE_WEIGHT_BOOST="0.35"
    ;;
  early4ksoft_v1)
    DEFAULT_RUN_NAME="mip_to_soflr_surface_early4ksoft_v1"
    DEFAULT_FINAL_ITERATION="34000"
    DEFAULT_XYZ_LR="8e-6"
    DEFAULT_OPACITY_LR="4e-4"
    DEFAULT_SCALE_LR="1.2e-4"
    DEFAULT_LAMBDA_RGB_PRESERVE="1.0"
    DEFAULT_LAMBDA_DEPTH="0.28"
    DEFAULT_LAMBDA_NORMAL="0.04"
    DEFAULT_LAMBDA_ALPHA="0.05"
    DEFAULT_LAMBDA_MIP_CLOSURE_ALPHA="0.12"
    DEFAULT_LAMBDA_MIP_CLOSURE_PREMUL="0.15"
    DEFAULT_LAMBDA_MIP_CLOSURE_DEPTH="0.06"
    DEFAULT_LAMBDA_MIP_OBS_CLOSURE_ALPHA="0.0"
    DEFAULT_LAMBDA_MIP_OBS_CLOSURE_PREMUL="0.0"
    DEFAULT_LAMBDA_MIP_OBS_CLOSURE_DEPTH="0.0"
    DEFAULT_LAMBDA_OPACITY_ANCHOR="0.06"
    DEFAULT_LAMBDA_SCALE_ANCHOR="0.18"
    DEFAULT_LAMBDA_ANCHOR="60.0"
    DEFAULT_MAX_DISPLACEMENT_RATIO="0.0012"
    DEFAULT_SR_PRIOR_L1_WEIGHT="0.05"
    DEFAULT_SR_PRIOR_HF_WEIGHT="0.30"
    DEFAULT_SR_PRIOR_WARMUP_START_ITER="0"
    DEFAULT_SR_PRIOR_WARMUP_END_ITER="2000"
    DEFAULT_SR_PRIOR_START_SCALE="0.4"
    DEFAULT_SR_PRIOR_END_SCALE="0.7"
    DEFAULT_SR_PRIOR_UPDATE_SCALE="1.0"
    DEFAULT_SR_PRIOR_CONSISTENCY_THRESHOLD="0.08"
    DEFAULT_SR_PRIOR_MIN_VALID_RATIO="0.50"
    DEFAULT_SR_PRIOR_DELTA_CLIP="0.10"
    DEFAULT_DEPTH_PRIOR_SURFACE_WEIGHT_BOOST="0.30"
    ;;
  *)
    echo "[mip-to-sof-surface-v0] unsupported MIP_TO_SOF_PROFILE=${MIP_TO_SOF_PROFILE}; use default_v0 or early4ksoft_v1" >&2
    exit 1
    ;;
esac

MIP_MODEL_PATH="${MIP_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}}"
MIP_INPUT_MODEL_PATH="${MIP_INPUT_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${DEFAULT_MIP_INPUT_MODEL_NAME}}"
BASELINE_ITERATION="${BASELINE_ITERATION:-30000}"
FINAL_ITERATION="${FINAL_ITERATION:-${DEFAULT_FINAL_ITERATION}}"
MIP_ITERATION="${MIP_ITERATION:-${BASELINE_ITERATION}}"
PREPARE_INPUT_IF_MISSING="${PREPARE_INPUT_IF_MISSING:-1}"
DEBUG_DUMP_PREPARE_STAGES="${DEBUG_DUMP_PREPARE_STAGES:-0}"
DEBUG_DUMP_CANONICALIZE_SUBSTAGES="${DEBUG_DUMP_CANONICALIZE_SUBSTAGES:-0}"
SCALE_CLAMP_MODE="${SCALE_CLAMP_MODE:-${DEFAULT_SCALE_CLAMP_MODE}}"
OPACITY_COMPENSATE_SCALE_SHRINK="${OPACITY_COMPENSATE_SCALE_SHRINK:-area}"
OPACITY_COMPENSATION_POWER="${OPACITY_COMPENSATION_POWER:-1.0}"
MIN_OPACITY_COMPENSATION_SCALE="${MIN_OPACITY_COMPENSATION_SCALE:-0.05}"
MAX_COMPENSATED_OPACITY="${MAX_COMPENSATED_OPACITY:-0.95}"
INIT_REPAIR_MODE="${INIT_REPAIR_MODE:-${DEFAULT_INIT_REPAIR_MODE}}"
INIT_REPAIR_MAX_FRACTION="${INIT_REPAIR_MAX_FRACTION:-${DEFAULT_INIT_REPAIR_MAX_FRACTION}}"
INIT_REPAIR_MAX_COUNT="${INIT_REPAIR_MAX_COUNT:-${DEFAULT_INIT_REPAIR_MAX_COUNT}}"
INIT_REPAIR_MIN_OPACITY="${INIT_REPAIR_MIN_OPACITY:-${DEFAULT_INIT_REPAIR_MIN_OPACITY}}"
INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO="${INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO:-${DEFAULT_INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO}}"
INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO="${INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO:-${DEFAULT_INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO}}"
INIT_REPAIR_MIN_FILTER_SCALE_RATIO="${INIT_REPAIR_MIN_FILTER_SCALE_RATIO:-${DEFAULT_INIT_REPAIR_MIN_FILTER_SCALE_RATIO}}"
INIT_REPAIR_MIN_FULL_ANISOTROPY="${INIT_REPAIR_MIN_FULL_ANISOTROPY:-${DEFAULT_INIT_REPAIR_MIN_FULL_ANISOTROPY}}"
INIT_REPAIR_SPLIT_COUNT="${INIT_REPAIR_SPLIT_COUNT:-${DEFAULT_INIT_REPAIR_SPLIT_COUNT}}"
INIT_REPAIR_CHILD_LAYOUT="${INIT_REPAIR_CHILD_LAYOUT:-${DEFAULT_INIT_REPAIR_CHILD_LAYOUT}}"
INIT_REPAIR_CHILD_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_SCALE_MULTIPLIER:-${DEFAULT_INIT_REPAIR_CHILD_SCALE_MULTIPLIER}}"
INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER:-${DEFAULT_INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER}}"
INIT_REPAIR_CHILD_OPACITY_SCALE="${INIT_REPAIR_CHILD_OPACITY_SCALE:-${DEFAULT_INIT_REPAIR_CHILD_OPACITY_SCALE}}"
INIT_REPAIR_ENERGY_CONSERVE_MODE="${INIT_REPAIR_ENERGY_CONSERVE_MODE:-${DEFAULT_INIT_REPAIR_ENERGY_CONSERVE_MODE}}"
INIT_REPAIR_FILTER_SCALE="${INIT_REPAIR_FILTER_SCALE:-${DEFAULT_INIT_REPAIR_FILTER_SCALE}}"
INIT_REPAIR_FILTER_CAP_RATIO="${INIT_REPAIR_FILTER_CAP_RATIO:-${DEFAULT_INIT_REPAIR_FILTER_CAP_RATIO}}"
INIT_REPAIR_OFFSET_SCALE="${INIT_REPAIR_OFFSET_SCALE:-${DEFAULT_INIT_REPAIR_OFFSET_SCALE}}"
INIT_REPAIR_BRIGHT_MAX_FRACTION="${INIT_REPAIR_BRIGHT_MAX_FRACTION:-${DEFAULT_INIT_REPAIR_BRIGHT_MAX_FRACTION}}"
INIT_REPAIR_BRIGHT_MAX_COUNT="${INIT_REPAIR_BRIGHT_MAX_COUNT:-${DEFAULT_INIT_REPAIR_BRIGHT_MAX_COUNT}}"
INIT_REPAIR_BRIGHT_TARGET="${INIT_REPAIR_BRIGHT_TARGET:-${DEFAULT_INIT_REPAIR_BRIGHT_TARGET}}"
INIT_REPAIR_BRIGHT_MIN_OPACITY="${INIT_REPAIR_BRIGHT_MIN_OPACITY:-${DEFAULT_INIT_REPAIR_BRIGHT_MIN_OPACITY}}"
INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO="${INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO:-${DEFAULT_INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO}}"
INIT_REPAIR_BRIGHT_LUMA_QUANTILE="${INIT_REPAIR_BRIGHT_LUMA_QUANTILE:-${DEFAULT_INIT_REPAIR_BRIGHT_LUMA_QUANTILE}}"
INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO="${INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO:-${DEFAULT_INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO}}"
INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA="${INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA:-${DEFAULT_INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA}}"
INIT_REPAIR_BRIGHT_NEIGHBOR_K="${INIT_REPAIR_BRIGHT_NEIGHBOR_K:-${DEFAULT_INIT_REPAIR_BRIGHT_NEIGHBOR_K}}"
INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER="${INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER:-${DEFAULT_INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER}}"
INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER="${INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER:-${DEFAULT_INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER}}"
INIT_REPAIR_BRIGHT_OPACITY_SCALE="${INIT_REPAIR_BRIGHT_OPACITY_SCALE:-${DEFAULT_INIT_REPAIR_BRIGHT_OPACITY_SCALE}}"
INIT_REPAIR_BRIGHT_DC_SCALE="${INIT_REPAIR_BRIGHT_DC_SCALE:-${DEFAULT_INIT_REPAIR_BRIGHT_DC_SCALE}}"
INIT_REPAIR_BRIGHT_REST_SCALE="${INIT_REPAIR_BRIGHT_REST_SCALE:-${DEFAULT_INIT_REPAIR_BRIGHT_REST_SCALE}}"
INIT_REPAIR_BRIGHT_FILTER_SCALE="${INIT_REPAIR_BRIGHT_FILTER_SCALE:-${DEFAULT_INIT_REPAIR_BRIGHT_FILTER_SCALE}}"
INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO="${INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO:-${DEFAULT_INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO}}"

SOF_SURFACE_MODEL="${SOF_SURFACE_MODEL:-${SCENE_ASSET_ROOT}/${SCENE_NAME}_sof_vanilla_images8_v1/soflr30k}"
SOF_SURFACE_ITERATION="${SOF_SURFACE_ITERATION:-${BASELINE_ITERATION}}"

RUN_NAME="${RUN_NAME:-${DEFAULT_RUN_NAME}}"
RUN_ROOT="${RUN_ROOT:-${SOF_ROOT}/output/mip_to_sof_surface_v0/${SCENE_NAME}/${RUN_NAME}}"
OUTPUT_MODEL="${OUTPUT_MODEL:-${RUN_ROOT}/pulled_mip_model}"
BASE_RENDER_DIR="${BASE_RENDER_DIR:-${RUN_ROOT}/base_mip_renders_no_gt}"
PULLED_RENDER_DIR="${PULLED_RENDER_DIR:-${RUN_ROOT}/pulled_mip_renders_no_gt}"
RENDER_COMPARE_DIR="${RENDER_COMPARE_DIR:-${RUN_ROOT}/render_diff_vs_base}"

SURFACE_IMAGES_SUBDIR="${SURFACE_IMAGES_SUBDIR:-images_8}"
RENDER_IMAGES_SUBDIR="${RENDER_IMAGES_SUBDIR:-images_2}"
OUTPUT_ITERATION="${OUTPUT_ITERATION:-${FINAL_ITERATION}}"
MAX_VIEWS="${MAX_VIEWS:-16}"
if [[ -z "${ITERATIONS:-}" ]]; then
  ITERATIONS=$((FINAL_ITERATION - BASELINE_ITERATION))
fi
if (( ITERATIONS <= 0 )); then
  echo "[mip-to-sof-surface-v0] ITERATIONS must be positive; got ${ITERATIONS} from baseline=${BASELINE_ITERATION} final=${FINAL_ITERATION}" >&2
  exit 1
fi
XYZ_LR="${XYZ_LR:-${DEFAULT_XYZ_LR}}"
OPACITY_LR="${OPACITY_LR:-${DEFAULT_OPACITY_LR}}"
SCALE_LR="${SCALE_LR:-${DEFAULT_SCALE_LR}}"
LAMBDA_RGB_PRESERVE="${LAMBDA_RGB_PRESERVE:-${DEFAULT_LAMBDA_RGB_PRESERVE}}"
LAMBDA_DEPTH="${LAMBDA_DEPTH:-${DEFAULT_LAMBDA_DEPTH}}"
LAMBDA_NORMAL="${LAMBDA_NORMAL:-${DEFAULT_LAMBDA_NORMAL}}"
LAMBDA_ALPHA="${LAMBDA_ALPHA:-${DEFAULT_LAMBDA_ALPHA}}"
LAMBDA_MIP_CLOSURE_ALPHA="${LAMBDA_MIP_CLOSURE_ALPHA:-${DEFAULT_LAMBDA_MIP_CLOSURE_ALPHA}}"
LAMBDA_MIP_CLOSURE_PREMUL="${LAMBDA_MIP_CLOSURE_PREMUL:-${DEFAULT_LAMBDA_MIP_CLOSURE_PREMUL}}"
LAMBDA_MIP_CLOSURE_DEPTH="${LAMBDA_MIP_CLOSURE_DEPTH:-${DEFAULT_LAMBDA_MIP_CLOSURE_DEPTH}}"
LAMBDA_MIP_OBS_CLOSURE_ALPHA="${LAMBDA_MIP_OBS_CLOSURE_ALPHA:-${DEFAULT_LAMBDA_MIP_OBS_CLOSURE_ALPHA}}"
LAMBDA_MIP_OBS_CLOSURE_PREMUL="${LAMBDA_MIP_OBS_CLOSURE_PREMUL:-${DEFAULT_LAMBDA_MIP_OBS_CLOSURE_PREMUL}}"
LAMBDA_MIP_OBS_CLOSURE_DEPTH="${LAMBDA_MIP_OBS_CLOSURE_DEPTH:-${DEFAULT_LAMBDA_MIP_OBS_CLOSURE_DEPTH}}"
LAMBDA_OPACITY_ANCHOR="${LAMBDA_OPACITY_ANCHOR:-${DEFAULT_LAMBDA_OPACITY_ANCHOR}}"
LAMBDA_SCALE_ANCHOR="${LAMBDA_SCALE_ANCHOR:-${DEFAULT_LAMBDA_SCALE_ANCHOR}}"
LAMBDA_ANCHOR="${LAMBDA_ANCHOR:-${DEFAULT_LAMBDA_ANCHOR}}"
MIN_SURFACE_ALPHA="${MIN_SURFACE_ALPHA:-0.08}"
MIN_LOSS_PIXELS="${MIN_LOSS_PIXELS:-256}"
MIP_CLOSURE_KERNEL="${MIP_CLOSURE_KERNEL:-25}"
MIP_CLOSURE_ALPHA_THRESHOLD="${MIP_CLOSURE_ALPHA_THRESHOLD:-0.05}"
MIP_OBS_CLOSURE_IMAGES_SUBDIR="${MIP_OBS_CLOSURE_IMAGES_SUBDIR:-${RENDER_IMAGES_SUBDIR}}"
MIP_OBS_CLOSURE_SPLIT="${MIP_OBS_CLOSURE_SPLIT:-${RENDER_SPLIT:-test}}"
MIP_OBS_CLOSURE_MAX_VIEWS="${MIP_OBS_CLOSURE_MAX_VIEWS:-${MAX_VIEWS}}"
FILTER_IMAGES_SUBDIR="${FILTER_IMAGES_SUBDIR:-${RENDER_IMAGES_SUBDIR}}"
FILTER_SPLIT="${FILTER_SPLIT:-train}"
FILTER_MAX_VIEWS="${FILTER_MAX_VIEWS:-0}"
MIP_CLOSURE_REFERENCE_LOWPASS="${MIP_CLOSURE_REFERENCE_LOWPASS:-1}"
MAX_DISPLACEMENT_RATIO="${MAX_DISPLACEMENT_RATIO:-${DEFAULT_MAX_DISPLACEMENT_RATIO}}"
MAX_DISPLACEMENT_ABS="${MAX_DISPLACEMENT_ABS:-0.0}"
DEPTH_RELATIVE_MIN="${DEPTH_RELATIVE_MIN:-0.5}"
ENABLE_OPACITY_UPDATE="${ENABLE_OPACITY_UPDATE:-1}"
ENABLE_SCALE_UPDATE="${ENABLE_SCALE_UPDATE:-1}"
OPTIMIZE_GAUSSIAN_MASK_PAYLOAD="${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD:-}"
OPTIMIZE_GAUSSIAN_MASK_KEY="${OPTIMIZE_GAUSSIAN_MASK_KEY:-selected_mask}"
GAUSSIAN_UPDATE_SCALE="${GAUSSIAN_UPDATE_SCALE:-1.0}"
GAUSSIAN_SCALE_AXIS_MODE="${GAUSSIAN_SCALE_AXIS_MODE:-all}"
GAUSSIAN_SCALE_MIN_MULTIPLIER="${GAUSSIAN_SCALE_MIN_MULTIPLIER:-0.0}"
GAUSSIAN_SCALE_MAX_MULTIPLIER="${GAUSSIAN_SCALE_MAX_MULTIPLIER:-0.0}"

MIPSPLATTING_ROOT="${MIPSPLATTING_ROOT:-${DEFAULT_MIPSPLATTING_ROOT}}"
SR_PRIOR_DIR="${SR_PRIOR_DIR-/root/autodl-tmp/kitchen/priors}"
# Reference images are only used to gate/fuse SR priors. Keep this GT-free by
# defaulting to the LR/input views; the preparation tool upsamples them to the
# SR prior resolution before computing discrepancy masks.
SR_REFERENCE_IMAGES_SUBDIR="${SR_REFERENCE_IMAGES_SUBDIR:-${SURFACE_IMAGES_SUBDIR}}"
SR_REFERENCE_DIR="${SR_REFERENCE_DIR:-${SCENE_ROOT}/${SR_REFERENCE_IMAGES_SUBDIR}}"
SR_PRIOR_SUBDIR="${SR_PRIOR_SUBDIR:-fused_priors}"
SR_PRIOR_MASK_SUBDIR="${SR_PRIOR_MASK_SUBDIR:-usable_masks}"
SR_ANCHOR_SUBDIR="${SR_ANCHOR_SUBDIR:-aligned_references}"
SR_IMAGES_SUBDIR="${SR_IMAGES_SUBDIR:-images_2}"
SR_MAX_VIEWS="${SR_MAX_VIEWS:-${MAX_VIEWS}}"
FORCE_PREPARE_SR_PRIORS="${FORCE_PREPARE_SR_PRIORS:-0}"
SR_MASK_THRESHOLD="${SR_MASK_THRESHOLD:-0.12}"
SR_MASK_MODE="${SR_MASK_MODE:-soft}"
SR_DISCREPANCY_FLOOR="${SR_DISCREPANCY_FLOOR:-0.05}"
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT:-${DEFAULT_SR_PRIOR_L1_WEIGHT}}"
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT:-${DEFAULT_SR_PRIOR_HF_WEIGHT}}"
SR_PRIOR_WARMUP_START_ITER="${SR_PRIOR_WARMUP_START_ITER:-${DEFAULT_SR_PRIOR_WARMUP_START_ITER}}"
SR_PRIOR_WARMUP_END_ITER="${SR_PRIOR_WARMUP_END_ITER:-${DEFAULT_SR_PRIOR_WARMUP_END_ITER}}"
SR_PRIOR_START_SCALE="${SR_PRIOR_START_SCALE:-${DEFAULT_SR_PRIOR_START_SCALE}}"
SR_PRIOR_END_SCALE="${SR_PRIOR_END_SCALE:-${DEFAULT_SR_PRIOR_END_SCALE}}"
SR_PRIOR_UPDATE_SCALE="${SR_PRIOR_UPDATE_SCALE:-${DEFAULT_SR_PRIOR_UPDATE_SCALE}}"
SR_PRIOR_SCHEDULE_MODE="${SR_PRIOR_SCHEDULE_MODE:-smoothstep}"
SR_PRIOR_MASK_FLOOR="${SR_PRIOR_MASK_FLOOR:-0.0}"
SR_PRIOR_CONSISTENCY_THRESHOLD="${SR_PRIOR_CONSISTENCY_THRESHOLD:-${DEFAULT_SR_PRIOR_CONSISTENCY_THRESHOLD}}"
SR_PRIOR_MIN_VALID_RATIO="${SR_PRIOR_MIN_VALID_RATIO:-${DEFAULT_SR_PRIOR_MIN_VALID_RATIO}}"
SR_PRIOR_MIN_PIXELS="${SR_PRIOR_MIN_PIXELS:-64}"
SR_PRIOR_DELTA_CLIP="${SR_PRIOR_DELTA_CLIP:-${DEFAULT_SR_PRIOR_DELTA_CLIP}}"
DISABLE_SR_PRIOR_HF_RESIDUAL="${DISABLE_SR_PRIOR_HF_RESIDUAL:-0}"
PREPARED_SR_PRIOR_ROOT="${PREPARED_SR_PRIOR_ROOT:-${SCENE_ASSET_ROOT}/prepared_sr_priors/sof_surface_v0_${SR_REFERENCE_IMAGES_SUBDIR}_to_${SR_IMAGES_SUBDIR}_mask${SR_MASK_THRESHOLD}_${SR_MASK_MODE}}"

DEPTH_PRIOR_ROOT="${DEPTH_PRIOR_ROOT:-}"
DEPTH_PRIOR_SUBDIRS="${DEPTH_PRIOR_SUBDIRS:-depth,}"
DEPTH_PRIOR_CONFIDENCE_SUBDIRS="${DEPTH_PRIOR_CONFIDENCE_SUBDIRS:-auto}"
LAMBDA_DEPTH_PRIOR="${LAMBDA_DEPTH_PRIOR:-0.05}"
LAMBDA_DEPTH_PRIOR_NORMAL="${LAMBDA_DEPTH_PRIOR_NORMAL:-0.0}"
LAMBDA_DEPTH_PRIOR_DISTORTION="${LAMBDA_DEPTH_PRIOR_DISTORTION:-100.0}"
LAMBDA_DEPTH_PRIOR_SELF_NORMAL="${LAMBDA_DEPTH_PRIOR_SELF_NORMAL:-0.05}"
DEPTH_PRIOR_CONFIDENCE_MIN="${DEPTH_PRIOR_CONFIDENCE_MIN:-0.05}"
DEPTH_PRIOR_AGREEMENT_THRESHOLD="${DEPTH_PRIOR_AGREEMENT_THRESHOLD:-0.15}"
DEPTH_PRIOR_AGREEMENT_FLOOR="${DEPTH_PRIOR_AGREEMENT_FLOOR:-0.15}"
DEPTH_PRIOR_ALIGN_MODE="${DEPTH_PRIOR_ALIGN_MODE:-affine_robust}"
DEPTH_PRIOR_ALIGN_MIN_PIXELS="${DEPTH_PRIOR_ALIGN_MIN_PIXELS:-2048}"
DEPTH_PRIOR_SURFACE_WEIGHT_BOOST="${DEPTH_PRIOR_SURFACE_WEIGHT_BOOST:-${DEFAULT_DEPTH_PRIOR_SURFACE_WEIGHT_BOOST}}"
DEPTH_PRIOR_WARMUP_START_ITER="${DEPTH_PRIOR_WARMUP_START_ITER:-0}"
DEPTH_PRIOR_WARMUP_END_ITER="${DEPTH_PRIOR_WARMUP_END_ITER:-1200}"
DEPTH_PRIOR_START_SCALE="${DEPTH_PRIOR_START_SCALE:-1.0}"
DEPTH_PRIOR_END_SCALE="${DEPTH_PRIOR_END_SCALE:-1.6}"
DEPTH_PRIOR_UPDATE_SCALE="${DEPTH_PRIOR_UPDATE_SCALE:-1.0}"
DEPTH_PRIOR_SCHEDULE_MODE="${DEPTH_PRIOR_SCHEDULE_MODE:-smoothstep}"
DEPTH_PRIOR_WEIGHT_GAIN="${DEPTH_PRIOR_WEIGHT_GAIN:-1.25}"
DEPTH_PRIOR_WEIGHT_POWER="${DEPTH_PRIOR_WEIGHT_POWER:-0.85}"
DEPTH_PRIOR_WEIGHT_MIN="${DEPTH_PRIOR_WEIGHT_MIN:-0.0}"
GRADIENT_GUARD_MODE="${GRADIENT_GUARD_MODE:-none}"
GRADIENT_GUARD_START_ITER="${GRADIENT_GUARD_START_ITER:-150}"
GRADIENT_GUARD_XYZ_THRESHOLD="${GRADIENT_GUARD_XYZ_THRESHOLD:-0.02}"
GRADIENT_GUARD_OPACITY_THRESHOLD="${GRADIENT_GUARD_OPACITY_THRESHOLD:-0.02}"
GRADIENT_GUARD_SCALE_THRESHOLD="${GRADIENT_GUARD_SCALE_THRESHOLD:-0.05}"
GRADIENT_GUARD_MAX_FRACTION="${GRADIENT_GUARD_MAX_FRACTION:-0.002}"
GRADIENT_GUARD_MAX_POINTS="${GRADIENT_GUARD_MAX_POINTS:-64}"
GRADIENT_GUARD_ONLY_UPDATE_MASK="${GRADIENT_GUARD_ONLY_UPDATE_MASK:-1}"
DEPTH_FEEDBACK_MODE="${DEPTH_FEEDBACK_MODE:-none}"
DEPTH_FEEDBACK_START_ITER="${DEPTH_FEEDBACK_START_ITER:-300}"
DEPTH_FEEDBACK_INTERVAL="${DEPTH_FEEDBACK_INTERVAL:-200}"
DEPTH_FEEDBACK_MIN_VISIBLE="${DEPTH_FEEDBACK_MIN_VISIBLE:-4}"
DEPTH_FEEDBACK_MIN_SCORE="${DEPTH_FEEDBACK_MIN_SCORE:-0.0}"
DEPTH_FEEDBACK_TOP_FRACTION="${DEPTH_FEEDBACK_TOP_FRACTION:-0.001}"
DEPTH_FEEDBACK_TOP_POINTS="${DEPTH_FEEDBACK_TOP_POINTS:-48}"
DEPTH_FEEDBACK_DROPOUT_ITERS="${DEPTH_FEEDBACK_DROPOUT_ITERS:-250}"
DEPTH_FEEDBACK_ONLY_UPDATE_MASK="${DEPTH_FEEDBACK_ONLY_UPDATE_MASK:-1}"

RUN_RENDER="${RUN_RENDER:-1}"
RUN_BASE_RENDER="${RUN_BASE_RENDER:-1}"
RUN_RENDER_COMPARE="${RUN_RENDER_COMPARE:-1}"
RENDER_SPLIT="${RENDER_SPLIT:-test}"
PYTHON_BIN="${PYTHON_BIN:-python}"

resolve_prepared_input_iteration() {
  local model_root="$1"
  local requested_iter="$2"
  local requested_ply="${model_root}/point_cloud/iteration_${requested_iter}/point_cloud.ply"
  if [[ -e "${requested_ply}" ]]; then
    printf '%s\n' "${requested_iter}"
    return 0
  fi

  local summary_path="${model_root}/mip_input_field_summary.json"
  if [[ -f "${summary_path}" ]]; then
    local summary_iter
    summary_iter="$("${PYTHON_BIN}" - "${summary_path}" <<'PY'
import json
import sys

summary_path = sys.argv[1]
with open(summary_path, "r", encoding="utf-8") as f:
    data = json.load(f)
value = data.get("output_iteration", None)
if value is None:
    raise SystemExit(1)
print(int(value))
PY
)" || summary_iter=""
    if [[ -n "${summary_iter}" && -e "${model_root}/point_cloud/iteration_${summary_iter}/point_cloud.ply" ]]; then
      printf '%s\n' "${summary_iter}"
      return 0
    fi
  fi

  local latest_iter
  latest_iter="$("${PYTHON_BIN}" - "${model_root}" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1]) / "point_cloud"
iters = []
if root.is_dir():
    for child in root.iterdir():
        if child.is_dir() and child.name.startswith("iteration_"):
            try:
                iters.append(int(child.name.split("_")[-1]))
            except ValueError:
                pass
if not iters:
    raise SystemExit(1)
print(max(iters))
PY
)" || latest_iter=""
  if [[ -n "${latest_iter}" && -e "${model_root}/point_cloud/iteration_${latest_iter}/point_cloud.ply" ]]; then
    printf '%s\n' "${latest_iter}"
    return 0
  fi
  return 1
}

if [[ "${PREPARE_INPUT_IF_MISSING}" == "1" && ! -e "${MIP_INPUT_MODEL_PATH}/point_cloud/iteration_${MIP_ITERATION}/point_cloud.ply" ]]; then
  echo "[mip-to-sof-surface-v0] preparing SOF-native mip input field ..."
  SCENE_NAME="${SCENE_NAME}" \
  SCENE_ROOT="${SCENE_ROOT}" \
  SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
  MIP_MODEL_PATH="${MIP_MODEL_PATH}" \
  OUTPUT_MODEL_PATH="${MIP_INPUT_MODEL_PATH}" \
  MIP_ITERATION="${MIP_ITERATION}" \
  SCALE_CLAMP_MODE="${SCALE_CLAMP_MODE}" \
  OPACITY_COMPENSATE_SCALE_SHRINK="${OPACITY_COMPENSATE_SCALE_SHRINK}" \
  OPACITY_COMPENSATION_POWER="${OPACITY_COMPENSATION_POWER}" \
  MIN_OPACITY_COMPENSATION_SCALE="${MIN_OPACITY_COMPENSATION_SCALE}" \
  MAX_COMPENSATED_OPACITY="${MAX_COMPENSATED_OPACITY}" \
  INIT_REPAIR_MODE="${INIT_REPAIR_MODE}" \
  INIT_REPAIR_MAX_FRACTION="${INIT_REPAIR_MAX_FRACTION}" \
  INIT_REPAIR_MAX_COUNT="${INIT_REPAIR_MAX_COUNT}" \
  INIT_REPAIR_MIN_OPACITY="${INIT_REPAIR_MIN_OPACITY}" \
  INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO="${INIT_REPAIR_MIN_EFFECTIVE_SCALE_RATIO}" \
  INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO="${INIT_REPAIR_MIN_VOLUME_RADIUS_RATIO}" \
  INIT_REPAIR_MIN_FILTER_SCALE_RATIO="${INIT_REPAIR_MIN_FILTER_SCALE_RATIO}" \
  INIT_REPAIR_MIN_FULL_ANISOTROPY="${INIT_REPAIR_MIN_FULL_ANISOTROPY}" \
  INIT_REPAIR_SPLIT_COUNT="${INIT_REPAIR_SPLIT_COUNT}" \
  INIT_REPAIR_CHILD_LAYOUT="${INIT_REPAIR_CHILD_LAYOUT}" \
  INIT_REPAIR_CHILD_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_SCALE_MULTIPLIER}" \
  INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER="${INIT_REPAIR_CHILD_MAJOR_SCALE_MULTIPLIER}" \
  INIT_REPAIR_CHILD_OPACITY_SCALE="${INIT_REPAIR_CHILD_OPACITY_SCALE}" \
  INIT_REPAIR_ENERGY_CONSERVE_MODE="${INIT_REPAIR_ENERGY_CONSERVE_MODE}" \
  INIT_REPAIR_FILTER_SCALE="${INIT_REPAIR_FILTER_SCALE}" \
  INIT_REPAIR_FILTER_CAP_RATIO="${INIT_REPAIR_FILTER_CAP_RATIO}" \
  INIT_REPAIR_OFFSET_SCALE="${INIT_REPAIR_OFFSET_SCALE}" \
  INIT_REPAIR_BRIGHT_MAX_FRACTION="${INIT_REPAIR_BRIGHT_MAX_FRACTION}" \
  INIT_REPAIR_BRIGHT_MAX_COUNT="${INIT_REPAIR_BRIGHT_MAX_COUNT}" \
  INIT_REPAIR_BRIGHT_TARGET="${INIT_REPAIR_BRIGHT_TARGET}" \
  INIT_REPAIR_BRIGHT_MIN_OPACITY="${INIT_REPAIR_BRIGHT_MIN_OPACITY}" \
  INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO="${INIT_REPAIR_BRIGHT_MAX_EFFECTIVE_SCALE_RATIO}" \
  INIT_REPAIR_BRIGHT_LUMA_QUANTILE="${INIT_REPAIR_BRIGHT_LUMA_QUANTILE}" \
  INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO="${INIT_REPAIR_BRIGHT_MIN_LOCAL_LUMA_RATIO}" \
  INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA="${INIT_REPAIR_BRIGHT_MIN_COLOR_DELTA}" \
  INIT_REPAIR_BRIGHT_NEIGHBOR_K="${INIT_REPAIR_BRIGHT_NEIGHBOR_K}" \
  INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER="${INIT_REPAIR_BRIGHT_EXPAND_SCALE_MULTIPLIER}" \
  INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER="${INIT_REPAIR_BRIGHT_SMALLEST_AXIS_SCALE_MULTIPLIER}" \
  INIT_REPAIR_BRIGHT_OPACITY_SCALE="${INIT_REPAIR_BRIGHT_OPACITY_SCALE}" \
  INIT_REPAIR_BRIGHT_DC_SCALE="${INIT_REPAIR_BRIGHT_DC_SCALE}" \
  INIT_REPAIR_BRIGHT_REST_SCALE="${INIT_REPAIR_BRIGHT_REST_SCALE}" \
  INIT_REPAIR_BRIGHT_FILTER_SCALE="${INIT_REPAIR_BRIGHT_FILTER_SCALE}" \
  INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO="${INIT_REPAIR_BRIGHT_FILTER_CAP_RATIO}" \
  DEBUG_DUMP_PREPARE_STAGES="${DEBUG_DUMP_PREPARE_STAGES}" \
  DEBUG_DUMP_CANONICALIZE_SUBSTAGES="${DEBUG_DUMP_CANONICALIZE_SUBSTAGES}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  bash "${SOF_ROOT}/scripts/run_prepare_hrgs_mip_input_scene.sh"
fi

if [[ ! -e "${MIP_INPUT_MODEL_PATH}/point_cloud/iteration_${MIP_ITERATION}/point_cloud.ply" ]]; then
  RESOLVED_PREPARED_MIP_ITERATION="$(resolve_prepared_input_iteration "${MIP_INPUT_MODEL_PATH}" "${MIP_ITERATION}" || true)"
  if [[ -n "${RESOLVED_PREPARED_MIP_ITERATION}" && "${RESOLVED_PREPARED_MIP_ITERATION}" != "${MIP_ITERATION}" ]]; then
    echo "[mip-to-sof-surface-v0] resolved prepared input iteration ${MIP_ITERATION} -> ${RESOLVED_PREPARED_MIP_ITERATION}"
    MIP_ITERATION="${RESOLVED_PREPARED_MIP_ITERATION}"
  fi
fi

if [[ ! -e "${MIP_INPUT_MODEL_PATH}/point_cloud/iteration_${MIP_ITERATION}/point_cloud.ply" ]]; then
  echo "[mip-to-sof-surface-v0] missing SOF-native mip input: ${MIP_INPUT_MODEL_PATH}" >&2
  exit 1
fi

if [[ ! -e "${SOF_SURFACE_MODEL}/point_cloud/iteration_${SOF_SURFACE_ITERATION}/point_cloud.ply" ]]; then
  echo "[mip-to-sof-surface-v0] missing SOF surface teacher: ${SOF_SURFACE_MODEL}" >&2
  exit 1
fi

if [[ -n "${SR_PRIOR_DIR}" && ! -d "${SR_PRIOR_DIR}" ]]; then
  echo "[mip-to-sof-surface-v0] missing raw SR prior dir: ${SR_PRIOR_DIR}" >&2
  exit 1
fi

if [[ -n "${SR_PRIOR_DIR}" && ! -d "${SR_REFERENCE_DIR}" ]]; then
  echo "[mip-to-sof-surface-v0] missing SR reference image dir: ${SR_REFERENCE_DIR}" >&2
  exit 1
fi

echo "[mip-to-sof-surface-v0] scene root      : ${SCENE_ROOT}"
echo "[mip-to-sof-surface-v0] mip raw         : ${MIP_MODEL_PATH}"
echo "[mip-to-sof-surface-v0] profiles        : train=${MIP_TO_SOF_PROFILE} prepare=${PREPARE_INPUT_PROFILE}"
echo "[mip-to-sof-surface-v0] mip input       : ${MIP_INPUT_MODEL_PATH}"
echo "[mip-to-sof-surface-v0] SOF teacher     : ${SOF_SURFACE_MODEL}"
echo "[mip-to-sof-surface-v0] output model    : ${OUTPUT_MODEL}"
echo "[mip-to-sof-surface-v0] scale clamp     : ${SCALE_CLAMP_MODE}"
echo "[mip-to-sof-surface-v0] opacity comp    : ${OPACITY_COMPENSATE_SCALE_SHRINK} power=${OPACITY_COMPENSATION_POWER}"
echo "[mip-to-sof-surface-v0] init repair     : ${INIT_REPAIR_MODE} split=${INIT_REPAIR_SPLIT_COUNT} bright_target=${INIT_REPAIR_BRIGHT_TARGET}"
echo "[mip-to-sof-surface-v0] surface views   : ${SURFACE_IMAGES_SUBDIR} max=${MAX_VIEWS}"
echo "[mip-to-sof-surface-v0] train           : baseline=${BASELINE_ITERATION} final=${FINAL_ITERATION} steps=${ITERATIONS} xyz_lr=${XYZ_LR} max_disp_ratio=${MAX_DISPLACEMENT_RATIO}"
echo "[mip-to-sof-surface-v0] train params    : opacity=${ENABLE_OPACITY_UPDATE} scale=${ENABLE_SCALE_UPDATE} lrs=${OPACITY_LR}/${SCALE_LR}"
if [[ -n "${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD}" ]]; then
  echo "[mip-to-sof-surface-v0] gaussian mask   : payload=${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD} key=${OPTIMIZE_GAUSSIAN_MASK_KEY} scale=${GAUSSIAN_UPDATE_SCALE} axis=${GAUSSIAN_SCALE_AXIS_MODE} range=[${GAUSSIAN_SCALE_MIN_MULTIPLIER},${GAUSSIAN_SCALE_MAX_MULTIPLIER}]"
fi
echo "[mip-to-sof-surface-v0] filter3D        : images=${FILTER_IMAGES_SUBDIR:-<train-domain>} split=${FILTER_SPLIT} max=${FILTER_MAX_VIEWS}"
echo "[mip-to-sof-surface-v0] losses          : rgb=${LAMBDA_RGB_PRESERVE} depth=${LAMBDA_DEPTH} normal=${LAMBDA_NORMAL} alpha=${LAMBDA_ALPHA} anchor=${LAMBDA_ANCHOR}"
echo "[mip-to-sof-surface-v0] mip closure     : alpha=${LAMBDA_MIP_CLOSURE_ALPHA} premul=${LAMBDA_MIP_CLOSURE_PREMUL} depth=${LAMBDA_MIP_CLOSURE_DEPTH} kernel=${MIP_CLOSURE_KERNEL} alpha>${MIP_CLOSURE_ALPHA_THRESHOLD} ref_lowpass=${MIP_CLOSURE_REFERENCE_LOWPASS}"
echo "[mip-to-sof-surface-v0] obs closure     : images=${MIP_OBS_CLOSURE_IMAGES_SUBDIR} split=${MIP_OBS_CLOSURE_SPLIT} max=${MIP_OBS_CLOSURE_MAX_VIEWS} alpha=${LAMBDA_MIP_OBS_CLOSURE_ALPHA} premul=${LAMBDA_MIP_OBS_CLOSURE_PREMUL} depth=${LAMBDA_MIP_OBS_CLOSURE_DEPTH}"
echo "[mip-to-sof-surface-v0] mass anchors    : opacity=${LAMBDA_OPACITY_ANCHOR} scale=${LAMBDA_SCALE_ANCHOR}"

PRIOR_ARGS=()
if [[ -n "${SR_PRIOR_DIR}" ]]; then
  if [[ "${FORCE_PREPARE_SR_PRIORS}" == "1" || ! -f "${PREPARED_SR_PRIOR_ROOT}/manifest.json" || ! -d "${PREPARED_SR_PRIOR_ROOT}/${SR_PRIOR_SUBDIR}" || ! -d "${PREPARED_SR_PRIOR_ROOT}/${SR_PRIOR_MASK_SUBDIR}" || ! -d "${PREPARED_SR_PRIOR_ROOT}/${SR_ANCHOR_SUBDIR}" ]]; then
    if [[ ! -d "${MIPSPLATTING_ROOT}" ]]; then
      echo "[mip-to-sof-surface-v0] missing mip-splatting root for SR prior preparation: ${MIPSPLATTING_ROOT}" >&2
      exit 1
    fi
    echo "[mip-to-sof-surface-v0] prepare SR priors : raw=${SR_PRIOR_DIR} ref=${SR_REFERENCE_DIR}"
    (
      cd "${MIPSPLATTING_ROOT}"
      "${PYTHON_BIN}" -m hybrid_sdfgs.tools.prepare_existing_sr_priors \
        --prior_dir "${SR_PRIOR_DIR}" \
        --reference_dir "${SR_REFERENCE_DIR}" \
        --output_root "${PREPARED_SR_PRIOR_ROOT}" \
        --mask_threshold "${SR_MASK_THRESHOLD}" \
        --mask_mode "${SR_MASK_MODE}" \
        --discrepancy_floor "${SR_DISCREPANCY_FLOOR}" \
        --copy_raw_priors \
        --save_fused_priors
    )
  else
    echo "[mip-to-sof-surface-v0] reuse prepared SR priors: ${PREPARED_SR_PRIOR_ROOT}"
  fi

  if [[ ! -d "${PREPARED_SR_PRIOR_ROOT}/${SR_PRIOR_SUBDIR}" ]]; then
    echo "[mip-to-sof-surface-v0] missing prepared SR fused prior dir after prepare: ${PREPARED_SR_PRIOR_ROOT}/${SR_PRIOR_SUBDIR}" >&2
    exit 1
  fi

  if [[ ! -d "${PREPARED_SR_PRIOR_ROOT}/${SR_PRIOR_MASK_SUBDIR}" ]]; then
    echo "[mip-to-sof-surface-v0] missing prepared SR usable mask dir after prepare: ${PREPARED_SR_PRIOR_ROOT}/${SR_PRIOR_MASK_SUBDIR}" >&2
    exit 1
  fi

  if [[ ! -d "${PREPARED_SR_PRIOR_ROOT}/${SR_ANCHOR_SUBDIR}" ]]; then
    echo "[mip-to-sof-surface-v0] missing prepared SR GT-free anchor dir after prepare: ${PREPARED_SR_PRIOR_ROOT}/${SR_ANCHOR_SUBDIR}" >&2
    exit 1
  fi

  echo "[mip-to-sof-surface-v0] SR raw prior    : ${SR_PRIOR_DIR}"
  echo "[mip-to-sof-surface-v0] SR reference    : ${SR_REFERENCE_DIR} (LR gate, not GT)"
  echo "[mip-to-sof-surface-v0] SR prior        : ${PREPARED_SR_PRIOR_ROOT} subdir=${SR_PRIOR_SUBDIR} mask=${SR_PRIOR_MASK_SUBDIR} anchor=${SR_ANCHOR_SUBDIR}"
  echo "[mip-to-sof-surface-v0] SR loss         : l1=${SR_PRIOR_L1_WEIGHT} hf=${SR_PRIOR_HF_WEIGHT} images=${SR_IMAGES_SUBDIR} max=${SR_MAX_VIEWS}"
  echo "[mip-to-sof-surface-v0] SR schedule     : ${SR_PRIOR_START_SCALE}->${SR_PRIOR_END_SCALE} update=${SR_PRIOR_UPDATE_SCALE} iter=${SR_PRIOR_WARMUP_START_ITER}->${SR_PRIOR_WARMUP_END_ITER} mode=${SR_PRIOR_SCHEDULE_MODE}"
  PRIOR_ARGS+=(
    --sr_prior_root "${PREPARED_SR_PRIOR_ROOT}"
    --sr_prior_subdir "${SR_PRIOR_SUBDIR}"
    --sr_prior_mask_subdir "${SR_PRIOR_MASK_SUBDIR}"
    --sr_anchor_subdir "${SR_ANCHOR_SUBDIR}"
    --sr_images_subdir "${SR_IMAGES_SUBDIR}"
    --sr_max_views "${SR_MAX_VIEWS}"
    --sr_prior_l1_weight "${SR_PRIOR_L1_WEIGHT}"
    --sr_prior_hf_weight "${SR_PRIOR_HF_WEIGHT}"
    --sr_prior_warmup_start_iter "${SR_PRIOR_WARMUP_START_ITER}"
    --sr_prior_warmup_end_iter "${SR_PRIOR_WARMUP_END_ITER}"
    --sr_prior_start_scale "${SR_PRIOR_START_SCALE}"
    --sr_prior_end_scale "${SR_PRIOR_END_SCALE}"
    --sr_prior_update_scale "${SR_PRIOR_UPDATE_SCALE}"
    --sr_prior_schedule_mode "${SR_PRIOR_SCHEDULE_MODE}"
    --sr_prior_mask_floor "${SR_PRIOR_MASK_FLOOR}"
    --sr_prior_consistency_threshold "${SR_PRIOR_CONSISTENCY_THRESHOLD}"
    --sr_prior_min_valid_ratio "${SR_PRIOR_MIN_VALID_RATIO}"
    --sr_prior_min_pixels "${SR_PRIOR_MIN_PIXELS}"
    --sr_prior_delta_clip "${SR_PRIOR_DELTA_CLIP}"
  )
  if [[ "${DISABLE_SR_PRIOR_HF_RESIDUAL}" == "1" ]]; then
    PRIOR_ARGS+=(--disable_sr_prior_hf_residual)
  fi
else
  echo "[mip-to-sof-surface-v0] SR prior        : disabled"
fi

if [[ -n "${DEPTH_PRIOR_ROOT}" ]]; then
  if [[ ! -d "${DEPTH_PRIOR_ROOT}" ]]; then
    echo "[mip-to-sof-surface-v0] missing depth prior root: ${DEPTH_PRIOR_ROOT}" >&2
    exit 1
  fi
  echo "[mip-to-sof-surface-v0] depth prior     : ${DEPTH_PRIOR_ROOT} lambda=${LAMBDA_DEPTH_PRIOR} normal=${LAMBDA_DEPTH_PRIOR_NORMAL} distort=${LAMBDA_DEPTH_PRIOR_DISTORTION} selfn=${LAMBDA_DEPTH_PRIOR_SELF_NORMAL}"
  echo "[mip-to-sof-surface-v0] depth inject    : scale=${DEPTH_PRIOR_START_SCALE}->${DEPTH_PRIOR_END_SCALE} update=${DEPTH_PRIOR_UPDATE_SCALE} iter=${DEPTH_PRIOR_WARMUP_START_ITER}->${DEPTH_PRIOR_WARMUP_END_ITER} mode=${DEPTH_PRIOR_SCHEDULE_MODE} boost=${DEPTH_PRIOR_SURFACE_WEIGHT_BOOST} weight=${DEPTH_PRIOR_WEIGHT_GAIN}*w^${DEPTH_PRIOR_WEIGHT_POWER} min=${DEPTH_PRIOR_WEIGHT_MIN}"
  PRIOR_ARGS+=(
    --depth_prior_root "${DEPTH_PRIOR_ROOT}"
    --depth_prior_subdirs "${DEPTH_PRIOR_SUBDIRS}"
    --depth_prior_confidence_subdirs "${DEPTH_PRIOR_CONFIDENCE_SUBDIRS}"
    --lambda_depth_prior "${LAMBDA_DEPTH_PRIOR}"
    --lambda_depth_prior_normal "${LAMBDA_DEPTH_PRIOR_NORMAL}"
    --lambda_depth_prior_distortion "${LAMBDA_DEPTH_PRIOR_DISTORTION}"
    --lambda_depth_prior_self_normal "${LAMBDA_DEPTH_PRIOR_SELF_NORMAL}"
    --depth_prior_confidence_min "${DEPTH_PRIOR_CONFIDENCE_MIN}"
    --depth_prior_agreement_threshold "${DEPTH_PRIOR_AGREEMENT_THRESHOLD}"
    --depth_prior_agreement_floor "${DEPTH_PRIOR_AGREEMENT_FLOOR}"
    --depth_prior_align_mode "${DEPTH_PRIOR_ALIGN_MODE}"
    --depth_prior_align_min_pixels "${DEPTH_PRIOR_ALIGN_MIN_PIXELS}"
    --depth_prior_surface_weight_boost "${DEPTH_PRIOR_SURFACE_WEIGHT_BOOST}"
    --depth_prior_warmup_start_iter "${DEPTH_PRIOR_WARMUP_START_ITER}"
    --depth_prior_warmup_end_iter "${DEPTH_PRIOR_WARMUP_END_ITER}"
    --depth_prior_start_scale "${DEPTH_PRIOR_START_SCALE}"
    --depth_prior_end_scale "${DEPTH_PRIOR_END_SCALE}"
    --depth_prior_update_scale "${DEPTH_PRIOR_UPDATE_SCALE}"
    --depth_prior_schedule_mode "${DEPTH_PRIOR_SCHEDULE_MODE}"
    --depth_prior_weight_gain "${DEPTH_PRIOR_WEIGHT_GAIN}"
    --depth_prior_weight_power "${DEPTH_PRIOR_WEIGHT_POWER}"
    --depth_prior_weight_min "${DEPTH_PRIOR_WEIGHT_MIN}"
  )
else
  echo "[mip-to-sof-surface-v0] depth prior     : disabled"
fi

if [[ "${GRADIENT_GUARD_MODE}" != "none" ]]; then
  echo "[mip-to-sof-surface-v0] grad guard      : mode=${GRADIENT_GUARD_MODE} start=${GRADIENT_GUARD_START_ITER} xyz>${GRADIENT_GUARD_XYZ_THRESHOLD} opacity>${GRADIENT_GUARD_OPACITY_THRESHOLD} scale>${GRADIENT_GUARD_SCALE_THRESHOLD} cap=${GRADIENT_GUARD_MAX_FRACTION}/${GRADIENT_GUARD_MAX_POINTS} masked=${GRADIENT_GUARD_ONLY_UPDATE_MASK}"
fi
if [[ "${DEPTH_FEEDBACK_MODE}" != "none" ]]; then
  echo "[mip-to-sof-surface-v0] depth feedback  : mode=${DEPTH_FEEDBACK_MODE} start=${DEPTH_FEEDBACK_START_ITER} interval=${DEPTH_FEEDBACK_INTERVAL} min_visible=${DEPTH_FEEDBACK_MIN_VISIBLE} min_score=${DEPTH_FEEDBACK_MIN_SCORE} cap=${DEPTH_FEEDBACK_TOP_FRACTION}/${DEPTH_FEEDBACK_TOP_POINTS} dropout=${DEPTH_FEEDBACK_DROPOUT_ITERS} masked=${DEPTH_FEEDBACK_ONLY_UPDATE_MASK}"
fi

mkdir -p "${RUN_ROOT}" "${OUTPUT_MODEL}"

"${PYTHON_BIN}" -u "${SOF_ROOT}/train_mip_to_sof_surface_v0.py" \
  --scene_root "${SCENE_ROOT}" \
  --mip_model_path "${MIP_INPUT_MODEL_PATH}" \
  --sof_surface_model_path "${SOF_SURFACE_MODEL}" \
  --output_model_path "${OUTPUT_MODEL}" \
  --images_subdir "${SURFACE_IMAGES_SUBDIR}" \
  --mip_iteration "${MIP_ITERATION}" \
  --sof_iteration "${SOF_SURFACE_ITERATION}" \
  --output_iteration "${OUTPUT_ITERATION}" \
  --max_views "${MAX_VIEWS}" \
  --iterations "${ITERATIONS}" \
  --xyz_lr "${XYZ_LR}" \
  --opacity_lr "${OPACITY_LR}" \
  --scale_lr "${SCALE_LR}" \
  --lambda_rgb_preserve "${LAMBDA_RGB_PRESERVE}" \
  --lambda_depth "${LAMBDA_DEPTH}" \
  --lambda_normal "${LAMBDA_NORMAL}" \
  --lambda_alpha "${LAMBDA_ALPHA}" \
  --lambda_mip_closure_alpha "${LAMBDA_MIP_CLOSURE_ALPHA}" \
  --lambda_mip_closure_premul "${LAMBDA_MIP_CLOSURE_PREMUL}" \
  --lambda_mip_closure_depth "${LAMBDA_MIP_CLOSURE_DEPTH}" \
  --lambda_mip_obs_closure_alpha "${LAMBDA_MIP_OBS_CLOSURE_ALPHA}" \
  --lambda_mip_obs_closure_premul "${LAMBDA_MIP_OBS_CLOSURE_PREMUL}" \
  --lambda_mip_obs_closure_depth "${LAMBDA_MIP_OBS_CLOSURE_DEPTH}" \
  --lambda_opacity_anchor "${LAMBDA_OPACITY_ANCHOR}" \
  --lambda_scale_anchor "${LAMBDA_SCALE_ANCHOR}" \
  --lambda_anchor "${LAMBDA_ANCHOR}" \
  --min_surface_alpha "${MIN_SURFACE_ALPHA}" \
  --min_loss_pixels "${MIN_LOSS_PIXELS}" \
  --mip_closure_kernel "${MIP_CLOSURE_KERNEL}" \
  --mip_closure_alpha_threshold "${MIP_CLOSURE_ALPHA_THRESHOLD}" \
  --mip_closure_reference_lowpass "${MIP_CLOSURE_REFERENCE_LOWPASS}" \
  --mip_obs_closure_images_subdir "${MIP_OBS_CLOSURE_IMAGES_SUBDIR}" \
  --mip_obs_closure_split "${MIP_OBS_CLOSURE_SPLIT}" \
  --mip_obs_closure_max_views "${MIP_OBS_CLOSURE_MAX_VIEWS}" \
  --filter_images_subdir "${FILTER_IMAGES_SUBDIR}" \
  --filter_split "${FILTER_SPLIT}" \
  --filter_max_views "${FILTER_MAX_VIEWS}" \
  --depth_relative_min "${DEPTH_RELATIVE_MIN}" \
  --max_displacement_ratio "${MAX_DISPLACEMENT_RATIO}" \
  --max_displacement_abs "${MAX_DISPLACEMENT_ABS}" \
  --enable_opacity_update "${ENABLE_OPACITY_UPDATE}" \
  --enable_scale_update "${ENABLE_SCALE_UPDATE}" \
  --optimize_gaussian_mask_payload "${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD}" \
  --optimize_gaussian_mask_key "${OPTIMIZE_GAUSSIAN_MASK_KEY}" \
  --gaussian_update_scale "${GAUSSIAN_UPDATE_SCALE}" \
  --gaussian_scale_axis_mode "${GAUSSIAN_SCALE_AXIS_MODE}" \
  --gaussian_scale_min_multiplier "${GAUSSIAN_SCALE_MIN_MULTIPLIER}" \
  --gaussian_scale_max_multiplier "${GAUSSIAN_SCALE_MAX_MULTIPLIER}" \
  --gradient_guard_mode "${GRADIENT_GUARD_MODE}" \
  --gradient_guard_start_iter "${GRADIENT_GUARD_START_ITER}" \
  --gradient_guard_xyz_threshold "${GRADIENT_GUARD_XYZ_THRESHOLD}" \
  --gradient_guard_opacity_threshold "${GRADIENT_GUARD_OPACITY_THRESHOLD}" \
  --gradient_guard_scale_threshold "${GRADIENT_GUARD_SCALE_THRESHOLD}" \
  --gradient_guard_max_fraction "${GRADIENT_GUARD_MAX_FRACTION}" \
  --gradient_guard_max_points "${GRADIENT_GUARD_MAX_POINTS}" \
  --gradient_guard_only_update_mask "${GRADIENT_GUARD_ONLY_UPDATE_MASK}" \
  --depth_feedback_mode "${DEPTH_FEEDBACK_MODE}" \
  --depth_feedback_start_iter "${DEPTH_FEEDBACK_START_ITER}" \
  --depth_feedback_interval "${DEPTH_FEEDBACK_INTERVAL}" \
  --depth_feedback_min_visible "${DEPTH_FEEDBACK_MIN_VISIBLE}" \
  --depth_feedback_min_score "${DEPTH_FEEDBACK_MIN_SCORE}" \
  --depth_feedback_top_fraction "${DEPTH_FEEDBACK_TOP_FRACTION}" \
  --depth_feedback_top_points "${DEPTH_FEEDBACK_TOP_POINTS}" \
  --depth_feedback_dropout_iters "${DEPTH_FEEDBACK_DROPOUT_ITERS}" \
  --depth_feedback_only_update_mask "${DEPTH_FEEDBACK_ONLY_UPDATE_MASK}" \
  "${PRIOR_ARGS[@]}"

if [[ "${RUN_BASE_RENDER}" == "1" ]]; then
  "${PYTHON_BIN}" -u "${SOF_ROOT}/scripts/render_model_no_gt.py" \
    --scene_root "${SCENE_ROOT}" \
    --model_path "${MIP_INPUT_MODEL_PATH}" \
    --output_dir "${BASE_RENDER_DIR}" \
    --images_subdir "${RENDER_IMAGES_SUBDIR}" \
    --iteration "${MIP_ITERATION}" \
    --split "${RENDER_SPLIT}"
fi

if [[ "${RUN_RENDER}" == "1" ]]; then
  "${PYTHON_BIN}" -u "${SOF_ROOT}/scripts/render_model_no_gt.py" \
    --scene_root "${SCENE_ROOT}" \
    --model_path "${OUTPUT_MODEL}" \
    --output_dir "${PULLED_RENDER_DIR}" \
    --images_subdir "${RENDER_IMAGES_SUBDIR}" \
    --iteration "${OUTPUT_ITERATION}" \
    --split "${RENDER_SPLIT}"
fi

if [[ "${RUN_RENDER_COMPARE}" == "1" && "${RUN_BASE_RENDER}" == "1" && "${RUN_RENDER}" == "1" ]]; then
  "${PYTHON_BIN}" -u "${SOF_ROOT}/scripts/compare_render_dirs_no_gt.py" \
    --reference_dir "${BASE_RENDER_DIR}/${RENDER_SPLIT}/ours_${MIP_ITERATION}/renders" \
    --candidate_dir "${PULLED_RENDER_DIR}/${RENDER_SPLIT}/ours_${OUTPUT_ITERATION}/renders" \
    --output_dir "${RENDER_COMPARE_DIR}"
fi

echo "[done] output model    : ${OUTPUT_MODEL}"
echo "[done] output ply      : ${OUTPUT_MODEL}/point_cloud/iteration_${OUTPUT_ITERATION}/point_cloud.ply"
echo "[done] summary         : ${OUTPUT_MODEL}/mip_to_sof_surface_v0_summary.json"
if [[ "${RUN_RENDER}" == "1" ]]; then
  echo "[done] pulled renders  : ${PULLED_RENDER_DIR}/${RENDER_SPLIT}/ours_${OUTPUT_ITERATION}/renders"
fi
if [[ "${RUN_BASE_RENDER}" == "1" ]]; then
  echo "[done] base renders    : ${BASE_RENDER_DIR}/${RENDER_SPLIT}/ours_${MIP_ITERATION}/renders"
fi
if [[ "${RUN_RENDER_COMPARE}" == "1" && "${RUN_BASE_RENDER}" == "1" && "${RUN_RENDER}" == "1" ]]; then
  echo "[done] render diff     : ${RENDER_COMPARE_DIR}/summary.json"
  echo "[done] render absdiff  : ${RENDER_COMPARE_DIR}/absdiff"
fi
