#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
SCENE_ROOT="${SCENE_ROOT:-/root/autodl-tmp/kitchen}"
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT:-${SCENE_ROOT}/_hrgsrefiner_assets}"
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP:-${SCENE_NAME}_mip_vanilla_images8_v1}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k}"
MIP_ITERATION="${MIP_ITERATION:-30000}"
PYTHON_BIN="${PYTHON_BIN:-python}"
BASE_TAG="${BASE_TAG:-k22}"

IMAGE22_MIP_MODEL_PATH="${IMAGE22_MIP_MODEL_PATH:-${SCENE_ASSET_ROOT}/${MIP_EXPERIMENT_GROUP}/${MIP_EXPERIMENT_NAME}_sof_native_input_init_repair_v0}"
IMAGE22_RUN_NAME="${IMAGE22_RUN_NAME:-${BASE_TAG}_clean}"
IMAGE22_RUN_ROOT="${IMAGE22_RUN_ROOT:-${SOF_ROOT}/output/cleanup_mip_view_aligned_volume_artifacts_v0/${SCENE_NAME}/${IMAGE22_RUN_NAME}}"
POST_REFIT_NAME="${POST_REFIT_NAME:-refit_l}"
POST_REFIT_MODEL="${POST_REFIT_MODEL:-${IMAGE22_RUN_ROOT}/cleaned_mip_model_view_volume_v1_${POST_REFIT_NAME}}"
POST_REFIT_RENDER="${POST_REFIT_RENDER:-0}"
RUN_BASE_CLEANUP="${RUN_BASE_CLEANUP:-0}"

PATCH_RUN_NAME="${PATCH_RUN_NAME:-${BASE_TAG}_patch}"
PATCH_MODEL_PATH="${PATCH_MODEL_PATH:-${SOF_ROOT}/output/post_cleanup_surface_patch_carriers_v0/${SCENE_NAME}/${PATCH_RUN_NAME}}"
RUN_PATCH_RENDER="${RUN_PATCH_RENDER:-1}"

RECOVER_RUN_NAME="${RECOVER_RUN_NAME:-${BASE_TAG}_patch_ie}"
RUN_RECOVER_RENDER="${RUN_RECOVER_RENDER:-1}"

SELECT_QUANTILE="${SELECT_QUANTILE:-0.975}"
MIN_DEFICIT_SCORE="${MIN_DEFICIT_SCORE:-0.035}"
MIN_PLANARITY="${MIN_PLANARITY:-4.0}"
MIN_OPACITY="${MIN_OPACITY:-0.020}"
MIN_TANGENT_EXTENT_RATIO="${MIN_TANGENT_EXTENT_RATIO:-0.00045}"
MAX_CANDIDATE_FRACTION="${MAX_CANDIDATE_FRACTION:-0.020}"
MAX_CANDIDATE_COUNT="${MAX_CANDIDATE_COUNT:-24000}"
PATCH_GRID_SIDE="${PATCH_GRID_SIDE:-2}"
PATCH_OFFSET_SCALE="${PATCH_OFFSET_SCALE:-0.72}"
PATCH_TANGENT_SCALE_MULTIPLIER="${PATCH_TANGENT_SCALE_MULTIPLIER:-0.48}"
PATCH_NORMAL_SCALE_MULTIPLIER="${PATCH_NORMAL_SCALE_MULTIPLIER:-0.28}"
PATCH_OPACITY_SCALE="${PATCH_OPACITY_SCALE:-0.55}"
PATCH_MAX_OPACITY="${PATCH_MAX_OPACITY:-0.26}"
PATCH_FILTER_SCALE="${PATCH_FILTER_SCALE:-0.22}"
FILTER_CAP_RATIO="${FILTER_CAP_RATIO:-0.00045}"
ENERGY_CONSERVE_MODE="${ENERGY_CONSERVE_MODE:-area}"
FEATURES_REST_SCALE="${FEATURES_REST_SCALE:-0.0}"

RECOVER_PROFILE="${RECOVER_PROFILE:-prior_recovery_v1}"
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT:-0.08}"
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT:-0.42}"
LAMBDA_SR_RISK_OPACITY="${LAMBDA_SR_RISK_OPACITY:-0.040}"
LAMBDA_SR_RISK_SCALE="${LAMBDA_SR_RISK_SCALE:-0.008}"
SR_RISK_BOOST="${SR_RISK_BOOST:-1.80}"
ITERATIONS="${ITERATIONS:-1800}"
MAX_DISPLACEMENT_RATIO="${MAX_DISPLACEMENT_RATIO:-0.0016}"

echo "[image22-surfacepatch-iesrgs] scene        : ${SCENE_ROOT}"
echo "[image22-surfacepatch-iesrgs] image22 input: ${IMAGE22_MIP_MODEL_PATH}"
echo "[image22-surfacepatch-iesrgs] post refit   : ${POST_REFIT_MODEL}"
echo "[image22-surfacepatch-iesrgs] patch model  : ${PATCH_MODEL_PATH}"
echo "[image22-surfacepatch-iesrgs] recover run  : ${RECOVER_RUN_NAME}"

SCENE_NAME="${SCENE_NAME}" \
SCENE_ROOT="${SCENE_ROOT}" \
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP}" \
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
PYTHON_BIN="${PYTHON_BIN}" \
RUN_BASE_CLEANUP="${RUN_BASE_CLEANUP}" \
RUN_POST_REFIT_RENDER="${POST_REFIT_RENDER}" \
RUN_LR_RECOVER=0 \
POST_REFIT_NAME="${POST_REFIT_NAME}" \
bash "${SCRIPT_DIR}/run_image22_cleanup_then_post_curve_refit_v1_looser_kitchen.sh"

if [[ ! -e "${POST_REFIT_MODEL}/point_cloud/iteration_${MIP_ITERATION}/point_cloud.ply" ]]; then
  echo "[image22-surfacepatch-iesrgs] missing post-refit model: ${POST_REFIT_MODEL}/point_cloud/iteration_${MIP_ITERATION}/point_cloud.ply" >&2
  exit 1
fi

SCENE_NAME="${SCENE_NAME}" \
SCENE_ROOT="${SCENE_ROOT}" \
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
MIP_EXPERIMENT_GROUP="${MIP_EXPERIMENT_GROUP}" \
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME}" \
MODEL_PATH="${POST_REFIT_MODEL}" \
ITERATION="${MIP_ITERATION}" \
MIP_MODEL_PATH="${IMAGE22_MIP_MODEL_PATH}" \
MIP_ITERATION="${MIP_ITERATION}" \
RUN_NAME="${PATCH_RUN_NAME}" \
OUTPUT_MODEL_PATH="${PATCH_MODEL_PATH}" \
RUN_RENDER="${RUN_PATCH_RENDER}" \
SELECT_QUANTILE="${SELECT_QUANTILE}" \
MIN_DEFICIT_SCORE="${MIN_DEFICIT_SCORE}" \
MIN_PLANARITY="${MIN_PLANARITY}" \
MIN_OPACITY="${MIN_OPACITY}" \
MIN_TANGENT_EXTENT_RATIO="${MIN_TANGENT_EXTENT_RATIO}" \
MAX_CANDIDATE_FRACTION="${MAX_CANDIDATE_FRACTION}" \
MAX_CANDIDATE_COUNT="${MAX_CANDIDATE_COUNT}" \
PATCH_GRID_SIDE="${PATCH_GRID_SIDE}" \
PATCH_OFFSET_SCALE="${PATCH_OFFSET_SCALE}" \
PATCH_TANGENT_SCALE_MULTIPLIER="${PATCH_TANGENT_SCALE_MULTIPLIER}" \
PATCH_NORMAL_SCALE_MULTIPLIER="${PATCH_NORMAL_SCALE_MULTIPLIER}" \
PATCH_OPACITY_SCALE="${PATCH_OPACITY_SCALE}" \
PATCH_MAX_OPACITY="${PATCH_MAX_OPACITY}" \
PATCH_FILTER_SCALE="${PATCH_FILTER_SCALE}" \
FILTER_CAP_RATIO="${FILTER_CAP_RATIO}" \
ENERGY_CONSERVE_MODE="${ENERGY_CONSERVE_MODE}" \
FEATURES_REST_SCALE="${FEATURES_REST_SCALE}" \
PYTHON_BIN="${PYTHON_BIN}" \
bash "${SCRIPT_DIR}/run_inject_mip_surface_patch_carriers_v0_kitchen.sh"

if [[ ! -e "${PATCH_MODEL_PATH}/point_cloud/iteration_${MIP_ITERATION}/point_cloud.ply" ]]; then
  echo "[image22-surfacepatch-iesrgs] missing patch model: ${PATCH_MODEL_PATH}/point_cloud/iteration_${MIP_ITERATION}/point_cloud.ply" >&2
  exit 1
fi

SCENE_NAME="${SCENE_NAME}" \
SCENE_ROOT="${SCENE_ROOT}" \
SCENE_ASSET_ROOT="${SCENE_ASSET_ROOT}" \
START_MODEL_PATH="${PATCH_MODEL_PATH}" \
START_ITERATION="${MIP_ITERATION}" \
ANCHOR_MODEL_PATH="${IMAGE22_MIP_MODEL_PATH}" \
ANCHOR_ITERATION="${MIP_ITERATION}" \
REFINE_PROFILE="${RECOVER_PROFILE}" \
RUN_NAME="${RECOVER_RUN_NAME}" \
RUN_RENDER="${RUN_RECOVER_RENDER}" \
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT}" \
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT}" \
LAMBDA_SR_RISK_OPACITY="${LAMBDA_SR_RISK_OPACITY}" \
LAMBDA_SR_RISK_SCALE="${LAMBDA_SR_RISK_SCALE}" \
SR_RISK_BOOST="${SR_RISK_BOOST}" \
ITERATIONS="${ITERATIONS}" \
MAX_DISPLACEMENT_RATIO="${MAX_DISPLACEMENT_RATIO}" \
PYTHON_BIN="${PYTHON_BIN}" \
bash "${SOF_ROOT}/scripts/run_recover_cleaned_mip_lr_v0_kitchen.sh"

echo "[done] post refit model : ${POST_REFIT_MODEL}"
echo "[done] patch model      : ${PATCH_MODEL_PATH}"
echo "[done] recover run      : ${SOF_ROOT}/output/recover_cleaned_mip_lr_v0/${SCENE_NAME}/${RECOVER_RUN_NAME}"
