#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

BASE_TAG="${BASE_TAG:-k22}" \
POST_REFIT_NAME="${POST_REFIT_NAME:-refit_ie}" \
LR_RECOVER_PROFILE="${LR_RECOVER_PROFILE:-prior_recovery_v1}" \
LR_RECOVER_RUN_NAME="${LR_RECOVER_RUN_NAME:-${BASE_TAG}_${POST_REFIT_NAME}}" \
SR_PRIOR_L1_WEIGHT="${SR_PRIOR_L1_WEIGHT:-0.08}" \
SR_PRIOR_HF_WEIGHT="${SR_PRIOR_HF_WEIGHT:-0.42}" \
LAMBDA_SR_RISK_OPACITY="${LAMBDA_SR_RISK_OPACITY:-0.040}" \
LAMBDA_SR_RISK_SCALE="${LAMBDA_SR_RISK_SCALE:-0.008}" \
SR_RISK_BOOST="${SR_RISK_BOOST:-1.80}" \
ITERATIONS="${ITERATIONS:-1800}" \
MAX_DISPLACEMENT_RATIO="${MAX_DISPLACEMENT_RATIO:-0.0016}" \
POST_REFIT_MAX_FRACTION="${POST_REFIT_MAX_FRACTION:-0.14}" \
POST_REFIT_MAX_COUNT="${POST_REFIT_MAX_COUNT:-220000}" \
POST_REFIT_MIN_OPACITY="${POST_REFIT_MIN_OPACITY:-0.018}" \
POST_REFIT_MIN_EFFECTIVE_SCALE_RATIO="${POST_REFIT_MIN_EFFECTIVE_SCALE_RATIO:-0.0015}" \
POST_REFIT_MIN_VOLUME_RADIUS_RATIO="${POST_REFIT_MIN_VOLUME_RADIUS_RATIO:-0.00065}" \
POST_REFIT_MIN_FILTER_SCALE_RATIO="${POST_REFIT_MIN_FILTER_SCALE_RATIO:-0.25}" \
POST_REFIT_MIN_FULL_ANISOTROPY="${POST_REFIT_MIN_FULL_ANISOTROPY:-1.9}" \
bash "${SCRIPT_DIR}/run_image22_cleanup_then_post_curve_refit_v1_kitchen.sh"
