#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_hfseed_viewmajor_v12_hfshape_imprint}"

# v12 keeps the HF-shaped birth from v11, but makes the newborn carriers
# visibly responsible for prior high-frequency energy during a short window.
# The key change is recent-seed imprint: render only recent PRIOR_INJECTED seeds
# on black and require their HF energy to approach the prior residual HF energy.
export PRIOR_BUBBLE_CLEANUP_ENABLE="${PRIOR_BUBBLE_CLEANUP_ENABLE:-0}"

export PRIOR_HF_SEED_SHAPE_MODE="${PRIOR_HF_SEED_SHAPE_MODE:-hf_oriented}"
export PRIOR_HF_SEED_SHAPE_LONG_RATIO="${PRIOR_HF_SEED_SHAPE_LONG_RATIO:-2.35}"
export PRIOR_HF_SEED_SHAPE_SHORT_RATIO="${PRIOR_HF_SEED_SHAPE_SHORT_RATIO:-0.72}"
export PRIOR_HF_SEED_SHAPE_NORMAL_RATIO="${PRIOR_HF_SEED_SHAPE_NORMAL_RATIO:-0.18}"
export PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER="${PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER:-0.55}"

export PRIOR_HF_SEED_SCALE_MODE="${PRIOR_HF_SEED_SCALE_MODE:-pixel}"
export PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-0.62}"
export PRIOR_HF_SEED_MIN_PIXEL_RADIUS="${PRIOR_HF_SEED_MIN_PIXEL_RADIUS:-0.22}"
export PRIOR_HF_SEED_MAX_PIXEL_RADIUS="${PRIOR_HF_SEED_MAX_PIXEL_RADIUS:-0.86}"
export PRIOR_HF_SEED_MAX_PROVIDER_RATIO="${PRIOR_HF_SEED_MAX_PROVIDER_RATIO:-0.13}"
export PRIOR_HF_SEED_SCALE_CLAMP_ENABLE="${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE:-1}"
export PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS:-0.020}"
export PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY:-18.0}"
export PRIOR_HF_SEED_DIAG_LARGE_SCALE="${PRIOR_HF_SEED_DIAG_LARGE_SCALE:-0.020}"

export PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.46}"
export PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.000}"
export PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN="${PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN:-4.2}"

export PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-768}"
export PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-393216}"
export PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.042}"
export PRIOR_HF_SEED_PRUNE_PROTECT_ITERS="${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS:-1100}"
export PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST:-4.2}"
export PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT="${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT:-2.4}"
export PRIOR_HF_SEED_RECENT_IMPRINT_GAIN="${PRIOR_HF_SEED_RECENT_IMPRINT_GAIN:-1.55}"
export PRIOR_HF_SEED_RECENT_IMPRINT_ITERS="${PRIOR_HF_SEED_RECENT_IMPRINT_ITERS:-180}"

export PRIOR_HF_LOWFREQ_CLEANUP_ENABLE="${PRIOR_HF_LOWFREQ_CLEANUP_ENABLE:-1}"
export PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER:-30500}"
export PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER:-32000}"
export PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL="${PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL:-20}"
export PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS="${PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS:-260}"
export PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN:-0.055}"
export PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN:-0.0045}"
export PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX:-0.022}"
export PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX:-0.0}"
export PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY:-0.74}"
export PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW="${PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW:-0.020}"
export PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION:-0.004}"
export PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT:-5000}"

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen_viewmajor_hfsmall_hfshape.sh"
