#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

PHASE_MODE="${PHASE_MODE:-appearance_only}"
REFINE_PROFILE="${REFINE_PROFILE:-mip_hr_anchor_v0}"
ITERATIONS="${ITERATIONS:-300}"
MAX_VIEWS="${MAX_VIEWS:-0}"
SR_MAX_VIEWS="${SR_MAX_VIEWS:-0}"
SR_VIEW_MODE="${SR_VIEW_MODE:-all_train}"

ENABLE_DC_UPDATE="${ENABLE_DC_UPDATE:-1}"
DC_LR="${DC_LR:-5e-4}"
ENABLE_REST_UPDATE="${ENABLE_REST_UPDATE:-0}"
REST_LR="${REST_LR:-0.0}"

ENABLE_OPACITY_UPDATE="${ENABLE_OPACITY_UPDATE:-1}"
ENABLE_SCALE_UPDATE="${ENABLE_SCALE_UPDATE:-1}"

PRIOR_PREFILTER_MODE="${PRIOR_PREFILTER_MODE:-sr_touch_v0}"
PRIOR_PREFILTER_VIEW_LIMIT="${PRIOR_PREFILTER_VIEW_LIMIT:-0}"
PRIOR_PREFILTER_MIN_TOUCH_VIEWS="${PRIOR_PREFILTER_MIN_TOUCH_VIEWS:-1}"
PRIOR_PREFILTER_MIN_VISIBLE_VIEWS="${PRIOR_PREFILTER_MIN_VISIBLE_VIEWS:-1}"
PRIOR_PREFILTER_MIN_TOUCH_RATIO="${PRIOR_PREFILTER_MIN_TOUCH_RATIO:-0.0}"
PRIOR_PREFILTER_MIN_CANDIDATE_OPACITY="${PRIOR_PREFILTER_MIN_CANDIDATE_OPACITY:-0.0}"
PRIOR_PREFILTER_RADIUS_SCALE="${PRIOR_PREFILTER_RADIUS_SCALE:-0.5}"
PRIOR_PREFILTER_MIN_TOUCH_RADIUS_PX="${PRIOR_PREFILTER_MIN_TOUCH_RADIUS_PX:-2.0}"
PRIOR_PREFILTER_MAX_TOUCH_RADIUS_PX="${PRIOR_PREFILTER_MAX_TOUCH_RADIUS_PX:-16.0}"

RUN_NAME="${RUN_NAME:-${START_RUN_NAME:-view_aligned_volume_delete_v1}_${REFINE_PROFILE}_ab_${PHASE_MODE}_short_v0}"

export PHASE_MODE
export REFINE_PROFILE
export ITERATIONS
export MAX_VIEWS
export SR_MAX_VIEWS
export SR_VIEW_MODE
export ENABLE_DC_UPDATE
export DC_LR
export ENABLE_REST_UPDATE
export REST_LR
export ENABLE_OPACITY_UPDATE
export ENABLE_SCALE_UPDATE
export PRIOR_PREFILTER_MODE
export PRIOR_PREFILTER_VIEW_LIMIT
export PRIOR_PREFILTER_MIN_TOUCH_VIEWS
export PRIOR_PREFILTER_MIN_VISIBLE_VIEWS
export PRIOR_PREFILTER_MIN_TOUCH_RATIO
export PRIOR_PREFILTER_MIN_CANDIDATE_OPACITY
export PRIOR_PREFILTER_RADIUS_SCALE
export PRIOR_PREFILTER_MIN_TOUCH_RADIUS_PX
export PRIOR_PREFILTER_MAX_TOUCH_RADIUS_PX
export RUN_NAME

bash "${SOF_ROOT}/scripts/run_recover_cleaned_mip_lr_v0_kitchen.sh"
