#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

BASE_TAG="${BASE_TAG:-k22}" \
POST_REFIT_NAME="${POST_REFIT_NAME:-refit_l}" \
POST_REFIT_MAX_FRACTION="${POST_REFIT_MAX_FRACTION:-0.14}" \
POST_REFIT_MAX_COUNT="${POST_REFIT_MAX_COUNT:-220000}" \
POST_REFIT_MIN_OPACITY="${POST_REFIT_MIN_OPACITY:-0.018}" \
POST_REFIT_MIN_EFFECTIVE_SCALE_RATIO="${POST_REFIT_MIN_EFFECTIVE_SCALE_RATIO:-0.0015}" \
POST_REFIT_MIN_VOLUME_RADIUS_RATIO="${POST_REFIT_MIN_VOLUME_RADIUS_RATIO:-0.00065}" \
POST_REFIT_MIN_FILTER_SCALE_RATIO="${POST_REFIT_MIN_FILTER_SCALE_RATIO:-0.25}" \
POST_REFIT_MIN_FULL_ANISOTROPY="${POST_REFIT_MIN_FULL_ANISOTROPY:-1.9}" \
bash "${SCRIPT_DIR}/run_image22_cleanup_then_post_curve_refit_v1_kitchen.sh"
