#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

SCENE_NAME="${SCENE_NAME:-kitchen}"
MIP_EXPERIMENT_NAME="${MIP_EXPERIMENT_NAME:-mip30k_rerun_check_directsrc_r1_v0}"
SURFACE_STATE_RUN_NAME="${SURFACE_STATE_RUN_NAME:-${MIP_EXPERIMENT_NAME}_gs2mesh_surface_state_v0}"
SURFACE_STATE_PAYLOAD="${SURFACE_STATE_PAYLOAD:-${SOF_ROOT}/output/gaussian_surface_state_v0/${SCENE_NAME}/${SURFACE_STATE_RUN_NAME}/gaussian_surface_state_v0.pt}"

export RUN_TAG="${RUN_TAG:-mip30k_r1_qwen_dynlayerfreq_v3_priorhf_anneal}"
export MIP_EXPERIMENT_NAME

# This is the cleaner NoSR-style route: no explicit HF seed birth or bubble
# pruning. Classic densify creates carriers, while dynamic layer-frequency
# routing pushes HF residuals to surface descendants and penalizes wrong-layer HF.
export PRIOR_HF_SEED_ENABLE="${PRIOR_HF_SEED_ENABLE:-0}"
export PRIOR_BUBBLE_CLEANUP_ENABLE="${PRIOR_BUBBLE_CLEANUP_ENABLE:-0}"
export PRIOR_HF_LOWFREQ_CLEANUP_ENABLE="${PRIOR_HF_LOWFREQ_CLEANUP_ENABLE:-0}"
export PRIOR_HF_SEED_SCALE_CLAMP_ENABLE="${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE:-0}"

export OPTIMIZE_SOURCE_TAG="${OPTIMIZE_SOURCE_TAG:-all}"
export PRIOR_VIEW_SAMPLE_PROB="${PRIOR_VIEW_SAMPLE_PROB:-0.90}"
export PRIOR_RESIDUAL_USE_MASKS="${PRIOR_RESIDUAL_USE_MASKS:-1}"
export PRIOR_SOFT_MASK_POWER="${PRIOR_SOFT_MASK_POWER:-0.75}"
export PRIOR_HARD_MASK_THRESHOLD="${PRIOR_HARD_MASK_THRESHOLD:-0.35}"
export PRIOR_RESIDUAL_HF_WEIGHT="${PRIOR_RESIDUAL_HF_WEIGHT:-3.20}"
export PRIOR_RESIDUAL_DELTA_CLIP="${PRIOR_RESIDUAL_DELTA_CLIP:-0.20}"
export PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-5.0}"
export PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-2.4}"
export PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-1.20}"
export PRIOR_RESIDUAL_MASKED_UPDATE="${PRIOR_RESIDUAL_MASKED_UPDATE:-1}"
export PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL:-1}"
export PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE:-5.0}"
export PRIOR_GUIDANCE_DECAY_FROM_ITER="${PRIOR_GUIDANCE_DECAY_FROM_ITER:-30800}"
export PRIOR_GUIDANCE_DECAY_UNTIL_ITER="${PRIOR_GUIDANCE_DECAY_UNTIL_ITER:-31800}"
export PRIOR_GUIDANCE_FINAL_SCALE="${PRIOR_GUIDANCE_FINAL_SCALE:-0.30}"

export PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD="${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD:-${SURFACE_STATE_PAYLOAD}}"
export PRIOR_LOSS_GAUSSIAN_MASK_KEY="${PRIOR_LOSS_GAUSSIAN_MASK_KEY:-surface_carrier}"
export PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS="${PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS:-1}"
export LAYER_FREQUENCY_MASK_PAYLOAD="${LAYER_FREQUENCY_MASK_PAYLOAD:-${SURFACE_STATE_PAYLOAD}}"
export LAYER_FREQUENCY_NON_SURFACE_KEY="${LAYER_FREQUENCY_NON_SURFACE_KEY:-non_surface_active}"
export LAYER_FREQUENCY_SURFACE_KEY="${LAYER_FREQUENCY_SURFACE_KEY:-surface_carrier}"
export LAYER_FREQUENCY_DYNAMIC_ROOTS="${LAYER_FREQUENCY_DYNAMIC_ROOTS:-1}"
export LAYER_FREQUENCY_SURFACE_TARGET="${LAYER_FREQUENCY_SURFACE_TARGET:-prior}"
export LAMBDA_NON_SURFACE_HF="${LAMBDA_NON_SURFACE_HF:-0.035}"
export LAMBDA_NON_SURFACE_RGB_ENERGY="${LAMBDA_NON_SURFACE_RGB_ENERGY:-0.0005}"
export LAMBDA_NON_SURFACE_ALPHA_HF="${LAMBDA_NON_SURFACE_ALPHA_HF:-0.0}"
export LAMBDA_NON_SURFACE_ALPHA_MASS="${LAMBDA_NON_SURFACE_ALPHA_MASS:-0.0}"
export LAMBDA_SURFACE_HF_CLOSURE="${LAMBDA_SURFACE_HF_CLOSURE:-0.20}"
export SURFACE_HF_UPDATE_SCALE="${SURFACE_HF_UPDATE_SCALE:-2.2}"
export LAYER_FREQUENCY_FROM_ITER="${LAYER_FREQUENCY_FROM_ITER:-30000}"
export LAYER_FREQUENCY_UNTIL_ITER="${LAYER_FREQUENCY_UNTIL_ITER:-32000}"
export LAYER_FREQUENCY_LOG_INTERVAL="${LAYER_FREQUENCY_LOG_INTERVAL:-50}"

export SURFACE_NORMAL_LOCK="${SURFACE_NORMAL_LOCK:-1}"
export SURFACE_NORMAL_LOCK_PAYLOAD="${SURFACE_NORMAL_LOCK_PAYLOAD:-${SURFACE_STATE_PAYLOAD}}"
export SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS="${SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS:-1}"

export DENSIFY_FROM_ITER="${DENSIFY_FROM_ITER:-30000}"
export DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER:-32000}"
export DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL:-50}"
export DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.00005}"
export OPACITY_RESET_INTERVAL="${OPACITY_RESET_INTERVAL:-1000000}"

if [[ ! -f "${SURFACE_STATE_PAYLOAD}" ]]; then
  echo "[dynlayerfreq-v0] missing surface-state payload: ${SURFACE_STATE_PAYLOAD}" >&2
  echo "[dynlayerfreq-v0] build the row-aligned payload first:" >&2
  echo "  MIP_EXPERIMENT_NAME=${MIP_EXPERIMENT_NAME} \\" >&2
  echo "  RUN_NAME=${SURFACE_STATE_RUN_NAME} \\" >&2
  echo "  bash scripts/run_classify_mip_surface_state_v0_kitchen.sh" >&2
  exit 1
fi

bash "${SCRIPT_DIR}/run_mipsplatting_hf_seed_prior_v0_kitchen.sh"
