#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
DEFAULT_MIPSPLATTING_ROOT="$(cd -- "${SOF_ROOT}/.." && pwd)/mip-splatting"

WORK_ROOT="${WORK_ROOT:-/root/autodl-tmp}"
ARCHIVE_ROOT="${ARCHIVE_ROOT:-${WORK_ROOT}/archive}"
SCENE_NAME="${SCENE_NAME:-kitchen}"
if [[ -z "${SCENE_ROOT:-}" ]]; then
  DIRECT_SCENE_ROOT="${WORK_ROOT}/${SCENE_NAME}"
  ARCHIVE_SCENE_ROOT="${ARCHIVE_ROOT}/${SCENE_NAME}"
  if [[ -d "${DIRECT_SCENE_ROOT}" ]]; then
    SCENE_ROOT="${DIRECT_SCENE_ROOT}"
  else
    SCENE_ROOT="${ARCHIVE_SCENE_ROOT}"
  fi
else
  SCENE_ROOT="${SCENE_ROOT}"
fi

LR_REFERENCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR:-${SOURCE_IMAGES_SUBDIR:-images_8}}"
TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR:-images_2}"
TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR:-images_2}"
LR_REFERENCE_IMAGES_DIR="${LR_REFERENCE_IMAGES_DIR:-${SCENE_ROOT}/${LR_REFERENCE_IMAGES_SUBDIR}}"
TRAIN_IMAGES_DIR="${TRAIN_IMAGES_DIR:-${SCENE_ROOT}/${TRAIN_IMAGES_SUBDIR}}"
TARGET_IMAGES_DIR="${TARGET_IMAGES_DIR:-${SCENE_ROOT}/${TARGET_IMAGES_SUBDIR}}"
PRIOR_DIR="${PRIOR_DIR:-${SCENE_ROOT}/priors}"

ALIAS_ROOT="${ALIAS_ROOT:-${WORK_ROOT}/aliases}"
MIPSPLATTING_ROOT="${MIPSPLATTING_ROOT:-${DEFAULT_MIPSPLATTING_ROOT}}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${SOF_ROOT}/output}"
PRIOR_STRENGTH_PROFILE="${PRIOR_STRENGTH_PROFILE:-aggressive_v1}"
SOF_PARAM_PROFILE="${SOF_PARAM_PROFILE:-default_v1}"

case "${PRIOR_STRENGTH_PROFILE}" in
  stronger_v1)
    DEFAULT_PREPARED_PRIOR_TAG="prepared_stablesr_lrref_v1"
    DEFAULT_EXPERIMENT_NAME="stablesr_mipsplatting_hrprior_finetune_stronger_v1"
    DEFAULT_MASK_THRESHOLD="0.12"
    DEFAULT_PRIOR_SUBDIR="fused_priors"
    DEFAULT_PRIOR_L1_WEIGHT="0.05"
    DEFAULT_PRIOR_HF_WEIGHT="0.30"
    DEFAULT_PRIOR_CONSISTENCY_THRESHOLD="0.12"
    DEFAULT_PRIOR_MIN_VALID_RATIO="0.50"
    DEFAULT_PRIOR_DELTA_CLIP="0.15"
    ;;
  aggressive_v1)
    DEFAULT_PREPARED_PRIOR_TAG="prepared_stablesr_lrref_aggressive_v1"
    DEFAULT_EXPERIMENT_NAME="stablesr_mipsplatting_hrprior_finetune_aggressive_v1"
    DEFAULT_MASK_THRESHOLD="0.16"
    DEFAULT_PRIOR_SUBDIR="priors"
    DEFAULT_PRIOR_L1_WEIGHT="0.08"
    DEFAULT_PRIOR_HF_WEIGHT="0.50"
    DEFAULT_PRIOR_CONSISTENCY_THRESHOLD="0.18"
    DEFAULT_PRIOR_MIN_VALID_RATIO="0.30"
    DEFAULT_PRIOR_DELTA_CLIP="0.25"
    ;;
  *)
    echo "[mipsplatting-stablesr-prior] unknown PRIOR_STRENGTH_PROFILE: ${PRIOR_STRENGTH_PROFILE}" >&2
    exit 1
    ;;
esac

case "${SOF_PARAM_PROFILE}" in
  default_v1)
    DEFAULT_PRIOR_LOCAL_FROM_ITER="0"
    DEFAULT_PRIOR_EDGE_FROM_ITER="0"
    DEFAULT_DISTORTION_FROM_ITER="0"
    DEFAULT_DEPTH_NORMAL_FROM_ITER="0"
    DEFAULT_LAMBDA_DISTORTION="0.0"
    DEFAULT_LAMBDA_DEPTH_NORMAL="0.0"
    DEFAULT_LAMBDA_SMOOTHNESS="0.0"
    DEFAULT_LAMBDA_EXTENT="0.0"
    DEFAULT_LAMBDA_OPACITY_FIELD="0.0"
    DEFAULT_PRIOR_EDGE_DETAIL_ALPHA="0.6"
    DEFAULT_PRIOR_EDGE_DETAIL_ALPHA_FINAL="-1.0"
    DEFAULT_PRIOR_EDGE_DETAIL_WARMUP_ITERS="0"
    DEFAULT_PRIOR_EDGE_DETAIL_WEIGHT="1.0"
    DEFAULT_PRIOR_EDGE_LOWFREQ_WEIGHT="0.05"
    DEFAULT_PRIOR_EDGE_GRAD_WEIGHT="0.0"
    DEFAULT_PRIOR_EDGE_LOWFREQ_THRESHOLD="0.08"
    DEFAULT_PRIOR_EDGE_LOWFREQ_ANCHOR="render"
    DEFAULT_PRIOR_EDGE_DETAIL_MIN_GAIN="0.0"
    DEFAULT_PRIOR_EDGE_CONFIDENCE_POWER="1.0"
    ;;
  early4ksoft_v1)
    DEFAULT_PRIOR_LOCAL_FROM_ITER="0"
    DEFAULT_PRIOR_EDGE_FROM_ITER="0"
    DEFAULT_DISTORTION_FROM_ITER="4000"
    DEFAULT_DEPTH_NORMAL_FROM_ITER="4000"
    DEFAULT_LAMBDA_DISTORTION="200"
    DEFAULT_LAMBDA_DEPTH_NORMAL="0.02"
    DEFAULT_LAMBDA_SMOOTHNESS="0.005"
    DEFAULT_LAMBDA_EXTENT="0.1"
    DEFAULT_LAMBDA_OPACITY_FIELD="0.004"
    DEFAULT_PRIOR_EDGE_DETAIL_ALPHA="0.4"
    DEFAULT_PRIOR_EDGE_DETAIL_ALPHA_FINAL="0.7"
    DEFAULT_PRIOR_EDGE_DETAIL_WARMUP_ITERS="2000"
    DEFAULT_PRIOR_EDGE_DETAIL_WEIGHT="1.0"
    DEFAULT_PRIOR_EDGE_LOWFREQ_WEIGHT="0.05"
    DEFAULT_PRIOR_EDGE_GRAD_WEIGHT="0.05"
    DEFAULT_PRIOR_EDGE_LOWFREQ_THRESHOLD="0.08"
    DEFAULT_PRIOR_EDGE_LOWFREQ_ANCHOR="gt"
    DEFAULT_PRIOR_EDGE_DETAIL_MIN_GAIN="0.005"
    DEFAULT_PRIOR_EDGE_CONFIDENCE_POWER="1.5"
    ;;
  *)
    echo "[mipsplatting-stablesr-prior] unknown SOF_PARAM_PROFILE: ${SOF_PARAM_PROFILE}" >&2
    exit 1
    ;;
esac

BASELINE_MODEL_DIR="${BASELINE_MODEL_DIR:-${OUTPUT_ROOT}/${SCENE_NAME}_mipsplatting_lr_ablation_v1/mipsplatting_x8to2_baseline_directsrc_v1}"
RUN_ROOT="${RUN_ROOT:-${OUTPUT_ROOT}/mipsplatting_prior_repro/${SCENE_NAME}}"
PREPARED_PRIOR_ROOT="${PREPARED_PRIOR_ROOT:-${RUN_ROOT}/${DEFAULT_PREPARED_PRIOR_TAG}}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-${DEFAULT_EXPERIMENT_NAME}}"
PRIOR_MODEL_DIR="${PRIOR_MODEL_DIR:-${RUN_ROOT}/${EXPERIMENT_NAME}}"
COMPARE_JSON="${COMPARE_JSON:-${RUN_ROOT}/baseline_compare.json}"

BASELINE_ITERATION="${BASELINE_ITERATION:-30000}"
ITERATIONS="${ITERATIONS:-32000}"
RENDER_RESOLUTION="${RENDER_RESOLUTION:-1}"
TRAIN_RESOLUTION="${TRAIN_RESOLUTION:-4}"
TRAIN_PORT="${TRAIN_PORT:-6009}"
USE_MERGED_SOF_RASTERIZER="${USE_MERGED_SOF_RASTERIZER:-0}"
USE_VANILLA_SOF_RASTERIZER="${USE_VANILLA_SOF_RASTERIZER:-0}"
REQUIRE_MERGED_SOF_AUX="${REQUIRE_MERGED_SOF_AUX:-0}"
PYTHON_BIN="${PYTHON_BIN:-python}"
CONDA_ENV_NAME="${CONDA_ENV_NAME:-}"
RUN_BASELINE_IF_MISSING="${RUN_BASELINE_IF_MISSING:-1}"
RUN_RENDER_AFTER="${RUN_RENDER_AFTER:-1}"
RUN_METRICS_AFTER="${RUN_METRICS_AFTER:-1}"
SAVE_CHECKPOINT_AFTER="${SAVE_CHECKPOINT_AFTER:-1}"
FORCE_RERUN="${FORCE_RERUN:-0}"

MASK_THRESHOLD="${MASK_THRESHOLD:-${DEFAULT_MASK_THRESHOLD}}"
MASK_MODE="${MASK_MODE:-soft}"
DISCREPANCY_FLOOR="${DISCREPANCY_FLOOR:-0.05}"
FORCE_PREPARE_PRIORS="${FORCE_PREPARE_PRIORS:-0}"
ALLOW_PREPARED_PRIOR_REBUILD="${ALLOW_PREPARED_PRIOR_REBUILD:-${FORCE_PREPARE_PRIORS}}"

PRIOR_SUBDIR="${PRIOR_SUBDIR:-${DEFAULT_PRIOR_SUBDIR}}"
PRIOR_MASK_SUBDIR="${PRIOR_MASK_SUBDIR:-usable_masks}"
DISABLE_PRIOR_USABLE_MASKS="${DISABLE_PRIOR_USABLE_MASKS:-0}"
PRIOR_LOSS_MODE="${PRIOR_LOSS_MODE:-rgb_hf}"
PRIOR_ANCHOR_DIR="${PRIOR_ANCHOR_DIR:-}"
PRIOR_SOFT_MASK_DIR="${PRIOR_SOFT_MASK_DIR:-}"
PRIOR_HARD_MASK_DIR="${PRIOR_HARD_MASK_DIR:-}"
PRIOR_SOFT_MASK_POWER="${PRIOR_SOFT_MASK_POWER:-1.0}"
PRIOR_HARD_MASK_THRESHOLD="${PRIOR_HARD_MASK_THRESHOLD:-0.5}"
PRIOR_MASKED_MIN_PIXELS="${PRIOR_MASKED_MIN_PIXELS:-64}"
PRIOR_RESIDUAL_USE_MASKS="${PRIOR_RESIDUAL_USE_MASKS:-1}"
PRIOR_VIEW_SAMPLE_PROB="${PRIOR_VIEW_SAMPLE_PROB:-0.0}"
PRIOR_DIRECT_XYZ_NUDGE_LR="${PRIOR_DIRECT_XYZ_NUDGE_LR:-0.0}"
PRIOR_DIRECT_XYZ_NUDGE_MAX_STEP="${PRIOR_DIRECT_XYZ_NUDGE_MAX_STEP:-0.0}"
PRIOR_RESIDUAL_MASKED_UPDATE="${PRIOR_RESIDUAL_MASKED_UPDATE:-0}"
PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL:-0}"
PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE="${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE:-1.0}"
PRIOR_L1_WEIGHT="${PRIOR_L1_WEIGHT:-${DEFAULT_PRIOR_L1_WEIGHT}}"
PRIOR_HF_WEIGHT="${PRIOR_HF_WEIGHT:-${DEFAULT_PRIOR_HF_WEIGHT}}"
PRIOR_MASK_FLOOR="${PRIOR_MASK_FLOOR:-0.0}"
PRIOR_CONSISTENCY_THRESHOLD="${PRIOR_CONSISTENCY_THRESHOLD:-${DEFAULT_PRIOR_CONSISTENCY_THRESHOLD}}"
PRIOR_MIN_VALID_RATIO="${PRIOR_MIN_VALID_RATIO:-${DEFAULT_PRIOR_MIN_VALID_RATIO}}"
PRIOR_DELTA_CLIP="${PRIOR_DELTA_CLIP:-${DEFAULT_PRIOR_DELTA_CLIP}}"
DISABLE_PRIOR_HF_RESIDUAL="${DISABLE_PRIOR_HF_RESIDUAL:-0}"
PRIOR_SUPERVISION_IMAGES_SUBDIR="${PRIOR_SUPERVISION_IMAGES_SUBDIR-${TARGET_IMAGES_SUBDIR}}"
PREPARED_PRIOR_EXPECTED_REFERENCE_DIR="${PREPARED_PRIOR_EXPECTED_REFERENCE_DIR:-${LR_REFERENCE_IMAGES_DIR}}"
PRIOR_SUPERVISION_RESOLUTION="${PRIOR_SUPERVISION_RESOLUTION:-1}"
PRIOR_SUPERVISION_CACHE_SIZE="${PRIOR_SUPERVISION_CACHE_SIZE:-4}"
START_CHECKPOINT="${START_CHECKPOINT:-${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth}"
PRIOR_LOCAL_DIR="${PRIOR_LOCAL_DIR:-}"
PRIOR_LOCAL_MASK_DIR="${PRIOR_LOCAL_MASK_DIR:-}"
LAMBDA_PRIOR_LOCAL="${LAMBDA_PRIOR_LOCAL:-0.0}"
PRIOR_LOCAL_MIN_PIXELS="${PRIOR_LOCAL_MIN_PIXELS:-64}"
PRIOR_LOCAL_FROM_ITER="${PRIOR_LOCAL_FROM_ITER:-${DEFAULT_PRIOR_LOCAL_FROM_ITER}}"
PRIOR_EDGE_DIR="${PRIOR_EDGE_DIR:-}"
PRIOR_EDGE_MASK_DIR="${PRIOR_EDGE_MASK_DIR:-}"
LAMBDA_PRIOR_EDGE="${LAMBDA_PRIOR_EDGE:-0.0}"
PRIOR_EDGE_LOSS_MODE="${PRIOR_EDGE_LOSS_MODE:-rgb}"
PRIOR_EDGE_BLEND_ALPHA="${PRIOR_EDGE_BLEND_ALPHA:-1.0}"
PRIOR_EDGE_MIN_PIXELS="${PRIOR_EDGE_MIN_PIXELS:-64}"
PRIOR_EDGE_FROM_ITER="${PRIOR_EDGE_FROM_ITER:-${DEFAULT_PRIOR_EDGE_FROM_ITER}}"
PRIOR_EDGE_TOUCH_MIN_RADIUS_PX="${PRIOR_EDGE_TOUCH_MIN_RADIUS_PX:-2.0}"
PRIOR_EDGE_TOUCH_RADIUS_SCALE="${PRIOR_EDGE_TOUCH_RADIUS_SCALE:-0.5}"
PRIOR_EDGE_TOUCH_MAX_RADIUS_PX="${PRIOR_EDGE_TOUCH_MAX_RADIUS_PX:-16.0}"
PRIOR_EDGE_DETAIL_BLUR_KERNEL="${PRIOR_EDGE_DETAIL_BLUR_KERNEL:-9}"
PRIOR_EDGE_DETAIL_ALPHA="${PRIOR_EDGE_DETAIL_ALPHA:-${DEFAULT_PRIOR_EDGE_DETAIL_ALPHA}}"
PRIOR_EDGE_DETAIL_ALPHA_FINAL="${PRIOR_EDGE_DETAIL_ALPHA_FINAL:-${DEFAULT_PRIOR_EDGE_DETAIL_ALPHA_FINAL}}"
PRIOR_EDGE_DETAIL_WARMUP_ITERS="${PRIOR_EDGE_DETAIL_WARMUP_ITERS:-${DEFAULT_PRIOR_EDGE_DETAIL_WARMUP_ITERS}}"
PRIOR_EDGE_DETAIL_WEIGHT="${PRIOR_EDGE_DETAIL_WEIGHT:-${DEFAULT_PRIOR_EDGE_DETAIL_WEIGHT}}"
PRIOR_EDGE_LOWFREQ_WEIGHT="${PRIOR_EDGE_LOWFREQ_WEIGHT:-${DEFAULT_PRIOR_EDGE_LOWFREQ_WEIGHT}}"
PRIOR_EDGE_GRAD_WEIGHT="${PRIOR_EDGE_GRAD_WEIGHT:-${DEFAULT_PRIOR_EDGE_GRAD_WEIGHT}}"
PRIOR_EDGE_LOWFREQ_THRESHOLD="${PRIOR_EDGE_LOWFREQ_THRESHOLD:-${DEFAULT_PRIOR_EDGE_LOWFREQ_THRESHOLD}}"
PRIOR_EDGE_LOWFREQ_ANCHOR="${PRIOR_EDGE_LOWFREQ_ANCHOR:-${DEFAULT_PRIOR_EDGE_LOWFREQ_ANCHOR}}"
PRIOR_EDGE_DETAIL_MIN_GAIN="${PRIOR_EDGE_DETAIL_MIN_GAIN:-${DEFAULT_PRIOR_EDGE_DETAIL_MIN_GAIN}}"
PRIOR_EDGE_CONFIDENCE_POWER="${PRIOR_EDGE_CONFIDENCE_POWER:-${DEFAULT_PRIOR_EDGE_CONFIDENCE_POWER}}"
PRIOR_EDGE_UPDATE_SCALE="${PRIOR_EDGE_UPDATE_SCALE:-1.0}"
PRIOR_HF_SEED_ENABLE="${PRIOR_HF_SEED_ENABLE:-0}"
PRIOR_HF_SEED_FROM_ITER="${PRIOR_HF_SEED_FROM_ITER:-0}"
PRIOR_HF_SEED_UNTIL_ITER="${PRIOR_HF_SEED_UNTIL_ITER:-0}"
PRIOR_HF_SEED_INTERVAL="${PRIOR_HF_SEED_INTERVAL:-100}"
PRIOR_HF_SEED_MAX_PER_ITER="${PRIOR_HF_SEED_MAX_PER_ITER:-512}"
PRIOR_HF_SEED_MAX_TOTAL="${PRIOR_HF_SEED_MAX_TOTAL:-8192}"
PRIOR_HF_SEED_SCALE_MULTIPLIER="${PRIOR_HF_SEED_SCALE_MULTIPLIER:-0.35}"
PRIOR_HF_SEED_SCALE_MODE="${PRIOR_HF_SEED_SCALE_MODE:-legacy_max}"
PRIOR_HF_SEED_MIN_PIXEL_RADIUS="${PRIOR_HF_SEED_MIN_PIXEL_RADIUS:-0.0}"
PRIOR_HF_SEED_MAX_PIXEL_RADIUS="${PRIOR_HF_SEED_MAX_PIXEL_RADIUS:-0.0}"
PRIOR_HF_SEED_MAX_PROVIDER_RATIO="${PRIOR_HF_SEED_MAX_PROVIDER_RATIO:-0.0}"
PRIOR_HF_SEED_SHAPE_MODE="${PRIOR_HF_SEED_SHAPE_MODE:-isotropic}"
PRIOR_HF_SEED_SHAPE_LONG_RATIO="${PRIOR_HF_SEED_SHAPE_LONG_RATIO:-1.0}"
PRIOR_HF_SEED_SHAPE_SHORT_RATIO="${PRIOR_HF_SEED_SHAPE_SHORT_RATIO:-1.0}"
PRIOR_HF_SEED_SHAPE_NORMAL_RATIO="${PRIOR_HF_SEED_SHAPE_NORMAL_RATIO:-1.0}"
PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER="${PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER:-1.0}"
PRIOR_HF_SEED_DIAG_LARGE_SCALE="${PRIOR_HF_SEED_DIAG_LARGE_SCALE:-0.0}"
PRIOR_HF_SEED_SCALE_CLAMP_ENABLE="${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE:-0}"
PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS:-0.0}"
PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS="${PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS:-0.0}"
PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY="${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY:-0.0}"
PRIOR_BUBBLE_CLEANUP_ENABLE="${PRIOR_BUBBLE_CLEANUP_ENABLE:-0}"
PRIOR_BUBBLE_CLEANUP_FROM_ITER="${PRIOR_BUBBLE_CLEANUP_FROM_ITER:-0}"
PRIOR_BUBBLE_CLEANUP_UNTIL_ITER="${PRIOR_BUBBLE_CLEANUP_UNTIL_ITER:-0}"
PRIOR_BUBBLE_CLEANUP_INTERVAL="${PRIOR_BUBBLE_CLEANUP_INTERVAL:-1}"
PRIOR_BUBBLE_CLEANUP_OPACITY_MIN="${PRIOR_BUBBLE_CLEANUP_OPACITY_MIN:-0.10}"
PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN:-0.0}"
PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX="${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX:-0.0}"
PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX="${PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX:-2.5}"
PRIOR_BUBBLE_CLEANUP_MIN_GENERATION="${PRIOR_BUBBLE_CLEANUP_MIN_GENERATION:-0}"
LAMBDA_PRIOR_BUBBLE_HF="${LAMBDA_PRIOR_BUBBLE_HF:-0.0}"
LAMBDA_PRIOR_BUBBLE_RGB_ENERGY="${LAMBDA_PRIOR_BUBBLE_RGB_ENERGY:-0.0}"
LAMBDA_PRIOR_BUBBLE_ALPHA_HF="${LAMBDA_PRIOR_BUBBLE_ALPHA_HF:-0.0}"
LAMBDA_PRIOR_BUBBLE_ALPHA_MASS="${LAMBDA_PRIOR_BUBBLE_ALPHA_MASS:-0.0}"
PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY="${PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY:-1.0}"
PRIOR_HF_SEED_OPACITY="${PRIOR_HF_SEED_OPACITY:-0.02}"
PRIOR_HF_SEED_JITTER_SCALE="${PRIOR_HF_SEED_JITTER_SCALE:-0.15}"
PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN="${PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN:-1.0}"
PRIOR_HF_SEED_GUIDANCE_THRESHOLD="${PRIOR_HF_SEED_GUIDANCE_THRESHOLD:-0.0}"
PRIOR_HF_SEED_FIRST_CYCLE_ONLY="${PRIOR_HF_SEED_FIRST_CYCLE_ONLY:-0}"
PRIOR_HF_SEED_ORIGINAL_ONLY="${PRIOR_HF_SEED_ORIGINAL_ONLY:-1}"
PRIOR_HF_SEED_PRUNE_PROTECT_ITERS="${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS:-0}"
PRIOR_HF_SEED_RECENT_HF_BOOST="${PRIOR_HF_SEED_RECENT_HF_BOOST:-0.0}"
PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT="${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT:-0.0}"
PRIOR_HF_SEED_RECENT_IMPRINT_GAIN="${PRIOR_HF_SEED_RECENT_IMPRINT_GAIN:-1.0}"
PRIOR_HF_SEED_RECENT_IMPRINT_ITERS="${PRIOR_HF_SEED_RECENT_IMPRINT_ITERS:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_ENABLE="${PRIOR_HF_LOWFREQ_CLEANUP_ENABLE:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER="${PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER:-0}"
PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL="${PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL:-20}"
PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS="${PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS:-240}"
PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN:-0.06}"
PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX="${PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY="${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY:-1.0}"
PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW="${PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION:-0.0}"
PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT="${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT:-0}"
PRIOR_HF_FOCUS_BOOST="${PRIOR_HF_FOCUS_BOOST:-0.0}"
PRIOR_HF_FOCUS_POWER="${PRIOR_HF_FOCUS_POWER:-1.0}"
PRIOR_GUIDANCE_DECAY_FROM_ITER="${PRIOR_GUIDANCE_DECAY_FROM_ITER:-0}"
PRIOR_GUIDANCE_DECAY_UNTIL_ITER="${PRIOR_GUIDANCE_DECAY_UNTIL_ITER:-0}"
PRIOR_GUIDANCE_FINAL_SCALE="${PRIOR_GUIDANCE_FINAL_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_ENABLE="${PRIOR_VIEW_CURRICULUM_ENABLE:-0}"
PRIOR_VIEW_CURRICULUM_START_ITER="${PRIOR_VIEW_CURRICULUM_START_ITER:-0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS:-2}"
PRIOR_VIEW_CURRICULUM_MAX_VIEWS="${PRIOR_VIEW_CURRICULUM_MAX_VIEWS:-0}"
PRIOR_VIEW_CURRICULUM_SETTLE_ITERS="${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY="${PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY:-1}"
PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE="${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE="${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE:-1.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS="${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS:-0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN:-1.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL:-7}"
PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION:-0.15}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE:-0.08}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN:-1.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL:-0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT:-0.0}"
PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL="${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL:-15}"
SURFACE_ROUTE_CONSENSUS_ROOT="${SURFACE_ROUTE_CONSENSUS_ROOT:-}"
LAMBDA_SURFACE_ROUTE_CONSENSUS="${LAMBDA_SURFACE_ROUTE_CONSENSUS:-0.0}"
SURFACE_ROUTE_CONSENSUS_FROM_ITER="${SURFACE_ROUTE_CONSENSUS_FROM_ITER:-0}"
SURFACE_ROUTE_CONSENSUS_MIN_PIXELS="${SURFACE_ROUTE_CONSENSUS_MIN_PIXELS:-64}"
SURFACE_ROUTE_VIEW_SAMPLE_PROB="${SURFACE_ROUTE_VIEW_SAMPLE_PROB:-0.0}"
SURFACE_ROUTE_SURFACE_ONLY="${SURFACE_ROUTE_SURFACE_ONLY:-0}"
OPTIMIZE_SOURCE_TAG="${OPTIMIZE_SOURCE_TAG:-all}"
OPTIMIZE_GAUSSIAN_MASK_PAYLOAD="${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD:-}"
OPTIMIZE_GAUSSIAN_MASK_KEY="${OPTIMIZE_GAUSSIAN_MASK_KEY:-selected_mask}"
PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD="${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD:-}"
PRIOR_LOSS_GAUSSIAN_MASK_KEY="${PRIOR_LOSS_GAUSSIAN_MASK_KEY:-selected_mask}"
PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS="${PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS:-0}"
SURFACE_NORMAL_LOCK="${SURFACE_NORMAL_LOCK:-0}"
SURFACE_NORMAL_LOCK_PAYLOAD="${SURFACE_NORMAL_LOCK_PAYLOAD:-}"
SURFACE_NORMAL_LOCK_NORMAL_KEY="${SURFACE_NORMAL_LOCK_NORMAL_KEY:-anchor_normal}"
SURFACE_NORMAL_LOCK_ANCHOR_KEY="${SURFACE_NORMAL_LOCK_ANCHOR_KEY:-anchor_xyz}"
SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS="${SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS:-0}"
SURFACE_FILTER_3D="${SURFACE_FILTER_3D:-0}"
SURFACE_FILTER_3D_PAYLOAD="${SURFACE_FILTER_3D_PAYLOAD:-}"
SURFACE_FILTER_3D_KEY="${SURFACE_FILTER_3D_KEY:-surface_carrier}"
SURFACE_FILTER_3D_SCALE="${SURFACE_FILTER_3D_SCALE:-1.4142135623730951}"
SURFACE_FILTER_3D_MIN="${SURFACE_FILTER_3D_MIN:-0.0}"
LAYER_FREQUENCY_MASK_PAYLOAD="${LAYER_FREQUENCY_MASK_PAYLOAD:-}"
LAYER_FREQUENCY_NON_SURFACE_KEY="${LAYER_FREQUENCY_NON_SURFACE_KEY:-non_surface_active}"
LAYER_FREQUENCY_SURFACE_KEY="${LAYER_FREQUENCY_SURFACE_KEY:-surface_carrier}"
LAYER_FREQUENCY_DYNAMIC_ROOTS="${LAYER_FREQUENCY_DYNAMIC_ROOTS:-0}"
LAYER_FREQUENCY_SURFACE_TARGET="${LAYER_FREQUENCY_SURFACE_TARGET:-gt}"
LAMBDA_NON_SURFACE_HF="${LAMBDA_NON_SURFACE_HF:-0.0}"
LAMBDA_NON_SURFACE_RGB_ENERGY="${LAMBDA_NON_SURFACE_RGB_ENERGY:-0.0}"
LAMBDA_NON_SURFACE_ALPHA_HF="${LAMBDA_NON_SURFACE_ALPHA_HF:-0.0}"
LAMBDA_NON_SURFACE_ALPHA_MASS="${LAMBDA_NON_SURFACE_ALPHA_MASS:-0.0}"
LAMBDA_SURFACE_HF_CLOSURE="${LAMBDA_SURFACE_HF_CLOSURE:-0.0}"
SURFACE_HF_UPDATE_SCALE="${SURFACE_HF_UPDATE_SCALE:-1.0}"
LAYER_FREQUENCY_FROM_ITER="${LAYER_FREQUENCY_FROM_ITER:-0}"
LAYER_FREQUENCY_UNTIL_ITER="${LAYER_FREQUENCY_UNTIL_ITER:-0}"
LAYER_FREQUENCY_LOG_INTERVAL="${LAYER_FREQUENCY_LOG_INTERVAL:-100}"
SURFACE_MIGRATION_PAYLOAD="${SURFACE_MIGRATION_PAYLOAD:-}"
SURFACE_MIGRATION_MASK_KEY="${SURFACE_MIGRATION_MASK_KEY:-near_surface_uncertain}"
SURFACE_MIGRATION_ANCHOR_SOURCE_KEY="${SURFACE_MIGRATION_ANCHOR_SOURCE_KEY:-surface_carrier}"
SURFACE_MIGRATION_NORMAL_KEY="${SURFACE_MIGRATION_NORMAL_KEY:-anchor_normal}"
SURFACE_MIGRATION_ANCHOR_KEY="${SURFACE_MIGRATION_ANCHOR_KEY:-anchor_xyz}"
SURFACE_MIGRATION_TARGET_NORMAL_COORD="${SURFACE_MIGRATION_TARGET_NORMAL_COORD:-0.0}"
LAMBDA_SURFACE_MIGRATION_NORMAL="${LAMBDA_SURFACE_MIGRATION_NORMAL:-0.0}"
LAMBDA_SURFACE_MIGRATION_TANGENT="${LAMBDA_SURFACE_MIGRATION_TANGENT:-0.0}"
LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN="${LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN:-0.0}"
LAMBDA_SURFACE_MIGRATION_THIN="${LAMBDA_SURFACE_MIGRATION_THIN:-0.0}"
SURFACE_MIGRATION_THIN_TARGET_RATIO="${SURFACE_MIGRATION_THIN_TARGET_RATIO:-0.25}"
SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA="${SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA:-0.0}"
SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA="${SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA:-0.0}"
SURFACE_MIGRATION_FROM_ITER="${SURFACE_MIGRATION_FROM_ITER:-0}"
SURFACE_MIGRATION_UNTIL_ITER="${SURFACE_MIGRATION_UNTIL_ITER:-0}"
SURFACE_MIGRATION_LOG_INTERVAL="${SURFACE_MIGRATION_LOG_INTERVAL:-100}"
PRIOR_ONLY_EDGE_FINETUNE="${PRIOR_ONLY_EDGE_FINETUNE:-0}"
DENSIFY_FROM_ITER="${DENSIFY_FROM_ITER:-500}"
DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER:-15000}"
DENSIFICATION_INTERVAL="${DENSIFICATION_INTERVAL:-100}"
DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.0002}"
OPACITY_RESET_INTERVAL="${OPACITY_RESET_INTERVAL:-3000}"
OPACITY_REG="${OPACITY_REG:-0.0}"
SCALE_REG="${SCALE_REG:-0.0}"
MIN_SCALE_REG="${MIN_SCALE_REG:-0.0}"
LAMBDA_DISTORTION="${LAMBDA_DISTORTION:-${DEFAULT_LAMBDA_DISTORTION}}"
LAMBDA_DEPTH_NORMAL="${LAMBDA_DEPTH_NORMAL:-${DEFAULT_LAMBDA_DEPTH_NORMAL}}"
LAMBDA_SMOOTHNESS="${LAMBDA_SMOOTHNESS:-${DEFAULT_LAMBDA_SMOOTHNESS}}"
LAMBDA_EXTENT="${LAMBDA_EXTENT:-${DEFAULT_LAMBDA_EXTENT}}"
LAMBDA_OPACITY_FIELD="${LAMBDA_OPACITY_FIELD:-${DEFAULT_LAMBDA_OPACITY_FIELD}}"
DISTORTION_FROM_ITER="${DISTORTION_FROM_ITER:-${DEFAULT_DISTORTION_FROM_ITER}}"
DEPTH_NORMAL_FROM_ITER="${DEPTH_NORMAL_FROM_ITER:-${DEFAULT_DEPTH_NORMAL_FROM_ITER}}"
SOF_REG_LOG_INTERVAL="${SOF_REG_LOG_INTERVAL:-100}"
SURFACE_THIN_MESH_PATH="${SURFACE_THIN_MESH_PATH:-}"
LAMBDA_SURFACE_THIN="${LAMBDA_SURFACE_THIN:-0.0}"
SURFACE_THIN_FROM_ITER="${SURFACE_THIN_FROM_ITER:-0}"
SURFACE_THIN_UNTIL_ITER="${SURFACE_THIN_UNTIL_ITER:-0}"
SURFACE_THIN_SAMPLE_COUNT="${SURFACE_THIN_SAMPLE_COUNT:-500000}"
SURFACE_THIN_UPDATE_INTERVAL="${SURFACE_THIN_UPDATE_INTERVAL:-500}"
SURFACE_THIN_GAUSSIAN_SAMPLE_COUNT="${SURFACE_THIN_GAUSSIAN_SAMPLE_COUNT:-65536}"
SURFACE_THIN_OFFSET_MARGIN="${SURFACE_THIN_OFFSET_MARGIN:-0.02}"
SURFACE_THIN_NORMAL_SCALE_TARGET="${SURFACE_THIN_NORMAL_SCALE_TARGET:-0.0}"
SURFACE_THIN_NORMAL_SCALE_WEIGHT="${SURFACE_THIN_NORMAL_SCALE_WEIGHT:-1.0}"

if [[ "${DISABLE_PRIOR_USABLE_MASKS}" == "1" ]]; then
  PRIOR_MASK_SUBDIR=""
fi

CUDA_HOME="${CUDA_HOME:-/usr/local/cuda}"
export CUDA_HOME
export PATH="${CUDA_HOME}/bin:${PATH}"
export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH:-}"
export PYTHONUNBUFFERED=1

if [[ ! "${OMP_NUM_THREADS:-}" =~ ^[0-9]+$ ]]; then
  export OMP_NUM_THREADS=1
fi

if [[ -n "${CONDA_ENV_NAME}" ]]; then
  source /root/miniconda3/etc/profile.d/conda.sh
  conda activate "${CONDA_ENV_NAME}"
fi

MIP_PYTHONPATH="${MIPSPLATTING_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"

validate_prepared_priors() {
  (
    cd "${MIPSPLATTING_ROOT}"
    export PYTHONPATH="${MIP_PYTHONPATH}"
    VALIDATE_ARGS=(
      "${PYTHON_BIN}" -m hybrid_sdfgs.tools.validate_prepared_sr_priors
      --output_root "${PREPARED_PRIOR_ROOT}"
      --prior_subdir "${PRIOR_SUBDIR}"
    )
    if [[ -n "${PRIOR_MASK_SUBDIR}" ]]; then
      VALIDATE_ARGS+=(--mask_subdir "${PRIOR_MASK_SUBDIR}")
    fi
    "${VALIDATE_ARGS[@]}"
  )
}

validate_prepared_prior_reference_dir() {
  (
    export PREPARED_PRIOR_MANIFEST="${PREPARED_PRIOR_MANIFEST}"
    export EXPECTED_REFERENCE_DIR="${PREPARED_PRIOR_EXPECTED_REFERENCE_DIR}"
    "${PYTHON_BIN}" - <<'PY'
import json
import os
from pathlib import Path

manifest_path = Path(os.environ["PREPARED_PRIOR_MANIFEST"]).resolve()
expected_reference = Path(os.environ["EXPECTED_REFERENCE_DIR"]).resolve()
if not manifest_path.is_file():
    raise SystemExit(1)
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
reference_dir = manifest.get("reference_dir")
if not reference_dir:
    print(f"[prepared-prior-ref] manifest missing reference_dir: {manifest_path}", flush=True)
    raise SystemExit(1)
actual_reference = Path(reference_dir).resolve()
print(
    f"[prepared-prior-ref] manifest reference_dir={actual_reference} expected={expected_reference}",
    flush=True,
)
if actual_reference != expected_reference:
    raise SystemExit(1)
PY
  )
}

validate_merged_sof_rasterizer() {
  (
    cd "${MIPSPLATTING_ROOT}"
    export PYTHONPATH="${MIP_PYTHONPATH}"
    "${PYTHON_BIN}" - <<'PY'
from diff_gaussian_rasterization import GaussianRasterizationSettings, supports_merged_features
try:
    from diff_gaussian_rasterization import ExtendedSettings
except ImportError:
    ExtendedSettings = None

fields = set(getattr(GaussianRasterizationSettings, "_fields", ()))
required = {"inv_viewprojmatrix", "settings", "debug_data"}
ok = (
    ExtendedSettings is not None
    and bool(supports_merged_features())
    and required.issubset(fields)
)
if not ok:
    print("[merged-check] merged SOF rasterizer is unavailable in the active diff_gaussian_rasterization build.", flush=True)
    print(f"[merged-check] ExtendedSettings={'yes' if ExtendedSettings is not None else 'no'} supports_merged_features={bool(supports_merged_features())} fields_ok={required.issubset(fields)}", flush=True)
    raise SystemExit(1)
print("[merged-check] merged SOF rasterizer is available.", flush=True)
PY
  )
}

validate_vanilla_sof_rasterizer() {
  (
    cd "${MIPSPLATTING_ROOT}"
    export PYTHONPATH="${MIP_PYTHONPATH}"
    "${PYTHON_BIN}" - <<'PY'
try:
    import diff_gaussian_rasterization_sof_vanilla as vanilla
except ImportError as exc:
    print(f"[vanilla-check] vanilla SOF rasterizer is unavailable: {exc}", flush=True)
    raise SystemExit(1)

fields = set(getattr(vanilla.GaussianRasterizationSettings, "_fields", ()))
required = {"inv_viewprojmatrix", "settings", "debug_data"}
ok = required.issubset(fields)
if not ok:
    print("[vanilla-check] vanilla SOF rasterizer settings are incomplete.", flush=True)
    print(f"[vanilla-check] fields_ok={required.issubset(fields)}", flush=True)
    raise SystemExit(1)
print("[vanilla-check] vanilla SOF rasterizer is available.", flush=True)
PY
  )
}

mkdir -p "${ALIAS_ROOT}" "${RUN_ROOT}" "${PRIOR_MODEL_DIR}"

for path in "${SCENE_ROOT}" "${TARGET_IMAGES_DIR}" "${MIPSPLATTING_ROOT}" "${TRAIN_IMAGES_DIR}"; do
  if [[ ! -e "${path}" ]]; then
    echo "[mipsplatting-stablesr-prior] required path not found: ${path}" >&2
    exit 1
  fi
done

if [[ ! -d "${SCENE_ROOT}/sparse/0" ]]; then
  echo "[mipsplatting-stablesr-prior] missing sparse/0: ${SCENE_ROOT}/sparse/0" >&2
  exit 1
fi

if [[ ! -d "${LR_REFERENCE_IMAGES_DIR}" ]]; then
  echo "[mipsplatting-stablesr-prior] ${LR_REFERENCE_IMAGES_SUBDIR} missing, generating from ${TARGET_IMAGES_SUBDIR}"
  (
    cd "${SOF_ROOT}"
    "${PYTHON_BIN}" scripts/generate_downsampled_images.py \
      --source_dir "${TARGET_IMAGES_DIR}" \
      --output_dir "${LR_REFERENCE_IMAGES_DIR}" \
      --scale 4 \
      --resize_filter bicubic
  )
fi

BASELINE_RESULTS_JSON="${BASELINE_MODEL_DIR}/results_psnr_ssim.json"
BASELINE_CHECKPOINT_PATH="${BASELINE_MODEL_DIR}/chkpnt${BASELINE_ITERATION}.pth"
PRIOR_RESULTS_JSON="${PRIOR_MODEL_DIR}/results_psnr_ssim.json"
PRIOR_CHECKPOINT_PATH="${PRIOR_MODEL_DIR}/chkpnt${ITERATIONS}.pth"
PREPARED_PRIOR_MANIFEST="${PREPARED_PRIOR_ROOT}/manifest.json"
PREPARED_PRIOR_IMAGE_DIR="${PREPARED_PRIOR_ROOT}/${PRIOR_SUBDIR}"
PREPARED_PRIOR_MASK_DIR=""
if [[ -n "${PRIOR_MASK_SUBDIR}" ]]; then
  PREPARED_PRIOR_MASK_DIR="${PREPARED_PRIOR_ROOT}/${PRIOR_MASK_SUBDIR}"
fi

if [[ "${PRIOR_LOSS_MODE}" == "masked_residual_hf_v1" ]]; then
  if [[ -z "${PRIOR_ANCHOR_DIR}" ]]; then
    PRIOR_ANCHOR_DIR="${PREPARED_PRIOR_ROOT}/aligned_references"
  fi
  if [[ "${PRIOR_RESIDUAL_USE_MASKS}" != "0" ]]; then
    if [[ -z "${PRIOR_SOFT_MASK_DIR}" && -n "${PREPARED_PRIOR_MASK_DIR}" ]]; then
      PRIOR_SOFT_MASK_DIR="${PREPARED_PRIOR_MASK_DIR}"
    fi
    if [[ -z "${PRIOR_HARD_MASK_DIR}" && -n "${PREPARED_PRIOR_MASK_DIR}" ]]; then
      PRIOR_HARD_MASK_DIR="${PREPARED_PRIOR_MASK_DIR}"
    fi
  else
    PRIOR_SOFT_MASK_DIR=""
    PRIOR_HARD_MASK_DIR=""
  fi
fi

echo "[mipsplatting-stablesr-prior] scene              : ${SCENE_NAME}"
echo "[mipsplatting-stablesr-prior] scene root         : ${SCENE_ROOT}"
echo "[mipsplatting-stablesr-prior] LR ref images      : ${LR_REFERENCE_IMAGES_DIR}"
echo "[mipsplatting-stablesr-prior] train images       : ${TRAIN_IMAGES_DIR}"
echo "[mipsplatting-stablesr-prior] target images      : ${TARGET_IMAGES_DIR}"
echo "[mipsplatting-stablesr-prior] prior profile      : ${PRIOR_STRENGTH_PROFILE}"
echo "[mipsplatting-stablesr-prior] SOF param profile  : ${SOF_PARAM_PROFILE}"
echo "[mipsplatting-stablesr-prior] input SR priors     : ${PRIOR_DIR}"
echo "[mipsplatting-stablesr-prior] prior source dir   : ${PRIOR_SUBDIR}"
echo "[mipsplatting-stablesr-prior] prepared rebuild   : ${ALLOW_PREPARED_PRIOR_REBUILD} (force=${FORCE_PREPARE_PRIORS})"
echo "[mipsplatting-stablesr-prior] prior loss mode    : ${PRIOR_LOSS_MODE}"
if [[ "${DISABLE_PRIOR_USABLE_MASKS}" == "1" ]]; then
  echo "[mipsplatting-stablesr-prior] prior image masks  : disabled (consistency-only gating)"
else
  echo "[mipsplatting-stablesr-prior] prior mask dir     : ${PRIOR_MASK_SUBDIR}"
fi
if [[ "${PRIOR_LOSS_MODE}" == "masked_residual_hf_v1" ]]; then
  echo "[mipsplatting-stablesr-prior] residual anchor   : ${PRIOR_ANCHOR_DIR:-<missing>}"
  if [[ "${PRIOR_RESIDUAL_USE_MASKS}" == "0" ]]; then
    echo "[mipsplatting-stablesr-prior] residual masks    : disabled (full-frame residual, anchor-only)"
  else
    echo "[mipsplatting-stablesr-prior] residual soft mask: ${PRIOR_SOFT_MASK_DIR:-<missing>} power=${PRIOR_SOFT_MASK_POWER}"
    echo "[mipsplatting-stablesr-prior] residual hard mask: ${PRIOR_HARD_MASK_DIR:-<missing>} threshold=${PRIOR_HARD_MASK_THRESHOLD} min_pixels=${PRIOR_MASKED_MIN_PIXELS}"
  fi
  echo "[mipsplatting-stablesr-prior] residual view prob: ${PRIOR_VIEW_SAMPLE_PROB}"
  echo "[mipsplatting-stablesr-prior] residual anneal   : ${PRIOR_GUIDANCE_DECAY_FROM_ITER}->${PRIOR_GUIDANCE_DECAY_UNTIL_ITER} final_scale=${PRIOR_GUIDANCE_FINAL_SCALE}"
  echo "[mipsplatting-stablesr-prior] residual xyz nudge: lr=${PRIOR_DIRECT_XYZ_NUDGE_LR} max_step=${PRIOR_DIRECT_XYZ_NUDGE_MAX_STEP}"
  if [[ "${PRIOR_RESIDUAL_MASKED_UPDATE}" == "1" ]]; then
    echo "[mipsplatting-stablesr-prior] residual GS route : masked update through prior-loss gaussian mask"
  fi
  if [[ "${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL}" == "1" ]]; then
    echo "[mipsplatting-stablesr-prior] residual densify : masked prior loss contributes viewspace densify signal scale=${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE}"
  fi
fi
if [[ -n "${PRIOR_SUPERVISION_IMAGES_SUBDIR}" ]]; then
  echo "[mipsplatting-stablesr-prior] HR prior camera    : ${SCENE_ROOT}/${PRIOR_SUPERVISION_IMAGES_SUBDIR} @ r=${PRIOR_SUPERVISION_RESOLUTION}"
else
  echo "[mipsplatting-stablesr-prior] HR prior camera    : disabled"
fi
echo "[mipsplatting-stablesr-prior] mipsplatting dir   : ${MIPSPLATTING_ROOT}"
echo "[mipsplatting-stablesr-prior] baseline model dir : ${BASELINE_MODEL_DIR}"
echo "[mipsplatting-stablesr-prior] prepared prior dir : ${PREPARED_PRIOR_ROOT}"
echo "[mipsplatting-stablesr-prior] prepared ref grid  : ${PREPARED_PRIOR_EXPECTED_REFERENCE_DIR}"
echo "[mipsplatting-stablesr-prior] prior model dir    : ${PRIOR_MODEL_DIR}"
echo "[mipsplatting-stablesr-prior] baseline iter      : ${BASELINE_ITERATION}"
echo "[mipsplatting-stablesr-prior] iterations         : ${ITERATIONS}"
echo "[mipsplatting-stablesr-prior] train resolution   : ${TRAIN_RESOLUTION}"
echo "[mipsplatting-stablesr-prior] eval resolution    : ${RENDER_RESOLUTION}"
echo "[mipsplatting-stablesr-prior] save checkpoint    : ${SAVE_CHECKPOINT_AFTER}"
echo "[mipsplatting-stablesr-prior] merged rasterizer  : use=${USE_MERGED_SOF_RASTERIZER} require_aux=${REQUIRE_MERGED_SOF_AUX}"
echo "[mipsplatting-stablesr-prior] vanilla rasterizer : use=${USE_VANILLA_SOF_RASTERIZER}"
if [[ "${LAMBDA_PRIOR_LOCAL}" != "0" && "${LAMBDA_PRIOR_LOCAL}" != "0.0" ]]; then
  echo "[mipsplatting-stablesr-prior] SOF prior local    : ${PRIOR_LOCAL_DIR} (mask=${PRIOR_LOCAL_MASK_DIR}, lambda=${LAMBDA_PRIOR_LOCAL}, from=${PRIOR_LOCAL_FROM_ITER})"
fi
if [[ "${LAMBDA_PRIOR_EDGE}" != "0" && "${LAMBDA_PRIOR_EDGE}" != "0.0" ]]; then
  echo "[mipsplatting-stablesr-prior] SOF prior edge     : ${PRIOR_EDGE_DIR} (mask=${PRIOR_EDGE_MASK_DIR}, lambda=${LAMBDA_PRIOR_EDGE}, mode=${PRIOR_EDGE_LOSS_MODE}, from=${PRIOR_EDGE_FROM_ITER}, update_scale=${PRIOR_EDGE_UPDATE_SCALE})"
fi
if [[ "${PRIOR_HF_SEED_ENABLE}" == "1" ]]; then
  echo "[mipsplatting-stablesr-prior] HF seed carrier    : from=${PRIOR_HF_SEED_FROM_ITER} until=${PRIOR_HF_SEED_UNTIL_ITER} interval=${PRIOR_HF_SEED_INTERVAL} per_iter=${PRIOR_HF_SEED_MAX_PER_ITER} total=${PRIOR_HF_SEED_MAX_TOTAL} scale=${PRIOR_HF_SEED_SCALE_MULTIPLIER} mode=${PRIOR_HF_SEED_SCALE_MODE} shape=${PRIOR_HF_SEED_SHAPE_MODE}[long=${PRIOR_HF_SEED_SHAPE_LONG_RATIO},short=${PRIOR_HF_SEED_SHAPE_SHORT_RATIO},normal=${PRIOR_HF_SEED_SHAPE_NORMAL_RATIO},conf_pow=${PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER}] px=[${PRIOR_HF_SEED_MIN_PIXEL_RADIUS},${PRIOR_HF_SEED_MAX_PIXEL_RADIUS}] provider_cap=${PRIOR_HF_SEED_MAX_PROVIDER_RATIO} large_diag=${PRIOR_HF_SEED_DIAG_LARGE_SCALE} clamp=${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE}:${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS}/${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY} opacity=${PRIOR_HF_SEED_OPACITY} color_gain=${PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN}"
  if [[ "${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT}" != "0" && "${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT}" != "0.0" ]]; then
    echo "[mipsplatting-stablesr-prior] HF seed imprint   : weight=${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT} gain=${PRIOR_HF_SEED_RECENT_IMPRINT_GAIN} iters=${PRIOR_HF_SEED_RECENT_IMPRINT_ITERS}"
  fi
  if [[ "${PRIOR_HF_LOWFREQ_CLEANUP_ENABLE}" == "1" ]]; then
    echo "[mipsplatting-stablesr-prior] HF lowfreq cleanup: from=${PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER} until=${PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER} every=${PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL} stale=${PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS} opacity>=${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN} scale=[${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN},${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX}] anis<=${PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX} decay=${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY} prune_below=${PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW} prune_cap=${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION}/${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT}"
  fi
fi
if [[ "${PRIOR_BUBBLE_CLEANUP_ENABLE}" == "1" ]]; then
  echo "[mipsplatting-stablesr-prior] prior bubble clean : from=${PRIOR_BUBBLE_CLEANUP_FROM_ITER} until=${PRIOR_BUBBLE_CLEANUP_UNTIL_ITER} every=${PRIOR_BUBBLE_CLEANUP_INTERVAL} opacity>=${PRIOR_BUBBLE_CLEANUP_OPACITY_MIN} max_axis=[${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN},${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX}] anis<=${PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX} min_gen=${PRIOR_BUBBLE_CLEANUP_MIN_GENERATION} hf=${LAMBDA_PRIOR_BUBBLE_HF} rgb=${LAMBDA_PRIOR_BUBBLE_RGB_ENERGY} alpha_hf=${LAMBDA_PRIOR_BUBBLE_ALPHA_HF} alpha=${LAMBDA_PRIOR_BUBBLE_ALPHA_MASS} post_decay=${PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY}"
fi
if [[ "${PRIOR_VIEW_CURRICULUM_ENABLE}" == "1" ]]; then
  echo "[mipsplatting-stablesr-prior] view curriculum    : start=${PRIOR_VIEW_CURRICULUM_START_ITER} primary=${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS} neighbor=${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS} radius=${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS} max_views=${PRIOR_VIEW_CURRICULUM_MAX_VIEWS} settle=${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS} primary_hfe=${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT}x${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN} band=${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT}@${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL} residual=${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT} patch=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT}@top${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION}/min${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE} gain=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN} hp=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL} lf_guard=${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT}@${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL} boot=${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS}"
fi
if [[ "${LAMBDA_SURFACE_ROUTE_CONSENSUS}" != "0" && "${LAMBDA_SURFACE_ROUTE_CONSENSUS}" != "0.0" ]]; then
  echo "[mipsplatting-stablesr-prior] surface route loss : ${SURFACE_ROUTE_CONSENSUS_ROOT} (lambda=${LAMBDA_SURFACE_ROUTE_CONSENSUS}, from=${SURFACE_ROUTE_CONSENSUS_FROM_ITER}, min_pixels=${SURFACE_ROUTE_CONSENSUS_MIN_PIXELS}, view_sample_prob=${SURFACE_ROUTE_VIEW_SAMPLE_PROB}, surface_only=${SURFACE_ROUTE_SURFACE_ONLY})"
fi
if [[ "${OPTIMIZE_SOURCE_TAG}" != "all" || -n "${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD}" || "${PRIOR_ONLY_EDGE_FINETUNE}" == "1" ]]; then
  echo "[mipsplatting-stablesr-prior] SOF update filter  : source=${OPTIMIZE_SOURCE_TAG} mask=${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD:-<none>} key=${OPTIMIZE_GAUSSIAN_MASK_KEY} prior_only=${PRIOR_ONLY_EDGE_FINETUNE}"
fi
if [[ -n "${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD}" ]]; then
  echo "[mipsplatting-stablesr-prior] SOF prior-only mask: ${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD} key=${PRIOR_LOSS_GAUSSIAN_MASK_KEY} dynamic_roots=${PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS}"
fi
if [[ "${SURFACE_NORMAL_LOCK}" == "1" ]]; then
  echo "[mipsplatting-stablesr-prior] surface normal lock: payload=${SURFACE_NORMAL_LOCK_PAYLOAD:-${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD:-<infer>}} normal_key=${SURFACE_NORMAL_LOCK_NORMAL_KEY} anchor_key=${SURFACE_NORMAL_LOCK_ANCHOR_KEY} dynamic_roots=${SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS}"
fi
if [[ "${SURFACE_FILTER_3D}" == "1" ]]; then
  echo "[mipsplatting-stablesr-prior] surface 3D filter : payload=${SURFACE_FILTER_3D_PAYLOAD:-<infer>} key=${SURFACE_FILTER_3D_KEY} mode=global_plus_surface_extra scale=${SURFACE_FILTER_3D_SCALE} min=${SURFACE_FILTER_3D_MIN}"
fi
if [[ "${LAMBDA_NON_SURFACE_HF}" != "0" && "${LAMBDA_NON_SURFACE_HF}" != "0.0" ]] || [[ "${LAMBDA_NON_SURFACE_RGB_ENERGY}" != "0" && "${LAMBDA_NON_SURFACE_RGB_ENERGY}" != "0.0" ]] || [[ "${LAMBDA_NON_SURFACE_ALPHA_HF}" != "0" && "${LAMBDA_NON_SURFACE_ALPHA_HF}" != "0.0" ]] || [[ "${LAMBDA_NON_SURFACE_ALPHA_MASS}" != "0" && "${LAMBDA_NON_SURFACE_ALPHA_MASS}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_HF_CLOSURE}" != "0" && "${LAMBDA_SURFACE_HF_CLOSURE}" != "0.0" ]]; then
  echo "[mipsplatting-stablesr-prior] layer freq reg    : payload=${LAYER_FREQUENCY_MASK_PAYLOAD:-${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD:-<none>}} non_surface=${LAYER_FREQUENCY_NON_SURFACE_KEY} surface=${LAYER_FREQUENCY_SURFACE_KEY} target=${LAYER_FREQUENCY_SURFACE_TARGET} ns_hf=${LAMBDA_NON_SURFACE_HF} ns_rgb=${LAMBDA_NON_SURFACE_RGB_ENERGY} ns_alpha_hf=${LAMBDA_NON_SURFACE_ALPHA_HF} ns_alpha=${LAMBDA_NON_SURFACE_ALPHA_MASS} surf_hf=${LAMBDA_SURFACE_HF_CLOSURE} surf_scale=${SURFACE_HF_UPDATE_SCALE} from=${LAYER_FREQUENCY_FROM_ITER} until=${LAYER_FREQUENCY_UNTIL_ITER} dynamic_roots=${LAYER_FREQUENCY_DYNAMIC_ROOTS}"
fi
if [[ "${LAMBDA_SURFACE_MIGRATION_NORMAL}" != "0" && "${LAMBDA_SURFACE_MIGRATION_NORMAL}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_MIGRATION_TANGENT}" != "0" && "${LAMBDA_SURFACE_MIGRATION_TANGENT}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN}" != "0" && "${LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_MIGRATION_THIN}" != "0" && "${LAMBDA_SURFACE_MIGRATION_THIN}" != "0.0" ]] || [[ "${SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA}" != "0" && "${SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA}" != "0.0" ]] || [[ "${SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA}" != "0" && "${SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA}" != "0.0" ]]; then
  echo "[mipsplatting-stablesr-prior] surface migration: payload=${SURFACE_MIGRATION_PAYLOAD:-${LAYER_FREQUENCY_MASK_PAYLOAD:-${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD:-<none>}}} mask=${SURFACE_MIGRATION_MASK_KEY} anchor_source=${SURFACE_MIGRATION_ANCHOR_SOURCE_KEY} target_n=${SURFACE_MIGRATION_TARGET_NORMAL_COORD} normal=${LAMBDA_SURFACE_MIGRATION_NORMAL} tangent=${LAMBDA_SURFACE_MIGRATION_TANGENT} align=${LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN} thin=${LAMBDA_SURFACE_MIGRATION_THIN} post_n=${SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA} post_t=${SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA} from=${SURFACE_MIGRATION_FROM_ITER} until=${SURFACE_MIGRATION_UNTIL_ITER}"
fi
echo "[mipsplatting-stablesr-prior] densify            : from=${DENSIFY_FROM_ITER} until=${DENSIFY_UNTIL_ITER} interval=${DENSIFICATION_INTERVAL} grad=${DENSIFY_GRAD_THRESHOLD}"
if [[ "${OPACITY_REG}" != "0" && "${OPACITY_REG}" != "0.0" ]] || [[ "${SCALE_REG}" != "0" && "${SCALE_REG}" != "0.0" ]] || [[ "${MIN_SCALE_REG}" != "0" && "${MIN_SCALE_REG}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_THIN}" != "0" && "${LAMBDA_SURFACE_THIN}" != "0.0" ]] || [[ "${LAMBDA_DISTORTION}" != "0" && "${LAMBDA_DISTORTION}" != "0.0" ]] || [[ "${LAMBDA_DEPTH_NORMAL}" != "0" && "${LAMBDA_DEPTH_NORMAL}" != "0.0" ]] || [[ "${LAMBDA_SMOOTHNESS}" != "0" && "${LAMBDA_SMOOTHNESS}" != "0.0" ]] || [[ "${LAMBDA_EXTENT}" != "0" && "${LAMBDA_EXTENT}" != "0.0" ]] || [[ "${LAMBDA_OPACITY_FIELD}" != "0" && "${LAMBDA_OPACITY_FIELD}" != "0.0" ]]; then
  echo "[mipsplatting-stablesr-prior] SOF portable reg  : opacity=${OPACITY_REG} scale=${SCALE_REG} min_scale=${MIN_SCALE_REG} dist=${LAMBDA_DISTORTION} depth_norm=${LAMBDA_DEPTH_NORMAL} smooth=${LAMBDA_SMOOTHNESS} extent=${LAMBDA_EXTENT} opacity_field=${LAMBDA_OPACITY_FIELD} surface_thin=${LAMBDA_SURFACE_THIN}"
fi

if [[ ! -f "${BASELINE_CHECKPOINT_PATH}" ]]; then
  if [[ -f "${START_CHECKPOINT}" ]]; then
    echo "[mipsplatting-stablesr-prior] baseline checkpoint missing, reusing explicit start checkpoint: ${START_CHECKPOINT}"
    echo
    echo "[1/5] reuse explicit start checkpoint"
  elif [[ "${RUN_BASELINE_IF_MISSING}" != "1" ]]; then
    echo "[mipsplatting-stablesr-prior] baseline checkpoint missing: ${BASELINE_CHECKPOINT_PATH}" >&2
    exit 1
  else
    echo
    echo "[1/5] train plain mip-splatting baseline (missing)"
    (
      cd "${SOF_ROOT}"
      CUDA_HOME="${CUDA_HOME}" \
      MIPSPLATTING_ROOT="${MIPSPLATTING_ROOT}" \
      SCENE_NAME="${SCENE_NAME}" \
      SCENE_ROOT="${SCENE_ROOT}" \
      SOURCE_IMAGES_SUBDIR="${LR_REFERENCE_IMAGES_SUBDIR}" \
      TARGET_IMAGES_SUBDIR="${TARGET_IMAGES_SUBDIR}" \
      ALIAS_ROOT="${ALIAS_ROOT}" \
      MODEL_DIR="${BASELINE_MODEL_DIR}" \
      ITERATIONS="${BASELINE_ITERATION}" \
      RENDER_RESOLUTION="${RENDER_RESOLUTION}" \
      PYTHON_BIN="${PYTHON_BIN}" \
      OMP_NUM_THREADS="${OMP_NUM_THREADS}" \
      bash scripts/run_mipsplatting_x8to2_baseline_scene.sh
    )
  fi
else
  echo
  echo "[1/5] reuse existing baseline"
fi

echo
echo "[2/5] validate prepared SR priors"
PREPARED_PRIOR_READY=0
PREPARED_PRIOR_INVALID_REASON=""
if [[ "${FORCE_PREPARE_PRIORS}" == "1" ]]; then
  PREPARED_PRIOR_INVALID_REASON="forced rebuild requested"
elif [[ ! -f "${PREPARED_PRIOR_MANIFEST}" ]]; then
  PREPARED_PRIOR_INVALID_REASON="missing manifest: ${PREPARED_PRIOR_MANIFEST}"
elif [[ ! -d "${PREPARED_PRIOR_IMAGE_DIR}" ]]; then
  PREPARED_PRIOR_INVALID_REASON="missing prior image dir: ${PREPARED_PRIOR_IMAGE_DIR}"
elif [[ -n "${PRIOR_MASK_SUBDIR}" && ! -d "${PREPARED_PRIOR_MASK_DIR}" ]]; then
  PREPARED_PRIOR_INVALID_REASON="missing prior mask dir: ${PREPARED_PRIOR_MASK_DIR}"
elif ! PREPARED_PRIOR_VALIDATE_OUTPUT="$(validate_prepared_priors 2>&1)"; then
  PREPARED_PRIOR_INVALID_REASON="validation failed: ${PREPARED_PRIOR_VALIDATE_OUTPUT}"
elif ! validate_prepared_prior_reference_dir; then
  PREPARED_PRIOR_INVALID_REASON="manifest reference_dir does not match expected reference: ${PREPARED_PRIOR_EXPECTED_REFERENCE_DIR}"
else
  PREPARED_PRIOR_READY=1
  echo "[mipsplatting-stablesr-prior] prepared priors valid, reusing: ${PREPARED_PRIOR_ROOT}"
fi
if [[ "${PREPARED_PRIOR_READY}" != "1" ]]; then
  echo "[mipsplatting-stablesr-prior] prepared priors not ready: ${PREPARED_PRIOR_INVALID_REASON}" >&2
  if [[ "${ALLOW_PREPARED_PRIOR_REBUILD}" != "1" ]]; then
    echo "[mipsplatting-stablesr-prior] refusing to rebuild prepared priors from PRIOR_DIR=${PRIOR_DIR}" >&2
    echo "[mipsplatting-stablesr-prior] upload or repair PREPARED_PRIOR_ROOT, or explicitly set ALLOW_PREPARED_PRIOR_REBUILD=1 FORCE_PREPARE_PRIORS=1." >&2
    exit 1
  fi
  if [[ ! -e "${PRIOR_DIR}" ]]; then
    echo "[mipsplatting-stablesr-prior] prior dir required to rebuild prepared priors, but not found: ${PRIOR_DIR}" >&2
    exit 1
  fi
  if [[ "${FORCE_PREPARE_PRIORS}" != "1" && -f "${PREPARED_PRIOR_MANIFEST}" ]]; then
    echo "[mipsplatting-stablesr-prior] prepared priors invalid or incomplete, rebuilding: ${PREPARED_PRIOR_ROOT}"
  fi
  (
    cd "${MIPSPLATTING_ROOT}"
    export PYTHONPATH="${MIP_PYTHONPATH}"
    PREPARE_ARGS=(
      "${PYTHON_BIN}" -m hybrid_sdfgs.tools.prepare_existing_sr_priors
      --prior_dir "${PRIOR_DIR}"
      --reference_dir "${PREPARED_PRIOR_EXPECTED_REFERENCE_DIR}"
      --output_root "${PREPARED_PRIOR_ROOT}"
      --mask_threshold "${MASK_THRESHOLD}"
      --mask_mode "${MASK_MODE}"
      --discrepancy_floor "${DISCREPANCY_FLOOR}"
      --copy_raw_priors
      --save_fused_priors
    )
    if [[ "${DISABLE_PRIOR_USABLE_MASKS}" == "1" ]]; then
      PREPARE_ARGS+=(--disable_usable_masks)
    fi
    "${PREPARE_ARGS[@]}"
  )
  if ! validate_prepared_prior_reference_dir; then
    echo "[mipsplatting-stablesr-prior] rebuilt prepared priors still do not match expected reference dir: ${PREPARED_PRIOR_EXPECTED_REFERENCE_DIR}" >&2
    exit 1
  fi
else
  validate_prepared_prior_reference_dir
fi

if [[ "${PRIOR_LOSS_MODE}" == "masked_residual_hf_v1" ]]; then
  if [[ ! -d "${PRIOR_ANCHOR_DIR}" ]]; then
    echo "[mipsplatting-stablesr-prior] masked residual mode missing anchor dir: ${PRIOR_ANCHOR_DIR}" >&2
    exit 1
  fi
  if [[ "${PRIOR_RESIDUAL_USE_MASKS}" != "0" ]]; then
    if [[ ! -d "${PRIOR_SOFT_MASK_DIR}" ]]; then
      echo "[mipsplatting-stablesr-prior] masked residual mode missing soft-mask dir: ${PRIOR_SOFT_MASK_DIR}" >&2
      exit 1
    fi
    if [[ ! -d "${PRIOR_HARD_MASK_DIR}" ]]; then
      echo "[mipsplatting-stablesr-prior] masked residual mode missing hard-mask dir: ${PRIOR_HARD_MASK_DIR}" >&2
      exit 1
    fi
  fi
fi

echo
echo "[3/5] train mip-splatting with StableSR priors"
if [[ "${USE_VANILLA_SOF_RASTERIZER}" == "1" && ( "${USE_MERGED_SOF_RASTERIZER}" == "1" || "${REQUIRE_MERGED_SOF_AUX}" == "1" ) ]]; then
  echo "[mipsplatting-stablesr-prior] vanilla SOF rasterizer cannot be combined with merged SOF rasterizer or require_aux." >&2
  exit 1
fi
if [[ "${USE_VANILLA_SOF_RASTERIZER}" == "1" ]]; then
  validate_vanilla_sof_rasterizer
fi
if [[ "${USE_MERGED_SOF_RASTERIZER}" == "1" || "${REQUIRE_MERGED_SOF_AUX}" == "1" ]]; then
  validate_merged_sof_rasterizer
fi
if [[ "${FORCE_RERUN}" == "1" || ! -f "${PRIOR_CHECKPOINT_PATH}" ]]; then
  PRIOR_TRAIN_ARGS=(
    "${PYTHON_BIN}" -m hybrid_sdfgs.train
    -s "${SCENE_ROOT}"
    -i "${TRAIN_IMAGES_SUBDIR}"
    -m "${PRIOR_MODEL_DIR}"
    -r "${TRAIN_RESOLUTION}"
    --eval
    --disable_gui
    --port "${TRAIN_PORT}"
    --iterations "${ITERATIONS}"
    --test_iterations "${ITERATIONS}"
    --save_iterations "${ITERATIONS}"
    --start_checkpoint "${START_CHECKPOINT}"
    --densify_from_iter "${DENSIFY_FROM_ITER}"
    --densify_until_iter "${DENSIFY_UNTIL_ITER}"
    --densification_interval "${DENSIFICATION_INTERVAL}"
    --densify_grad_threshold "${DENSIFY_GRAD_THRESHOLD}"
    --opacity_reset_interval "${OPACITY_RESET_INTERVAL}"
    --external_prior_root "${PREPARED_PRIOR_ROOT}"
    --external_prior_subdir "${PRIOR_SUBDIR}"
    --prior_loss_mode "${PRIOR_LOSS_MODE}"
    --prior_anchor_dir "${PRIOR_ANCHOR_DIR}"
    --prior_soft_mask_dir "${PRIOR_SOFT_MASK_DIR}"
    --prior_hard_mask_dir "${PRIOR_HARD_MASK_DIR}"
    --prior_soft_mask_power "${PRIOR_SOFT_MASK_POWER}"
    --prior_hard_mask_threshold "${PRIOR_HARD_MASK_THRESHOLD}"
    --prior_masked_min_pixels "${PRIOR_MASKED_MIN_PIXELS}"
    --prior_view_sample_prob "${PRIOR_VIEW_SAMPLE_PROB}"
    --prior_direct_xyz_nudge_lr "${PRIOR_DIRECT_XYZ_NUDGE_LR}"
    --prior_direct_xyz_nudge_max_step "${PRIOR_DIRECT_XYZ_NUDGE_MAX_STEP}"
    --prior_l1_weight "${PRIOR_L1_WEIGHT}"
    --prior_hf_weight "${PRIOR_HF_WEIGHT}"
    --prior_mask_floor "${PRIOR_MASK_FLOOR}"
    --prior_consistency_threshold "${PRIOR_CONSISTENCY_THRESHOLD}"
    --prior_min_valid_ratio "${PRIOR_MIN_VALID_RATIO}"
    --prior_delta_clip "${PRIOR_DELTA_CLIP}"
    --prior_supervision_images_subdir "${PRIOR_SUPERVISION_IMAGES_SUBDIR}"
    --prior_supervision_resolution "${PRIOR_SUPERVISION_RESOLUTION}"
    --prior_supervision_cache_size "${PRIOR_SUPERVISION_CACHE_SIZE}"
    --prior_local_dir "${PRIOR_LOCAL_DIR}"
    --prior_local_mask_dir "${PRIOR_LOCAL_MASK_DIR}"
    --lambda_prior_local "${LAMBDA_PRIOR_LOCAL}"
    --prior_local_min_pixels "${PRIOR_LOCAL_MIN_PIXELS}"
    --prior_local_from_iter "${PRIOR_LOCAL_FROM_ITER}"
    --prior_edge_dir "${PRIOR_EDGE_DIR}"
    --prior_edge_mask_dir "${PRIOR_EDGE_MASK_DIR}"
    --lambda_prior_edge "${LAMBDA_PRIOR_EDGE}"
    --prior_edge_loss_mode "${PRIOR_EDGE_LOSS_MODE}"
    --prior_edge_blend_alpha "${PRIOR_EDGE_BLEND_ALPHA}"
    --prior_edge_min_pixels "${PRIOR_EDGE_MIN_PIXELS}"
    --prior_edge_from_iter "${PRIOR_EDGE_FROM_ITER}"
    --prior_edge_touch_min_radius_px "${PRIOR_EDGE_TOUCH_MIN_RADIUS_PX}"
    --prior_edge_touch_radius_scale "${PRIOR_EDGE_TOUCH_RADIUS_SCALE}"
    --prior_edge_touch_max_radius_px "${PRIOR_EDGE_TOUCH_MAX_RADIUS_PX}"
    --prior_edge_detail_blur_kernel "${PRIOR_EDGE_DETAIL_BLUR_KERNEL}"
    --prior_edge_detail_alpha "${PRIOR_EDGE_DETAIL_ALPHA}"
    --prior_edge_detail_alpha_final "${PRIOR_EDGE_DETAIL_ALPHA_FINAL}"
    --prior_edge_detail_warmup_iters "${PRIOR_EDGE_DETAIL_WARMUP_ITERS}"
    --prior_edge_detail_weight "${PRIOR_EDGE_DETAIL_WEIGHT}"
    --prior_edge_lowfreq_weight "${PRIOR_EDGE_LOWFREQ_WEIGHT}"
    --prior_edge_grad_weight "${PRIOR_EDGE_GRAD_WEIGHT}"
    --prior_edge_lowfreq_threshold "${PRIOR_EDGE_LOWFREQ_THRESHOLD}"
    --prior_edge_lowfreq_anchor "${PRIOR_EDGE_LOWFREQ_ANCHOR}"
    --prior_edge_detail_min_gain "${PRIOR_EDGE_DETAIL_MIN_GAIN}"
    --prior_edge_confidence_power "${PRIOR_EDGE_CONFIDENCE_POWER}"
    --prior_edge_update_scale "${PRIOR_EDGE_UPDATE_SCALE}"
    --prior_hf_seed_from_iter "${PRIOR_HF_SEED_FROM_ITER}"
    --prior_hf_seed_until_iter "${PRIOR_HF_SEED_UNTIL_ITER}"
    --prior_hf_seed_interval "${PRIOR_HF_SEED_INTERVAL}"
    --prior_hf_seed_max_per_iter "${PRIOR_HF_SEED_MAX_PER_ITER}"
    --prior_hf_seed_max_total "${PRIOR_HF_SEED_MAX_TOTAL}"
    --prior_hf_seed_scale_multiplier "${PRIOR_HF_SEED_SCALE_MULTIPLIER}"
    --prior_hf_seed_scale_mode "${PRIOR_HF_SEED_SCALE_MODE}"
    --prior_hf_seed_min_pixel_radius "${PRIOR_HF_SEED_MIN_PIXEL_RADIUS}"
    --prior_hf_seed_max_pixel_radius "${PRIOR_HF_SEED_MAX_PIXEL_RADIUS}"
    --prior_hf_seed_max_provider_ratio "${PRIOR_HF_SEED_MAX_PROVIDER_RATIO}"
    --prior_hf_seed_shape_mode "${PRIOR_HF_SEED_SHAPE_MODE}"
    --prior_hf_seed_shape_long_ratio "${PRIOR_HF_SEED_SHAPE_LONG_RATIO}"
    --prior_hf_seed_shape_short_ratio "${PRIOR_HF_SEED_SHAPE_SHORT_RATIO}"
    --prior_hf_seed_shape_normal_ratio "${PRIOR_HF_SEED_SHAPE_NORMAL_RATIO}"
    --prior_hf_seed_shape_confidence_power "${PRIOR_HF_SEED_SHAPE_CONFIDENCE_POWER}"
    --prior_hf_seed_diag_large_scale "${PRIOR_HF_SEED_DIAG_LARGE_SCALE}"
    --prior_hf_seed_scale_clamp_max_axis "${PRIOR_HF_SEED_SCALE_CLAMP_MAX_AXIS}"
    --prior_hf_seed_scale_clamp_min_axis "${PRIOR_HF_SEED_SCALE_CLAMP_MIN_AXIS}"
    --prior_hf_seed_scale_clamp_max_anisotropy "${PRIOR_HF_SEED_SCALE_CLAMP_MAX_ANISOTROPY}"
    --prior_bubble_cleanup_from_iter "${PRIOR_BUBBLE_CLEANUP_FROM_ITER}"
    --prior_bubble_cleanup_until_iter "${PRIOR_BUBBLE_CLEANUP_UNTIL_ITER}"
    --prior_bubble_cleanup_interval "${PRIOR_BUBBLE_CLEANUP_INTERVAL}"
    --prior_bubble_cleanup_opacity_min "${PRIOR_BUBBLE_CLEANUP_OPACITY_MIN}"
    --prior_bubble_cleanup_max_axis_min "${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MIN}"
    --prior_bubble_cleanup_max_axis_max "${PRIOR_BUBBLE_CLEANUP_MAX_AXIS_MAX}"
    --prior_bubble_cleanup_anisotropy_max "${PRIOR_BUBBLE_CLEANUP_ANISOTROPY_MAX}"
    --prior_bubble_cleanup_min_generation "${PRIOR_BUBBLE_CLEANUP_MIN_GENERATION}"
    --lambda_prior_bubble_hf "${LAMBDA_PRIOR_BUBBLE_HF}"
    --lambda_prior_bubble_rgb_energy "${LAMBDA_PRIOR_BUBBLE_RGB_ENERGY}"
    --lambda_prior_bubble_alpha_hf "${LAMBDA_PRIOR_BUBBLE_ALPHA_HF}"
    --lambda_prior_bubble_alpha_mass "${LAMBDA_PRIOR_BUBBLE_ALPHA_MASS}"
    --prior_bubble_cleanup_post_opacity_decay "${PRIOR_BUBBLE_CLEANUP_POST_OPACITY_DECAY}"
    --prior_hf_seed_opacity "${PRIOR_HF_SEED_OPACITY}"
    --prior_hf_seed_jitter_scale "${PRIOR_HF_SEED_JITTER_SCALE}"
    --prior_hf_seed_color_residual_gain "${PRIOR_HF_SEED_COLOR_RESIDUAL_GAIN}"
    --prior_hf_seed_guidance_threshold "${PRIOR_HF_SEED_GUIDANCE_THRESHOLD}"
    --prior_hf_seed_prune_protect_iters "${PRIOR_HF_SEED_PRUNE_PROTECT_ITERS}"
    --prior_hf_seed_recent_hf_boost "${PRIOR_HF_SEED_RECENT_HF_BOOST}"
    --prior_hf_seed_recent_imprint_weight "${PRIOR_HF_SEED_RECENT_IMPRINT_WEIGHT}"
    --prior_hf_seed_recent_imprint_gain "${PRIOR_HF_SEED_RECENT_IMPRINT_GAIN}"
    --prior_hf_seed_recent_imprint_iters "${PRIOR_HF_SEED_RECENT_IMPRINT_ITERS}"
    --prior_hf_lowfreq_cleanup_from_iter "${PRIOR_HF_LOWFREQ_CLEANUP_FROM_ITER}"
    --prior_hf_lowfreq_cleanup_until_iter "${PRIOR_HF_LOWFREQ_CLEANUP_UNTIL_ITER}"
    --prior_hf_lowfreq_cleanup_interval "${PRIOR_HF_LOWFREQ_CLEANUP_INTERVAL}"
    --prior_hf_lowfreq_cleanup_stale_iters "${PRIOR_HF_LOWFREQ_CLEANUP_STALE_ITERS}"
    --prior_hf_lowfreq_cleanup_opacity_min "${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_MIN}"
    --prior_hf_lowfreq_cleanup_scale_max_min "${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MIN}"
    --prior_hf_lowfreq_cleanup_scale_max_max "${PRIOR_HF_LOWFREQ_CLEANUP_SCALE_MAX_MAX}"
    --prior_hf_lowfreq_cleanup_anisotropy_max "${PRIOR_HF_LOWFREQ_CLEANUP_ANISOTROPY_MAX}"
    --prior_hf_lowfreq_cleanup_opacity_decay "${PRIOR_HF_LOWFREQ_CLEANUP_OPACITY_DECAY}"
    --prior_hf_lowfreq_cleanup_prune_opacity_below "${PRIOR_HF_LOWFREQ_CLEANUP_PRUNE_OPACITY_BELOW}"
    --prior_hf_lowfreq_cleanup_max_prune_fraction "${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_FRACTION}"
    --prior_hf_lowfreq_cleanup_max_prune_count "${PRIOR_HF_LOWFREQ_CLEANUP_MAX_PRUNE_COUNT}"
    --prior_hf_focus_boost "${PRIOR_HF_FOCUS_BOOST}"
    --prior_hf_focus_power "${PRIOR_HF_FOCUS_POWER}"
    --prior_guidance_decay_from_iter "${PRIOR_GUIDANCE_DECAY_FROM_ITER}"
    --prior_guidance_decay_until_iter "${PRIOR_GUIDANCE_DECAY_UNTIL_ITER}"
    --prior_guidance_final_scale "${PRIOR_GUIDANCE_FINAL_SCALE}"
    --prior_view_curriculum_start_iter "${PRIOR_VIEW_CURRICULUM_START_ITER}"
    --prior_view_curriculum_primary_iters "${PRIOR_VIEW_CURRICULUM_PRIMARY_ITERS}"
    --prior_view_curriculum_neighbor_iters "${PRIOR_VIEW_CURRICULUM_NEIGHBOR_ITERS}"
    --prior_view_curriculum_neighbor_radius "${PRIOR_VIEW_CURRICULUM_NEIGHBOR_RADIUS}"
    --prior_view_curriculum_max_views "${PRIOR_VIEW_CURRICULUM_MAX_VIEWS}"
    --prior_view_curriculum_settle_iters "${PRIOR_VIEW_CURRICULUM_SETTLE_ITERS}"
    --prior_view_curriculum_primary_hf_scale "${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_SCALE}"
    --prior_view_curriculum_neighbor_hf_scale "${PRIOR_VIEW_CURRICULUM_NEIGHBOR_HF_SCALE}"
    --prior_view_curriculum_settle_hf_scale "${PRIOR_VIEW_CURRICULUM_SETTLE_HF_SCALE}"
    --prior_view_curriculum_primary_bootstrap_iters "${PRIOR_VIEW_CURRICULUM_PRIMARY_BOOTSTRAP_ITERS}"
    --prior_view_curriculum_primary_hf_energy_weight "${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_WEIGHT}"
    --prior_view_curriculum_primary_hf_energy_gain "${PRIOR_VIEW_CURRICULUM_PRIMARY_HF_ENERGY_GAIN}"
    --prior_view_curriculum_primary_band_weight "${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_WEIGHT}"
    --prior_view_curriculum_primary_band_kernel "${PRIOR_VIEW_CURRICULUM_PRIMARY_BAND_KERNEL}"
    --prior_view_curriculum_primary_residual_weight "${PRIOR_VIEW_CURRICULUM_PRIMARY_RESIDUAL_WEIGHT}"
    --prior_view_curriculum_primary_patch_weight "${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_WEIGHT}"
    --prior_view_curriculum_primary_patch_top_fraction "${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_TOP_FRACTION}"
    --prior_view_curriculum_primary_patch_min_guidance "${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_MIN_GUIDANCE}"
    --prior_view_curriculum_primary_patch_delta_gain "${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_DELTA_GAIN}"
    --prior_view_curriculum_primary_patch_highpass_kernel "${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_HIGHPASS_KERNEL}"
    --prior_view_curriculum_primary_patch_lowfreq_guard_weight "${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_WEIGHT}"
    --prior_view_curriculum_primary_patch_lowfreq_guard_kernel "${PRIOR_VIEW_CURRICULUM_PRIMARY_PATCH_LOWFREQ_GUARD_KERNEL}"
    --surface_route_consensus_root "${SURFACE_ROUTE_CONSENSUS_ROOT}"
    --lambda_surface_route_consensus "${LAMBDA_SURFACE_ROUTE_CONSENSUS}"
    --surface_route_consensus_from_iter "${SURFACE_ROUTE_CONSENSUS_FROM_ITER}"
    --surface_route_consensus_min_pixels "${SURFACE_ROUTE_CONSENSUS_MIN_PIXELS}"
    --surface_route_view_sample_prob "${SURFACE_ROUTE_VIEW_SAMPLE_PROB}"
    --optimize_source_tag "${OPTIMIZE_SOURCE_TAG}"
    --optimize_gaussian_mask_key "${OPTIMIZE_GAUSSIAN_MASK_KEY}"
    --prior_loss_gaussian_mask_key "${PRIOR_LOSS_GAUSSIAN_MASK_KEY}"
    --opacity_reg "${OPACITY_REG}"
    --scale_reg "${SCALE_REG}"
    --min_scale_reg "${MIN_SCALE_REG}"
    --lambda_distortion "${LAMBDA_DISTORTION}"
    --lambda_depth_normal "${LAMBDA_DEPTH_NORMAL}"
    --lambda_smoothness "${LAMBDA_SMOOTHNESS}"
    --lambda_extent "${LAMBDA_EXTENT}"
    --lambda_opacity_field "${LAMBDA_OPACITY_FIELD}"
    --distortion_from_iter "${DISTORTION_FROM_ITER}"
    --depth_normal_from_iter "${DEPTH_NORMAL_FROM_ITER}"
    --sof_reg_log_interval "${SOF_REG_LOG_INTERVAL}"
    --surface_thin_mesh_path "${SURFACE_THIN_MESH_PATH}"
    --lambda_surface_thin "${LAMBDA_SURFACE_THIN}"
    --surface_thin_from_iter "${SURFACE_THIN_FROM_ITER}"
    --surface_thin_until_iter "${SURFACE_THIN_UNTIL_ITER}"
    --surface_thin_sample_count "${SURFACE_THIN_SAMPLE_COUNT}"
    --surface_thin_update_interval "${SURFACE_THIN_UPDATE_INTERVAL}"
    --surface_thin_gaussian_sample_count "${SURFACE_THIN_GAUSSIAN_SAMPLE_COUNT}"
    --surface_thin_offset_margin "${SURFACE_THIN_OFFSET_MARGIN}"
    --surface_thin_normal_scale_target "${SURFACE_THIN_NORMAL_SCALE_TARGET}"
    --surface_thin_normal_scale_weight "${SURFACE_THIN_NORMAL_SCALE_WEIGHT}"
  )
  if [[ "${USE_MERGED_SOF_RASTERIZER}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--use_merged_sof_rasterizer)
  fi
  if [[ "${SAVE_CHECKPOINT_AFTER}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--checkpoint_iterations "${ITERATIONS}")
  fi
  if [[ -n "${PRIOR_MASK_SUBDIR}" ]]; then
    PRIOR_TRAIN_ARGS+=(--external_prior_mask_subdir "${PRIOR_MASK_SUBDIR}")
  fi
  if [[ "${USE_VANILLA_SOF_RASTERIZER}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--use_vanilla_sof_rasterizer)
  fi
  if [[ "${SURFACE_ROUTE_SURFACE_ONLY}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--surface_route_surface_only)
  fi
  if [[ -n "${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD}" ]]; then
    PRIOR_TRAIN_ARGS+=(--optimize_gaussian_mask_payload "${OPTIMIZE_GAUSSIAN_MASK_PAYLOAD}")
  fi
  if [[ -n "${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD}" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_loss_gaussian_mask_payload "${PRIOR_LOSS_GAUSSIAN_MASK_PAYLOAD}")
  fi
  if [[ "${PRIOR_LOSS_GAUSSIAN_MASK_DYNAMIC_ROOTS}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_loss_gaussian_mask_dynamic_roots)
  fi
  if [[ "${SURFACE_NORMAL_LOCK}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--surface_normal_lock)
    if [[ -n "${SURFACE_NORMAL_LOCK_PAYLOAD}" ]]; then
      PRIOR_TRAIN_ARGS+=(--surface_normal_lock_payload "${SURFACE_NORMAL_LOCK_PAYLOAD}")
    fi
    PRIOR_TRAIN_ARGS+=(--surface_normal_lock_normal_key "${SURFACE_NORMAL_LOCK_NORMAL_KEY}")
    PRIOR_TRAIN_ARGS+=(--surface_normal_lock_anchor_key "${SURFACE_NORMAL_LOCK_ANCHOR_KEY}")
    if [[ "${SURFACE_NORMAL_LOCK_DYNAMIC_ROOTS}" == "1" ]]; then
      PRIOR_TRAIN_ARGS+=(--surface_normal_lock_dynamic_roots)
    fi
  fi
  if [[ "${SURFACE_FILTER_3D}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--surface_filter_3d)
    if [[ -n "${SURFACE_FILTER_3D_PAYLOAD}" ]]; then
      PRIOR_TRAIN_ARGS+=(--surface_filter_3d_payload "${SURFACE_FILTER_3D_PAYLOAD}")
    fi
    PRIOR_TRAIN_ARGS+=(--surface_filter_3d_key "${SURFACE_FILTER_3D_KEY}")
    PRIOR_TRAIN_ARGS+=(--surface_filter_3d_scale "${SURFACE_FILTER_3D_SCALE}")
    PRIOR_TRAIN_ARGS+=(--surface_filter_3d_min "${SURFACE_FILTER_3D_MIN}")
  fi
  if [[ "${LAMBDA_NON_SURFACE_HF}" != "0" && "${LAMBDA_NON_SURFACE_HF}" != "0.0" ]] || [[ "${LAMBDA_NON_SURFACE_RGB_ENERGY}" != "0" && "${LAMBDA_NON_SURFACE_RGB_ENERGY}" != "0.0" ]] || [[ "${LAMBDA_NON_SURFACE_ALPHA_HF}" != "0" && "${LAMBDA_NON_SURFACE_ALPHA_HF}" != "0.0" ]] || [[ "${LAMBDA_NON_SURFACE_ALPHA_MASS}" != "0" && "${LAMBDA_NON_SURFACE_ALPHA_MASS}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_HF_CLOSURE}" != "0" && "${LAMBDA_SURFACE_HF_CLOSURE}" != "0.0" ]]; then
    if [[ -n "${LAYER_FREQUENCY_MASK_PAYLOAD}" ]]; then
      PRIOR_TRAIN_ARGS+=(--layer_frequency_mask_payload "${LAYER_FREQUENCY_MASK_PAYLOAD}")
    fi
    PRIOR_TRAIN_ARGS+=(--layer_frequency_non_surface_key "${LAYER_FREQUENCY_NON_SURFACE_KEY}")
    PRIOR_TRAIN_ARGS+=(--layer_frequency_surface_key "${LAYER_FREQUENCY_SURFACE_KEY}")
    PRIOR_TRAIN_ARGS+=(--layer_frequency_surface_target "${LAYER_FREQUENCY_SURFACE_TARGET}")
    PRIOR_TRAIN_ARGS+=(--lambda_non_surface_hf "${LAMBDA_NON_SURFACE_HF}")
    PRIOR_TRAIN_ARGS+=(--lambda_non_surface_rgb_energy "${LAMBDA_NON_SURFACE_RGB_ENERGY}")
    PRIOR_TRAIN_ARGS+=(--lambda_non_surface_alpha_hf "${LAMBDA_NON_SURFACE_ALPHA_HF}")
    PRIOR_TRAIN_ARGS+=(--lambda_non_surface_alpha_mass "${LAMBDA_NON_SURFACE_ALPHA_MASS}")
    PRIOR_TRAIN_ARGS+=(--lambda_surface_hf_closure "${LAMBDA_SURFACE_HF_CLOSURE}")
    PRIOR_TRAIN_ARGS+=(--surface_hf_update_scale "${SURFACE_HF_UPDATE_SCALE}")
    PRIOR_TRAIN_ARGS+=(--layer_frequency_from_iter "${LAYER_FREQUENCY_FROM_ITER}")
    PRIOR_TRAIN_ARGS+=(--layer_frequency_until_iter "${LAYER_FREQUENCY_UNTIL_ITER}")
    PRIOR_TRAIN_ARGS+=(--layer_frequency_log_interval "${LAYER_FREQUENCY_LOG_INTERVAL}")
    if [[ "${LAYER_FREQUENCY_DYNAMIC_ROOTS}" == "1" ]]; then
      PRIOR_TRAIN_ARGS+=(--layer_frequency_dynamic_roots)
    fi
  fi
  if [[ "${LAMBDA_SURFACE_MIGRATION_NORMAL}" != "0" && "${LAMBDA_SURFACE_MIGRATION_NORMAL}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_MIGRATION_TANGENT}" != "0" && "${LAMBDA_SURFACE_MIGRATION_TANGENT}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN}" != "0" && "${LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN}" != "0.0" ]] || [[ "${LAMBDA_SURFACE_MIGRATION_THIN}" != "0" && "${LAMBDA_SURFACE_MIGRATION_THIN}" != "0.0" ]] || [[ "${SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA}" != "0" && "${SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA}" != "0.0" ]] || [[ "${SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA}" != "0" && "${SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA}" != "0.0" ]]; then
    if [[ -n "${SURFACE_MIGRATION_PAYLOAD}" ]]; then
      PRIOR_TRAIN_ARGS+=(--surface_migration_payload "${SURFACE_MIGRATION_PAYLOAD}")
    fi
    PRIOR_TRAIN_ARGS+=(--surface_migration_mask_key "${SURFACE_MIGRATION_MASK_KEY}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_anchor_source_key "${SURFACE_MIGRATION_ANCHOR_SOURCE_KEY}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_normal_key "${SURFACE_MIGRATION_NORMAL_KEY}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_anchor_key "${SURFACE_MIGRATION_ANCHOR_KEY}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_target_normal_coord "${SURFACE_MIGRATION_TARGET_NORMAL_COORD}")
    PRIOR_TRAIN_ARGS+=(--lambda_surface_migration_normal "${LAMBDA_SURFACE_MIGRATION_NORMAL}")
    PRIOR_TRAIN_ARGS+=(--lambda_surface_migration_tangent "${LAMBDA_SURFACE_MIGRATION_TANGENT}")
    PRIOR_TRAIN_ARGS+=(--lambda_surface_migration_normal_align "${LAMBDA_SURFACE_MIGRATION_NORMAL_ALIGN}")
    PRIOR_TRAIN_ARGS+=(--lambda_surface_migration_thin "${LAMBDA_SURFACE_MIGRATION_THIN}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_thin_target_ratio "${SURFACE_MIGRATION_THIN_TARGET_RATIO}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_post_step_normal_alpha "${SURFACE_MIGRATION_POST_STEP_NORMAL_ALPHA}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_post_step_tangent_alpha "${SURFACE_MIGRATION_POST_STEP_TANGENT_ALPHA}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_from_iter "${SURFACE_MIGRATION_FROM_ITER}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_until_iter "${SURFACE_MIGRATION_UNTIL_ITER}")
    PRIOR_TRAIN_ARGS+=(--surface_migration_log_interval "${SURFACE_MIGRATION_LOG_INTERVAL}")
  fi
  if [[ "${PRIOR_ONLY_EDGE_FINETUNE}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_only_edge_finetune)
  fi
  if [[ "${PRIOR_HF_SEED_ENABLE}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_hf_seed_enable)
  fi
  if [[ "${PRIOR_RESIDUAL_MASKED_UPDATE}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_residual_masked_update)
  fi
  if [[ "${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_masked_update_densify_signal)
    PRIOR_TRAIN_ARGS+=(--prior_masked_update_densify_signal_scale "${PRIOR_MASKED_UPDATE_DENSIFY_SIGNAL_SCALE}")
  fi
  if [[ "${PRIOR_HF_SEED_SCALE_CLAMP_ENABLE}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_hf_seed_scale_clamp_enable)
  fi
  if [[ "${PRIOR_HF_LOWFREQ_CLEANUP_ENABLE}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_hf_lowfreq_cleanup_enable)
  fi
  if [[ "${PRIOR_BUBBLE_CLEANUP_ENABLE}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_bubble_cleanup_enable)
  fi
  if [[ "${PRIOR_HF_SEED_ORIGINAL_ONLY}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_hf_seed_original_only)
  fi
  if [[ "${PRIOR_HF_SEED_FIRST_CYCLE_ONLY}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_hf_seed_first_cycle_only)
  fi
  if [[ "${PRIOR_VIEW_CURRICULUM_ENABLE}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_view_curriculum_enable)
  fi
  if [[ "${PRIOR_VIEW_CURRICULUM_BIRTH_PRIMARY_ONLY}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--prior_view_curriculum_birth_primary_only)
  fi
  if [[ "${REQUIRE_MERGED_SOF_AUX}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--require_merged_sof_aux)
  fi
  if [[ "${DISABLE_PRIOR_HF_RESIDUAL}" == "1" ]]; then
    PRIOR_TRAIN_ARGS+=(--disable_prior_hf_residual)
  fi
  (
    cd "${MIPSPLATTING_ROOT}"
    export PYTHONPATH="${MIP_PYTHONPATH}"
    "${PRIOR_TRAIN_ARGS[@]}"
  )
else
  echo "[mipsplatting-stablesr-prior] checkpoint exists, skipping training: ${PRIOR_CHECKPOINT_PATH}"
fi

echo
if [[ "${RUN_RENDER_AFTER}" == "1" ]]; then
  echo "[4/5] render on ${TARGET_IMAGES_SUBDIR}"
  PRIOR_RENDER_DIR="${PRIOR_MODEL_DIR}/test/ours_${ITERATIONS}/test_preds_${RENDER_RESOLUTION}"
  if [[ "${FORCE_RERUN}" == "1" || ! -d "${PRIOR_RENDER_DIR}" ]]; then
    (
      cd "${MIPSPLATTING_ROOT}"
      export PYTHONPATH="${MIP_PYTHONPATH}"
      "${PYTHON_BIN}" render.py \
        -m "${PRIOR_MODEL_DIR}" \
        -s "${SCENE_ROOT}" \
        -i "${TARGET_IMAGES_SUBDIR}" \
        -r "${RENDER_RESOLUTION}" \
        --iteration "${ITERATIONS}" \
        --skip_train
    )
  fi
else
  echo "[4/5] skip render (RUN_RENDER_AFTER=${RUN_RENDER_AFTER})"
fi

echo
if [[ "${RUN_METRICS_AFTER}" == "1" ]]; then
  echo "[5/5] summarize PSNR/SSIM and compare with baseline"
  (
    cd "${SOF_ROOT}"
    "${PYTHON_BIN}" scripts/summarize_mipsplatting_render_metrics.py \
      --model_dir "${PRIOR_MODEL_DIR}" \
      --iteration "${ITERATIONS}" \
      --resolution "${RENDER_RESOLUTION}"
  )

  if [[ -f "${BASELINE_RESULTS_JSON}" && -f "${PRIOR_RESULTS_JSON}" ]]; then
    (
      cd "${SOF_ROOT}"
      "${PYTHON_BIN}" scripts/compare_mipsplatting_summary_json.py \
        --baseline_json "${BASELINE_RESULTS_JSON}" \
        --current_json "${PRIOR_RESULTS_JSON}" \
        --output_json "${COMPARE_JSON}"
    )
  fi
else
  echo "[5/5] skip metrics (RUN_METRICS_AFTER=${RUN_METRICS_AFTER})"
fi

echo
echo "[done] baseline model : ${BASELINE_MODEL_DIR}"
echo "[done] prior model    : ${PRIOR_MODEL_DIR}"
echo "[done] prepared priors: ${PREPARED_PRIOR_ROOT}"
echo "[done] metrics        : ${PRIOR_RESULTS_JSON}"
echo "[done] compare        : ${COMPARE_JSON}"
