#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOF_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

PHASE_MODE="${PHASE_MODE:-alternating}"
TOTAL_STEPS="${TOTAL_STEPS:-5000}"
APPEARANCE_STEPS="${APPEARANCE_STEPS:-50}"
GEOMETRY_STEPS="${GEOMETRY_STEPS:-50}"
SAVE_EVERY_CYCLES="${SAVE_EVERY_CYCLES:-10}"
MAX_VIEWS="${MAX_VIEWS:-0}"
PRUNE_AFTER_CYCLE="${PRUNE_AFTER_CYCLE:-1}"

# Keep pruning conservative for the first long run.
PRUNE_BAD_STREAK="${PRUNE_BAD_STREAK:-3}"
PRUNE_CONFIDENCE_THRESHOLD="${PRUNE_CONFIDENCE_THRESHOLD:-0.015}"
PRUNE_DISAGREEMENT_THRESHOLD="${PRUNE_DISAGREEMENT_THRESHOLD:-0.20}"
PRUNE_COLOR_ERROR_THRESHOLD="${PRUNE_COLOR_ERROR_THRESHOLD:-0.14}"
PROTECT_CONFIDENCE_THRESHOLD="${PROTECT_CONFIDENCE_THRESHOLD:-0.10}"

RUN_TAG="${RUN_TAG:-mainline5k_v0}"
RUN_NAME="${RUN_NAME:-${START_RUN_NAME:-debug_stage_00b3_after_scale_canonicalize_geometry_only_v0}_bounded_${PHASE_MODE}_${RUN_TAG}}"

export PHASE_MODE
export TOTAL_STEPS
export APPEARANCE_STEPS
export GEOMETRY_STEPS
export SAVE_EVERY_CYCLES
export MAX_VIEWS
export PRUNE_AFTER_CYCLE
export PRUNE_BAD_STREAK
export PRUNE_CONFIDENCE_THRESHOLD
export PRUNE_DISAGREEMENT_THRESHOLD
export PRUNE_COLOR_ERROR_THRESHOLD
export PROTECT_CONFIDENCE_THRESHOLD
export RUN_NAME

bash "${SOF_ROOT}/scripts/run_bounded_surface_alternating_v0_kitchen.sh"
