#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export OUTPUT_ROOT="${OUTPUT_ROOT:-/root/autodl-tmp/SOFSR/output/proxy_ray_surface/push_full_softalpha_relaxed_nearmesh_continue3k_v0}"
export FORCE_REBUILD="${FORCE_REBUILD:-1}"
export FORCE_TRAIN="${FORCE_TRAIN:-1}"
export RUN_TRAIN_AFTER="${RUN_TRAIN_AFTER:-1}"
export RUN_RENDER_AFTER="${RUN_RENDER_AFTER:-1}"
export RUN_METRICS_AFTER="${RUN_METRICS_AFTER:-1}"

export PROXY_ANCHOR_MODE="${PROXY_ANCHOR_MODE:-ray_surface}"
export PROXY_OUTPUT_MODE="${PROXY_OUTPUT_MODE:-replace_cloned_donors}"
export PROXY_RAY_SURFACE_MODE="${PROXY_RAY_SURFACE_MODE:-push_away}"
export PROXY_MAX_DONORS="${PROXY_MAX_DONORS:-0}"
export PROXY_RAY_PRESERVE_SCREEN_SCALE="${PROXY_RAY_PRESERVE_SCREEN_SCALE:-1}"
export PROXY_RAY_MAX_HIT_TO_DONOR_GAP_RATIO="${PROXY_RAY_MAX_HIT_TO_DONOR_GAP_RATIO:-1.0}"
export PROXY_RAY_RELAX_UNANCHORED_WITH_MESH="${PROXY_RAY_RELAX_UNANCHORED_WITH_MESH:-1}"
export PROXY_RAY_RELAXED_MAX_HIT_TO_DONOR_GAP_RATIO="${PROXY_RAY_RELAXED_MAX_HIT_TO_DONOR_GAP_RATIO:-8.0}"
export PROXY_RAY_RELAXED_PROJECTED_CENTER_TOLERANCE_PX="${PROXY_RAY_RELAXED_PROJECTED_CENTER_TOLERANCE_PX:-4.0}"
export PROXY_TANGENT_OFFSET_SCALE="${PROXY_TANGENT_OFFSET_SCALE:-0.0}"
export PROXY_NORMAL_OFFSET_RATIO="${PROXY_NORMAL_OFFSET_RATIO:-0.02}"
export PROXY_OPACITY_SCALE="${PROXY_OPACITY_SCALE:-0.2}"
export PROXY_TANGENT_SCALE_MULTIPLIER="${PROXY_TANGENT_SCALE_MULTIPLIER:-0.5}"

export CONTINUE_STEPS="${CONTINUE_STEPS:-3000}"
export START_PLY_ITERATION="${START_PLY_ITERATION:-${MIP_ITERATION:-30000}}"
export FINAL_ITERATION="${FINAL_ITERATION:-$((START_PLY_ITERATION + CONTINUE_STEPS))}"
export TRAIN_IMAGES_SUBDIR="${TRAIN_IMAGES_SUBDIR:-images_2}"
export EVAL_IMAGES_SUBDIR="${EVAL_IMAGES_SUBDIR:-images_2}"
export TRAIN_DATA_DEVICE="${TRAIN_DATA_DEVICE:-cpu}"

# Keep the surface/proxy carrier topology fixed during this distillation pass.
export DENSIFY_UNTIL_ITER="${DENSIFY_UNTIL_ITER:-0}"
export DENSIFY_FROM_ITER="${DENSIFY_FROM_ITER:-${FINAL_ITERATION}}"
export OPACITY_RESET_INTERVAL="${OPACITY_RESET_INTERVAL:-1000000000}"

bash "${SCRIPT_DIR}/run_mipsplatting_surface_proxy_augmented_supervision_v0_kitchen.sh"
